### ISSUE TITLE
[Círculo del valor]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1]
Círculo del valor / Arena de Orgrimmar
http://es.wowhead.com/zone=4406 
No salta cuando apuntas arenas.

**Comment by Dekadencee** [comment]
Pendiente de testeo en rewrite, pero segurísimo que está reparada, en cuanto se testee que el rewrite no genera ningún problema externo lo aplicamos al servidor.

Un saludo

**Comment by asfo** [comment]
Esto hasta donde tengo entendido, ya está. Cierro.
