### ISSUE TITLE
[Hunter > Spec: Marksmanship > Spell > Careful Aim]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#10]
-Afinar la puntería ( 60% critico /se aplica a todas las spells de cazador / extra en objetivos con 90% de salud o más )
http://es.wowhead.com/spell=34483

Bug: No aumenta el crítico en los objetivos.

**Comment by adrianrp1988** [comment]
Reparado en la próxima Rev
