### ISSUE TITLE
Logros bug

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1000]
Actualizo: quite el logro/titulo que no esta bug y puse más datos.
El primer logro es este, A todas las ardillas que he amado http://es.wowhead.com/achievement=1206
Faltan los polllos http://es.wowhead.com/npc=620 no estan por ninguno de los lugares que indica wow head.

El segundo logro es, Conocimiento superior http://es.wowhead.com/achievement=1956
Faltan los 8 libros en Dalaran:
*Las Escuelas de la Magia Arcana: Transmutación http://es.wowhead.com/object=192867 Coord: 47.0, 39.9
*Las Escuelas de la Magia Arcana: Ilusión http://es.wowhead.com/object=192865 Coord: 49.0, 40.7 o 64.5, 52.9
*Las Escuelas de la Magia Arcana: Adivinación http://es.wowhead.com/object=192711 Coord: 47.2, 40.7 o 26,5, 51.8
*Las Escuelas de la Magia Arcana: Abjuración http://es.wowhead.com/object=192709 Coord: 52.5, 54.6 o 52.2, 55.5
*Las Escuelas de la Magia Arcana: Nigromancia http://es.wowhead.com/object=192866 Coord: 47.0, 39.5
*Las Escuelas de la Magia Arcana: Encantamiento http://es.wowhead.com/object=192713 Coord: 43.5, 47.5
*Las Escuelas de la Magia Arcana: Conjuración http://es.wowhead.com/object=192710 Coord: 30.9, 46.5
*Las Escuelas de la Magia Arcana: Introducción http://es.wowhead.com/object=192708 Coord: 56.5, 45.8

Los libros aparecen cada 1 o 2 horas y aparecen aleatoriamente en una u otra coordenada, si es que hay dos coordenadas (esto segun comentarios de wowhead).

**Comment by redneo** [comment]
En primer lugar, enhorabuena por el bugtracker #1000 
los pollos, ciertamente no aparecían aun estando spawneados, solo salian bajo un evento de los anuales, puestos que estan siempre por ahí. 

Sapos hay 125 spawneados, he ido a mirar uno cualquiera, y por ejemplo me lo he encontrado en Los humedales.

El titulo "el camellero" creo que se implementó en parches superiores, ya que en los dbc, el ultimo titulo que sale es el 229 http://es.wowhead.com/title=229

Lo de los libros, tendrian que salir aleatoriamente, cosa que creo que no hacen, cierto?

**Comment by ghost** [comment]
Gracias xd, con 500 reportes cerrados tendras que pedir a searum y dekadeence unas vacaciones pagas xd.

Supongo que lo de los pollos no lo tocaste porque siguen sin estar.

Lo de los libros si con aleatoriamente te refieres a que salgan en cualquier lado, no, tienen una hubicación exacta pero entre 1 o 2 horas aleatorias en volver a aparecer, los libros al leerlos tardan 3 min en desaparecer (según comentarios de wowhead).

**Comment by ghost** [comment]
Gracias redneo, arreglado.
