### ISSUE TITLE
Vuela hasta allí

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1001]
Vuela hasta allí
http://es.wowhead.com/quest=27006

Bien el mismo nombre de la quest lo dice TODO. Simplemente tienes que llegar al lugar y pararte ahi. Si es todo; Pero no pasa nada, se supone que se deberia completer la quest y luego ir a entregarla.

![GitHub Logo](http://wow.zamimg.com/uploads/screenshots/resized/200328.jpg)

---

Una pregunta no relacionada con la quest: Cuando arreglan las quest cierran el post. no?
1. Pero tengo que esperar a que caiga el server para ver los cambios? O si se aplican al momento en que se cierra el post declarado como arreglado.

---

-=Porque la pregunta?=- es que hoy cerraron creo 2 reportes y los declararon ya arreglados. Bueno fui a investigar las quest reportadas, y siguen bug. Bueno eso fue hace mas de 4 horas no se si en el tiempo que deje de jugar ya se aplicaron los cambios.

---

Porfis no se enojen. No mas es un pregunta por curiosidad. THANKS for read ME >.<

**Comment by ghost** [comment]
Cuando cierran el reporte significa que esta arreglado, pero las correcciones se introducen luego de que el server cae (por cualquier motivo).

**Comment by redneo** [comment]
Misión arreglada.

Veamos, cuando pongo que está arreglada, es que la he arreglado, y seguramente testado, en el servidor de pruebas, que lo puedo tirar todas las veces que quiera, ya que estoy solo.

No voy a tirar el servidor normal, o hacer mil recargas de tablas, ya que incordiaria a los jugadores, y a parte, tardaria 20 veces mas en hacer las cosas, por los contantes, "ey GM te puedo susurrar" y cosas por el estilo. Es por eso, que no hago las cosas en el server normal.

Con lo cual, cuando pongo que está arreglada, tendrias que mirar hace cuanto tiempo que no se cae el servidor y compararlo con la respuesta de "arreglado", si se ha caido tras haber puesto arreglado, tendria que ir, siempre puede pasar que se me olvide meter las sentencias en el reino normal, o que haya metido la pata de alguna forma.

Espero haberte ayudado.

Un saludo
