### ISSUE TITLE
El desencriptado nunca fue tan fácil

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1002]
El desencriptado nunca fue tan fácil
http://es.wowhead.com/quest=27040
![GitHub Logo](http://wow.zamimg.com/uploads/screenshots/resized/197475.jpg)
La verdad es que ni tan facil. Por que esta bug. Y es que para completarla primero te la deben de dar :P hahah.

---

Exploradora Mowi <Liga de Expedicionarios>
http://es.wowhead.com/npc=44799
![GitHub Logo](http://wow.zamimg.com/uploads/screenshots/thumb/200022.jpg)

-=BUG=-
Bien, el problema para comenzar el NPC si te muestra la quest. Pero te la muestra como una QUEST DIARIA (? azul) cuando en realidad debe de ser una quest normal (? amarillo). Pero ni aun siendo quest diaria no te dan la quest.

---

QUE que!!!... Que como se que es una quest normal y no diaria? Bueno esta quest pertenece a una cadena de 7 quest. Y dudo que una de ellas sea diraria mientras las otras no :P

**Comment by WarSxNes** [comment]
Me hago un auto-comentario. Para contarles lo que me paso hoy fui a investigar esta quest.
![WoWScrnShot_040813_151630](https://f.cloud.github.com/assets/2059256/354416/4ada8f32-a09e-11e2-83a5-4cd8c6d06c4d.jpg)
Bien, acepte la quest creyendo que ya estaba arreglada. Y creo se auto-completo y se auto-entrego y me dio esa exp.

![Untitled](https://f.cloud.github.com/assets/2059256/354442/3e3b559e-a09f-11e2-9eab-c8c5d41bbd9b.jpg)
esta pequena grafica muestra donde voy y lo que hace falta para completer la cadena.

---

Que hago? ya acepte la quest y creo que se auto-entrego y no se si cuando esta este arreglada pueda seguir con las demas quest.

Digo: si ya la complete entonces tendria que ver las demas no? las demas quest comienzan y terminan con el mismo NPC, delocontrario a lo major el NPC o las quest que faltan han de estar bug.

**Comment by redneo** [comment]
Ya la tendrian que dar, no se si funciona
