### ISSUE TITLE
[Paladín > Maestria Protección > Divine Bulwark]

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#1005]
Hola queria informar que la maestria del pala prote no presenta cambios al ser activada por talentos ya pues antes de activarla tenia un 5% de bloqueo y despues de activarla lo mismo y deberia de añadir 2.25 extra por cada punto de maestria y yo tengo  1101 de maestria (+6.14 maestria) lo cual no me añade nada y es de lo más importante  para un paladín tanquear bosses en pve.
Maestría: Baluarte divino  http://old.wowhead.com/spell=76671

Adjunto foto:
![WoWScrnShot_040713_150331](https://f.cloud.github.com/assets/3537253/348776/c41331d6-9f83-11e2-9289-a7ee6c211daa.jpg)

![WoWScrnShot_040713_150335](https://f.cloud.github.com/assets/3537253/348777/cf73f68c-9f83-11e2-9453-b71ff1fee8c2.jpg)

Espero que el reporte sirva para su reparación, un saludo.

**Comment by Overseer101** [comment]
Con la del Warrior pasa algo parecido, pero es que se queda pillada y no te marca lo que deberia, normalmente al reloguear o cambiar talentos vuelve sola, a veces no a la primera, pero vuelve

**Comment by crowel** [comment]
Llevo un ratito comprobando si al reloguear o cambiar talentos se me arregla y no soy capaz, si pudieras probar este metodo  tu para decirme si así funciona aunque creo que esta mal la maestria.

**Comment by DatJetto** [comment]
Si, he escuchado de esto, creo que tienes que quitarte todo el set, reloguea, cambia de spec y vuelve a tank y reloguea y te pones el set y se te añade el bloqueo @_@creo que era así.

**Comment by crowel** [comment]
ok gracias me funciono de la manera exacta que dijiste gro, ahora voi a comprobar si poniendo mas maestria a mi armadura me aumenta el bloqueo(gracias a la maestria claro).
Cuando compruebe que funciona y sube el bloqueo cierro post :), un saludo.
