### ISSUE TITLE
[Paladín > Talento Protección > Holy Shield]

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#1006]
Hola queria informar sobre este talento
Escudo sagrado : http://old.wowhead.com/spell=20925
Este hechizo al usar Palabra de gloria o Inquisición deberia aumentar un 10% la cantidad de bloqueo del escudo durante 20sec al usarlo, el problema es que no funciona, no pasa nada al usar las dos habilidades antes mencionadas.
Este talento y la maestria que reporte hace un momento son lo que hacen realmente un paladín protección para pve.
Espero se pueda solucionar, un saludo.

**Comment by redneo** [comment]
http://old.wowhead.com/spell=87342 ese es el efecto... a ver si lo puedo arreglar a la tarde...

Pregunta tonta, usando un .cast 20925 salen chispas de la mano del paladin, sale cuando tienes el talento?

**Comment by crowel** [comment]
No te entendi muy bien lo que te refieres al usar el 20925 para comprobar lo de las chispas, probando mis habilidades con el talento puesto no vi que salieran, si me pudieras detallar un poquito más para comprobarlo.

**Comment by DatJetto** [comment]
No, no salen chispas.

**Comment by redneo** [comment]
Jou Jou Jou!

**Comment by crowel** [comment]
Gracias redneo, un trabajo excelente!
