### ISSUE TITLE
mision al abrir cajones o coger objetosde mision

### ISSUE THREAD

**Issue by earb08** [RoDNet/Bugtracker-Infinium-4.0.6a#101]
cuando se mata un pnj y al intentar acceder a la recompensa mi personaje, no hace de nada, no abre la bolsa, y mucho menos muestra los objetos, asi mismo con los objetos de mision

**Comment by Dekadencee** [comment]
Usa el nuevo parche de RoD, puedes descargarlo en http://www.mediafire.com/download.php?d6k9e8207j22vas
