### ISSUE TITLE
¡Gluber! -  EL PAVO

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1012]
¡Gluber!
http://es.wowhead.com/quest=27950
![GitHub Logo](http://wow.zamimg.com/uploads/screenshots/resized/273366.jpg)
Esta quest es bien chistosa y tambien su historia. Se supone que vas a ayudar a Gluber para quitarle su maldicion. Pero se convierte por la sobrecarga en PAVO ASADO :P

---

Bien, este NPC es el que te da la quest.
Comandante Schnottz
http://es.wowhead.com/npc=47159
![GitHub Logo](http://wow.zamimg.com/uploads/screenshots/thumb/196778.jpg)

PERO OJO con las coordenadas 24.4 - 64.2

-= BUG =-
Cuando te da la quest te pide que hables con el, cuando estes listo para ver el ritual.
Entonces, haces CLICK sobre el para ver la ventana de dialogo y luego CLICK en "estoy listo" (supondo) Ahora les explico por que.

---

-=BUGs alternativos =-
WoW... esto si les llevara algo de tiempo en arreglar toda la zona.

La zona se llama Embarcadero de Schnottz. Y el principal NPC de este lugar es el mismo Comandante Schnottz.

Pues da la casualidad que hay varios NPC de el mismo, en el mismo lugar PERO en un lugar que no deberia de estar (o no deberian de estar :P)

![WoWScrnShot_040713_211026](https://f.cloud.github.com/assets/2059256/350032/c483acc0-a002-11e2-9c3a-92c784901b9f.jpg)

Bien, el Segundo de izquierda a derecha es el que te da la quest. PERO... OJO creo que cada uno de ellos estan en una ETAPA diferente de la historia. Por que cada uno te da una quest direfente.

Gluber! es la 3ra quest de una cadena de quest. Pero este NPC te da otras quest. Asi que supongo....

---

-=Teoria=-

Si eliminas un NPC de el mismo creo que tambien eliminas la quest (mas bien una de 6 quest incluyendo una de la CADENA de quest). Porque? si no mal recuerdo cada uno de ellos te da una quest diferente.

Entonces creo que la solucion seria CREAR un NPC que tenga todas las quest incluidas. O ponerle auras a cada NPC para que desaparescan y aparescan dependiendo en que parte de la historia te encuentres.

OJO te recuerdo que ellos estan mal hubicados. Las coordenadas son las que te estoy poniendo arriba. (segun WOWHEAD)

--- Afuera de la choza encuentras a varios NPCs incluyendo 2 pavos. Los NPCs pertenecen a varias quest asi que creo que no deberian de ser tocados por que pertenecen a una de las quest.

---

NOTA ADICIONAL:
![WoWScrnShot_040713_215646](https://f.cloud.github.com/assets/2059256/350113/4abf40aa-a009-11e2-936d-f0314675460b.jpg)

Aunque si lees el dialogo EL dice que "depues del fracaso del ritual voy a cobrartelo" He de suponer que ese NPC a de ser el NPC que aparece despues de que esta quest ahiga sigo completada. Y debe de haber otro NPC anterior el que debiera de dar la quest no?

![Untitled](https://f.cloud.github.com/assets/2059256/350140/bc67fd7c-a00a-11e2-8c1a-d2b8bf49ae04.jpg)
En esta imagen podras ver el NPC que da la quest con el simbolo "!" amarillo, pero el que estoy señalando esta como ENEMIGO. Bueno, si mi intuicion no me falla, creo que este debe de tener el dialogo "Im ready" o algo asi, y el que deberia de darte la quest. (creo es una supocicion).

---

-=SUGERENCIA=-
Si es tanto rollo, para poder arreglar la zona. Tengo una sugerencia.

Poner la quest (esta quest la que estoy reportando por que las demas si estan funcionando) como auto-completada.

Facil no, simlemente que seria una lastima no poder ver la escena cuando el pavo es asado :P

**Comment by WarSxNes** [comment]
Me hago un autocomentario :P para contarles que esta quest hace referencia a [Joesph Goebbels](http://en.wikipedia.org/wiki/Joseph_Goebbels) un personaje de la Segunda Guerra Mundial.

[Comandante Schnottz](http://es.wowhead.com/npc=47159)
![GitHub Logo](http://wow.zamimg.com/uploads/screenshots/thumb/196778.jpg)
-= Es ni mas ni menos que =-
[Adolf Hitler](http://en.wikipedia.org/wiki/Adolf_Hitler)
![GitHub Logo](http://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Bundesarchiv_Bild_183-S33882%2C_Adolf_Hitler_retouched.jpg/230px-Bundesarchiv_Bild_183-S33882%2C_Adolf_Hitler_retouched.jpg)

Si es que logran arreglar la quest veran este dialogo:

Commander Schnottz says: Very vell, zhen. Let me just check my notes vone lasht time...
Commander Schnottz says: Mmm-hmmm, yes, yes... simple enough...
Commander Schnottz yells: Oh, Gobbles! Ve're ready to begin! Come, come!
Commander Schnottz says: Hold on, Gobbles! Shtand back everyvone!
Commander Schnottz yells: VHAT!
Commander Schnottz says: My poor Gobbles...
Commander Schnottz yells: Vhat could haf possibly gone vrong? I followed every lasht detail...
Commander Schnottz says: Vait a shekkont! Vhat's zhist?
Commander Schnottz yells: You only brought me eight idols!
Commander Schnottz yells: Zhe ritual shpecifically calls for NINE!
Commander Schnottz yells: NINE! NINE! NINE! NINE! NINE!
Commander Schnottz yells: Out of my sight, vizh you! Auch...

Referente a un episodio de South Park :P o un episodio de la pelicula.

[South Park- Turkey Gobbles - ThanksGiving](http://www.youtube.com/watch?v=gzIxx03ldOA)
[Hitler NEIN! ](http://www.youtube.com/watch?v=xoMgnJDXd3k&f)

Pero lo mas chistoso es que los tontos de BLIZZARD se equivocaron por que vocalmente Nine! en aleman quiere decir NO!... y si claro en su traduccion escrita en ingles significa el numero 9 :P

**Comment by redneo** [comment]
Esa zona es un infiernooooooooooooooooooo!!! a ver que puedo hacer....

Vale, he movido alguno de los tipejos y la misión que comentas la he puesto que cuando le des al bocadillo (ya has asegurado el perimetro) se complete, pero OJO!

Esa misión no tiene quien la recoja, con lo cual, cuando la completas es como si la hubieras entregado peeeeeeeero, es una de las pocas misiones que no da oro para cerciorarse por chat que la has terminado, simplemente, desaparece de la lista de misiones.

Como bien dices es una pena no poder hacer la animación ni meter los textos... siempre nos quedará youtube

Edito... No es como youtube, pero casi, jejejeje

Cierro bug, si no hay mayor inconveniente.
