### ISSUE TITLE
That's IT - WarFace-WOW - Bwahaha!!

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1013]
Es una broma no?

Acaso este Emulador le pertence a otro server? :p

Hoy 4/7/2013 encontre una quest llamada That's IT en el Obelisco de las Estrellas - Uldum

Con el NPC [Harrison Jones](http://es.wowhead.com/npc=45296) que esta hubicado no dentro del templo si no afuera.

![WoWScrnShot_040713_235023](https://f.cloud.github.com/assets/2059256/350364/300b013a-a019-11e2-8161-5ea2c89fed28.jpg)

![WoWScrnShot_040813_000940](https://f.cloud.github.com/assets/2059256/350398/8b97de86-a01b-11e2-8812-be13b1e08c00.jpg)

![WoWScrnShot_040813_001531](https://f.cloud.github.com/assets/2059256/350416/7d54d364-a01c-11e2-9c41-51ecfe550093.jpg)
1. OK, para comenzar este NPC deberia estar dentro del templo. :P y esta fuera de el.
2. Este NPC tiene una quest llamada THAT'S IT que le hace propaganda a un SERVER llamada WARFACE-WOW ..... Bwahaha!!! es una broma no?

[WarFace-WoW](http://www.youtube.com/watch?v=teYYNVLx9cY)
http://warface-wow.com/ - Por fortuna el website de este sever creo que se callo o el mismo esta MUERTDO ;P

---

Por si no saben leer ingles les hago la traduccion.

Diagolo:

Eso es!
Ahora tu estas Listo para explorar EL NIVEL  "85"
Ve a tu cuidad principal y busca a cualquier grupo para ir de/a Mazmorras o Banda! O si quieres solamente puedes hacer Campos de Batalla Aleatoreos! Recuerda de votar por Warface-WoW cada Dia!
- Buena Suerte!

Objetivos de la Mision
Hablar con Harrison Jones.

---

Bwahahah!! ("\;..;/") chistoso no :P aunque no es mala IDEA que en lugar que sea warface-wow dijiera Reing of Darkness no? :)

Alfin y al cabo no es tan mala la idea.

---

NOTA: OJO MUCHO OJO

No borren este NPC por que este tiene varias quest. Simplemente esta mal hubicado, y obvio tiene incluida esa propaganda.

![gitlogo](http://wow.zamimg.com/uploads/screenshots/resized/301814.jpg) Ahi en esta imagen podran ver al fondo que este esta dentro del templo. (fuente wowhead)

**Comment by WarSxNes** [comment]
Me hago un auto-comentario para REPETIRLES este NPC tiene otras quest.

http://es.wowhead.com/quest=27517

Tiene 4 quest en total + 1 quest propaganda.
1. Preparate
2. Rompiendo el equilibrio
3. Tras la caida
4. Haz los honores.
5. THAT'S IT = propaganda :P

---

Y saben que: indagando por CARBONITE y WOWHEAD creo que he descubierto que estos npc estan bug les explico:

[npc=45296](http://es.wowhead.com/npc=45296) deberia estan dentro del TEMPLO y no tener la quest propaganda.
[npc=45180](http://www.wowhead.com/npc=45180) se recuerdan del que dije que estaba bien. Pues no esta bien. supuestamente ese te debe de dar otra cadena de quest.

Pero la verdad no estoy muy seguro necesito leer bien los argumentos por que asegun el que esta fuera te da una cadena de 3 quest y luego sigue con el que esta abajo dentro del templo con las otras 4 escritas arriba ^

No cierren el post para escribirles cuando termine de leer el argumento.

---

Ok, creo que encontre la Linea de Tiempo de ULDUM en esta pagina. (haber si es de utilidad para crear las cadenas)

[ULDUM chain quest wowwiki.com](http://www.wowwiki.com/Uldum_quests) esta en ingles pero gracias al registro de carbonite les dire cuales he hecho de la linea de "La historia de Harrison" haber si las pueden arreglar. (aun sigo leyendo el argumente no cierren)

---

![Untitled2](https://f.cloud.github.com/assets/2059256/350698/b0442718-a029-11e2-8a27-4f9b04dd0a5c.jpg)
OK, segun wowwiki y la cronologia de CARBONITE (addon) esta claro que las cadenas de quest estan mal ordanizadas. Veran en la pequeña grafica que hice las quest tachadas son las que he completado; Pero los numeros rojos estan mal organizados por que asi fue como las hize segun el carbonite.

La pagina wowwiki esta muy Buena tiene todas las lineas de tiempo de cada zona haber si les ayuda en algo esa pagina.

---

---Nota:--- Agrego que las quest que no he marcado son las que no he podido empezar por que no las encuentro. EJEMPLO: [Just the tip](http://www.wowhead.com/quest=27176/just-the-tip) esta comienza segun wowhead con este objeto [Elaborate Disc](http://www.wowhead.com/object=205266) ya lo he buscado y no lo encuentro creo que voy hacer un Nuevo post para reportar esta quest.

Oh! ya pueden cerrar :) espero les ayude la pagina http://www.wowwiki.com

**Comment by redneo** [comment]
Movidos algunos de los Harrison.
Borrada esa mision
Cambiada http://www.wowhead.com/quest=27141 para que la recoja el harry correcto
(como siempre tras una caida, jejeje)
