### ISSUE TITLE
Just the Tip - Solo la parte superior

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1014]
Bien para completar una quest primero hay que cogerla (tomarla en mi region ;P).

[Just the Tip](http://es.wowhead.com/quest=27176)

Comienza con [Elaborate Disc](http://www.wowhead.com/object=205266) coordenada 64.9 - 29.5
Termina con [Harrison Jones npc=45180](http://es.wowhead.com/npc=45180) coordenada  64.6 - 28.6 en las afueras del templo.

---

BUG: no esta el disco por ningun lado.

**Comment by redneo** [comment]
Fixed (cuando caiga el server)
