### ISSUE TITLE
Haz un favor al mundo

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1015]
Haber si entiendo. Segun wowhead y wowiki esta quest es auto-aceptable y se auto-entrega.

[Haz un favor al mundo](http://es.wowhead.com/quest=27187) Comienza matando a este NPC [Mogrollo](http://es.wowhead.com/npc=45204) que esta justo al lado donde completas el objetivo de otra quest [Solo la parte superior](http://es.wowhead.com/quest=27176). Provocando que este te ataque y cuando lo mates auto-aceptes la quest. Y al completar el objetivo se auto-entrega y ganas la exp.

coordenadas 68.0 - 31.6

-= bug =- Lo matas y no pasa nada no te dan la quest.

**Comment by redneo** [comment]
Fixed (cuando caiga el server)
