### ISSUE TITLE
Lecciones del pasado

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1018]
[Lecciones del pasado](http://es.wowhead.com/quest=27541) Esta quest es bien funciona al 100%

Haciendo referencia a post https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1013 Si es que ya reubicaron a este
[Harrison Jones npc=45296](http://es.wowhead.com/npc=45296) 
![WoWScrnShot_040813_092619](https://f.cloud.github.com/assets/2059256/352632/fada9984-a069-11e2-8ab8-b17404af1bd3.jpg)
Este deberia estar debajo del templo. (si ya esta reubicado ignoren este reporte por que la quest es bien)

Adiciono que segun la historia este NPC deberia estar muerto.
[Explorador de Schnottz](http://es.wowhead.com/npc=45874)
![gitlogo](http://wow.zamimg.com/uploads/screenshots/thumb/205377.jpg)
Pero miren esta vivito y coleando :P
## ![WoWScrnShot_040813_092544](https://f.cloud.github.com/assets/2059256/352647/6967476c-a06a-11e2-9ac9-fd58eb7be1f6.jpg)

-Error- solamente reubicar al npc [Harrison Jones npc=45296](http://es.wowhead.com/npc=45296)

**Comment by redneo** [comment]
Fallaba alguna cosa más a parte en la zona, faltan unas trampas, a ver si encuentro la id y las pongo.
