### ISSUE TITLE
Por la luz de las estrellas

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1019]
Relacionado con este post https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1018

[Por la luz de las estrellas](http://es.wowhead.com/quest=27549) Esta quest esta auto-completada y no deberia de estar asi. _(si es que alguien ya la habia reportado y la arreglaron poniendola auto-completable por que era muy dificil arreglarla ignoren este post)_

---

-=Error=-
Se supone que la aceptas y te dan unos [Anteojos de zafiro](http://es.wowhead.com/item=61509) que funcionan como un item para la cabeza. Te lo pones y ahora ya puedes ver unos Objetos invisibles. [Luz estelar suspendida - Objeto](http://es.wowhead.com/object=205582)

Ya que logras ver estos simplemente recolectas lo que te pide la quest. [Luz estelar suspendida - Item](http://es.wowhead.com/item=61376), la completas y la vas a entregar.

**Comment by redneo** [comment]
Reparada
