### ISSUE TITLE
Rompiendo el equilibrio

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1020]
[Rompiendo el equilibrio](http://es.wowhead.com/quest=27431) Esta quest te la deberia dar este NPC en un orden cronologico. Yo ya termine la cadena de quests, y nunca me dio dicha quest ;P [Harrison Jones npc=45296](http://es.wowhead.com/npc=45296) Comienza con el y termina con el mismo.

[Rompiendo el equilibrio Video](http://www.youtube.com/watch?v=KlmWgihKmzk&list=PLC6E622FF44143D21) Asi deberia de ser ;)

-=bug=- El npc mencionado no te da la quest en orden cronologico. O por lo menos deberia dartela.

**Comment by redneo** [comment]
Ya tendria que darlo en orden, lo que no se si funcionara (me juego el cuello que no)
