### ISSUE TITLE
La secuencia errónea

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1027]
En referencia a este post el cual sigue BUG pero es otra quest relacionada. https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1002

[La secuencia errónea](http://es.wowhead.com/quest=27058) Es la quest que le sigue al post anterior. Y me Adelanto a decir que seguramente esta bug.

---

-=Bug=-

Despues de aceptarla debes ir a [Controlador de puerta](http://es.wowhead.com/object=205161) para hacer lo que te pide la quest.
![WoWScrnShot_040813_160053](https://f.cloud.github.com/assets/2059256/354497/ecfcc86e-a0a0-11e2-92c6-090af1d29e38.jpg)
Pero no esta en su lugar este objeto. Asi que cuando arreglen la quest anterior obvio esta estara bug por que el objeto no se encuentra en su lugar.

_-Nota-_ esta quest empieza y termina con el mismo NPC de la quest anterior. (post anterior)

**Comment by redneo** [comment]
Arreglado
