### ISSUE TITLE
Inteligencia artificial

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1028]
[Inteligencia artificial](http://es.wowhead.com/quest=27760) Esta ques comienza una NUEVA CADENA DE QUEST.

**-=BUG=-**
Para comenzar la quest necesitar coger/tomar este item [Comunicador A.I.D.A.](http://es.wowhead.com/item=62483)
El cual segun wowhead el mejor mob para obtenerlo es este [Miembro de expedición](http://es.wowhead.com/npc=46920) este tiene el 100% de tirarlo **pero no esta por ningun lado** no esta en la coordenadas  que indican.

Los otros mobs:
http://es.wowhead.com/npc=46590
http://es.wowhead.com/npc=47014

Que tienen menos %%% de tirarlo. Ya voy matando varios de ellos y nada que lo tiran.

HE de suponer que el LOOT debe estar bug.

**Comment by WarSxNes** [comment]
Me auto-contesto por que no se si fue por que el server se estaba CALLENDO la verdad es que no estoy seguro. Pero cuando llegaba al lugar, no habia ningun NPC. Ahora que el server esta estable hay un centenar de enanos y el Boss :P Pero eso si el LOOT esta bug por que se supone que los miembro de expedicion tienen el 100% de tirar el item de la quest.

**Comment by redneo** [comment]
Reparadada
