### ISSUE TITLE
Una distracción que desarma - Terminal A.I.D.A.

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1029]
Haciendo referencia al post https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1028
[Una distracción que desarma](http://es.wowhead.com/quest=27761) Esta quest al parecer no esta relacionada con la anterior. Pero segun WOWWIKI.COM esta esta relacionada en el argumento **Curse of the Tombs**

http://www.wowwiki.com/Uldum_quests

Bien esta quest EMPIEZA Y TERMINA con [Terminal A.I.D.A.](http://es.wowhead.com/object=206293)

---

**-=BUG=-**
Si es que esta relacionada, al momento de arreglar la quest anterior a esta; Es seguro que tambien esta estara bug.

![WoWScrnShot_040813_201024](https://f.cloud.github.com/assets/2059256/355056/253b57fa-a0c3-11e2-9f7f-7d9c70ad4841.jpg)

**Comment by WarSxNes** [comment]
AAaA...!!! que lastima que no ahigan visto a tiempo este post.

Bueno acaba de **caer** el server y se aplicaron los cambios despues de 18hrs y fui a investigar la quest anterior. Y ya funciona ahora el problema es que la maquina no esta **:(**

**Comment by redneo** [comment]
SI que lo leí (suelo leer todos los de misiones y alguno más) lo que pasa es que me lié con el tema de los portales, cosa que voy a estar haciendo unos dias...

**Comment by redneo** [comment]
Puesto el gob, es de suponer que irá bien cuando se caiga el server!
