### ISSUE TITLE
Naraat - Y sus quest Bug

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1030]
Bien este NPC [Naraat el Hablatierra](http://es.wowhead.com/npc=45226) tiene varias quest. Y al parecer estan bug.

---

Este NPC esta en ventormenta en la isla donde estan todos los portales. Se supone que cada portal deberia estar BLOQUEADO y se desbloquean asta que completas ciertas quest.

Me di cuenta del problema por que estoy haciendo la cadena de quest que lleva a Infralar:
[Infralar - quest](http://www.wowwiki.com/Deepholm_quests) _fuente WOWWIKI_

---

**CADENA DE 7 QUEST**
1 [Una invocación personal](http://es.wowhead.com/quest=28825) Naraat te esta esperando para completar una quest. No tiene comienzo. Solamente hablas con el y la entregas. **BUG**

2 [El ojo de la tormenta](http://es.wowhead.com/quest=28826) Aceptas la quest. Y tienes que ir y hacer CLICK en [Aguas de Clarividencia](http://es.wowhead.com/npc=50088) despues de ver la animacion se completa y se la entregas a Naraat. **BUG**

Bien en este momento solamente hablare de estas 2 por que me interesa Infralar.

---

**HACIA INFRALAR**

Tras haber completado la cadena anterior y las primeras 2 quest. Ahora estas listo para recibir las siguientes quest.
1. [Se busca héroe: ¡Infralar!](http://es.wowhead.com/quest=27727) Esta es una de 4 quest que puedes **coger/tomar** para ir a infralar. Pero por ser la mas cercana hablare de esta. _(esta en ventormenta)_ **funciona al 100%**
2. [La Vorágine](http://es.wowhead.com/quest=27203) Tras haber completado la quest anterior **O** una de las otras 3. Se habre un portal hacia _la voragine_. Ahora eres elegible para **coger/tomar** esta quest, y atravezar el portal que esta ahi mismo.
   EMPIEZA: con Naraat - TERMINA: con [Thrall](http://es.wowhead.com/npc=45042)
   **Esta esta BUG** por que la anterior ya la complete y Naraat no me la dio. Y el portal no esta.
   ![WoWScrnShot_040813_220653](https://f.cloud.github.com/assets/2059256/355356/5bed4e12-a0d6-11e2-9231-b58123e778f3.jpg)
   Asi se deberia de ver.
   ![Portal](http://wow.zamimg.com/uploads/screenshots/thumb/207004.jpg)
   [Portal a la Vorágine](http://es.wowhead.com/spell=84463)

---

Bien por el momento hablare solo de estas quest. Para seguir reportando primero debo completar estas.

**Comment by redneo** [comment]
Tienes toda la razón, creo que me voy a pasar un tiempo capando los portales de la isla famosa tanto horda como alianza, ordenando las cadenas de misiones y haciendo que solo se puedan usar los portales si tienes hecha cierta quest, que es como tendría que ser.

Edito:
Cadena de misiones arreglada, Portal a Infralar, capado hasta que no se termine la misión http://es.wowhead.com/quest=27123
Portal a la Voragine, spawneado y solo se puede usar tras haber acabado la misión http://es.wowhead.com/quest=27203

Pronto seguiré con los otros portales.

**Comment by WarSxNes** [comment]
Cierto pero las mensionas alrevez.

1 http://es.wowhead.com/quest=27203 **La Vorágine**
2 http://es.wowhead.com/quest=27123 **Infralar, reino de la tierra**

Asi como explique arriba Primero completas la cadena anterior que se supone te lleva a Vashj'i _(zona lvl 80-82)_
Cadena de 7 quest relacionada con:
[Una invocación personal - http://es.wowhead.com/quest=28825](http://es.wowhead.com/quest=28825)
[El ojo de la tormenta - http://es.wowhead.com/quest=28826](http://es.wowhead.com/quest=28826) _esta segun es requisito para abrir el portal hacia la voragine segun comentarios de wowhead._

Se supone que para ese entonces ya eres lvl 82 o mayor. Segun el argumento en Vashj'i (supongo) te estas preparando para aventurarte hacia La Voragine tras completer la quest 27203 ahi mismo te montas a un hipoglifo que te lleva hacia Infralar 27123 [Infralar, reino de la tierra - **VIDEO**](http://www.youtube.com/watch?v=MYoHquuhXUg&feature=youtu.be) _Tal y como tu lo indicas nomas que alrevez :P_

---

**4/9/2013 Hora del Pacifico -8 UTC**
Edito: Hoy despues de 18hrs callo el server y alfin pude apreciar los cambios.

Ya probe el portal sin la quest. y no esta bloquedo :P pude entrar. Ahora tome la quest y automaticamente me invoco a la voragine 100% tal y como deberia de ser.

Bueno, lastimosamente no se vio la escena del hipoglifo al tomar la quest 27123, automaticamente me invoco a infralar. Y pude entregar la quest. _(lastima que la parte del hipoglifo no se pudo apreciar)_

---

Bien, solo queda una cosa por hacer. Bloquear los portales asta que se completen estas quest.
Y supuestamente estas quest se habilitan al completar. [El ojo de la tormenta](http://es.wowhead.com/quest=28826) _(segun comentarios de wowhead)_ Pero algo es algo y esta bien.

**Comment by WarSxNes** [comment]
Ok me auto-contesto para decirte que los NPC de La Voragine tienen una faccion erronea.

[Thrall](http://es.wowhead.com/npc=45042)
[Dracoleon](http://es.wowhead.com/npc=45005)
[Aggra](http://es.wowhead.com/npc=45006)

Deberian de ser faccion [El Anillo de la Tierra](http://es.wowhead.com/faction=1135)

Bien y en vista de que el Dracoleon no se puede usar para viajar a infralar tengo una sugerencia.

---

Cuando terminas la quest que te lleva a infralar. Ya no hay forma de salir de la voragine _(si es que se te ocurre regresar)_, por que el Dracoleon no funciona. Seria de mucha utilidad si hubieran portales de regreso a Ventormenta y Ogrimar no?

**nota:** _ahora mismo tengo que esperar 30mins para utilizer mi piedra hogar y salir de ahi :P_

**Edito:** encontre estos spells en wowhead haber si sirven de algo
[Teletransporte al barco- spell=95772](http://es.wowhead.com/spell=95772)
[Teletransporte de barco- spell=134163](http://es.wowhead.com/spell=134163)
Se me ocurrio que en lugar de aplicarselo al barco se le aplicara al Dracoleon una montura-vehiculo que se moviera sola y que te llevara a infralar.

**Comment by ghost** [comment]
Bueno como aquí esta el tema de los portales, no se si estara bug o no, pero el unico portal que ya no puedo ver es el de Vash'jir (que ya hice las misiones tanto orden jefe de guerra como la otra, y sigo sin poder ver el portal), los demás siguen ahi aunque no haya hecho las misiones.

**Comment by crowel** [comment]
Tengo el mismo problema que tu Lv, no puedo ver el portal de Vash´jir.

**Comment by WarSxNes** [comment]
![WoWScrnShot_040913_160930](https://f.cloud.github.com/assets/2059256/360782/f5473ea0-a1a9-11e2-8d74-9efce8fe065a.jpg)
Una imagen vale mas que mil palabras :P Yo veo a todos ahi.

**Comment by crowel** [comment]
![WoWScrnShot_041013_141929](https://f.cloud.github.com/assets/3537253/361936/ea8c4c06-a1d8-11e2-8fc3-adfb88e62e11.jpg)

**Comment by WarSxNes** [comment]
**CROWEL** que nos quieres decir ahi? que no esta el portal de Vashj'ir?

Ya hiciste las quest de introduccion?

En la imagen que yo deje de ventormenta yo puedo ver todos los portales. Pero yo ya habia hecho las quest de introduccion.

 _O y para la proxima digan si son GORDAS o Alis :P_

**Comment by redneo** [comment]
Puede que me lo haya cargado con el tema de cambio/arreglo de portales, pronto lo tendreis...
