### ISSUE TITLE
Prepárate - el esqueleto

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1035]
http://es.wowhead.com/quest=27517
Empieza: http://es.wowhead.com/object=205540
Termina: http://es.wowhead.com/npc=45296

Haces CLICK sobre el esqueleto y te tendria que dar la quest y este item
http://es.wowhead.com/item=61322

Luego ya solo consigues 5 mas de otros que esqueletos que anden por ahi completas y entregas la quest.

**BUG** no esta el esqueleto.

**Comment by redneo** [comment]
arreglado
