### ISSUE TITLE
Tierras crepusculares - Cadena de quest "intro" bug.

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1037]
http://es.wowhead.com/quest=28716 Se busca héroe: ¡Tierras Altas Crepusculares! <<< 100%
http://es.wowhead.com/quest=26960 Mi hijo, el Príncipe <<<<< BUG

Esta comienza y termina con
http://es.wowhead.com/npc=29611 Rey Varian Wrynn <Rey de Ventormenta>

Y se supondria que las demas quest deberian de estar ocultas asta que completes la cadena de Anduin.

---

Bueno para comenzar la que esta bug:

**BUG** Hablas con el rey, aceptas la quest y luego justo al lado de el esta Anduin haces CLICK te presentas y completas la quest y la entregas.

**Comment by WarSxNes** [comment]
Cadena de quest - Anduin Wrynn
![WoWScrnShot_040913_174631](https://f.cloud.github.com/assets/2059256/360026/74e72402-a17a-11e2-92be-5742f8ea6f8f.jpg)
Como veran en mi crokis :P la **cronologia** de la cadena esta erronea.

2 http://es.wowhead.com/quest=26997 **Sospechosos habituales** <<< **BUG** tienes que ir a hablar con los [Trabajador del muelle de Ventormenta ](http://es.wowhead.com/npc=29152) pero no te cuentan.

3 http://es.wowhead.com/quest=27060 **¡La madre del ternero!** <<< **BUG** esta no la entiendo pero parece que te tiene que acompanar Anduin asta la escena del crimen. Y estando ahi supongo que se debe de completar la quest. **en la escena del crimen tendria que hacer un cadaver o algo pero esta limpio**
![WoWScrnShot_040913_183742](https://f.cloud.github.com/assets/2059256/360114/7808983c-a17f-11e2-820b-e46c8abca2a7.jpg)

**Comment by WarSxNes** [comment]
Otra cadena de quest relacionada:
![Untitled3](https://f.cloud.github.com/assets/2059256/360095/3d59d530-a17e-11e2-8b03-c724f9f08f85.jpg)
http://es.wowhead.com/quest=27038 **Piezas que faltan**
**BUG** ---- Como dice el titulo de la quest _Piezas que faltan_ :P si es cierto hacen falta no estan >.<
http://es.wowhead.com/item=60757

**NOTA** me di cuenta que tambien esta mal el LOOt de las ratas. 
http://es.wowhead.com/npc=49540 Rata de Ventormenta
Ya extermine a todas las ratas de ventormenta y ninguna tiro las piezas 8% segun wowhead

Las ratas deberian ademas tirar varias cositas.

**Comment by redneo** [comment]
Estoy con ellas, solo me ha llevado todo el dia ordenarlas, y no se si estaran bien ordenadas....

**Comment by redneo** [comment]
Arreglada toda la cadena de misiones, los portales, el spawn de npcs, gobs y demas relacionado con las misiones, cuidado con el orden, que antes no estaban ordenadas!

Solo de la alianza, por ahora
