### ISSUE TITLE
[Bug > Campos del Torneo Argenta > Quest]

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.0.6a#1038]
Buenas, vengo a informar que la quest ''El desafio del aspirante'' ( http://es.wowhead.com/quest=13680/el-desafio-del-aspirante )  no anda funcionando, puesto a que por mas valerosos argenta que me enfrente y derrote ninguno me cuenta, aqui les dejo unas sucesiones de screenshots de el momento de la invocacion, el momento cuando llega, el momento cuando luchamos y el esta a punto de morir y el momento en el que el se desvanecio sin haberme contado en este mismo orden sucesivo: 
![WoWScrnShot_041013_200623](https://f.cloud.github.com/assets/3613748/365403/1d8bef8c-a245-11e2-9401-45475d3326a5.jpg)
![WoWScrnShot_041013_200632](https://f.cloud.github.com/assets/3613748/365404/1dbc74cc-a245-11e2-8759-78b2562e4cf4.jpg)
![WoWScrnShot_041013_200641](https://f.cloud.github.com/assets/3613748/365405/1dc03904-a245-11e2-8652-84406b46eba5.jpg)
![WoWScrnShot_041013_200644](https://f.cloud.github.com/assets/3613748/365406/1dc7efdc-a245-11e2-9d04-c2e0f6c322dc.jpg)
![WoWScrnShot_041013_200649](https://f.cloud.github.com/assets/3613748/365407/1dcb659a-a245-11e2-9ef7-74aacf02c81d.jpg)
espero que puedan repararlo, Gracias por su atencion.

**Comment by ghost** [comment]
Ya lo reporte #967 esta en el comentario.
