### ISSUE TITLE
Bug - Huargen [Hacia la mansión Cringris] [Éxodo]

### ISSUE THREAD

**Issue by Detsu** [RoDNet/Bugtracker-Infinium-4.0.6a#104]
Hola, estoy por acabar esta misión pero donde supuestamente ha de estar la chicha que me acaba la misión no hay nadie

Ayuda para solucionarlo !

Unos compañeros me han comentado que la misión Éxodo tampoco funciona, que hablan con el chico pero no dice nada, arreglar, las misiones Huarguen Porfavor !!

Un saludo !

Añado misiones: 
http://es.wowhead.com/quest=14465#.

http://es.wowhead.com/quest=24438

**Comment by searum** [comment]
Arreglado para la siguiente actualizacion
