### ISSUE TITLE
El antiguo cuartel

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1041]
Relacionado con el post https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1037

[El antiguo cuartel](http://es.wowhead.com/quest=27072) Tienes que matar a los [Cultor enloquecido](http://es.wowhead.com/npc=44814)

**BUG** no estan por ninguna parte.

**Comment by redneo** [comment]
Arreglado
