### ISSUE TITLE
Portal a Hyjal bug

### ISSUE THREAD

**Issue by dragonoit** [RoDNet/Bugtracker-Infinium-4.0.6a#1045]
hace aproximadamente un par de semanas podia entrar lo mas bien y ahora me pide realizar la quest
http://es.wowhead.com/quest=25316/mientras-hyjal-arde#.
pero voy a buscarla y no me la dan (y si es que la hize porque la verdad no me acuerdo ahora  no me la toma )

**Comment by dragonoit** [comment]
ya encontre el problemas tema cerrado xD

**Comment by ghost** [comment]
Si es tema cerrado.. ¿por qué no lo cierras?
