### ISSUE TITLE
Apuntando alto - Tie. Altas Crep. - Nueva cadena

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1046]
http://es.wowhead.com/quest=28598 <<< **Apuntando alto**
Empieza
Termina
http://es.wowhead.com/npc=49020 <<< **Fargo Cierrasílex**

![Untitled](https://f.cloud.github.com/assets/2059256/370891/07456192-a30b-11e2-9136-e1eca4590f30.jpg)

**BUG**
se supone que debes ir a una nave aerea que esta sobre-volando el lugar. Te montas/subes **O** el mismo Fargo lo hace, y te lanza por el cañon cierrasilex.

Debes completer 2 objetivos.
![canon](http://wow.zamimg.com/uploads/screenshots/thumb/267540.jpg)
![polvora](http://wow.zamimg.com/uploads/screenshots/thumb/240677.jpg)

Las imagenes hablan por si solas.
1 ser lanzado por el cañon cierrasilex.
2 colocar los explosivos en el centro de la nave.

---

**SUGERENCIA**
Para completer el objetivo de ser lanzado. Podrian hacer que haciendo CLICK sobre el cañon cierrasilex te teletransporte a la nave. Y asi poner los explosivos, y que te cuente el 1er objetivo. _dos pajaros de un tiro_

Talcual han arreglado otras quest. Que cuando haces CLICK sobre determinado NPC te invoca hacia determinado lugar.

---

**--NOTA--**
Les recuerdo que si quieren ver la LINEA de tiempo de determinada zona vean [WoWwiki - Twilight Highlands quest](http://www.wowpedia.org/Twilight_Highlands_quests) Y asi podras darle seguimiento a una zona por si hay mas bugs.

![WoWScrnShot_041113_180347](https://f.cloud.github.com/assets/2059256/370939/30755bf6-a30d-11e2-89a1-72cf9c5ee79d.jpg)

**Comment by redneo** [comment]
Arreglada sin muchas complicaciones.
