### ISSUE TITLE
Conquista - Tie. Altas Crep. - Cadena 2

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1047]
Haciendo referencia a la cadena anterior ya que esta sigue despues. https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1046

http://es.wowhead.com/quest=27366 <<<< **CONQUISTA**
![Untitled2](https://f.cloud.github.com/assets/2059256/371016/99cc35d4-a312-11e2-8057-ca673e5aef41.jpg)

Bien esta es simple de explicar.
![WoWScrnShot_041113_184543](https://f.cloud.github.com/assets/2059256/371029/4d2b671c-a313-11e2-9bf6-fb0965a3fe53.jpg)

Entendieron o.0?

:P

**Comment by redneo** [comment]
http://es.wowhead.com/npc=45175 cambiado de facción, se les tendria que poder dar.
