### ISSUE TITLE
[Item Arqueologia]Hacha barbada Nafsavar

### ISSUE THREAD

**Issue by Gorland** [RoDNet/Bugtracker-Infinium-4.0.6a#1052]
Este hacha es de Arqueología y se vincula a la cuenta.
Como se puede ver la leyenda dice que se necesita ser nivel 71 para usarla,
pero al clickar para equiparla dice que se debe alcanzar nivel 80, como se ve en el aviso  en rojo.

![WoWScrnShot_041213_165841](https://f.cloud.github.com/assets/4137967/373490/7577f6ee-a382-11e2-8925-93f979f41b2e.jpg)

**Comment by redneo** [comment]
http://www.wowpedia.org/Nifflevar_Bearded_Axe ahi dice que en la versión 406 se bajo de 80 a 71 el nivel requerido, con lo cual, ya se lo he bajado.
