### ISSUE TITLE
Barco de Ventormenta a Tundra Boreal

### ISSUE THREAD

**Issue by Sonnea** [RoDNet/Bugtracker-Infinium-4.0.6a#1056]
Hola, me gustarían que miraran el barco a Tundra Boreal desde Ventormenta, lo he cogido hoy dos veces y las dos me deja en Vashj'ir, y al estar ahi el personaje va deslizándose por el suelo y las monturas de ruta de vuelo van como a cámara rápida. 
Gracias.

**Comment by crowel** [comment]
Estas cojiendo el que no es, es uno que esta mas a la derecha al final del muelle.

**Comment by DatJetto** [comment]
De hecho son en el mismo sitio, lo que pasa que uno es ''EL KRAKEN'' y es un barco como los que hay en los astilleros, con un águila de mascarón y el que tu estás cogiendo es un barco con las velas rojas y negras que si, va hacia Vash jir.

**Comment by Sonnea** [comment]
Esq no me ha pasado a mi sola, ademas gente que ha cogido ese barco me lo ha dicho, lo he cogido tres veces y las tres veces me ha llevado al mismo sitio

**Comment by ghost** [comment]
El barco que te lleva a rasganorte es identico al barco que te lleva a vash'jir, e incluso algunas veces se "enciman", debes elegir con cuidado aunque no sé como porque como dije, son identicos xd.

**Comment by Alfonn** [comment]
Sonnea , a mi me pasó y tras el segundo intento me di cuenta, pasan 2 barcos, uno más ''cutre'' por así decirlo, y otro más adornado y grande, xD.

**Comment by redneo** [comment]
El de Rasganorte es mucho mas grande, El de Vashjir es mas pequeño y rojo
