### ISSUE TITLE
Misión "Te veo al otro lado" en Colinas Pardas

### ISSUE THREAD

**Issue by cuandoso** [RoDNet/Bugtracker-Infinium-4.0.6a#1058]
Esta misión requiere golpear 3 gongs para que el boss aparezca, pero el que está frente a la entrada de las ruinas no puede ser activado, y por lo tanto la misión no puede completarse.
http://es.wowhead.com/quest=12121
Gracias de antemano por su atención.

**Comment by redneo** [comment]
Arreglado
