### ISSUE TITLE
bug para mision Mi hijo, el Príncipe

### ISSUE THREAD

**Issue by kiiit** [RoDNet/Bugtracker-Infinium-4.0.6a#1059]
esta mision es importante por q asi se toma la cadena de misionespara el portal de las tierras altas crepusculares no se pude terminar el npcde el principe con finalisa la mision solo te habla

**Comment by DatJetto** [comment]
No entiendo por qué lo pones 2 veces pero te digo lo mismo: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1061

Mi hijo el príncipe: http://es.wowhead.com/quest=26960
Solo es una quest anexa.
 Esta es la cadena: http://es.wowhead.com/quest=28596

**Comment by WarSxNes** [comment]
Hi guys, esta quest yo ya la habia reportado y supuestamente ya esta arreglada.

Yo la complete hace mas de 7 dias. Y funciono al 100%

ahi les dejo el link https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1037

**nota** el post fue cerrado por que a segun ya fue arreglada la cadena de quest. **OjO** segun el _ARGUMENTO_ de cataclyms tu ya tienes que ser lvl 84 para ir a esa zona. Y para atravezar el portal o hacer uso de el, tienes que completar cierta cadena de quest.

**nota II** segun el argumento tendrias que haberte aventurado en las zonas posteriores a Tierr. Alt. Crepu. como Valshj'ir, Aldum, Hyjal, e Infralar.

**nota III** para mas info. visiten http://www.wowwiki.com/List_of_quest_areas _(engrish)_

**Comment by redneo** [comment]
El problema era que faltaba un npc, el principe de joven...
