### ISSUE TITLE
no puedo comprar Fórmula: vara rúnica de elementium

### ISSUE THREAD

**Issue by kiiit** [RoDNet/Bugtracker-Infinium-4.0.6a#1061]
ya que para comprar se pide ir alas tierras altas crepusculares y puedo ir pero no aparese el npc debido a q debo completar una cadena de misiones y no se puede completar por una q esta bug es esta "mi hijo,el principe" porfabor arreglad esta mision el rey pide q busken a su hijo q esta al lado de el y uno debe hablarle yo ya le e hablado pero no marca la mision osea esta bug porfabor arregladla

**Comment by DatJetto** [comment]
1 - Mi hijo el príncipe no forma parte de esa cadena, es una quest secundaria. Lo digo porque he completado la cadena perfectamente.
2 - Puedes ir volando XD 
3 - Esta es la cadena de quest perfectametne disponible: http://es.wowhead.com/quest=28596
