### ISSUE TITLE
bug para mision Mi hijo, el Príncipe

### ISSUE THREAD

**Issue by kiiit** [RoDNet/Bugtracker-Infinium-4.0.6a#1063]
repito esta mision es necesaria para poder aseceder ala otra secuencia de misiones no crean q lo ago por molestar nadie de la hermandad lucha o muere a podido aser las misiones devido a los bug porfabor revisen esto porfabor

**Comment by kiiit** [comment]
incluso si lees los comentarios de el mismo enlace de wow head te daras cuenta  es necesaria esa mision

**Comment by redneo** [comment]
Arreglado
