### ISSUE TITLE
Mision "Más ojos de basilisco" Bug

### ISSUE THREAD

**Issue by lllalvarolll** [RoDNet/Bugtracker-Infinium-4.0.6a#1064]
Buenas. La misión "Más ojos de basilisco" debería de ser una misión repetitiva y debería poderse hacer más de una vez para poder subir la reputación "los arúspices" (es la única forma de llegar a ser amistoso con los arúspices si eres odiado con "Los aldor" y "Los arúspices").

**Comment by redneo** [comment]
Arreglada
