### ISSUE TITLE
Loot de Mal Ganis en Matanza de Stratholme

### ISSUE THREAD

**Issue by Arezhas** [RoDNet/Bugtracker-Infinium-4.0.6a#1066]
Hola miembros del Staff
Me dirijo a ustedes con el proposito de comunicarles que el cofre de loot de Mal Ganis, que es el ultimo boss de Matanza de Stratholme esta bug puesto que no lo lotea.
Llevo tiempo intentando hacerlo para que me lotee el escudo llamado "Blason real de Lordaeron"
Les estaria muy agradecido si lo arreglaran, o en su defecto su pudieran darme el escudo antes nombrado, aunque preferiria que arreglaran el loot para que mas gente puediera beneficiarse.
Se me olvidaba, quiero dicho escudo para transfigurarlo ya que es el escudo que mas me gusta del wow.
Gracias por su atencion

**Comment by redneo** [comment]
Teoricamente arreglado (no lo he probado) tendrias que borrar temporales y esperar que el server caiga para poder lotearlo en heroico.
