### ISSUE TITLE
Sacerdote - Talento y Hechizos - Bug ?????

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1068]
Quiero aclarar que al igual que el PICARO esta informacion no esta en _WOWHEAD_ ni en ningun otro website. https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1055

_Lastimosamente despues de la actualizacion del parche 4.0.1 no entiendo por que motivo las descripciones de cada hechizo, carecen de detalle para describir la capacidad de estos_.

Bien voy a hablarles de un hechizo en particular. Y realmente espero que al tener la razon y puedan arreglarlo.

[RENOVAR](http://es.wowhead.com/spell=139/renovar) <<< lastimosamente la descripcion en wowhead es para MoP.

---

**N I V E L - 85**

![WoWScrnShot_041813_154608](https://f.cloud.github.com/assets/2059256/399805/908e25a0-a87f-11e2-8129-ea8925642d1c.jpg)

Bien como veran en mi crokis la sanacion base es de 1224p. _(sin PcH)_ ni _(equipo ni puntos de talento ni maestria)_

**Aclaremos algo** aqui el modificador es PcH y no Intel. + las mejoras que se obtienen de la rama de talentos y la maestria.

---

![WoWScrnShot_041813_163547](https://f.cloud.github.com/assets/2059256/399836/d6118c42-a880-11e2-8f1b-55c5fc6a63b9.jpg)

Bien como se habran dado cuenta la sanacion total que hago es de 1302 que incluye solamente PcH pues aunque en maestria diga que tengo 8p. creo que esto no cuenta, pues claramente dice que debo de escoger una rama de talentos para activarla.

Bien habiendo aclarado lo anterior voy a proceder a agregar un punto de talento y espero presten atencion a los cambios.

---

**RENOVAR MEJORADO**  _lvl1 5%_ - _lvl2 10%_
![WoWScrnShot_041813_164728](https://f.cloud.github.com/assets/2059256/399868/6c3d5678-a882-11e2-8e74-2efd75c74a3e.jpg)

![WoWScrnShot_041813_165401](https://f.cloud.github.com/assets/2059256/399916/1034654a-a884-11e2-9c4d-eb8b423e50ab.jpg)

Ahora veamos que produjo este cambio.

![WoWScrnShot_041813_165041](https://f.cloud.github.com/assets/2059256/399953/7530d8e6-a886-11e2-925e-e0c617ec2c6a.jpg)

![WoWScrnShot_041813_170507](https://f.cloud.github.com/assets/2059256/399938/f01d1490-a884-11e2-90e9-bd90fd76aa40.jpg)

---

Basandonos en el punto de partida 1224p. (porque ahi? por que no sabemos el %  [0.78%] de PcH pero si su resultado) Ahora vamos a empezar a sumar.

**nota I:** _aclaro que este no es el motivo por el que hago este tema, mas adelante les dire cual se trata._

Segun para saber el porcentaje entre 2 cantidades debemos hacer la siguiente ecuasion.

A-B=C/100=%

**Ejem:**
1562 - 1302 = 260 / 100 = 2.6%
1562 - 1224 = 338 / 100 = 3.38%

._. Bien como veran ya comenzamos mal. se supone que deberia ser el 20%

Sip!!!.. 15% de _sanacion espiritual_ + 5% de Renovar Mejorado. = 20%

**nota II:** _si alguien se preguntara; bueno sanacion espiritual 15% es para sanar a un objetivo y no para el taumaturgo. Pues bien aun asi el resultado no llega ni al 5%_.

---

Ok ahora veamos el resultado con el lvl2 que nos da 10% _(les recuerdo que no estoy usando ningun glifo - set - arma - aura - buff - helixir - etc.)_

![WoWScrnShot_041813_173948](https://f.cloud.github.com/assets/2059256/400040/938b5f96-a88b-11e2-9bb3-2fc2f737d7ac.jpg)

![WoWScrnShot_041813_174837](https://f.cloud.github.com/assets/2059256/400041/9c17de3c-a88b-11e2-84b7-6eb3656b5811.jpg)

Ok ahora se supone que deberia de haber un incremento del 10%. Para saber haremos la siguente ecuacion.

1627 - 1562 = 65 / 100 = 0.65%
**(esta posiblemente este erronea debido a que BLIZZARD siempre hace sus formulas acumulativas basandose en el resultado base)** _supongo_

1627 - 1224 = 403 / 100 = 4.03%

Como veran el resultado es bastande desalentador. Ya que ni usando la sanacion base de 1224 llegamos al 5% y se supone que ya deberiamos de tener 25%

**nota III:** porque 25% y no 30%? pues como dije anteriormente Blizz tienen una manera de trabajar algo extraña _(supongo)_

El 5% del lvl1 de "renovar mejorado" es reemplazado por el 10% _(supongo)_ y en lugar de acumularse/sumar este resta el -5% anterior reemplazandolo por el 10% ._.

-------- **como veran ni aun asi no llegamos al 25% reemplazando el % de lvl1 por el lvl2 y para colmo de males no llegamos ni al 5% del lvl1**.

---

**Bueno por el momento me gustaria que vayamos paso por paso** y que revisen si tengo la razon o no, si la tengo arrelgarlo.

**nota IV:** cual era el motivo? pues hay mas talentos que quiero que revisen o hechizos pero para poder hacer un reporte de ellos necesito que primero arreglen este. Si es que necesita arreglo.

THANK YOU FOR READ ME :p

**Comment by WarSxNes** [comment]
Me auto-comento para dejarles mis resultados:

**Total - Base = ----------- = Porcentaje <<<<<<<<< Descripcion**

1302 - 1224 = 78 / 100 = 0.78% <<<< _solamente el PcH_

1562 - 1224 = 338 / 100 = 3.38% <<<< _0.78% PcH  + 15% sana. espi. + 5% Ren. Mejorado_ (20.78%)

1627 - 1224 = 403 / 100 = 4.03% <<<< _todo lo anterior, reemplazando el lvl1 por el 10% de lvl2_ (25.78%) _supongo_.

No llegamos ni al 5% que decepcionante ._.

**Comment by redneo** [comment]
Mis calculos, que no son tan concienzudos como los tuyos:

Sanacion Base: 1224
Más Poder de ataque (segun el DD) 0.655 \* 224 = 146 (Ya lo he cambiado en la base de datos)
Sanacion total aproximada: 1370
Sanacion realizada: 1370 ---> OK!

Talentos: Sanacion Espiritual (15% más)
1370 \* 1.15 = 1575 ---> OK!

Renovar mejorado, rango 1 (5% más en renovar) Aqui me empieza a fallar o no se a que afecta, si a los 1224 base, con el poder de ataque, la sanacion espiritual....

1575 \* 1.05 = 1653
Sanando 1643 

Renovar mejorado, rango 2 (10% más en renovar)
1575 \* 1.1 = 1732
Sanando 1712

El caso, que se ha ajustado el DoT bonus de renovar y creo que está un poco más ajustado

**Comment by WarSxNes** [comment]
Oe una pregunta que no es Poder con Hechizos?

**Comment by redneo** [comment]
Ataque, hechizos... tecnicismos! :P
