### ISSUE TITLE
el gran atraco al banco

### ISSUE THREAD

**Issue by nemesisanuvis** [RoDNet/Bugtracker-Infinium-4.0.6a#1069]
ayuda esta mision esta bug mi personaje se llama que teso soy . Es un goblin
![image](https://f.cloud.github.com/assets/4206994/404676/cedaf5b2-a966-11e2-8c10-8242afd32d14.png)

**Comment by ghost** [comment]
Buenas, un par de cosas te quería comentar:

Lo primero, a la hora de poner un post sobre un bug, procura poner información para que lo solucione lo antes posible el Staff, poniendo el link de la misión en este caso, qué es lo que no funciona en la misión en el caso de que se vea a simple vista, link de habilidades si reportas una habilidad, etc. Puedes mirar en varios sitios, pero te recomiendo es.wowhead.com 

Lo segundo, no pongas 2 veces la misma Issue, ya que por ponerlo más veces no va a hacer que lo solucionen antes. Hay cosas más importantes que estarán haciendo, por lo tanto a la hora de realizar arreglos de bugs que reportamos aquí, pondrán un orden de preferencia.

Un saludo!

**Comment by nemesisanuvis** [comment]
Buen día ZASKA:

Lo puse dos veces porque otro gm me dijo que lo volviera a colocar, adicional me dijo que tenia que estar en linea y le comente la diferencia de horarios, se supone que si dicen 24 horas, pues deben estar las 24 horas disponibles, precisamente por eso le envié y si hay cosas mas importantes es entendible pero las prioridades deben ser fijadas por igual, no se si consideres importante que una nueva raza al momento de jugarlo tenga misiones bug y por ende sea requisito realizarla para poder avanzar y mas si es al principio.El link es este http://es.wowhead.com/quest=14122/el-gran-atraco-al-banco la imagen queda adjunta estaré al tanto de la respuesta. mi personaje se llama quetesosoy.

gracias por la atención prestada.

Un abrazo y un saludo!
