### ISSUE TITLE
Rastrear Humanoides druida ( en gato)

### ISSUE THREAD

**Issue by rioga** [RoDNet/Bugtracker-Infinium-4.0.6a#1086]
No funciona lo de rastrear humanoides del druida ( gato), siempre me funciono  bien, y de un  dia para otro  ya no funciona, me dice que la skill no esta lista aun, he reseteado las skills y vuelto a poner y me sigue diciendo lo mismo.

**Comment by DatJetto** [comment]
Lo acabo de probar y me funciona perfectamente.

**Comment by rioga** [comment]
A mi no me va bien y por lo visto soy el único druida que tiene ese problema, los GM en el juego me mandan  a reportar el bug en esta pagina, ¿entonces cual es la solución?, ¿quien puede ayudarme con ese problema.?

Con el cazador   si que puedo rastrear, pero con el druida no.

**Comment by rioga** [comment]
Nose si vale de algo pero  esto es lo que me dice:
<a href='http://www.subirimagenes.com/otros-wowerrorrastrear0428-8409543.html'><img src='http://s2.subirimagenes.com/otros/previo/thump_8409543wowerrorrastrear0428.jpg' alt='subir imagenes' border='0'></a>

**Comment by DatJetto** [comment]
:$ Pues ni idea, si se ve perfectamente lo que quieres decir, intenta cambiando de specialización de talentos y volviendo a lo mejor se resetea y puedes cambiar, si no pide a un gm que te borre y reaprenda la spell

**Comment by rioga** [comment]
ya  esta solucionado, lo de cambiar de talentos ni resetear talentos no funciona, al final me lo arreglo un GM in game.

**Comment by DatJetto** [comment]
Genial, cierra el post :3
