### ISSUE TITLE
Mago (golpe de hechizo critico) - posible bug

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1089]
En relacion a otros post https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1068 - https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1055

---

Ahora si _( me escupo a mi mismo, si me equivoco)_,..... Haber expliquenme esto... _presten atencion a las imagenes_

![WoWScrnShot_042813_233253](https://f.cloud.github.com/assets/2059256/437271/ec38c142-b097-11e2-9bd4-481bc924eb2f.jpg)
![WoWScrnShot_042813_233303](https://f.cloud.github.com/assets/2059256/437273/f36069b6-b097-11e2-9b44-5e6587508e52.jpg)

**NOTA I:**  _ahora se por que el mago esta bien weak_ **(debilucho)** _Yo tengo un mago (fuego) pero en vista de que me recomendaron usar uno (hielo) pues me he hecho otro y estoy apuntando los stats para seguirle la pista_

---

Si no encontraron las diferencias procedo a mostrarles los cambios :P 
![WoWScrnShot_042813_233253](https://f.cloud.github.com/assets/2059256/437313/6caf6e6e-b09a-11e2-9a31-591707d6c558.jpg)

---

Vamos chicos, haber si me pueden explicar esto. _(de lo contrario es un bug,.... BUGAZO.)_
Yo supongo que los **stats** de todas las razas y clases van subiendo conforme el nivel no?

Como dije al principio tengo un mago (fuego) y la verdad me _ABURRI_ de el; Por que? era mas lo que corria y gasto de mana que lo que hacia de daño.

Se supone que el mago (fuego) es el mas fuerte de los 3, y obvio el que hace mas dps. Pero es todo lo contrario, con el no mato ni a una mosca.

Y como me recomendaron usar el mago (hielo) pues dije "voy a empezar de 0, he hire apuntando los stats" y luego que? ZAS..s.s.s!!!!!.... me topo con esto al nivel 13.

---

**NOTA II:** _haber si alguno de ustedes puede hacerse un mago y corroborar mi hallazgo; de lo contrario me tendre que limpiar la cara >,<_

**Comment by DatJetto** [comment]
1 - El que hace más Dps y daño de siempre ha sido Arcano, pero claro, es el que consume más maná.

2 - Esto no es un bug, a ver como lo explico, cada nivel tus requerimientos para conseguir stat secundarios, pericia, crítico, golpe, celeridad etc...  se vuelven más altos, dados que solo aumentan los stat primarios junto al personaje, > AGUANTE, FUERZA, AGILIDAD, INTELECTO Y ESPÍRITU. 
Los stat secundarios vienen dados generalmente por talentos y equipamiento, de manera que por ejemplo imaginemos un lvl 1 con stat de crítico 600 ( aunque sea imposible ) el crítico sobrepasaría del 100% ya que para su nivel es IMPOSIBLE alcanzar esa estadística con equipamiento y nivles, de manera que cuando suba de nivel ese % de crítico si permanece en 600 irá bajando a 90% - 80 % sucesivamente, cada nivel que subes, necesitas más crítico como estadística para que el % suba.

Si tu talento tiene 3% de crítico con todos los ataques esto no es problema ya que mínimo tendrás siempre 3% + el crítico conseguido por tu intelecto :3 

Si te queda alguna duda comenta y te ayudo, no se si quedó muy claro, es difícil de explicar :camel: 

3 - Con 3000 de poder con hechizos extra no está tan Weak e_e arcano mete criticals de 30k siendo verde a sañosos y si vas equipao puedes sacar 70 - 80k de arcane blast.

**Comment by WarSxNes** [comment]
Ok, tu punto de vista me parece razonable asta cierto punto. **Pero tienes alguna formula?** que lo respalde, si tubieras tambien algun link oficial tambien seria bueno.

Creo que en wowwiki te dejan ver los **stats** primordiales. Lo que no me logro "tragar" es la idea que al lvl 1 tengas un % de critico alto y que valla disminuyendo conforme subas al lvl 85. _(pero bueno si tienes algo que lo respalde, sera caso cerrado)_

---

**EDITO:** me la he pasado 2 horas buscando por google y yahoo y nada que encuentro un tema relacionado con lo que me explicas >.<

El unico que encontre fue uno en [WarcraftWiki](http://es.wow.wikia.com/wiki/Atributos) **<<<<** y este dice que... _(esto me respalda a mi)_

_Todos los jugadores reciben por inercia una cierta cantidad de cada atributo que va incrementandose a medida que se va subiendo de nivel. Este incremento depende en gran parte de la clase del personaje, por ejemplo los Magos recibirán mucho más Intelecto que un pícaro quien a su vez recibirá mucha más Agilidad. Los atributos pueden incrementarse con armaduras, buffs temporales, pócimas, scrolls o pergaminos, auras..._

Y pues el factor que incrementa esto es **INTELECTO**, entonces si intelecto incrementa el % de critico y este a su vez va incrementandose conforme vas subiendo de nivel. No me explico como el % de critico disminuyo si intelecto se incremento _(deberia ser todo lo contrario tendria que haber un aumento)_, como tedigo si encuentras una formula que lo explique, o un link oficial me sacas de las dudas.

**Comment by DatJetto** [comment]
Lo del crítico alto al lvl 1 solo era un ejemplo, para que comprendieras la idea, es obvio que un lvl 1 no va a tener mucho más de 3% de critico o ni eso xD

Lo que he expuesto no es una opinión o un punto de vista, simplemente es la forma racional y lógica por la cual se distribuyen las estadísticas en el 90% de los MMORPG. 

Vale, vamos a lo tuyo, tu set da x puntos de índice de golpe crítico ( IGC ), de acuerdo, ahora, esos puntos se transforman en un x% de Crítico, junto a las Gemas, Encantamientos, Talentos, Equipo que de IGC que tengas.

Te pongo un ejemplo simple, observa el Tier 11 de Cazador http://es.wowhead.com/itemset=-287 
Podrás ver que dice IGC 705 > si pasas el ratón por encima pone 3.93% al lvl 85 
Ahora mira este http://es.wowhead.com/itemset=361 38% de IGC > 0% al lvl 85 
Pero si pulsas al stat cambia para nivel de objeto y te dice 2.82% de Crítico para lvl 58
Así mismo mira este set de Pandaria: http://es.wowhead.com/itemset=1157
dice 1484 de IGC si clicas sale 2.49% al nivel 90, y es más del doble de la estadística del set 85.

Espero haber aclarado tus dudas, y si te he puesto el discurso de arriba, no es para inventármelo, es por que se cómo va aproximadamente en ideas generales, para molestar me voy ingame e_e

**Comment by ghost** [comment]
A mayor lvl necesitas más stats para mantener el mismo porcentaje, lo que indicaste con naranja y dice "bien el aumento esperado" no es porcentaje, son solo números "comunes".

Tus stats van aumentando conforme subes de lvl, pero no es el caso de los porcentajes, donde necesitas más y más, otro ejemplo seria que si tenes un war lvl 10 con su escudo, dice que reduce tanto % de daño físico, lo subes unos 5 lvls, ese tanto % habra bajado, ahora reduce menos porque necesitas más stats (armadura en este caso) para seguir manteniendo el porcentaje.

Así que sí, puedes escupirte, pero no te limpies la cara xd.

Y para que te quede bien claro, si en lvl 13 ya tienes 8.39 % de probabilidad de crítico (teniendo tan pocos stats),   y piensas que eso en vez de bajar, tiene que subir, ¿cuánto crítico crees que van a tener los lvls 85? tal vez unos 1000 % o más

**Comment by WarSxNes** [comment]
Lvmb@: todo va en relacion al valance. 8.39% es un numero "total" ya incluyendo Intel y equipo.

Se supone que entre los primarios Intel = Poder con hechizos, Critico, etc.. va en aumento. Si intel sube, todo lo demas debe de subir. _no lo contrario_

ademas lo de 1000% es una exageracion si estamos hablando de 0.00 decimas antes de la unidad haha xD

---

DatJetto@: a lo que voy es que en cuention de logica, debe de existir un valance entre clases.

Mele: **guerrero** +vida +armadura +esquivo/parada >>> -resistencia a la magia -resistencia a caidas -daño
Rango: **mago** +daño magico +probabilidades/opciones de escape >>> -vida -amor -esquivo/parada

**simple no?**

Te imaginas un guerrero con 330k de vida full set pvp **VS** un mago con 75k vida full set pvp

Y con esta clase de atributos segun ustedes dos, quien creen que ganaria. _no tomen encuenta la habilidad del jugador_

Es **logico** que habria un desvalance con esos atributos que segun ustedes es correcto, todas la probabilidades de perder las tiene el mago ._.

Un mago sin un % de critico razonable es como una mosca pegandole a una estatua de granito. =(
**y eso que NO estamos hablando del daño base**

Y cree me que cuando digo "corro mas y gasto mas mana" que lo que hago de daño es cierto.

Hablando de logica :P 

---

**NOTA**
Bueno mientras tanto les cuento que creo que encontre un posible talento bug, ahora en el MAGO(hielo). Pero no hablare de el asta no estar seguro al 100% luego les vengo a contar.

**EDITO**
Bien, hehe... si esta bug pls lean el siguiente post sobre "Cono de frio mejorado" Ojo.. las descripciones de [wowhead] son para MoP _(mago fuego, hielo ... estan plagados de bugs)_ =(
