### ISSUE TITLE
Denuncia abuso de bug por Metsi

### ISSUE THREAD

**Issue by chipi666** [RoDNet/Bugtracker-Infinium-4.0.6a#1091]
Hola reporto por medio del bug tracker ya que es muy dificil subir fotos al foro, el personaje metsi un poco abuson no deja de usar el bug de colera sagrada y esto en repetidas ocasiones que me canse de tomarle fotos esto a sucedido en 2 bg, xD

![WoWScrnShot_042913_121246](https://f.cloud.github.com/assets/3199832/440735/fff9df90-b105-11e2-9bbb-0b10644d87f1.jpg)

![WoWScrnShot_042913_121944](https://f.cloud.github.com/assets/3199832/440714/544dba68-b105-11e2-9e64-a504d8f2f418.jpg)

![WoWScrnShot_042913_122921](https://f.cloud.github.com/assets/3199832/440718/723c681c-b105-11e2-9f0d-da41c26aa9bc.jpg)

![WoWScrnShot_042913_123310](https://f.cloud.github.com/assets/3199832/440719/7a998b52-b105-11e2-8523-29cd0f76e7cf.jpg)

![WoWScrnShot_042913_123318](https://f.cloud.github.com/assets/3199832/440720/85b481b8-b105-11e2-8a26-af4ba16f33ad.jpg)

**Comment by chipi666** [comment]
Hola Aqui anexo mas bugeros a la lista espero que agan algo al respecto saludos...
PJ Wylde.

![wowscrnshot_043013_160445](https://f.cloud.github.com/assets/3199832/447089/d8431c92-b1ea-11e2-9698-934afdd31d9d.jpg)

![wowscrnshot_043013_160229](https://f.cloud.github.com/assets/3199832/447085/b5f9bd4e-b1ea-11e2-9d5b-139201929e4b.jpg)

**Comment by chipi666** [comment]
otro mas Personaje Allann.

![wowscrnshot_050113_112434](https://f.cloud.github.com/assets/3199832/450328/60270454-b28e-11e2-8866-c0744be07a9b.jpg)

![wowscrnshot_050113_112437](https://f.cloud.github.com/assets/3199832/450330/67854760-b28e-11e2-8c34-916c89729b61.jpg)

![wowscrnshot_050113_112457](https://f.cloud.github.com/assets/3199832/450332/71fe8db4-b28e-11e2-896e-be92df5eba85.jpg)

**Comment by chipi666** [comment]
otros para la colección espero que tomen cartas en el asunto por que ya es mucho abuso, saludos..
Personajes
Gharrison
Sherik

![wowscrnshot_050113_130903](https://f.cloud.github.com/assets/3199832/450779/844ffb26-b29b-11e2-87bd-f05e521e37bf.jpg)

![wowscrnshot_050113_130933](https://f.cloud.github.com/assets/3199832/450782/a6a90442-b29b-11e2-8430-e3592d31f39a.jpg)

**Comment by chipi666** [comment]
otro mas Personaje.
Krispin

![wowscrnshot_050113_133548](https://f.cloud.github.com/assets/3199832/450939/5f0793f2-b29f-11e2-9a4c-8bf11e0174ad.jpg)

![wowscrnshot_050113_133910](https://f.cloud.github.com/assets/3199832/450942/6af5f438-b29f-11e2-91a6-89e40764a48a.jpg)

**Comment by chipi666** [comment]
Denuevo encontramos a este personaje Krispin aprovechandoce del bug spell colera sagrada en Arenas ahora espero que tomen cartas sobre el asunto gracias y saludos...

![wowscrnshot_051213_130610](https://f.cloud.github.com/assets/3199832/493405/744642b4-bb40-11e2-84b0-6206f5a2b26b.jpg)

![wowscrnshot_051213_130655](https://f.cloud.github.com/assets/3199832/493406/85a140d6-bb40-11e2-98af-f20df6a9c963.jpg)

**Comment by Dekadencee** [comment]
Envia un ticket a nuestro staff para que lean esta issue y sancionen a los responsables.

Un saludo
