### ISSUE TITLE
Mago (hielo) Cono de frio mejorado

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1094]
En relacion al post https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1089

0.-- Si asi es chicos otro bug >.< Antes de comenzar quisiera saber si esta tabla de talentos "corresponde" o "correspondera" _tiempo futuro_ a la nueva version que se esta planificando para el server?
![untitled](https://f.cloud.github.com/assets/2059256/447733/7cf2ca30-b213-11e2-93b0-873eddd036e7.jpg)

---

Bien pues si no es asi estonces encontre otro bug xD

**Cono de frío** http://es.wowhead.com/spell=120/cono-de-frio
![GitHub Logo](http://wow.zamimg.com/uploads/screenshots/thumb/137034.jpg)

**NOTA I:** esta descripcion es para MoP

---

_IN-GAME Cata. 4.0.6a_

![wowscrnshot_043013_204929](https://f.cloud.github.com/assets/2059256/447744/3f16f744-b214-11e2-8e52-51d87175a314.jpg)
Se supone que esto al ser lanzado debe de congelar al objetivo por
2sec. LVL1
4sec. LVL2

Bien, pues no pasa nada ._.
![wowscrnshot_043013_204943](https://f.cloud.github.com/assets/2059256/447777/52e34514-b216-11e2-8a1e-caaa5ba9afd1.jpg)
![wowscrnshot_043013_205005](https://f.cloud.github.com/assets/2059256/447779/5d95b938-b216-11e2-95a9-52798c6539ba.jpg)
![wowscrnshot_043013_205035](https://f.cloud.github.com/assets/2059256/447780/61e098e6-b216-11e2-9784-c691acb388bb.jpg)

**Y para los que digan que NAHHHhh los tigres son inmunes ahi les va un troll ;P**

![wowscrnshot_043013_205100](https://f.cloud.github.com/assets/2059256/447785/79af6114-b216-11e2-8610-808dcbdec0a5.jpg)
![wowscrnshot_043013_205101](https://f.cloud.github.com/assets/2059256/447786/7de9e240-b216-11e2-8e44-e8b18e79b941.jpg)
![wowscrnshot_043013_205102](https://f.cloud.github.com/assets/2059256/447788/82dc89d8-b216-11e2-9d8b-001121560488.jpg)

Hasta en slow motion para que no crean que es trucado xD ni el troll se congela, y ya probe con muchos mas y nada que los congele.

**NOTA II:** Ojo el talento no dice % de probabilidad de congelarce, dice **"SE CONGELA"** cuidado con eso ehhh!! no se confundan.

Saludos. THANKS for READ ME ("\;..;/")

**NOTA III:** use nova de escarcha para usarla de ejemplo ya que esta congela a los objetivos, mientras que cono de frio deberia de hacer ambos, congelarlos y hacerlos lentos. me explico no? _NO SE CONFUNDAN_

**Comment by ghost** [comment]
Claramente es para la versión nueva ;) El post en sí es TODO sobre los avances de la 4.3.4

**Comment by WarSxNes** [comment]
**Zaska@:** entonces?

Respondo por ti: **"es otro bug"** ;P

**Comment by DatJetto** [comment]
Si es bug man pero que en 4.0.6 no van a arreglar apenas bugs, dejalo nomas.

**Comment by redneo** [comment]
Si fuese un spell que se lo echa al traumaturgo lo podria arreglar, pero siendo a los npcs, no puedo, ya que va por programación.

El caso que si tienes los dos rangos tendria que lanzar tambien los spells 83301 y 83302
