### ISSUE TITLE
Bug Daño Brujo Destrucción

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.0.6a#1095]
Hola buenas:

Veréis tengo un brujo destrucción full sañoso y he visto que no pega lo que deberia. Esta haciendo de daño en general en todos los hechizos un 20% menos.

Os pongo de ejemplo lo siguiente de base con fuego de alma (he escogido este pero pasa con los demás igual) sin ropa pego 3k al muñeco de entrenamiento. Pues bien con el equipo y las armas y tal tendría que pegar lo siguiente (3k + (hoja de alma hero) 2,2k + (intelecto) 5052 + (armadura vil) 638 + maestría = aprox. 12k es lo que debería hacer sin bufos ni nada al muñeco. Mientras que solo hago 9k. 

![brujo destru](https://f.cloud.github.com/assets/3939699/450102/e1c37058-b287-11e2-9bb4-f9014439b6c1.jpg)

![dao brujo destru](https://f.cloud.github.com/assets/3939699/450121/5d0d6174-b288-11e2-8b80-3ce1a7c1a8b7.jpg)

En estas imágenes os adjunto la prueba con los datos y el daño al muñeco.
Pongo este post sabiendo que el daño depende del temple del otro pj y tal y cual (lo digo por si alguien piensa soltar algo de eso), pero lo que no es normal es que cualquier otra clase con equipo sanguinario pegue más que yo.

También he comprobado el daño con el Dr. Damage (se que no es exacto) pero mirad en esta imagen el daño que debería estar haciendo:

![dibujo](https://f.cloud.github.com/assets/3939699/450140/5490c170-b289-11e2-9375-6b4c19e7722d.jpg)

Conclusión: por favor subirle el daño al brujo, es para mi gusto una de las mejores clases que tiene el wow y esta muy floja.

Gracias por vuestra atención

Un cordial saludo

**Comment by sussy** [comment]
jaja k devil los brujo vea jaja y si da pena ver pj como war con sanguinario bajando un resto como sañsosos pero ni modos

**Comment by redneo** [comment]
He estado probando y el problema del warlock es que la maestria no se la pone siempre... hay veces que la pierde, recomiendo probar con muñecos el daño mientras se cambia de rama de talentos.

**Comment by redneo** [comment]
Rectifico... era el daño de los spells que estaba un poco bajo.

Incinerar, fuego de alma, inmolar y descarga del caos se han ajustado.
