### ISSUE TITLE
[Hunter > Spec: Marksmanship > Spell > Termination ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#11]
-Remate 
http://www.wowhead.com/spell=83490
Bug: Al estar al 25% de salud; 

Disparo firme
http://es.wowhead.com/spell=56641

Disparo de cobra
http://es.wowhead.com/spell=77767

No otorgan 15p de Foco al Cazador.

**Comment by adrianrp1988** [comment]
Reparado en la proxima Rev
