### ISSUE TITLE
Palabras de poder

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1100]
Bien empezamos con las quest de Rasganorte...

http://es.wowhead.com/quest=11942/palabras-de-poder <<< bug

![wowscrnshot_050113_181209](https://f.cloud.github.com/assets/2059256/451988/d0e31dd6-b2c5-11e2-890e-63b421933e4e.jpg)
http://es.wowhead.com/npc=26073
_la hormigota esta completamente petrificada_ **(chiripiorca)** ;P

Tienes que matarla y te tira esto http://es.wowhead.com/item=35354

---

![wowscrnshot_050113_182503](https://f.cloud.github.com/assets/2059256/452009/2c1f28c4-b2c7-11e2-9ccc-659bf3c39c5b.jpg)
_Una cucarachota lujosa que tambien le dio_ **(chiripiorca)** ;P

Tienes que matarla y esta tira http://es.wowhead.com/item=35353

---

El elfo esta bien pero echenle un vistazo para confirmar.

**Comment by redneo** [comment]
Creo que está arreglado pruebalo tras la caida del server.

Arreglado!
