### ISSUE TITLE
el tesoro susurraniebla perdido

### ISSUE THREAD

**Issue by brujilla** [RoDNet/Bugtracker-Infinium-4.0.6a#1105]
esta mision se compone de dos partes una coger el tesoro y otra matar al señor de la guerra tartek pero  este no aparce por ninguna parte y no se puede acabar esta mision gracias

**Comment by redneo** [comment]
Puesto el npc.

Podiais poner los enlaces a wowhead para tardar menos en hacer las cosas.....
