### ISSUE TITLE
[ Priest > Renew ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1107]
http://es.wowhead.com/spell=139

Lo primero de todo es, QUE ME CUENTASS?! 
Esta spell ahora mismo está curando 9-10k sin crítico!!
cuando debería curar unos 2k - 3k por tick no crítico.
Wutufuck.

Video de un priest en el ofi en el 4.0.6 con sañoso - sanguinario > curando 2.4 - 3k per tick.
http://www.youtube.com/watch?v=MNPOrFUVHo0

**Comment by redneo** [comment]
...

A ver si nos ponemos de acuerdo https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1068

**Comment by DatJetto** [comment]
Ahí estáis tomando 1224p. de sanación, no entiendo  por qué como ''base'' cuando ese tooltip es erróneo y sale siempre por mucho intelecto que se tenga.

Renew cura X cantidad total ( viéndose afectada esa cantidad por talentos y aura que mejoren este hechizo ) esa cantidad total se divide en los segundos y los ticks correspondientes, es un HoT, no un casteo o canalización, cuestión de obviedad, no es la sanación principal del priest, es un claro hechizo de ayuda, que ha de curar una cantidad normal, sumando las demás curas que obtenga el priest en ese momento mediante hechizos como Flash Heal, Greater Heal, Penance etc... que es con lo que ha de curar realmente, ahora mismo cada tick te sube 9-10k, cuando silencias al priest el efecto persiste claro está y mientras tiene esos 3 sec de silencio pues se está curando 10k de manera que matar un priest a menos que le peguéis 5 o 6 en bg... para eso tiene un escudo y demás formas de sobrevivir, en arenas ya ni te digo, si la cagas en el CD inicial ya te tienes que dejar matar o algo porque no lo bajas ni queriendo.

Al igual que chamanes Resto y paladines Holy, los HoT como Escudo de Tierra y Radianza, son sanaciones supletorias que han de curar todos aproximadamente lo mismo, básicamente matar un pala heler ahora mismo está muy muy complicado, Radianza con equipo les cura 5 - 6k por tick cada segundo a todos los aliados en X 10 - 15 metros (?) mientras que el pala te echa holy shock y demás curas pues, adio.

EDIT: Video de un pala heler en el ofi ( se le ve el set al principio del video ) se tira Radianza Sagrada y se cura 1,2 - 1,8k con set de nivel bastante alto , t11 - sañoso, y ahora mismo un pala retry se cura más que eso, y un heler verde cura 2 - 3k por tick, y así va esto e_e
http://www.youtube.com/watch?v=1MW4qzydp5c

**Comment by ghost** [comment]
Yo en sombras llego a curar 10k de critico  en un tick xd aunque con el encantamiento y el abalorio activado.

**Comment by WarSxNes** [comment]
1224p. es la base indicada en los detalles del hechizo, eso nunca cambia. Para poder apreciar los cambios tienes que habilitar las opciones de interfaz para apreciar los letreros que te indicant la sanacion "total" ya modificada por los atributos y items.

En mi articulo publicado hace tiempo. Trato de entender por que el sacerdote cura muy poco. Cuando haciendo la suma de todos los modificadores indican lo contrario.

La verdad DatJetto asta hoy en dia no paso de los 1627p. de donde sacas los 9k-10k y los 5k-6k????

Que acaso estoy bug :P por que almenos yo no sano esa cantidad. Y respecto a los palas yo nunca he llegado a sanarme esas cantidades que mensionas; ahora comprendo por que la mayoria de los banneados son hordas :P doy fe a que no llego ni la octava parte de la sanacion que se mensiona aqui =) Sin equipos y sin items; puede que usando modificadores que te favorescan llegues a esas cantidades, DatJetto@: _no se si seas sacerdote/paladin/druida pero si lo fueras seria bueno que mostrando fotografias como evidencia sin equipo y sin items seria bueno_ =)

**NOTA I:** las descripciones en www.wowhead.com son para MoP ojo con eso no confundirce con lo mensionado ahi.

**NOTA II:** hay rumores en la web RoD que se trabaja en el parche 4.3.4 no? Yo almenos sugeriria que dejemos a un lado los bugs y se enfoquen en la implementacion de dicho parche lo antes possible, pues seria un desperdicio de tiempo arreglarlos y que al implementar el parche estos bugs posiblemente se arreglen o vuelvan a desarreglarse.
A no ser que la DB sea importada desde la antigua e implementarse en la nueva, o que esta siga siendo la misma sin verse afectada por los cambios de dicho parche. _tomenlo como sugerencia para evitar perditas de tiempo_

Yo almenos tengo una larga larga..... muy larga lista de bugs para rasganorte esperando :P pero no he querido publicarlas por lo mismo, mejor me espero para ver si hay mas noticias de dicho parche. =)

**Comment by DatJetto** [comment]
Soy cazador como principal, pero tengo Druida heler, y compañeros Sacerdotes y Paladines con los cuales he testeado.

Estoy hablando CON EQUIPO, siempre, lo que supongo que el % de SP que cogen los hechizos será bastante mayor del que deben.

**Comment by WarSxNes** [comment]
AAAa..... ahi esta la cosa **"equipo & items - enchan, gemas, glifos, etc."**

---

Ok, coge tu lapiz y papel ponde a sumar =) Segun yo se:
![wowscrnshot_051013_094418](https://f.cloud.github.com/assets/2059256/489099/e8701932-b990-11e2-868e-4b226dd9d415.jpg)
Osea que al momento de incrementarse Intel se incrementan esos 3 atributos secundarios.
Posiblemente tus compañeros/amigos tengan este atributo muy elevado logrando la hazaña de los 5k-9k =)

---

En cambio yo en mi post anterior lo publico sin **"equipo & items - enchan, gemas, glifos, etc."** y sin **"talentos"**.
Notando el cambio **(no logrado)** segun mis calculos en cada incremento de los talentos, y los pasivos del sacer. Pasate por mi post y veras que le hace falta curar un poco mas al sacer ;P https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1068 - Le hace falta hacer mas daño al mago/picaro y este ultimo tiene varios talentos bug haciendo que al lado de un guerrero paresca _[ una mosca pegandole a una estatua de granito ]_

**Nota:** el intel de la foto incluye **"equipo & items - enchan, gemas, glifos, etc."** comparalo.

**Comment by DatJetto** [comment]
Le hace falta curar más? ._. un priest con Renovar, escudo, y pasivas y algún penitencia, aguanta un Cazador full sañoso en Burst CD durante 15 segundos sin despeinarse. O no sabes mucho de sacerdotes o necesitas equipo, estamos hablando de sacerdote sanguinario - sañoso.

**Comment by WarSxNes** [comment]
A eso se le llama desvalance :P es obvio que cuando arregles una clase si la otra clase esta bug esta estara en desventaja.

Un sacer arreglado estara en ventaja ante otras clases _(caza)_

Ahi te puse de ejemplo en otros post donde reporto los bugs el mago (fuego) que tiene casi todos sus talentos bug, (hielo) que tiene cono de frio y otros mas talentos bug sin mencionar (arcano). El picaro tiene un sin numero de talentos bug con sus venenos los cuales deberian de hacer mas daño pero no los hace.

Es como tu y Lvbm dicen es cuestion de logica :P y eso como digo al sacer le hace falta sanar un poquito mas _(osea sigue bug)_

Ademas tu mismo lo has dicho tus calculos se basan con equipo, creo que ya se por que lo dices xD por el sacer (disciplina) y su escudo pero **OJO** es logico que sea muy dificil de matarlo por la maestria y todos los modificadores que aumenten maestria. Mientras mas % tengas en maestria aumenta la amortiguasion del escudo y si tienes el glifo de sanacion del escudo creo .... creo **creo**... que el 20% del daño recibido sana al sacer.

OK, ahora aqui entra la desventaja del los DPS bug: como el picaro/mago/ y e de supuner otros mas estan bug. El daño realizado por ellos es insuficiente provocado por los talentos bug. (desbalance)

Pero si prestas atencion en las BGs o Arenas nunca hace falta un guerrero over o druida que llegue a salvar el momento y haga trizas al sacer :P especialmente con esos anti-buffs que pasan horas y horas y no se te quitan asta que mueras o te dejes morir. _(no por nada la mayoria de hordas son guerreror o druidas)_ y los alis ya comenzados a hacer lo mismo aprovechando el bug. hahah lol

---

EEEeeh... buen punto no?  pideles a tus amigos que se quiten todo el equipo que traigan puesto incluyendo glifos y talentos. Y vallan agregando los talentos de 1 por 1 a la vez y ponte a pegarle a un muñeco de entrenamiento para que vean los cambios.

Es algo tedioso pero solo asi te daras cuenta que tanto el picaro como el sacer siguen bug (mago). Y que el guerrero esta over xD mucha vida armor y pega duro y ese antibuff es molesto.

Si un guerrero te logra tocar con su barrido y te hace stun estas muerto. El druida ni hablar ._.

**NOTA:** creo que asi como han sancionado a los palas con colera... deberian sancionar a los guerreros que se aprovechan de este anti-buff _(sugerencia)_

**Comment by DatJetto** [comment]
El pícaro y el mago pegan poco? .PFFFFFFFF, emboscada en el pícaro pega más de lo que debe y encima tiene DR bug, te deja stuneado 8 segundos cosa así con Golpe bajo, y riñones,  o trinkeas o mueres, el resto de habilidades alguna si pega menos, pero generalmente no es una clase desbalanceada.

El mago tiene 3k extra de poder con hechizos que no le pertenece, mi amigo en arcano ha metido hoy a un sacerdote 98K, SÍ SÍ 98K  de explosión arcana, y es sangui - sañoso. Escarcha mete bastante, te puede dar 40k y algo con un equipo decente, y Fuego tampoco se queda atrás, hace un gran daño.

No se de donde vienes, pero es obvio que del oficial no e_e''  y tengo amigos que han jugado estos parches y los helers de cata son bastante blanditos. Mira vídeos del oficial, y verás que los priest con renovar no curan más de 3.5 - 5k  full sañosos, en RoD un verde - sangui cura 4 - 6k.
