### ISSUE TITLE
glifos faltantes

### ISSUE THREAD

**Issue by kiiit** [RoDNet/Bugtracker-Infinium-4.0.6a#1109]
resulta que faltam muchos glifos por ejemplo el glifo de socorro oscuro no lo enseñan los instructores ademas de otros

**Comment by ghost** [comment]
Tienes investigación de rasganorte, tienes los libros de maestría en glifos e investigación para glifos menores... y el glifo que das de ejemplo yo lo tengo con mi DK así que si esta, no todo lo consigues con el instructor...

**Comment by WarSxNes** [comment]
## [Inscripción](http://es.wowhead.com/skill=773)

http://es.wowhead.com/spell=61177 <<<< **Investigación de inscripción de Rasganorte**
http://es.wowhead.com/item=45912 <<<< **Libro sobre maestría en glifos**
http://es.wowhead.com/spell=61288 <<<< **Investigación en inscripción menor**

Simple tienes que leer la historia de los inscriptores para darte cuenta que no todo se aprende con los instructores, incluso algunos se obtinen mediante misiones o comprandolos mediante otra clase de monedas especiales para inscripcion.

Suerte... y ponte a leer un poquito :P
