### ISSUE TITLE
[Quest > Token of Power] Misión > Una muestra de poder

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.0.6a#1110]
Misión: http://es.wowhead.com/quest=27402

La misión se desarrolla en la mazmorra Castillo de Colmillo Oscuro (http://es.wowhead.com/zone=209), solo en modo Normal.

Bugs:
- El objeto Libro de almas perdidas (http://es.wowhead.com/item=60873) no se encuentra en el sitio.
- El objeto Orbe tenebroso (http://es.wowhead.com/item=60882) debería darlo Lord Godfrey (http://es.wowhead.com/npc=46964) con 100% de probabilidad al tener la misión y no lo hace.

**Comment by redneo** [comment]
Arreglado
