### ISSUE TITLE
[BUG] Mision: ¡Ve tras Zherin!

### ISSUE THREAD

**Issue by Skt16** [RoDNet/Bugtracker-Infinium-4.0.6a#1117]
Esta mision se supone que hay que matar a Zherin creo, y que suelte unas ordenes (un objeto) pero no las suelta.

Facilito el link de la mision: http://es.wowhead.com/quest=25756

Un saludo.

**Comment by redneo** [comment]
No hay que matarlo... ya está arreglada.
