### ISSUE TITLE
[BUG] Mision: En caso de emergencia...

### ISSUE THREAD

**Issue by Skt16** [RoDNet/Bugtracker-Infinium-4.0.6a#1130]
En esta mision no puedo despojar los gobjects.

En caso de emergencia...: http://es.wowhead.com/quest=10161

**Comment by redneo** [comment]
Hay 4 objectos que se llaman igual, solo uno de ellos daba el loot apropiado, ya se ha cambiado para que lo den todos, a lo mejor tienes que limpiar la carpeta cache tras la caida del servidor.
