### ISSUE TITLE
Grim Batol (normal)

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.0.6a#1131]
Estuvimos haciendo la mazmorra de Grim Batol (http://es.wowhead.com/zone=4950/grim-batol), y con los dos primeros bosses no tuvimos ningún problema, aparecieron en su lugar y los pudimos matar. Sin embargo tuvimos un problema con los dos últimos Drahga Quemasombras, y Erudax, ya que ninguno de los dos aparecieron, y nos recorrimos posteriormente toda la mazmorra, y tampoco estaban.

Un saludo, y gracias

**Comment by ghost** [comment]
En normal no sé, pero ya la he hecho muchas veces en heroico y estan todos los boss.

**Comment by redneo** [comment]
Correcto, en normal no estaban, ahora si que estan.
