### ISSUE TITLE
[ Priest > Renew 2 ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1138]
Vuelvo a poner el post para que no nos perdamos entre comentarios etc, desde el https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1107 

( no borren este por favor ) 

ID: http://es.wowhead.com/spell=139 ( MoP )

Añado screen de LO QUE DEBE CURAR, indicado por el Tooltip y respecto de lo que cura en el sujeto en cuestión.

![renovar](https://f.cloud.github.com/assets/2728817/497099/04d799dc-bbf4-11e2-9154-2862336ca6e7.jpg)

En la foto vemos como debería curar 2693 y cura 5606, más de el doble y tick crítico de 8661. 

Ha de constar que en el renovar y su descripción se aplican los cambios por Equipo, Glifos, Talentos etc. de manera que está totalmente actualizado a como debe ser :3

Si tomamos por base que cura 1224 como afirma WarSxNes sería:

2693 - 1224 = 1469 ( Extraemos el % de curación base respecto del de curación recibida por Spell Power )
Ahora quedaría hacer 1469 / 7787 ( Spell Power correspondiente al sujeto ) = 0.188 ( Que es el resultante modificador de Spell Power para el hechizo )

De manera que la fórmula quedaría así: ( ( SP \* 0.1886 ) + 1224 )

**Comment by ghost** [comment]
No te quito meritos por tu trabajo, pero ¿para qué te tomas la molestia, si sabes que pasaremos a la nueva versión?  xd, ¿no es mejor  esperar a que pongan la nueva versión y ver qué tal esta el renovar?

Y para no poner enlaces de mop, podrías buscar el hechizo en old.wowhead.com, claro en inglés.

Y tampoco te puedes dejar llevar por lo que dice el tooltip, el toolptip puede estar mal, pero claro no me metere a discutir cuanto debe curar xd solo menciono esto.

**Comment by DatJetto** [comment]
Sí, pasaremos a 4.3, pero ¿Y SI EN 4.3 TAMBIÉN ESTÁ BUG? igualmente redactar todo y crear la imagen me ha tomado 5 minutos así que es satisfactorio para ambas partes.
El tooltip viene de las DBC y es 100% fiable.
La ID de la spell es lo único interesante, no el contenido, asímismo el link a OldWowhead tampoco corresponde a Cataclysm, por tanto, satisfacción para ambas partes, ya que estoy ofreciendo la fórmula.

**Comment by redneo** [comment]
Ya lo he bajado a 0.1886 como comentais, si está mal tambien en la 434 (aun no he probado) se puede bajar o subir sin problemas.

Con un pj full pve (Vestimentas mercuricas 4/5) me cura  3644 (7018 de poder de hechizos)

Un pj sin vestir, (poder hechizos 224) sana 1266.

Me acabo de fijar que el spell 63544 no va, pero si se pone ese aura, si que funciona y suma la cantidad correcta S:

**Comment by DatJetto** [comment]
ahora ya cura cantidades normales xD de 2 - 3k.
