### ISSUE TITLE
[Hunter > Spec: General > Spell > Cobra shot] 

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#114]
Disparo de cobra:
http://es.wowhead.com/spell=77767

hace un poco más de daño de lo que debe.

**Comment by aerz** [comment]
Estaría bien detallar un poco más el reporte si es posible porfavor :)

**Comment by macols77** [comment]
ole ole.. que majo el aerz

**Comment by DatJetto** [comment]
No sé que quieres que te diga, de este no tengo fórmula :c si quieres te subo una screen haciendo 40k en BM con cd de pet xD pero pega algo más que firme 2000 así debiendo ser el mismo daño aprox. así que supongo que podríais poner la formula de Steady Shot, ya que es igual solo que uno es de naturaleza y otro físico :camel:

**Comment by aerz** [comment]
mmm mas que nada si nos mostrases tus estadisticas y una screen estaría mas completo.
La fórmula creo que es: (248 + (RAP \* 0.086))
Deberíamos completar mas este reporte, solo digo eso XD
