### ISSUE TITLE
[ Desencantar épicos Cataclysm ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1143]
Buenas, hace un rato pedí a un amigo que me desencantara este abalorio, para conseguir cristales de la vorágine y hacerme un encantamiento.
http://es.wowhead.com/item=59520

En la descripción pone que al desencantar suelta cristal de la vorágine, pero esto no ocurrió así, le dio un polvo extraño, y por lo visto me comenta que para que suelte épico tiene un % muy bajo, cuando en el oficial desencantar cualquier épico por encima de ilvl 353  suelta vorágines, mínimo 1. 

Si hubiera alguna solución rápida antes de introducir 4.3 se agradecería, ya que conseguir cristales de la vorágine se hace casi imposible con este bug y entorpece la profesión de encantamiento. 

Saludos 3:

**Comment by redneo** [comment]
Ya lo puse bien, solo estaba ese item mal (a no ser que haya otro loot asignado a algun item por ahí) el caso que tiene 100% de soltar 1 o 2 cristales.
