### ISSUE TITLE
Npcs que cambian honor por otros items

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1144]
En Orgrimmar tenemos a Rogoc (http://es.wowhead.com/npc=52033) que nos cambia honor por items útiles, como Cristales de la Vorágine, Esencias celestiales, etc. Y en Ventormenta tenemos a Edlan Halsing (http://es.wowhead.com/npc=52029) que hace la misma función que Rogoc pero en la Alianza.
Estos dos npcs fueron añadidos en Cataclysm en la version qe estamos actualmente, pero en el servidor aun no estan.

**Comment by redneo** [comment]
Hola Wiinter, un placer volver a saber de ti!

Respecto a dichos npcs, estan spawneados... pero no aparecen desconozco el porqué ya que no tengo acceso a los logs del emulador.

A ver si alguien más te puede ayudar!

Edito: Ya he encontrado el fallo, cuando reinicie el server tendran que estar.

**Comment by ghost** [comment]
Nada más paso a decir que sigue sin estar en npc Rogoc en orgrimmar, y también, @redneo si puedes agregar estos: Togar http://es.wowhead.com/npc=52034 para la horda y Talric Franco http://es.wowhead.com/npc=52028 para la alianza, que son lo mismo pero con puntos de justicia.

**Comment by redneo** [comment]
Rogoc está y vende, Edlan no vendia.

Togar colocado y vendiendo
Talric Metido, pero necesito una caida del servidor para ponerlo, a ver si a la tarde hay suerte

**Comment by Wiinter** [comment]
Como siempre Redneo un placer que vuelvas y muchas gracias por arreglarlo
Hecho de menos que la gente se meta conmigo por chat jajajajajajaja y morir por culpa de .kill

P.D: Has subido el daño al destrucción y al demonología y el aflición los has dejado, porque? xD Es porque soy aflición?

**Comment by ghost** [comment]
@redneo perdón por venir a molestar más con esto xd, pero, está bien que venda solo 1 cristal de la voragine  cada cierto tiempo? tenía entendido que vende "infinitos", y también, esta mal el elementium, deberían ser packs de 20 y vende solo 1 mena por 1000 de honor, los cueros deberían ser packs de 5 y los paños packs de 20, ahora mismo todos los "packs" solo te dan 1 de lo que debería.

**Comment by redneo** [comment]
Cuando caiga el server todas las sugerencias metidas. (cristal de voragine, packs de telas, pieles y piedras...)

**Comment by Wiinter** [comment]
Diria qe el cristal de la voragine es uno cada cierto tiempo pero no lo puedo asegurar

**Comment by ghost** [comment]
De todas formas, @redneo ya lo dejo como lo dije ahí arriba y estan los npcs que venden con puntos honor y con puntos justicia (en la horda) así que muchisimas gracias redneo, sos un crack :P .
