### ISSUE TITLE
[ Paladin > Holy Radiance ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1145]
Hoy os traigo el gran secreto de los paladines heler bugeros en bg y arenas, que no puedes matar porque se curan más que su *****\* cara. 
Radiancia Sagrada: 
http://es.wowhead.com/spell=82327

Uno de los principales problemas está aquí, esta spell cura demasiado, siendo verde curas 1-2k como es mi caso, un pala bien equipado puede llegar a los 5-6k tic por segundo, ah que además te pone el escudito e_e''

![radianza](https://f.cloud.github.com/assets/2728817/518974/78871146-bf0a-11e2-9068-809d5f878d85.jpg)

Mi paladín lleva talentos con 6% más de sanación efectiva y 10% de sanación extra por el hecho de ser Holy, vale, tenemos un 16% de sanación extra.

El tooltip muestra que sanaremos 966p. cada segundo durante 10 sec, eso hace un total de 9660p, a CADA PERSONA en 20 metros.

Al lado se muestra mi Spell Power, ¿ridículo verdad? 2893, y ya cura 2422 y ticks de 3529.

Tomando por base que sanará 684p. por el tooltip del buff.

Hora de los cálculos:

( Lo que debería curar ) 966 - ( Sanación base ) 684 = 282p. extra deberían ser obtenidos vía Spell Power.

Dividimos para conocer el multiplicador > 282 / 2893 = 0.09

Fórmula que extraemos = ( ( SP \* 0.09 ) + 684 )

---

Ahora hagamos los cálculos respecto a como está actualmente para ver la desproporción.

Sana 2422 - 684 = 1738 ( Empieza a haber diferencias )

Dividimos > 1738 / 2893 = 0.6 !

¡ Está curando aproximadamente el 300% de lo que debería !

**Comment by redneo** [comment]
He bajado el spell segun a lo que me dice mi Dr. Damage:

Con un sp de 2590 sano 865 por tick, un poco más de lo que me dice el addon, comentad los paladines si es correcto por favor

**Comment by crowel** [comment]
Yo con sp 7000 curo 1447 - 2235 (critico) nosé si es la correspondiente sanacion pero al menos no cura una barbaridad, diria que es un pelín bajo aunque no anda lejos.
Un saludo

**Comment by DatJetto** [comment]
http://www.youtube.com/watch?v=1MW4qzydp5c Mira un video de un pala Heler en el ofi, El set se ve al principio, es 359 y algunos pvp y cura 1.2k - 1.8k de radianza.
http://www.youtube.com/watch?feature=endscreen&NR=1&v=TgLgSp4K_qA Este otro pala en el minuto 3:15 muestra Holy Radiance con 1.4k  de sanación por tick y críticos de 2.1k

**Comment by crowel** [comment]
En resumen que anda ya bien mas o menos verdad?

**Comment by ghost** [comment]
Según redneo, ya bajo la sanación.
