### ISSUE TITLE
El desafío del aspirante 

### ISSUE THREAD

**Issue by kiiit** [RoDNet/Bugtracker-Infinium-4.0.6a#1147]
empeso todo bien fui a hablar con el Escudero David hablas con el y manda al oponenete claro que tienes que estar montado en la montura que te mandan por facion y equipado con la lanza bueno llama al oponente empieso a peliar con el luego de derrotarlo o matarlo no marca la mision completa esta mision es la ultima para el torneo arjenta yes muy importante todas las demas del torneo estan bien bueno espero que lo arreglen de ante mano doy las gracias :)

**Comment by redneo** [comment]
Esta "solucionado" sale el aspirante, pero no se mueve como antes... tendria que mirar el codigo a ver como va y que killc da.
