### ISSUE TITLE
Vestimentas del Mar de Dunas

### ISSUE THREAD

**Issue by Eestheer** [RoDNet/Bugtracker-Infinium-4.0.6a#1149]
En la mazmorra  Ruinas de Ahn'Qiraj,  en el 1º boss, Kurinnaxx cae un vestido, Vestimentas del Mar de Dunas ( http://es.wowhead.com/item=21499 ) que tiene un 11% de posibilidades de caer, pero cada 3 días que es lo que dura su cd, mato al boss y nunca suelta ese vestido y llevo 2 meses así, entonces comprobad si realmente lo suelta, porque si no estoy perdiendo en tiempo por favor, gracias.

**Comment by redneo** [comment]
He cambiado el loot del boss..

tiene un
10% de tirar 21498
10% de tirar 21499
20% de tirar 21500
20% de tirar 21501
20% de tirar 21502
20% de tirar 21503
100% si tienes la mision de tirar 22217

luego...
15% de tirar uno de los siguientes items:
20727,
20728,
20729,
20730,
20731,
20734,
20736

100% de tirar uno de estos items 
20885,
20889

20% de tirar uno de estos items
20884,
20888

y un 100% de tirar dos items de los siguientes
21214,
21279,
21280,
21281,
21282,
21283,
21284,
21285,
21287,
21288,
21289,
21290,
21291,
21292,
21293,
21294,
21295,
21296,
21297,
21298,
21299,
21300,
21302,
21303,
21304,
21306,
21307

No se si te ha quedado claro, pero ahora el loot es mucho mas blizlike

**Comment by Eestheer** [comment]
Gracias ^-^ hoy según mate al boss me soltó ya el vestido a la primera, además voy a estar ausente durante un mes aprox. y no iva a poder hacer la mazmorra, asi que es una cosa que ya me quito de encima, muchas gracias otra vez :)
