### ISSUE TITLE
Misión El Drakkensryd

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1152]
Creo haber leido alguna vez que la arreglaste redneo, pero esta bug, no puedes atacar a los npcs "normalmente", tampoco con el arpon y si te subes al draco te tira hacia abajo.
Enlaces:
Misión: http://es.wowhead.com/quest=12886
Npc bug: http://es.wowhead.com/npc=29694

Tengo la esperanza de algún día completar toda la cadena de misiones xd.

**Comment by redneo** [comment]
parched!
