### ISSUE TITLE
Misiones Forjando una Alianza y No tiene pérdida

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1154]
Bueno, según un comentario de wowhead:
"Para completar este quest tienes que hacer lo siguiente:

1º Ir a hablar con el Rey Jokkum q se encuentra en las coords 65-60
( http://www.wowhead.com/?npc=30105 ) el cual t manda a hablar con Njormeld ( http://www.wowhead.com/?npc=30127 )
2º Completar la mision q t da la cual es guiar al viejo Snorri el cual esta a su derecha y con completar esa quest completaras tambien ESTA quest :D "

Lo de hablar con Njormeld es otra misión, "No tiene pérdida", que te manda a hablar con el npc Njormeld que no está.

Enlace de la misión Forjando una Alianza: http://es.wowhead.com/quest=12924
Enlace de la misión No tiene pérdida http://es.wowhead.com/quest=12966

**Comment by redneo** [comment]
Pasa lo mismo, los npcs estan, pero puede que no en la fase apropiada.

**Comment by ghost** [comment]
Eso significa que no sera arreglado o que falta que caiga el server? xd, y lo de las fases tienes razón, puedo ver algunos npcs e items de la misión Enmiendas (que es en la misma zona que esta y las otras que reporte) desde la zona de al lado.

**Comment by redneo** [comment]
Eso significa que a ver si te pillo online y voy cambiando de fases a la fase correcta a los npcs

**Comment by ghost** [comment]
Reparada, gracias =)
