### ISSUE TITLE
Misión Jormuttar está taaan gorda...

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1156]
Tienes que ir a una cueva, usar el item Navaja de siemprescarcha en un Oso Faucehielo muerto para que te de un pedazo de carne (no sé como se llama), y tirarlo en un agujero para que salga Jormuttar.

No funciona la parte de conseguir la carne del oso muerto, y supongo que tampoco funcionara la parte del poso.

Enlaces:
Misión: http://es.wowhead.com/quest=13011
Navaja de siemprescarcha: http://es.wowhead.com/item=42732
Oso Faucehielo: http://es.wowhead.com/npc=29562
Jormuttar: http://es.wowhead.com/npc=30340

**Comment by redneo** [comment]
Reparada a falta que se pruebe, a lo mejor los osos no estan en la fase apropiada, con el gm lo he podido hacer correctamente.

**Comment by ghost** [comment]
Los osos si estan en la cueva, lo que pasa es que no te da la carne, y ahora que la probe al usar el item para conseguir la carne dice "objetivo no válido", antes podías usarlo pero no daba la carne.

**Comment by redneo** [comment]
Hay otros osos muertos en la entrada, que como supongo, estan en otra fase... los voy a cambiar y poner en la misma fase que los osos normales.

**Comment by ghost** [comment]
Reparada, gracias redneo.
