### ISSUE TITLE
[ Shaman > Lightning Shield ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1161]
Escudo de relámpagos:
http://old.wowhead.com/spell=324

Para empezar tiene varios fallos, no se si se corresponderán a la propia spell o a talentos añadidos posteriormente pero el daño está bastante elevado.

La maestría puede ser una causa de ello: http://es.wowhead.com/spell=77223
o este talento: http://old.wowhead.com/spell=51881

1- Su daño, es claramente superior al que debería, puede matar un pícaro o un feral sin castear spells. 

2- Su CD actualmente NO tiene CD y la spell dice: Este efecto solo ocurre una vez cada pocos segundos.
Se supone que tiene un CD interno de 3 segundos el cual no se cumple.

3- Según las notas en Wowiki y algunos comentarios de Wowhead, ESTA SPELL NO PUEDE HACER DAÑO CRÍTICO pero sí lo hace.

http://www.wowwiki.com/Lightning_Shield

> The damage caused is considered direct damage, though it CANNOT crit.

El sujeto en cuestión para testear es Azraelt, ahora procedo con la imagen y a explicarla: 

![lightning shield](https://f.cloud.github.com/assets/2728817/556045/25a5db50-c3cf-11e2-8166-e7934597d428.jpg)

La imagen está dividida en 2 Recuadros:
- ROJO > DESNUDO. 0 Temple.
- AZUL > VESTIDO. 3667 ( 38,51% ) Temple.

Le pedí que me describiera el Tooltip y me dijo que pega 3229, de acuerdo, a ese 3229 debería quitarle mi temple y debería pegarme 1243p. 

Si pego desnudo obviamente debería pegarme aproximadamente 3229, la sorpresa es que pega 5128 y 6256 , ¡SIN CRITICO!

Con ropa me pega 3154 y entorno a 3000 - 3500

En las imágenes de abajo vemos como cuando mi maestría salta y tira doble flecha, el escudo me impacta 2 veces, hasta la última imagen en azul que me impacta 3410 - 3570   ¡ NADA MENOS QUE 6 VECES ! 

He de recalcar que Maestría: sobrecarga elemental NO debe afectar al escudo ya que solo afecta a los 3 hechizos primordiales del Chamán elemental, Cadena, Descarga de relámpagos y Ráfaga de lava.
http://es.wowhead.com/spell=77222

Añado una imagen por Jeiperman donde se ve cómo el pj es semi verde y el escudo le daña de 7-8k y 17k de crítico:
http://img818.imageshack.us/img818/3602/wowscrnshot052413154906.jpg

**Comment by Overseer101** [comment]
Debo añadir algo mas, yo con redneo tocamos el daño del escudo de relampagos, y en "Teoria" lo dejamos al nivel que tenia que tener, ahora bien, no se por que narices si estas en mejora y cambias a elemental, te aumenta el daño del escudo de relampagos, yo hice las pruebas en elemental puro y con eso y el daño era sustancial (y mas yo teniendo en cuenta que en mejora tengo 9 de mastery que en total es un 42.5% de daño elemental extra), lo mas gracioso es que SOLO afectaba a esa spell, y con respecto al cd de 3s he de decirte que lo probamos tambien y respetaba los 3s de cd entre impacto y impacto, ahora bien, has dicho que solo te pego 2 golpes al saltar la maestria?, entonces es posible que sea algun problema del carcaj salvaje en si, ya que con mi hunter me ha llegado a saltar como 7 veces a la vez O.O
![wowscrnshot_040513_132704](https://f.cloud.github.com/assets/3658679/565256/20400ef8-c5f8-11e2-8cb7-da6ae66b49ca.jpg)

Y no, no quiero echar balones fuera, pero si solo te ha echo el doble golpe con el impacto del carcaj salvaje puede ser que venga por ahi el desmadre, por que redneo, me pego a mi con un picaro precisamente para comprobarlo y no saltaba por cada dagazo que pegaba,asi que toca llamar a Mulder y Scully a ver si sacamos que pasa XD

P.D. No hace falta llamarlos, te confirmo que la maestria "Carcaj salvaje" hace que te comas varios impactos si salta mas de 1 vez, de echo en tu ultima imagen se ve claramente , de todas formas por si acaso lo he probado tambien...

**Comment by Overseer101** [comment]
Ah otra cosa, las tooltip no marcan el daño "Real" de una spell ya que no refleja muchos de los modificadores que tiene cada hechizo, si no usando tus calculos, el fulminar pegaria... 7k?, y es una spell que los 24k sin critico te los pega tranquilamente..., y lo de que no puede hacer daño critico... eso es en pandaria, eso si, te doy la razon en que pega de mas, y eso que lo dejamos para que pegase no mas de 6k con un equipo como el mio........., pues ahora me pega 8500...

**Comment by DatJetto** [comment]
Lol xD que de Carcajes, la verdad es que yo maestría lo mínimo así que me salta poco. Almenos hemos descubierto que +mástery + golpes por la cara (?) cuando solo debe ser uno xD.

El CD esque no entiendo que le pasa, porque cuando le tiro varios ataques siempre TODOS  me los devuelve el escudo en vez de darme 1 solo .n. 
Te hablo de por ejemplo tirar Firme, acto seguido el automático sale y tiras arcano, los 3 impactos llegan a la vez aproximadamente ( si no sale mastery, que serían 4 ) y me da 3 hits el escudo :$

**Comment by Overseer101** [comment]
Pues lo unico que se me puede ocurrir es que diferencie entre ataques a distancia y a melee, me explico, que por la razon X no respete el cd con los ataques a distancia, y a melee si los respetase, o eso o mi chaman es el unico que respeta cds y no pega 18k con una carga del escudo xDDDDDDDDDDDDD

P.D. Lo del carcaj salvaje no se por que es, pero desde luego yo voy con equipo de profesion, asi que mucha maestria no llevo, me da como si saltase consigo mismo cuando se le va la pinza...es raro xDDD

**Comment by DatJetto** [comment]
Si, yo también he pensado que pudiera darse el caso de:
1 - Un ataque puede ocasionar más de 1 proc de Wild Quiver.
2 - Wild Quiver puede ocasionar procs del propio 1 o varios WQ.
3 - Las anteriores juntas. 

Respecto a mi mastery creo que es de 1.37 o así.
