### ISSUE TITLE
el peor bug de todos !!!

### ISSUE THREAD

**Issue by kiiit** [RoDNet/Bugtracker-Infinium-4.0.6a#1162]
solo era para llamar la atencion una pregunta estoy perdiendo el tiempo en poner mis bug aqui por que e colocados muchos y muy importantes y nunca los arreglan asique sirve de algo reportar los bug plz seria bueno saberlo para dejar de perder el tiempo :)

**Comment by ghost** [comment]
Si quieres dejar de perder el tiempo deberías dejar wow en primer lugar... xd.
