### ISSUE TITLE
Arcanista Taelis <El Pacto de Plata>

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1164]
http://es.wowhead.com/npc=33625
![GitHub Logo](http://wow.zamimg.com/uploads/screenshots/thumb/126575.jpg)

Este NPC le faltan 2 quest (creo) Pues ya complete los requisitos y no me las da.

http://es.wowhead.com/quest=13689 Un Valeroso de Darnassus
http://es.wowhead.com/quest=13688 Un Valeroso de Gnomeregan

![wowscrnshot_052413_151313](https://f.cloud.github.com/assets/2059256/563105/ea2c1c64-c4bf-11e2-9eaf-c3b26138c4a5.jpg)
![wowscrnshot_052413_151500](https://f.cloud.github.com/assets/2059256/563104/e55e98c4-c4bf-11e2-9b8a-0640642f74cc.jpg)

Asi como muestran las imagenes debes ser exaltado con cada una de las ciudades de la alianza y ser Valeroso en Torneo Argenta, para despues habilitarte a darte la siguente cadena de quest.

Valeroso: Ventormenta, El Exodar, Forjaz, Darnassus, Gnomeregan

Pero estos 2 ultimos no te los da y ya soy exaltado con los 2.

---

**NOTA:**
Al principio crei que era nada mas con tu raza (humano en mi caso) pero no es asi puedes representar a cada una de las razas si eres exaltado con cada una de ellas. Y al final cuando seas CAMPEON ARGENTA te daran este logro.

http://es.wowhead.com/achievement=2817 Campeón Argenta Exaltado de la Alianza
![champion_of_the_alliance2](https://f.cloud.github.com/assets/2059256/563132/6d832fca-c4c1-11e2-8665-5c092a40d223.jpg)

**Comment by WarSxNes** [comment]
No mas te escribo para decir que hoy fui a probar las quest y siguen sin aparecer.
Hoy 5/26/2013 horario -8 UTC

_no te te enojes no mas es para no perderle el hilo ya que andas arreglando las de torneo argenta_ =) y de paso pues fui a verificar.

O y me dijieron algunos que tambien tienes que ser exaltado con Gilneas para darte esas 2 quest y pues ya soy exaltado y aun no las da. _solo faltan esas 2 que mencione arriba ^ en el primer comentario_

**Comment by redneo** [comment]
Te tendrian que dar la quest ya, lo que me parece que lo que hace mal es que te estas cogiendo las quest equivocadas....

Esas quest, tendrian que ser para cada raza, siendo para el resto de razas http://es.wowhead.com/quest=13704 pero no me voy a romper la cabeza con eso... ya me diras si va o no.

Un saludo

**Comment by WarSxNes** [comment]
**Como dije en el primer comentario este es el logro ^**
![champion_of_the_alliance2](https://f.cloud.github.com/assets/2059256/568680/10b7b8ba-c6e2-11e2-8efb-3ee2caf6b981.jpg)
**Y estos son los requicitos para alcanzar el logro**
![exalted champion of the alliance - achievement - world of warcraft 2013-05-27 08-28-06](https://f.cloud.github.com/assets/2059256/568681/1436308e-c6e2-11e2-80d8-8b02fb6e7f01.png)

Bien el requisito para esto es ser exaltado con cada una de las ciudades principales de cada faccion. Cada cadena se va habilitando conforme eres exaltado con cada una de ellas. Y luego tienes que completar la cadena de quest de cada raza para representarlos y asi obtener el logro y pasar a la siguiente fase, asi sucesivamente.

Tengo entendido que lograr todo esto lleva su tiempo en el oficial almenos para ser aspirante se toman 3 dias por los emblemas que necesitas dar (5 por dia) valeroso 25 emblemas (x3 por dia) y asi sucesivamente, creo que te lleva mas o menos como 1 mese completar todo el torneo.

**Comment by redneo** [comment]
Teoricamente esta arreglado, a mi pj le salian todas.

**Comment by WarSxNes** [comment]
Oo si ya funcionan, el comentario anterior solo fue una respuesta a lo que dijo sobre:
redneo@: _(lo que me parece que lo que hace mal es que te estas cogiendo las quest equivocadas....)_

Ya se ven todas, las puedo coger/tomar y funcionan correctamente. Salvo 2 quest que luego las reportare.

---

_CURIOSIDAD:_
_escribo "coger/tomar" por que en america coger se relaciona con el acto de copulacion entre 2 personas, tomar es una palabra homógrafa es decir tienes 2 o mas significados, en este caso beber un liquido, tomar algun objeto sobre una superficie y llevarlo hacia un punto A asta el punto B._
