### ISSUE TITLE
El gran combate cuerpo a cuerpo -  TORNEO ARGENTA valeroso

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1165]
![logo](http://wow.zamimg.com/uploads/screenshots/thumb/258588.jpg)
http://es.wowhead.com/quest=13665 El gran combate cuerpo a cuerpo

http://www.youtube.com/watch?v=7rLF_8mgRaY << VIDEO

---

**BUG:** bien tienes que hablar y luego pelear y derrotar a los valerosos... No pasa nada despues de hablar con ellos.

---

**NOTA:**
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1164 relacionandolo con el post anterior me hago una pregunta. _(no se vallan a enojar)_

Se que es mucho dolor de cabeza arreglarlos. Pero como ya anunciaron el nuevo parche 4.3.4 no se si valga la pena arreglarlos. _(asta incluso seguir jugando :p)_ y es que quien sabe si la DB actual sea compatible con el nuevo nucleo 4.3.4

Asta he llegado a pensar que podria perder todo _(hasta miedo me dio)_

Espero con ansias la noticia de apertura del reino de testo 4.3.4 y asi dejar de reportar bugs del antiguo.
_(seria bueno que dieran una fecha lo antes posible y comenzar todos a testearlo; me anoto en la lista)_
-- actualmente tengo una pequeña lista de 74 bugs solo en rasganorte -- :P

**Comment by DatJetto** [comment]
Buenas, con el conocimiento de que la futura 4.3 será TrinityCore y TC en Lich King tenía arreglada esa zona, supongo que la implementaría a Cataclysm, de manera que puedo estimar en un 75% que esa zona estará bien en 4.3 :3

La verdad es que los eventos del Torneo Argenta son de lo mejor de LK así que tenerlos sería bastante acertado, Nice Gaming!

**Comment by redneo** [comment]
Arreglado la versión alianza, a la espera de que alguien me lo compruebe y lo pase a la horda tambien.

Muchos, por no decir casi todos los datos que saco y aplico son de las bds de la 434 y mientras no tengamos la nueva versión merece la pena arreglar las cosas para el mejor funcionamiento de lo que se está usando en este momento, creo yo...

Eso sí cuando ya este puesto el server test, a ver como actuo.

Un saludo.

**Comment by ghost** [comment]
Arreglada en la horda, muchas gracias redneo.

**Comment by WarSxNes** [comment]
![wowscrnshot_052513_093357](https://f.cloud.github.com/assets/2059256/564340/932fb386-c559-11e2-9f20-9d60f2b7e85f.jpg)

Del lado de la alianza siguen bug... Ya borre cache y nada...

Solo los Valerosos de El Exodar reaccionan al hablar con ellos.

Ventor, Darna, Forjaz, Gnome siguen bug...

**Comment by redneo** [comment]
Probaste con la lanza y la montura?

**Comment by WarSxNes** [comment]
No se si se logra apreciar en la foto que voy montado sobre un caballo y llevo una estaca y escudo =) (una broma)

claro si con montura y lanza. Click sobre los NPC hablo con ellos. Pero esperame que este post ya lleva 1 dia voy a probar y luego regreso para responder.

**Comment by WarSxNes** [comment]
![wowscrnshot_052613_144027](https://f.cloud.github.com/assets/2059256/565922/bff2b5e0-c64d-11e2-8509-c036815f8a77.jpg)
![wowscrnshot_052613_144100](https://f.cloud.github.com/assets/2059256/565923/c541efac-c64d-11e2-8f18-8c5e679914eb.jpg)

Nop... ALIANZA valeroso sigue bug.. solo El Exodar funcionan y asta te atacan y todo xD.

**Comment by redneo** [comment]
![wowscrnshot_052713_091000](https://f.cloud.github.com/assets/1163425/566697/7a8eb3d8-c69c-11e2-917c-8e7468c6a2cd.jpg)

Y con un PJ

![wowscrnshot_052713_091115](https://f.cloud.github.com/assets/1163425/566699/a88db928-c69c-11e2-9fbe-f55eafee1e0d.jpg)

Tenemos un problema ya que si que lo pillo

**Comment by WarSxNes** [comment]
Tu hablas del texto _"Estoy listo para la Lucha"_?

Si eso tambien me sale... por eso digo despues de "hablar con ellos" cuando digo hablar me refiero despues de hacer CLICK en la frase _"estoy listo para la lucha"_.

Despues de hacer CLICK en la frase se deberian de poner como enemigos y comenzar a atacarte, tal y como lo hacen los de El Exodar no?

---

**NOTA:** creo que la confusion fue que en la foto que publique no sale la frase _"estoy listo para la lucha"_. y es que ya habia echo CLICK cuando saque la imagen =)

**Pregunta** de casualidad hiciste click en la frase? pues en ninguna de las 2 imagenes que publicaste te veo pelear =)

**Comment by WarSxNes** [comment]
![wowscrnshot_052713_090033](https://f.cloud.github.com/assets/2059256/568851/c5c35cdc-c6e7-11e2-90e0-636ad627016c.jpg)
![wowscrnshot_052713_090040](https://f.cloud.github.com/assets/2059256/568852/caac319c-c6e7-11e2-82fe-8283ea9edea0.jpg)
![wowscrnshot_052713_090103](https://f.cloud.github.com/assets/2059256/568854/cebe19da-c6e7-11e2-96ab-6a01ac0c653d.jpg)
![wowscrnshot_052713_090124](https://f.cloud.github.com/assets/2059256/568855/d21cea34-c6e7-11e2-9272-cfce8c139376.jpg)
![wowscrnshot_052713_090144](https://f.cloud.github.com/assets/2059256/568856/d52f77a0-c6e7-11e2-9053-637a74a4f4bf.jpg)

**Que tal mejor explicado no? =)** solo El Exodar Valeroso funciona el resto no hace nada; lado horda no tengo idea.

**Comment by WarSxNes** [comment]
![wowscrnshot_052713_091411](https://f.cloud.github.com/assets/2059256/568897/fa0dd17e-c6e8-11e2-9fce-5037735cd21c.jpg)
![wowscrnshot_052713_091427](https://f.cloud.github.com/assets/2059256/568898/fd2e0c70-c6e8-11e2-8c31-90b101ad70da.jpg)

Si no estoy mal parece que intentaste arreglarlos por que ahora se ponen como enemigos pero ahora sale un mensaje de "OBJETIVO NO VALIDO" en los valerosos gnomeran y forjaz.

Con darnassus y ventormenta no pasa nada siguen quedando como amistosos despues de hacer CLICK en el mensaje.

**Comment by ghost** [comment]
Eso que postea WarSxNes también pasa con Valeroso de Entrañas xd.

**Comment by redneo** [comment]
Creo que ya todos van bien (cuando caiga el server) aunque te tengas que desmontar para darlos ya que no cogen agro si les das desde el caballo.

**Comment by WarSxNes** [comment]
Hoy fui al a verificar y funcionan.... lo que no entiendo es por que dicen que hay que desmontarse del caballo.

Si es cierto, que se sanan; pero si no los matas es por que necesitas mas practica. _(como dicen ustedes en españa son mancos)_ _(or u r still a n0ob)_ :P

Ya les voy dejando varias fotos y no creo que no se aprecie que voy montado en un caballo :p por si acaso ahi les dejo otras;

**QUICK GUIDE by WarSxNes:** ("\;..;/") _Bwahaha!!!_

![wowscrnshot_052813_140132](https://f.cloud.github.com/assets/2059256/575382/16dbb2be-c7dc-11e2-8947-d5ce8e344ff7.jpg)
![wowscrnshot_052813_140552](https://f.cloud.github.com/assets/2059256/575383/19e73a1e-c7dc-11e2-890c-b0d0e6687c7a.jpg)
![wowscrnshot_052813_140957](https://f.cloud.github.com/assets/2059256/575385/1c5dde92-c7dc-11e2-932c-2f6c818718c5.jpg)
![wowscrnshot_052813_140622](https://f.cloud.github.com/assets/2059256/575386/1ee01630-c7dc-11e2-8b0a-391bc2e1d527.jpg)

Funcionan al 100%, ahora cada valeroso de cada faccion; hasta que no pase lo contrario. Good Job RedNeo =)
