### ISSUE TITLE
[Torneo Argenta] - Liza de los Campeones

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1167]
Unicamente por parte de la Horda, la Alianza no lo sé, se pueden retar a los Campeones de Gnomeran, Forjaz, Exodar y Sen'jin. Los demás no te dejan. Por ejemplo en el caso de Ventormenta y Darnasus no te dejan ni hablar con ellos y Lunargenta, Cima del Trueno y Orgrimmar te dejan hablar y te sale lo de retar pero al darle no hace nada.

Todo esto si lo haces siendo Horda, siendo Alianza no se si cambiará algo

**Comment by WarSxNes** [comment]
Nop estan bug y ya habia hecho un post relacionado xD _(te gane)_
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1165 <<< aqui el post

**Comment by ghost** [comment]
Tienes que ir con la montura, te vas les hablas y luego te desmontas y ahi puedes atacarlos.

**Comment by Wiinter** [comment]
No son los mismos npc qe los de ese post. Ese post habla sobre la liza de los valerosos yo hablo de la otra, que estan las dos facciones juntas.

Siempre hago eso de la montura y después me salgo, el problema es qe algunos campeones no van ni qe vayas montado en Alamuerte xD(es obvio que he ido en la montura del torneo y con su correspondiente lanza)

**Comment by ghost** [comment]
Pues.. si algunos van cual es el problema? ya puedes hacer la misión xd.

**Comment by redneo** [comment]
Estan los valerosos, que estan separados, cerca de cada tienda de campaña de cada faccion y luego los campeones, que estan todos reunidos en un gran rectangulo, creo que estan reparados todos...

Probad con monturas y lanzas!

**Comment by Wiinter** [comment]
Yo necesito qe vayan todos. Yo lo quiero para el logro, no para la mision xD

**Comment by redneo** [comment]
Decidme cual es el que no va y lo miro.

**Comment by Wiinter** [comment]
No van los de Lunargenta, Cima del Trueno, Orgrimmar, Entrañas, Darnasus y Ventormenta

**Comment by redneo** [comment]
Todos van ya, cierra el ticket cuando lo compruebes

**Comment by ghost** [comment]
@redneo ya todos funcionan, el logro http://es.wowhead.com/achievement=2836 se puede conseguir, pero solo si matas a los npcs "lento", o sea no hay que matarlos sino bajarles la vida lo minimo y te cuentan para el logro. 
No sé si puedes ponerles un "tope" de vida máxima que se les puede bajar y luego vuelven a ser amistosos?

**Comment by Wiinter** [comment]
La cosa es dejarle  2k de vida. Si por ejemplo le metes un critico de 20k y lo matas no te salta lo de Campeon, por lo demás funciona. Cierro
