### ISSUE TITLE
Misión Un arma digna

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1168]
Bueno, es simple, esta misión, es exactamente la misma que ya habías reparado con la excepción de que esta da "sellos de valeroso" y lo comienza otro npc. 

El problema esta en que no se pueden despojar los jacintos.

Enlaces:
Misión:http://es.wowhead.com/quest=13784
Jacintos: http://es.wowhead.com/item=4500

**Comment by redneo** [comment]
Arreglado cuando caiga el server.
