### ISSUE TITLE
Monedero de Campeón -  loot bug

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1171]
![mone](http://images1.wikia.nocookie.net/__cb20061111030708/wowwiki/images/thumb/4/47/Inv_misc_bag_10_blue.png/32px-Inv_misc_bag_10_blue.png) - http://es.wowhead.com/item=45724/monedero-de-campeon

Simple el loot esta bug, cada que completas una quest en torneo argenta valeroso o campeon te entregan uno de estos.

Siempre Siempre... se te deberia entregar 10 monedas de oro.

Aunque no esta comprobado, pues ni **wowhead** ni **wowwiki**  dicen a ciencia cierta si contiene tambien un [Sello de Campeón](http://es.wowhead.com/currency=241)

---

**NOTA:**
 wowwiki en su descripcion dice que ti contiene un sello siempre
http://www.wowwiki.com/Champion%27s_Purse

Y en wowhead solo los comentarios en English dicen que contiene un sello de campeon + 10g

_Post relacionados:_
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1165
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1164

**Comment by redneo** [comment]
Dificil solucion tiene...

Posee un loot de un 8% del item 44990, pero, creo que no cuenta para comprar cosas...

Poner un http://es.wowhead.com/currency=241 lo veo complicado, muchisimo!

**Comment by WarSxNes** [comment]
Bueno de todas formas deberia de dar oro 10g y no lo hace. Y segun wowwiki en Cata. da siempre el sello. ----

---

_Tengo una pregunta y como es entonces que el ORO, PLATA, BRONCE funcionan?_

No son item, supongo no? simplemente esta como despojo y automaticamente se añade al jugador.

OK, me imagino (ejemplo) si en el loot de un NPC (rata, o conejo). Lo matas y haces click sobre el y te aparece oro/plata/cobre ese dinero supongo que debe de tener un ID no? digamos 1345 (ejemplo).
Entonces supongamos que cuando matas un boss de alguna banda heroica te diene que dar puntos de justicia (digamos ID 395) cuando haces click sobre el boss ya muerto.
Entonces supongo que vendria siendo la misma funcion con el monedero haciendo click sobre el y te añade el currency/moneda automaticamente. no? (en teoria)

---

**NOTA I:**
Buscando por google wowhead y otros. No pude encontrar la ID del oro/plata/bronce pero supongo que deben de tener una (plural) y tambien he de suponer que son currency/moneda y no item.

**sugerencia**
Si... y digo SI sepuede, y si es como me lo imagino...... --- en el loot de cualquier cosa puede agregar o quitar cosas; en este caso si el monedero tiene 10g supongo que puedes agregarle otros 10g (por separado) haciendo 2 montos de oro dintintos no? bueno a lo que voy es que si oro tiene un ID como currency pues supongo que solo reemplazas esa ID por la del sello de campeon.. _(son puras tonterias las mias,,, pero me imagino que asi deberia de funcionar no)_

**Comment by redneo** [comment]
Te explico un poco por enciama...

Cada cosa suele ir en su tabla, por poner un ejemplo creature_template esta casi todo relacionado con los npcs, faccion, nombre... y el loot que dan incluyendo dos campos llamados `mingold`  y  `maxgold` eso quiere decir a un npc que cuando lo matas tiene que dar x monedas de bronce como minimo y x como maximo. De ahi se saca el loot de oro de un npc.

Ese tipo de campos, en item_template (lo mismo para los items, en este caso la bolsa) no existe.

Antes era sencillo meter los items de monedas, ya que por a o  por b seguian siendo items (en LK) con el paso del cata, las monedas son otro tipo de items que no son items, son CURRENCYS, que no existen en la base de datos como tal. Al principio de las emulaciones del cata, matabas bosses y no habia dios que te diera las monedas, pero luego se inventaron la tabla creature_onkill_reward (programando todo para ella, logicamente) en la cual se pone el npc que matas y lo que te tienes que soltar de currency, así como la reputación.

Como solucion complicada de cojones, podria hacer que tubiera de loot un item que te diera una mision, la cual al entregarla te diera 10 de oro y la currency apropiada, pero seria un tanto complejo... si insistes mucho mucho... :P

**Comment by WarSxNes** [comment]
Bueno guardare los monederos como recuerdo haber si algun dia se arregla xD
