### ISSUE TITLE
[Mazmorra] El Alcatraz

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1173]
Al matar los bosses Dalliah la Oradora del Sino http://es.wowhead.com/npc=20885 y Arúspice de cólera Soccothrates http://es.wowhead.com/npc=20886 en la mazmorra de El Alcatraz no se abre la puerta del siguiente nivel para ir a la zona del Pavellón de Aislamiento

**Comment by redneo** [comment]
ya se podran abrir la puerta cuando caiga el server

las dos que hemos mirado

**Comment by Wiinter** [comment]
Arreglado
