### ISSUE TITLE
Violación territorial

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1175]
Te vas al lugar de la misión usas el huevo y aparece la dragona, pero no se completa la misión.

Enlaces:
Misión: http://es.wowhead.com/quest=13051
Item: http://es.wowhead.com/item=42797

**Comment by redneo** [comment]
reparada cuando caiga el server, me comunicas si va....

**Comment by ghost** [comment]
Pues cayo el server, fui a hacer la misión pero sigue sin funcionar.

**Comment by redneo** [comment]
me faltó meter un script a un npc, ya va!
