### ISSUE TITLE
Loot Bug Suma Sacerdotiza Azil 

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1176]
El npc Suma sacedotiza Azil del nucleo petreo (Heroico) debería dar los items de la dificultad heroica pero solo da las de normal.

Enlaces:
items que debería dar: http://es.wowhead.com/npc=42333/suma-sacerdotisa-azil#drops:mode=heroico

Imagen de lo que da ahora:
![loot](https://f.cloud.github.com/assets/3508051/564565/6390aca2-c57c-11e2-8d9a-fddd55ecdea4.jpg)

Si lo consigues reparar @redneo puedes cerrar estos xd #952 #854

**Comment by redneo** [comment]
Pufff!!!

Para empezar, estabais matando a la sacerdotisa en modo normal, aunque estuviera en heroico. Ya está arreglado, pero ahora veo que el loot en normal está mal, ya que el ultimo boss de las mazmorras tiene que dar solamente 2 items (y a veces quest items y cosas por el estilo). 

Supongo que en un momento estaran las dos cosas completas arregladas.

**Comment by ghost** [comment]
Con razón estaba tan facil xd.

**Comment by ghost** [comment]
Creo que ya se arreglo, lo reabro si es que sigue bug, gracias redneo.
