### ISSUE TITLE
[Mision] Harrison Jones y El templo de Uldum

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1178]
Vas hasta el sitio indicado, pero no pasa nada. Entonces no puedes completar la mision y por tanto no puedes seguir con la cadena de misiones.

Aqui dejo el link: http://es.wowhead.com/quest=28612

Cabe decir qe me he pateado toda la plaza donde se supone qe debería completarse pero nada en ningun sitio se te completa. En el oficial se completa la quest despues de ver un video sobre el arca y Magni.

**Comment by redneo** [comment]
Arreglada (habla con bramm)
