### ISSUE TITLE
Misión Krolmir, el Martillo de las Tormentas

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1179]
Tienes que hablar con el Rey Jokkum para que te cuente una historia y completar la misión, pero no deja "avanzar" en la historia.

Enlaces:
Misión: http://es.wowhead.com/quest=13010
Npc: http://es.wowhead.com/npc=30105
Npc donde entregar la misión: http://es.wowhead.com/npc=30390

**Comment by redneo** [comment]
Arreglada cuando caiga el server
