### ISSUE TITLE
Misión El destino de los caídos

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1180]
Primero, faltan más de estos items "Cristal de alma desechado", solo encontre 2 en el lugar.
Segundo, al tener ese item y usar este otro item "Reliquia bendecida por la Luz" sobre los npcs "Espíritu de héroe caído" no cuenta/suma para completar la misión.

Enlaces:
Misión: 
Item/loot: http://es.wowhead.com/item=47035
Item misión: http://es.wowhead.com/item=47033
Npcs: http://es.wowhead.com/npc=32149

**Comment by redneo** [comment]
Arreglada, supongo que cuando caiga el server
