### ISSUE TITLE
Misión Rescate en el mar

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1181]
La misión en si funciona, el problema es que en el lugar de la misión estan los npc Arponero Kvaldir y Rabioso Kvaldir, pero al lado de sus nombres dice "(muerto)", entonces no suman ni cuentan para la misión. Aclaro que también estan los npcs que si suman y cuentan para la misión.

Enlaces:
Misión: http://es.wowhead.com/quest=14136
Arponero Kvaldir: http://es.wowhead.com/npc=34907
Rabioso Kvaldir: http://es.wowhead.com/npc=34947

**Comment by redneo** [comment]
Eso puede ser porque los npcs que hay por ahi los hayan matado... creo que va bien la mision

**Comment by ghost** [comment]
Si si, la misión va bien, el problema es que estan estos ncps con la palabra "muerto", peleando, y los otros sin esa palabra, que si cuentan para la misión.
O sea el bug sería que deberían estar solo los que no tienen la palabra "muerto".

**Comment by ghost** [comment]
Siguen ahí pero bueno, igual lo cierro xd.
