### ISSUE TITLE
[Mision] Por aire, tres

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1183]
Consiste en poner 3 bengales en el templo de Uldum pero por mucho que utilices el item qe te dan en los lugares correctos no funciona, ni si pone la bengala ni se marca en la qest
Aqui dejo el link: http://es.wowhead.com/quest=28622

Y aqui dejo un video de como debería hacerse la mision por si sirve de ayuda : http://www.youtube.com/watch?v=VPhwJfdmYRg&feature=youtu.be

**Comment by redneo** [comment]
Mision arreglada, de paso miro la siguiente.

Cuando caiga el server teoricamente estará la siguiente.

**Comment by Wiinter** [comment]
Gracias Red, Cierro tema
