### ISSUE TITLE
[ Murallas de fuego infernal > Vazruden el Heraldo ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1184]
Este npc http://es.wowhead.com/npc=17307 junto a su dragón Nazan http://es.wowhead.com/npc=17536 forman un Boss de Murallas de fuego infernal, el problema viene en el encuentro.

El Dragón y Vazruden bajan para luchar, y cuando derrotas al boss, este vuelve a su montura de gratis (?).

Si matas su montura mueren ambos, total la cosa es que no hay loot y es necesario obtener http://es.wowhead.com/item=24044 :3 

Cuando matas al boss el loot debe aparecer en este cofre, pero no hay cofre. http://es.wowhead.com/object=185168

**Comment by redneo** [comment]
esto.....

has probado a matar primero al dragon y luego al boss?

Lo hice asi y salio el cofre :S

**Comment by ghost** [comment]
Confirmo lo que dice redneo.

**Comment by DatJetto** [comment]
e_e ok. ahora probaré, esqueeee  eso de no ponerse los bosses bien es un lio D: y se bugean, gracias por la notificación e_e''
