### ISSUE TITLE
Misión El juramento terráneo

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1186]
Bueno, estan todos los npcs que matar, incluso funciona el item que invoca enanos para ayudarte, pero al matar a los npcs no suma/cuenta para la mision.

Enlaces:
Misión: http://es.wowhead.com/quest=13005
Npc1: http://es.wowhead.com/npc=29984
Npc2: http://es.wowhead.com/npc=29978

**Comment by redneo** [comment]
Arreglada, creo

**Comment by ghost** [comment]
Gracias redneo.
