### ISSUE TITLE
Portal Vash'Jir (Horda)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1187]
Si pudieras "copiar y pegar" el portal de vash'jir que esta en ventor, porque si me voy hasta ahi lo puedo usar perfectamente, pero el de la horda como sabes, no funciona ni de adorno xd. 

Si sé lo del barco, pero el barco de orgrimmar tarda 3 veces más que el barco de ventor, es mucho tiempo para ir hasta alla xd.

**Comment by redneo** [comment]
Un issue por post!

Casi imposible, pero se puede leer? xD si se puede leer ahi lo dejo...

Voy a por el portal...

**Comment by redneo** [comment]
Lo del portal cuando caiga el server

**Comment by ghost** [comment]
Gracias.

**Comment by ghost** [comment]
@redneo ahora no se le puede dar clic al portal xd.

Movido el "issue" del libro a otro reporte...

**Comment by redneo** [comment]
Arreglados los dos portales.

**Comment by ghost** [comment]
Muchas gracias.
