### ISSUE TITLE
Facción Los Hijos de Hodir

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1189]
Bueno, al terminar la misión Una chispa de esperanza http://es.wowhead.com/quest=12956 (que si funciona lo pongo nada más por si acaso xd), ganas reputación con los Hijos de Hodir hasta "neutral" (en realidad más por los rates x3), bueno a partir de este momento, tienes que poder ver a todos los npcs de la facción incluyendo el tan anhelado Lillehoff que vende el mamut xd, pero claro... no estan.

Enlace:
Todos los npcs faltantes: http://es.wowhead.com/faction=1119/los-hijos-de-hodir#members

Luego de que arregles esto redneo, envia un mensaje a todos para que te hagan un monumento xd.

**Comment by redneo** [comment]
Vale... pasa lo de siempre, que está pero no en la fase correcta, cuando estes online le pongo en la fase correcta.

**Comment by ghost** [comment]
Oks... u.u a ver si coincidimos esta semana xd.

**Comment by ghost** [comment]
Arreglado, ahora presumir de los mamuts xd, muchisimas gracias redneo, haz arreglado más de la mitad de las misiones de la cadena de misiones y los npcs.
