### ISSUE TITLE
Misiones>Profesiones>Joyería Figurilla de serpiente rota

### ISSUE THREAD

**Issue by andrixx** [RoDNet/Bugtracker-Infinium-4.0.6a#119]
Tengo todos los materiales que pide la misión  y me pide un item adicional que dice Completion Text , por eso no puedo completar la misión, si pudieran arreglarla les agradeceria.

http://es.wowhead.com/quest=28775/figurilla-de-serpiente-rota

http://es.wowhead.com/item=52186 x8
http://es.wowhead.com/item=52190 x2
Y http://es.wowhead.com/item=65896 que se tiene al iniciar la misión

**Comment by searum** [comment]
arreglada en la siguiente rev.
