### ISSUE TITLE
[Portales] Portal a Tierras Devastadas

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1190]
No hay ningun portal, almenos en su sitio, para ir a Tierras Devastadas. En la Alianza no lo sé pero en el Horda en ninguna capital he logrado encontrarlo

**Comment by ghost** [comment]
Pero si el habla de la horda... xd, justo hoy le pregunte sobre eso a redneo, y lo puso, esta en la parte de los trolls en orgrimmar, también esta en la cueva.

**Comment by WarSxNes** [comment]
la horda??  oooo Bwahahaha!!!  entendi mal :p

_(a esos feos que los dejen sin portal)_ xD

**Comment by Wiinter** [comment]
Pues solucionado. En Orgri ya está puesto en las demás no lo sé, pero cierro.

Gracias Redneo y a los qe comentaron :)
