### ISSUE TITLE
casilla de la hermanda N° 7,8

### ISSUE THREAD

**Issue by otakus1986** [RoDNet/Bugtracker-Infinium-4.0.6a#1191]
aver si me podian comodar ese bug ya somos lvl 11 y subiendo . de la casilla n° 7 , 8

**Comment by otakus1986** [comment]
a la hermanda es RyodaN

**Comment by ghost** [comment]
Primero aprender a leer y luego pedir las casillas xd.

http://www.reignofdarkness.net/wow/foros/t1689/

**Comment by otakus1986** [comment]
Shh.......
