### ISSUE TITLE
Puerta de salida de Halfus (Bastión del Crepúsculo) [Banda]

### ISSUE THREAD

**Issue by Alfonn** [RoDNet/Bugtracker-Infinium-4.0.6a#1192]
Seré breve. Al matar a Halfus y pasar a Valiona al wipear tan sólo 1 vez esta puerta se cierra y no permite poder volver a repetir a Valiona Y thelarion..

![image](https://f.cloud.github.com/assets/3854953/569863/49a8eccc-c717-11e2-8e11-20aca02e2b22.png)

**Comment by crowel** [comment]
Hola a nosotros también nos pasa esto cuando no lo tiramos a la 1ª es algo rollo.
Un saludo

**Comment by DatJetto** [comment]
Hasta el siglo 20.

**Comment by ghost** [comment]
Solo para la aclaración, ¿era 10 normal o 10 heroico?, la he hecho muchas veces en 10 normal, wipeando cientos de veces y jamás se cerro la puerta... pero en 10 heroico había problemas no sé donde.. fue hace mucho xd.

Como tal vez nunca se solucione esto... les recomiendo tener 1 brujo en su banda, que se ponga la piedra, luego que el brujo use el teleport de hermandad y le traiga a uno consigo para que den summon a los demas xd. (claro, esto si funciona el teleport dentro de la raid), o sino que el brujo use navaja con el healer, o le ponga la piedra al healer y reviva al brujo para summon.

**Comment by Alfonn** [comment]
Era normal 10J. Y no sé cómo no te ocurrió a ti , porque a la mayoría de gente como ves, sí.

**Comment by ghost** [comment]
Creeme que he wipeado cientos de veces esa raid y jamás se cerro la puerta (en 10 normal), no sé que es "J" xd, esta 10 jugadores Normal y 10 jugadores Heroico, por si la "J" es de jugadores.

**Comment by redneo** [comment]
Por si las moscas la he puesto que se puede clickear y pasar.
