### ISSUE TITLE
Item Las Escuelas de la Magia Arcana: Transmutación

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1193]
Bueno, muchas gracias por arreglar el logro, pero ¿puedes mover este libro por favor? es IMPOSIBLE darle clic "normalmente" al libro para leerlo. http://es.wowhead.com/object=192867 pruebalo tu mismo xd.

Si lo puedes mover solo un poco más afuera de la pared para que ya se le pueda dar clic y disfrutar del logro y la pet, pero si no, esta bien u.u, muchas gracias.

**Comment by DatJetto** [comment]
Yo mismo he sacado el logro hoy, TODOS se pueden conseguir, la cosa es que hay varios que están debajo de las estanterías y solo puedes clicar una leve esquina de apenas 1 píxel xDDDD

**Comment by ghost** [comment]
Si lo sé, hay 3 que estan en el piso, pero este en especial, no se lo puede clicear "normalmente", tienes que moverte y al mismo tiempo hacer clic tropocientasmilveces para con suerte "agarrar" el libro para leerlo.
Pero bueno, si se quedara así puedes cerrarlo redneo, o me avisas y lo cierro yo xd.
