### ISSUE TITLE
[Brujo] Daño del Brujo aflicción

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1197]
Llevo mucho tiempo quejandome de que el brujo no pega mucho, pero nunca me había puesto a hacer cuentas hasta hoy que he tenido el tiempo suficiente.

Despues de mi estudio me he dado cuenta que hay varias habilidades bastante importantes qe pegan de menos y otras en cambio qe pegan como deben. Tengo que decir que todos los datos que expondré son aproximados y la rotación que he provado yo ha sido muy parecida a la suya.

Primero lo que he hecho ha sido buscar una mas o menos fiable de informacion donde pueda contrastar mis datos y esta ha sido http://www.simulationcraft.org. Yo he escogido la opcion Warlock_Affliction_T11_359, ya que más o menos mi bruja tiene un equipo bastante parecido al qe dicen ellos, incluso diría qe el mío es algo mejor.

Pues empezemos con las fotos para ver los resultados obtenidos. Primero de todo la simulacion del simulationcraft que hicieron para el parche 4.0.6 para el tier 11 normal. 
![simulacion rotacion descarga sombras](https://f.cloud.github.com/assets/3757460/573767/65336444-c7b8-11e2-830b-00e7af3026b0.jpg)
He marcado con rojo el daño y el daño critico medio qe deberían hacer cada habilidad.

Ahora aqui mi simulacion, utilizando el Recount como ayuda.
![afflicion inestable rotacion descarga sombras](https://f.cloud.github.com/assets/3757460/573777/93d04cd6-c7b8-11e2-9741-d8043b787d10.jpg)
![corrupcion rotacion descarga de las sombras](https://f.cloud.github.com/assets/3757460/573778/9b241274-c7b8-11e2-9c98-c003f6dbc11d.jpg)
![drenar alma rotacion descarga de las sombras](https://f.cloud.github.com/assets/3757460/573779/9b5b1cc4-c7b8-11e2-92f5-efdbc1dc335a.jpg)
![descarga de las sombras rotacion descarga de las sombras](https://f.cloud.github.com/assets/3757460/573780/9b78d0de-c7b8-11e2-91e4-cb55206428c2.jpg)

Como podemos ver en la habilidad Corrupcion hay mas de 2k de diferencia por tik y lo mismo pasa con Drenar Alma que tiene mucha diferencia uno respecto a otro. Tengo qe decir qe esta simulacion lo he hecho en el palo y no se del cierto si augmenta el daño cuando baja la salud del 25%, porque diria qe no se le puede bajar la salud, entonces esta ultima habilidad no se si esta del todo bien.

Me gustaría hacer otra simulacion con otra rotacion haver qe resultados me dan, pero en un principio podemos llegar a la conclusion qe el principal problema que tiene el Brujo Afliccion, y me aventuraria a decir el Brujo, es que Corrupción pega 2k menos por tick.

Espero pronto poder añadir más información a este post. Cualquier duda o comentario al respecto lo podeis hacer aqui o ingame al pj Wiinter.

**Comment by redneo** [comment]
Bien, te hablo desde el dr damage que aunque no sea 100% cierto, se le acerca....
tengo poder con hechizos 2768, sin maestria ni nada, a nivel 85 me hace de daño a un guardia de ventormenta 700 cuando dice dr damage que tendria que hacer 6 ticks de 634.5

Me pongo especialidad afliccion, que me da un 25% a los spells de sombra, el daño pasa a 875 que es exactamente lo que sale de multiplicar 700 \* 1.25.

Me pongo 3 puntos en Corrupcion mejorada. El daño pasa a 980 que es lo mismo que si multiplicas el 875 \* 1.12.

A todo esto, el dr damage me dice en estas condiciones que tendria que hacer 6 ticks de 798.5

**Comment by Wiinter** [comment]
Acabo de comprobar lo del Dr. Damage en los postes de level 85 de Orgrimmar, con 183 de poder de hechizos y Corrupcion Mejorado y la Rama Aflicion debería hacer un debería hacer una media por tick de 584 y tengo una media de 506. Estos 80 puntos son bastante significantes si contamos qe solo tengo 183 puntos de poder con hechizos. Como puede ser qe nos de diferente?

Una pregunta cada punto de intelecto da un punto de poder con hechizos? 1 de intelecto = 1 de poder con hechizos?

Gracias por la respuesta Redneo, seguiré investigando a ver si encuentro algo más

**Comment by Wiinter** [comment]
He seguido haciendo pruebas desnudo y me da que pego menos de lo qe me dice el Dr Damage.

**Comment by Wiinter** [comment]
Haciendo más pruebas con mi amigo Dr. Damage y mi amigo. Aqui dejo mis resultados : 
Aunque todas las spells aparezcan juntas en el recount, cada una ha sido casteada individualmente para qe no hayan beneficios entre unas y otras  y asi hacerlo más fácil de analizar.
![affliccin inestable](https://f.cloud.github.com/assets/3757460/580400/f5a3e368-c886-11e2-92c5-a1618a1816ba.jpg)
![corrupcion](https://f.cloud.github.com/assets/3757460/580401/f5f37ce8-c886-11e2-8105-922b6c9619cb.jpg)
![descarga de las sombras](https://f.cloud.github.com/assets/3757460/580402/f5f6b26e-c886-11e2-9bca-616ad73bf7bd.jpg)
![drenar vida](https://f.cloud.github.com/assets/3757460/580403/f5f5129c-c886-11e2-9f52-64fb2924aa79.jpg)
![poseer](https://f.cloud.github.com/assets/3757460/580404/f5fd653c-c886-11e2-9d8c-ccf8baeae160.jpg)
![terror de agona](https://f.cloud.github.com/assets/3757460/580405/f600b23c-c886-11e2-902f-0e1a891f3f78.jpg)
He llegado a la misma que en los anteriores comentarios, pega menos de lo que debería. Por favor si hago algo mal o cualquier otra cosa avisadme para poder ayudarte en todo lo que pueda.

**Comment by Drogoth2** [comment]
Buenas:

Yo he hecho un breve análisis con mi brujo Evilknight (full sañoso como se ve en las imágenes, aunque esta transfigurado se puede ver en las estadísticas de las fotos) y el DrDamage.

He obtenido estos resultados en los que pongo el daño que he hecho sin nada de equipo comparados con el drdamage y lo que he hecho con el equipo puesto y la comparación con el drdamage también.

Hechizos                               Sin equipo   DrDamage          Con equipo         Dr Damage

Poseer                                   987               1408             4783              7691
Afli. Inest.                                    1840                2326               12390        17829
Corrupción                                  1752       2134               15900             20048
Terror Agonia                            2988       3826               18930             23689
Drenar Vida                           772              496                   6792             5778
Drenar Alma                          1180        1158               25040            27400
Desc. Sombras                           958              1099                8232            10473

Además os adjunto unas fotos con el hechizo de poseer para que se vea lo que hace en cualquiera d las dos situaciones

![image](https://f.cloud.github.com/assets/3939699/580573/49d60d68-c88b-11e2-8f94-e6b374ab997d.png)

![image](https://f.cloud.github.com/assets/3939699/580544/b5c69cbe-c88a-11e2-95ff-d30c53a50fa4.png)

![image](https://f.cloud.github.com/assets/3939699/580570/33027112-c88b-11e2-9d3a-e8641c674385.png)

Conclusión el daño parece estar algo bajo en la rama de aflicción (sabiendo claro esta que el DrDamage no es exacto).

Además quería añadir que corrupción y terror de agonía están bajos también en la rama de destrucción.

Espero que esta información sea de ayuda

P.D.: siento lo de la tabla no se que le ha pasado al copiar y pegar XDD.

Un saludo y gracias por adelantado

**Comment by sussy** [comment]
bueno corroboro todo lo k dicen y lo he dicho x el canal horda no entiendo x k le bajaron el daño a afliccion y le subieron a destruccion. cuando antes no abian ni 1 brujo y los post d k le subieran el daño de destruccion fue desde hace meses y ahora k le suben a destruccion le bajaron a poseer a corrupcion y drenar alma  de mi parte seguro aquellos pj k tenian brujos k eran destruccion volvieron a jugar y es bueno pero aquellos fieles como yo Cypress k siempre jugo con el brujo con drestrucc bajo y afliccion y siempre jugue mi brujo nos afecta ver k le bajaran al damage la rama afliccion. y mi equipo es full sañoso y aun asi pego lo mismo k pegaba destruccion con inmolar y incinerar esos 2 poders = a poseer y otra cosa mas no c diga nada de afliccion inestable no silencia cuantos helers alis andan x ahi limpiando ala gnt como si nada pero bueno solo digo por mi part ami me an arruinado ami brujo

**Comment by redneo** [comment]
Sussy, entre la alergia y la falta de comas o puntos o algo casi me quedo sin aliento.

Se AJUSTO ciertas spells de brujo, ya no se si demonologia, destrucción o rita la cantaora, pero se ajustaron con ayuda del dr. damage, mi pj medio equipado y un pj que estaba al lado full equipado.

El otro día con Wiinter estubimos mirando ciertos spells que teoricamente estaban bajos, pero llegamos a la conclusión que estaban bien.

Evil, podias explicar un poco mejor la tabla que no lo pillo????

**Comment by Wiinter** [comment]
Lo de evil es una tabla el primero valor es Sin equipo  y sin DrD, el segundo valor Sin equipo y con DrD, el tercer valor Con equipo y sin DrD y el ultimo valor Con equipo y con DrD.

Una cosa qe me gustaría añadir Red es que la Armadura Vil y la Armadura Demoniaca a veces desaparecen por arte de magia y las tienes qe volver a poner y si tienes 3 millones de buffos pues ni te enteras. Supestamente estas Armaduras son infinitas y no tienen tiempo

Y otra cosa, cuando hago llamas infernales me deberia sanar por cada personaje qe le haga daño y este solo me sana como si le estuviera dando solo a uno

**Comment by redneo** [comment]
Vamos con mis pruebas...
Creo un pj, lo subo a 85, me busco un palo de nivel 3 y le empiezo a dar. Poder de hechizos 181.
Poseer, daño que hago: 807, daño que me dice el dr damage: 807, situacion OK
Aflicción inestable: 5 ticks de 259. Daños del dr damage 5 ticks de 259.5, situacion OK
Corrupción: 6 ticks de 188, DrD 5x 178.5 Situación OVER!
Terror de agonía: Daño total 1752, Media DrD 1722. Dificil de decir si esta OVER ya que hace más daño cuanto más dura.
Drenar Vida: 3x142 DrD 3x141.5. Situación OK
Drenar Alma 3x223 DrD 3x222.5 Situación OK.
Descarga de las sombras:Media de 10 tiros: 729 DrD 733. Situación OK.

Todo esto después de haber cambiado algun spell esta mañana... Procedo a ponerme ropa.

Poder de hechizos: 10556
Poseer: 6430 DrD 6370
Aflicción Inestable: 2334 por tick. DrD 2334.5
Corrupción 2574 DrD 2004.5
Terror de agonia no lo puedo probar sin que me salten criticos!
Drenar vida: Tick 2010 DrD 1925.5.
Drenar Alma. Ticks 8616 DrD 4144.5 WTF!!!!!
Descargas de las sombras: 8548 de media DrD. 8556

Edito: Drenar alma lo he bajado a que me haga 4605 por tick, está over pero no tanto.
