### ISSUE TITLE
Los últimos ritos - Príncipe Valanar <Los San'layn>

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1199]
![tundra 2 - copy](https://f.cloud.github.com/assets/2059256/576230/a715d8ac-c7f8-11e2-9db2-57a510e4c620.png)

Volvemos a Rasganorte https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1100 << post de quest anterior relacionado a la cadena de quest. (# 14)

http://es.wowhead.com/npc=26170 <<<<< EMPIEZA - TERMINA - **Thassarian**
http://es.wowhead.com/quest=12019 <<< Quest bug

Bien no hay mucha informacion sobre la quest. Pero entiendo que tienes que presenciar un combate entre _"Príncipe Valanar [Los San'layn]_ **vs** _Thassarian"_ Y luego de matarlo (valanar) se completa la quest (creo).

---

Ahi te dejo el NPC que hay que matar. Y un video que encontre aunque el titulo dice arthas pero esta erroneo el que hay que matar es a valanar.
http://es.wowhead.com/npc=28189 <<< Objetivo de la quest - **Príncipe Valanar [Los San'layn]**
http://www.youtube.com/watch?v=6eLvxaS-of0& <<< VIDEO

**Comment by redneo** [comment]
es una jodienda, pq está enteramente programada, pero no se donde falla la misión. Matando al principe ya cuenta, pero molaria que hiciera todo el evento, no solo que se quede mirando como matan al consejero Talbot.

**Comment by WarSxNes** [comment]
![wowscrnshot_052913_094917](https://f.cloud.github.com/assets/2059256/583502/04fa8566-c8f4-11e2-86f4-31d52c3ce1e7.jpg)
![wowscrnshot_052913_095020](https://f.cloud.github.com/assets/2059256/583504/082f67d8-c8f4-11e2-8755-e85ad05d1f37.jpg)
![wowscrnshot_052913_095033](https://f.cloud.github.com/assets/2059256/583505/0b064a80-c8f4-11e2-83b4-2ce0b1aea8b7.jpg)
![wowscrnshot_052913_095159](https://f.cloud.github.com/assets/2059256/583506/0e0722e0-c8f4-11e2-8e41-817f5a933951.jpg)

Bien, ya complete la quest. Pero antes de comenzar el evento ya estaba en el centro un valanar. Luego de hablar con thassarian el evento comienza. Aparece los siguientes.

Arthas (desaparece)
Talbot (que se convierte en valanar)
y otros 2 NPC que se quedan aturdidos.
Thassarian (camina asta donde se ve en las fotos)

Bien, ahora el problema es que hay 2 Valanar elites, y creeme que es muy dificil matar 1 y ya con 2 ufff si no es por el especial de fenix de mi mascota yo tambien muero. Y thassarian se queda parado sin hacer nada.

**sugerencia**
seria bueno ver a cual de los dos mate, pues no estoy seguro a cual fue pues los 2 se me vienieron encima, y quitar a uno de los 2 y dejar a solo 1.

**Comment by redneo** [comment]
Spawnee uno temporalmente a ver si me hacia el encuentro, que por cierto, no me lo hacia, no se como leñes lo hiciste tu.

Una vez matado, tendria que desaparecer y quedarse nada mas el que se mueve y dice cosas...

Del evento, a mi solo me hacia que Thassarian caminara... creo que me tocará hacer toda la cadena de misiones a ver como va el final... si logro reparar el pc :S

**Comment by WarSxNes** [comment]
OOooOoo.. hehehe pues bueno lo que hice fue primero borrar la cache del wow. _(casi siempre lo acostumbro para cuando arreglan una quest)_ OH.. pero antes de hacerlo abandone la quest.

Luego fui con Thassarian el que encontras en "EL CONFIN DE LA MUERTE" son el mismo NPC con el mismo numero 26170 luego desaparece y aparece uno encima de Naxxanar.

Con el thassarian que esta arriba de naxxanar. solo hice CLICK sobre el y aparece una ventana no? y despues hice CLICK en el mensaje _(que no recuerdo como decia)_ pero supongamos que decia "estoy listo".

Despues de hacer CLICK en "estoy listo" (suponiendo) comenzo el evento. y paso todo lo que muestro en las fotos.

Aparecio arthars luego sale talbot salen otros dos NPC mas y talbot se arrodilla y se convierte en valanar, arthas le dice algo y luego te señala y se va, los otros 2 npc que aparecen se aturden y valanar te comienza a atacar.

Supondria que thassarian deberia de hacer algo pero no lo hiso, y como digo antes del evento ya habia un valanar en el centro que se me vino encima junto con el otro valanar que se convirtio. _(y mi perrito fue violado por los 2 elites )_

**Comment by WarSxNes** [comment]
Ok dejemos esta ya como buena.... Aun que aun asi sean 2 elites **lvl 72** los que salgan.... Dudo que un PJ low pueda matarlos.

> Y eso que es una quest lvl 72... para Pjs entre lvl 68-71 :P
