### ISSUE TITLE
[Hunter > Spec: Marksmanship > Spell > Rapid Recuperation]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#12]
-Recuperación Rápida ( Ganas 12p de foco cada 3s. cuando activas fuego rápido y 50p de foco al obtener Matanza rápida )
http://es.wowhead.com/spell=53232
Bug: Cuando obtienes;
Matanza rápida http://es.wowhead.com/spell=35099
o 
Fuego rápido http://es.wowhead.com/spell=3045

No recuperas 50p de foco instantáneamente ni 12p de foco cada 3 sec Respectivamente

**Comment by adrianrp1988** [comment]
Reparado en la próxima Rev
