### ISSUE TITLE
No es seria esta transmateria... - Piezas de repuesto de Palanqueta

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1202]
Sigo en rasganorte otra cadena de quest (#1) cadena opcional.

![tundra 2 - copy 2](https://f.cloud.github.com/assets/2059256/576973/8bdc693c-c81d-11e2-915e-8d77c8bc0334.png)

http://es.wowhead.com/npc=25702 EMPIEZA -  TERMINA
http://es.wowhead.com/quest=11710 <<<  **No es seria esta transmateria...**

![wowscrnshot_052813_215149](https://f.cloud.github.com/assets/2059256/576961/e3a867b6-c81c-11e2-953f-227b13d69ac7.jpg)

Las piezas que muestro en la imagen estan bug. Tienes que cogerlas/tomarlas para completar la quest.

http://es.wowhead.com/item=34972 <<< Piezas de repuesto de Palanqueta --- **BUG**

**Comment by redneo** [comment]
Arreglado todos los gob, tiene que caer el server y a lo mejor limpiar temporales.

**Comment by WarSxNes** [comment]
Funcionan al 100%
