### ISSUE TITLE
Misión ¡Lo que haga falta!

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1205]
Y aquí el gran final.. la última misión de la cadena de misiones de los Hijos de Hodir xd.

Tienes que matar al boss Loken en la mazmorra "Cámaras de Relámpagos" y agarrar su lengua, bueno lo mate.. pero no da el "loot".

Misión: http://es.wowhead.com/quest=13108
Npc: http://es.wowhead.com/npc=28923
Item que debe dar: http://es.wowhead.com/item=43151

**Comment by redneo** [comment]
Ya la tendria que soltar al 100% si tienes la mision.

**Comment by ghost** [comment]
Ya esta, muchas gracias redneo.
