### ISSUE TITLE
[Mision] Textos Crepusculares codificados

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1208]
Debería dejar completarla infinidad de veces y solo me ha dejado completar una vez.
Aqui esta el link de la mision: http://es.wowhead.com/quest=8319

**Comment by redneo** [comment]
Reparada, creo

**Comment by Wiinter** [comment]
Gracias, bueno ya tengo la repu a exaltado, ya no me hace falta. Pero para los que la intenten subir. Cierro.
