### ISSUE TITLE
1

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1209]
necesito un par de anteojos xD

**Comment by DatJetto** [comment]
- Favor de guardián AUMENTA LA DURACIÓN, no quita CD, no te confundas, es decir, si dura 4 segundos mano de libertad, con eso dura 8.

¿Reponerte el oro? yo me he gastado más de 2k haciendo testeos en mis ramas de talentos, se supone que testeas para tener un server mejor, si te gastas tu oro es cosa tuya, aparte 20 oros, no son nada...
