### ISSUE TITLE
Misión El desafío del Valeroso

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1210]
Tienes que hablar con el escudero Danny, para que aparesca un Campeón de Argenta y lo derrotes... pero le hablas y no aparece el campeón.

Enlaces:
Misión: http://es.wowhead.com/quest=13731
Campeón Argenta: http://es.wowhead.com/npc=33707
Escudero Danny: http://es.wowhead.com/npc=33518

**Comment by WarSxNes** [comment]
En realidad creo que esta mision, es neutral en los objetivos. Y ademas te falto poner las demas ciudades. Esa es solo para los elfos.

Ahi tan los link que te faltan...

http://es.wowhead.com/quest=13727<<< **Trols Lanza Negra**
http://es.wowhead.com/quest=13728<<< **Cima del Trueno**
http://es.wowhead.com/quest=13729<<< **Entrañas**
http://es.wowhead.com/quest=13731<<< **Lunargenta** <<< _(esta es la que tu dices)_
http://es.wowhead.com/quest=13726<<< **Orgrimmar**

Supongo,, que al estar bug una todas las demas lo han de estar. =) Por que es el mismo objetivo. _ALIANZA/H-GORDA_ xD

![J](http://wow.zamimg.com/uploads/screenshots/thumb/126518.jpg)[**Escudero Danny**](http://es.wowhead.com/npc=33518)

![k](http://wow.zamimg.com/uploads/screenshots/thumb/127560.jpg)[**Campeon Argenta**](http://es.wowhead.com/npc=33707)

![argent tournament - wowwiki - your guide to the world of warcraft 2013-06-01 09-57-31](https://f.cloud.github.com/assets/2059256/595132/103606ea-cadd-11e2-86cc-85813f661137.png)

**Comment by redneo** [comment]
Creo que ya va, al menos a mi... cuando caiga el server saldrá a caballo y todo

**Comment by ghost** [comment]
Gracias redneo.
