### ISSUE TITLE
El desafío del Valeroso -  TORNEO ARGENTA

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1214]
Pues esta esta bug pero,,, anticipo a decirles que son 5 quest del lado de la alianza que tienen el mismo nombre. Cada una corresponde a una ciudad capital diferente.

http://es.wowhead.com/quest=13725 << Darnassus
http://es.wowhead.com/quest=13723 << Gnomeregan
http://es.wowhead.com/quest=13724 << El Exodar
http://es.wowhead.com/quest=13699 << Ventormenta <<< **(aqui estoy en esta quest bug)**
http://es.wowhead.com/quest=13713 << Forjaz

Anticipo a decir que todas deben de estar bug. Les explico.

![wowscrnshot_053113_012338](https://f.cloud.github.com/assets/2059256/589806/78029020-c9cc-11e2-9146-f9a67fe291bc.jpg)

**Escudero Danny**
![J](http://wow.zamimg.com/uploads/screenshots/thumb/126518.jpg)
http://es.wowhead.com/npc=33518

Este NPC es el que comienza el evento, debes de hacer CLICK sobre el y luego CLICK en el mensaje que aparece en la imagen de arriba ^ "Estoy listo para la lucha" Y deberia de invocar a un Campeon Argenta.

![k](http://wow.zamimg.com/uploads/screenshots/thumb/127560.jpg)
http://es.wowhead.com/npc=33707

---

Y no pasa nada. =( supongo que debes de matarlo para completar la quest. OjO son 5 diferentes con el mismo objetivo.

**Comment by redneo** [comment]
Pregunta tonta...

Como esta habia antes otra misión que tenias que hablar con otro escudero, donde antes salia un npc montadito, pero no contaba al matarle, verdad? 

Estamos hablando de una misión nueva, un poco más avanzada, corregidme si me equivoco.

**Comment by WarSxNes** [comment]
Yes Sir... esa era otra mision eran las misiones de "ASPIRANTE a torneo", despues de esas siguen las de "aspirante a VALEROSO" (que fueron las pasadas que arreglaste https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1165), esta es para "aspirante a CAMPEON".

Y si la recuerdo muy bien, hablabas con [Escudero David](http://es.wowhead.com/npc=33447) que te invocaba a un [Valeroso Argenta](http://es.wowhead.com/npc=33448) montado en un corsel y al matarlo te completaba la quest **[El desafío del aspirante](http://es.wowhead.com/quest=13679)**, esa fue una de las primeras xD

---

Ahi te dejo una imagen

![argent tournament - wowwiki - your guide to the world of warcraft 2013-05-31 10-32-45](https://f.cloud.github.com/assets/2059256/592357/4082b038-ca19-11e2-98ac-10cf2e96ec41.png)

---

Y la verda yo si lo mate.. :P y me completo la quest =) el npc aparece justo enfrente del ring. (out of ring) fuera del ring... algo asi.. xD sale como neutral solo haces los pasos que puse en mi QUICK GUIDE para poder matarlo. Pues como decian los demas _(sin mencionar nombres)_ se curaba  pero es normal, tienes que darle con comper escudo para bajarle armor y asi lo matas xD

Bueno yo lo mate a la primera no se, si alguien lo reporto antes y tu lo arreglaste antes que yo empezara en el tornero.

**Comment by ghost** [comment]
Si te puedes fijar en la horda también redneo.. te deje el reporte #1210

**Comment by redneo** [comment]
Ya va...

**Comment by ghost** [comment]
Arreglado.. cierro mi reporte, gracias redneo.

**Comment by WarSxNes** [comment]
Bien arreglado =)
