### ISSUE TITLE
3

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1215]
ok... =)

**Comment by ghost** [comment]
Pues... yo hice esto.. y nunca más quiso volver a ver un reporte así de largo xd.

**Comment by DatJetto** [comment]
De hecho no WarSxNes , se trabaja con un issue por bug, no un issue por un conjunto de bugs, ya que si arregla una la puede cerrar y así.

**Comment by redneo** [comment]
SI, agradeceria un post por mision ya que asi no me hago un lio con las que he tocado o las que no.

De momento, creo haber organizado todas las misiones para que no las den a tutiplen
http://es.wowhead.com/quests=10.66

esas
