### ISSUE TITLE
Bug Escudo De Sangre DK

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1216]
Bueno, según las notas del parche 4.0.6 la habilidad Escudo de Sangre de la maestría del DK debería acumularse por cada uso del Golpe Letal y no reemplazarse como sucede en el server.

Notas del parche: http://eu.battle.net/wow/es/game/patch-notes/4-0-6

**Comment by DatJetto** [comment]
Si, tienes razón, pero el arreglo de esto sería ya sacar totalmente  de las casillas a un dk , que ahora mismo es INMORTAL si eres melee, entre el daño de las pegatinas, el sistema de runas bug que permite el uso de golpe letal demasiado continuado etc, un warr apenas tiene valor para bajar un Dk sangre... y un pala Retry que no pega menos...

Si eres rango TODAVÍA puedes matarlo porque con suerte y habilidad no te pega.

Así que recomiendo el retraso de este arreglo para cuando el Dk esté más blizzlike en 4.3.4 ya que ahora mismo lo que causaría es que la oleada masiva de Dk's del server siga creciendo y TODO  el mundo en bg fuera Dk ._.

**Comment by ghost** [comment]
Y no solo eso.. tenía entendido que hay un bug para que el escudo absorba más de lo que debe.
