### ISSUE TITLE
[Logro] Erudito

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1217]
Faltan varios libros que se encuentran en la mazmorra de Stratholme.
Aqui estan los links de los libros qe faltan:

Los siete reinos (http://es.wowhead.com/object=175737)
El triunfante Rey Exánime (http://es.wowhead.com/object=175762)
El nacimiento del Rey Exánime (http://es.wowhead.com/object=175748)
La plaga de Lordaeron (http://es.wowhead.com/object=175756)

Cabe decir qe todos se encuentran en la misma sale de Stratholme que es la situada cerca del Trono Carmesí en las coordenadas 25 : 70

**Comment by redneo** [comment]
![wowscrnshot_060213_173520](https://f.cloud.github.com/assets/1163425/596437/206564b2-cb9a-11e2-9d45-6ac3b407e17d.jpg)
![wowscrnshot_060213_173511](https://f.cloud.github.com/assets/1163425/596438/2082c520-cb9a-11e2-8d05-0b6cd5cf9fa8.jpg)
![wowscrnshot_060213_173457](https://f.cloud.github.com/assets/1163425/596439/20a022f0-cb9a-11e2-9f82-4cc1d38dabba.jpg)
![wowscrnshot_060213_173531](https://f.cloud.github.com/assets/1163425/596440/20afc3b8-cb9a-11e2-8e4a-2c6adf37b781.jpg)

Creo que epic Fail por tu parte...

**Comment by Wiinter** [comment]
Ostias, claro pq ponia Stratholme y no Scholomace -.-. Supuestamente estan en Stratholme no en esta. Gracias por la aclaracion y lo siento por la cagada
