### ISSUE TITLE
[Mision] La prision de Neferset

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1220]
Vas al Visir Tanotep y ni te deja coger la mision, tiene un extraño símbolo de interrogación azul y no hace nada.
Aqui te dejo el link de la quest: http://es.wowhead.com/quest=27707

**Comment by redneo** [comment]
Ummm teoricamente ya tendria que salir la ? bien.

Para completar la misión, hay que liberar al tipo... osea, que no este en combate. (cuando caiga el server)

**Comment by Wiinter** [comment]
Arreglada
