### ISSUE TITLE
[NPC] Alimañas 

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1223]
El Campañol de gruta no se encuentra, debería estar en la gruta de Fauces de Licanthoth en la posición 32:37 pero no está.
Aqui te dejo su link: http://es.wowhead.com/npc=50419

La víbora de piedra no está en los sitios que en wowhead pone que debería encontrarse.
Aqui te dejo su link: http://es.wowhead.com/npc=50481

La polilla de oasis no está en los sitios que en wowhead pone que debería encontrarse.
Aqui te dejo su link: http://es.wowhead.com/npc=50496

La marmota con tripa amarilla no está en los sitios que en wowhead pone que debería encontrarse.
Aqui te dejo su link: http://es.wowhead.com/npc=48683

El pavo de las tierras altas no está en los sitios que en wowhead pone que debería encontrarse.
Aqui te dejo su link: http://es.wowhead.com/npc=48706

El bucciono masticapiedras no está en los sitios que en wowhead pone que debería encontrarse.
Aqui te dejo su link:http://es.wowhead.com/npc=48848

El pepino de mar no está en los sitios que en wowhead pone que debería encontrarse.
Aqui te dejo su link: http://es.wowhead.com/npc=48802

**Comment by WarSxNes** [comment]
Intentas hacer el Logro? http://es.wowhead.com/achievement=5548 <<< A todas las ardillas a las que les he importado

**Comment by Wiinter** [comment]
sep xD

**Comment by redneo** [comment]
http://es.wowhead.com/npc=50481 si que está, pero desconozco el sitio.

El resto apareceran cuando caiga el server.

**Comment by Wiinter** [comment]
Arreglado
