### ISSUE TITLE
Entre los campeones - Aspirante a Campeon de Campeones =)

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1224]
Bien.... despues de un frenetico ataque hacia mi ordenador y despues de reiniciar todos los puertos del firewall Modem y eliminar el ataque xD... alfin pude acceder a la web....

---

http://es.wowhead.com/quest=13790 <<< Entre los campeones![icon_alliance_2v2](https://f.cloud.github.com/assets/2059256/595680/5a5a727e-cb1e-11e2-97c3-9f9ae21beddc.png)
http://es.wowhead.com/quest=13793 <<< Entre los campeones![icon_alliance_2v2](https://f.cloud.github.com/assets/2059256/595680/5a5a727e-cb1e-11e2-97c3-9f9ae21beddc.png)![50px-deathknight_classiconv2](https://f.cloud.github.com/assets/2059256/595681/63d49744-cb1e-11e2-9771-7aa0b9fbd933.png)
http://es.wowhead.com/quest=13811 <<< Entre los campeones![horde_iconv2](https://f.cloud.github.com/assets/2059256/595685/84d22d94-cb1e-11e2-996f-cc84026156d9.png)
http://es.wowhead.com/quest=13814 <<< Entre los campeones![horde_iconv2](https://f.cloud.github.com/assets/2059256/595685/84d22d94-cb1e-11e2-996f-cc84026156d9.png)![50px-deathknight_classiconv2](https://f.cloud.github.com/assets/2059256/595681/63d49744-cb1e-11e2-9771-7aa0b9fbd933.png)

Igual que lo anterior, al estar bug estoy seguro al 100% que las demas deben estar bug. Incluyendo las de las H-Gordas. *(y eso que no me gusta trabarjar con el enemigo) :P

---

![wowscrnshot_060113_172150](https://f.cloud.github.com/assets/2059256/595721/ff331860-cb22-11e2-8e86-c6b8567c681d.jpg)
![wowscrnshot_060113_172255](https://f.cloud.github.com/assets/2059256/595724/04c9a082-cb23-11e2-8f5b-42c768b3845e.jpg)
![wowscrnshot_060113_172334](https://f.cloud.github.com/assets/2059256/595725/08d90384-cb23-11e2-8106-b6a56c09d4df.jpg)
![wowscrnshot_060113_172524](https://f.cloud.github.com/assets/2059256/595728/0d74b2b2-cb23-11e2-847c-ddfe843517f8.jpg)
![wowscrnshot_060113_172555](https://f.cloud.github.com/assets/2059256/595729/14584382-cb23-11e2-9657-ba22c413e6a1.jpg)
![wowscrnshot_060113_172653](https://f.cloud.github.com/assets/2059256/595730/1816428a-cb23-11e2-8b82-553f79361867.jpg)
![wowscrnshot_060113_172654](https://f.cloud.github.com/assets/2059256/595731/1b6694f8-cb23-11e2-8562-7f1da61a811a.jpg)

Reviso mis bolsas/mochilas y nada ninguna marca o item extraño. Que fue lo que creo el caballo?

---

**CURIOSIDAD**

[Master Enchanter Theopolus](http://www.wowhead.com/npc=18801) habian visto o escuchado de esta NPC antes? Pues se supone que es ELLA digo ella por que muchos creian que era hombre :P la que se encarga de enviarte por correo las [Marca del Campeón](http://es.wowhead.com/item=45500) cuando tienes llena las bolsas/mochilas.

![master enchanter theopolus](https://f.cloud.github.com/assets/2059256/595738/db07f66c-cb23-11e2-94ba-b60ddba5c5e4.png)
![master enchanter theopolus - npc - world of warcraft 2013-06-01 17-30-26](https://f.cloud.github.com/assets/2059256/595739/df47cbee-cb23-11e2-93ad-eacce3ab78a8.png)
![2n891fc](https://f.cloud.github.com/assets/2059256/595741/23e12eee-cb24-11e2-9974-6e0f385da58d.jpg)

En la ultima imagen se ve como EL/Ella te manda las marcas, y se ve como el personaje tiene varios buffs.

---

**EXTRAS**
[Marca del Campeón](http://es.wowhead.com/item=45500) < objetivo
[Victoria de ataque cuerpo a cuerpo montado](http://es.wowhead.com/spell=63596) < spell que crea las marcas
_**NPC's - bug**_
[Campeón de Ventormenta](http://es.wowhead.com/npc=33747)
[Campeón de Forjaz](http://es.wowhead.com/npc=33743)
[Campeón de Darnassus](http://es.wowhead.com/npc=33738)
[Campeón de Gnomeregan](http://es.wowhead.com/npc=33740)
[Campeón de El Exodar](http://es.wowhead.com/npc=33739)
[Campeón de Entrañas](http://es.wowhead.com/npc=33749)
[Campeón de Cima del Trueno](http://es.wowhead.com/npc=33748)
[Campeón de Lunargenta](http://es.wowhead.com/npc=33746)

Como no soy H-gorda _(tengo un cuerpo atletico :P)_ no me se los nombre de todas las ciudades de lado horda. Si alguien los encuentra pongan los links que me faltan

![123](https://f.cloud.github.com/assets/2059256/595763/d9f8faca-cb26-11e2-989b-210d103999db.png)

**Comment by Wiinter** [comment]
Te comento lo que yo se sobre esto.

-Lo de las marcas es un follón, lo que tienes qe haces en vez de matarlo desde la montura tienes qe bajarte y matarlo tu, porque sino la Marca y el buffo se la da al caballo y no a ti.
-Cuando lo mates con tus hechizos procura no matarlo de golpe, intentalo dejar a poca vida primero para qe te salte el buffo, sino no te saltará.

Sino te sale o tienes cualquier duda, enviame un mensaje o susurrame al pj Wiinter y te ayudo

**Comment by ghost** [comment]
U.u yo perdi todas mis misiones hechas D: ya no puedo reportar bugs de ahí /llorar.

**Comment by redneo** [comment]
Doy la razón a wiinter, todo lo da al caballo, ya que cuenta como si le hubiera dado el.... puedo mirar de solucionarlo, pero ya me costo todo el proceso anterior...

**Comment by WarSxNes** [comment]
![wowscrnshot_060213_082723](https://f.cloud.github.com/assets/2059256/596453/8225c03c-cb9c-11e2-82ac-ff403fac1a53.jpg)
![wowscrnshot_060213_082947](https://f.cloud.github.com/assets/2059256/596454/872c5bb8-cb9c-11e2-9833-7cb389613277.jpg)
![wowscrnshot_060213_083248](https://f.cloud.github.com/assets/2059256/596455/8be0ce28-cb9c-11e2-9f21-254385c80daa.jpg)

Bueno chicos no entiendo algo xD no se si por alla **CREAR** y **RECIBIR** sea lo mismo ;P pero aqui en america son 2 palabras diferentes.

En las imagenes que deje en el primer comentario dice **"Corcel Quel'Dorei CREA Marca del Campeon"** no dice recibe :P

Bueno como sea no me dieron nada ni de una ni de otra forma. Ni derrotandolos con la montura. Ni como dice **Wiinter@:** manatando uno mismo.

**Comment by Wiinter** [comment]
Yo lo hice hace un par de días y tenia las marcas, por eso te lo he dicho

**Comment by redneo** [comment]
A ver.. idea... montas en caballo, con lanza... hablas con uno, te desmontas y le das, sin matarle, hasta llegar al 10% a ver que pasa.... (por dios no me hagas cambiar todos los script de los tipos esos!)

**Comment by ghost** [comment]
Lo que tenias que hacer redneo era que solo se les pueda hablar estando desmontado asi ya no pasaba esto xd.

Y confirmo lo que dicen redneo y Wiinter... si puedes conseguir esos items.

**Comment by WarSxNes** [comment]
Ok chicos, haber no se alteren...
1. **Wiinter@: y Lvmb@:** ustedes dicen que ya tienen los items no? como? lo que dice redneo? fotos o imagenes?

---
1. **Redneo@:** ok redneo eso fue lo que acabo de hacer no se si me explique bien en las imagenes que deje?
   En la primera imagen muestro que no se puede pelear con ellos a no se que vallas montado en un caballo. Y en la segunda imagen hice lo que acabas de decir.

_"montas en caballo, con lanza... hablas con uno, te desmontas y le das, sin matarle, hasta llegar al 10% a ver que pasa_"

---

Y no pasa nada.... voy hacer algo.... voy a borrar la cache y wtf y regreso a contarles

---

**Diantres funciono.... hahaha... ok ya funciono... resuelto xD**

**Pero OJO.... tube que borrar la cache y wtf**

**Comment by ghost** [comment]
Pues.. cierra el bug :P

**Comment by Wiinter** [comment]
Yo lo hice con Lvm por eso te lo decía xD Lo descubrimos juntos como se hacía xD

**Comment by WarSxNes** [comment]
tranqui,,, tranqui Ghost@: crei que lo debia cerrar redneo.....
- y es que crei que el llevaga un registro de sus quest reparadas, ya sabes cada cierto tiempo publica un post en el foro > taberna diciendo sus avances.
