### ISSUE TITLE
[Misión] El Foso de Escamas

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1225]
Tienes qe Liberar a Tahet. Al matar a todos los elites que tiene cerca, voy a hablar con él pero no pasa nada.

Aqui te dejo el link de la quest: http://es.wowhead.com/quest=27738

**Comment by redneo** [comment]
Arreglada cuando caiga el server

**Comment by Wiinter** [comment]
Arreglada
