### ISSUE TITLE
Paladin debilucho/weak

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1234]
Primero que nada les digo que las cantidades que se mostraran se basan al equipamiento y armamento que llevo puesto. Y que ademas RedNeo@: recuerdas que te pregunte si confiabas en el Dr. bien pues ahi dejo unas imagenes que muestran que el pala anda medio weak.

**OJO** las cantidades que menciono son las media osea deberian de estar entre:
F = (X entre Y) siendo F la media y (X-Y) las cantidasdes minimo y maximo que se basa la media

---

**GOLPE DE CRUZADO**

![wowscrnshot_060213_180245](https://f.cloud.github.com/assets/2059256/597402/7c0fbb78-cbf4-11e2-97f3-ef513948a74e.jpg)
![wowscrnshot_060213_180320](https://f.cloud.github.com/assets/2059256/597403/811ac0d6-cbf4-11e2-88ba-24215c049803.jpg)

---

**TORMENTA DIVINA**

![wowscrnshot_060213_182148](https://f.cloud.github.com/assets/2059256/597417/37b5c926-cbf5-11e2-8e0c-0f968cc64310.jpg)
![wowscrnshot_060213_182311](https://f.cloud.github.com/assets/2059256/597418/3d6e438e-cbf5-11e2-90ba-23f8058a347d.jpg)

---

**VEREDICTO DEL TEMPLARIO**

![wowscrnshot_060213_184011](https://f.cloud.github.com/assets/2059256/597422/73b83738-cbf5-11e2-93ad-5309252c32ba.jpg)
![wowscrnshot_060213_185213](https://f.cloud.github.com/assets/2059256/597423/7a154c60-cbf5-11e2-9394-c50123d8aa7a.jpg)
![wowscrnshot_060213_190827](https://f.cloud.github.com/assets/2059256/597424/7ea628a8-cbf5-11e2-809b-771da1b7c2ad.jpg)

---

**Sellos de Mando**
![wowscrnshot_060213_192422](https://f.cloud.github.com/assets/2059256/597426/b02cb590-cbf5-11e2-8a0d-41596ff01e5f.jpg)

http://old.wowhead.com/spell=85126 <<<< **old.wowhead**
http://www.wowwiki.com/Seal_of_Command_%28old%29 <<<< **old.wowwiki**

---

Bien, ahi les dejo esos para mientras y si pueden testear los demas seria bueno.

_**OJO es OLD.WOWHEAD Y OLD.WOWWIKI por que si van a los normales hablan sobre MoP**_

**Comment by redneo** [comment]
He modificado los siguientes spells:
85256 -- Veredicto del templario
53385 -- Tormenta divina
35395 -- Golpe de Cruzado

No hace falta que me hagas screens para decirme si van bien, con que me digas el daño que hace ahora de media y la media del DrD me vale...

Para Veredicto del templario lo he puesto a ojo, ya que me consume rapidamente las cargas y me resulta dificil probar con 3 cargas.

Sello de mando hace el 7% del daño del arma, en mi caso, un 7% de 187-281, que puede ser desde 13 a 19.

Edito: me he dado http://es.wowhead.com/item=65090 siendo su daño de 310 a 577 con lo cual sello de mando tendria que ser de 21.7 a 40.39 me ha hecho de media 48 ... con lo cual no se si coge de media el daño mele que es de 344-845 (24-59)

Edito de nuevo: mira http://old.wowhead.com/spell=20424#triggered-by ese spell va linkado a sello de comando, 85126, ahi dice que hace un 9% que no se de donde lo saca, ya que el tooltip del talento dice 7 :S

**Comment by DatJetto** [comment]
Redneo para que las cargas se hagan permanentes has de estar en combate, si no estás se desvanecen en unos segundos :)

**Comment by ghost** [comment]
@redneo , el spell 20424 que pusiste que dice "9%" si te fijas arriba... dice  "Database>Spells>NPC Abilities"
este es el del pala http://old.wowhead.com/spell=85126

**Comment by paellaencol** [comment]
El problema que te ocurre con las cargas de poder sagrado, es porque cuando se desvanece inquisicion te elimina por completo todas las cargas que tuvieras en ese momento (obviamente esto esta bug), y si lo intentas refrescar para que no pase te lo actualizara con valor de 10seg, independientemente que lo hayas reactivado con las cargas que sea, solo te contará como si hubiese sido una (bug también).

Este problema con las cargas también ocurre con el paladin healer, el cual al usar luz del alba con 3 cargas, solo le cuenta como si lo hubiese hecho con una http://es.wowhead.com/spell=85222/luz-del-alba
