### ISSUE TITLE
Un plan perfecto

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1242]
http://es.wowhead.com/quest=12823 <<< Un plan perfecto
![wowscrnshot_060313_220908](https://f.cloud.github.com/assets/2059256/603715/2e80d45a-ccd5-11e2-9e72-5099b0ce0ad3.jpg)
http://es.wowhead.com/npc=29432 <<< EMPIEZA Y TERMINA
http://es.wowhead.com/item=41431<<< el item que te dan para hacer explotar el altar.

El altar deberia de estar en lo mas alto de la cueva y no lo esta

---

**_nomas como recordatorio_**
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1252
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1243
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1251

**Comment by redneo** [comment]
Cuando caiga el server tendria que estar el altar.

**Comment by redneo** [comment]
Por cierto, no tendria que haber npcs por ahi?

**Comment by WarSxNes** [comment]
si los hay, los mate por eso no salen en la imagen, xD Un grandulon pero no tienen nada que ver con la quest o si? almenos lo mate y no me dio nada.

**Comment by redneo** [comment]
Nah, pa que molesten mas que otra cosa... Teoricamente tienen que guardar el sitio y no se si para otra mision son necesarios

**Comment by WarSxNes** [comment]
ok, confirmado ya funciona. Perdon por la expresion **(AHIIIIii.... Weyyy!!!!!)**

El PJ low que quiera hacer esta quest se va a llevar un buen susto. lol hahaha arrr.... ("\;..;/")

---

1 OK, cuando recien llegas, ya hay un Vigia Gram ahi parado (lo matas y listo). << _nada que ver con la quest_
2 Ahora pones los explosivos, Y se completa la primera parte dela quest.
3 Luego te salen 2 grandulones de la nada (cosa facil para mi, que lo hise con un pj lvl 85) y mata a uno y completas la quest.

Sugerencia:
Si enlugar de aparecer 2 apareciera 1 despues de poner los explosivos seria bueno. Pues la quest es para lvl 78 asi que no creo que un lvl 75-77 salga vivo de esta xD
