### ISSUE TITLE
Pjs inexistentes

### ISSUE THREAD

**Issue by Kroser** [RoDNet/Bugtracker-Infinium-4.0.6a#1247]
Desaparecieron los pjs de mi cuenta y de algunos compañeros de mi guild fue algun error del servidor?

**Comment by WarSxNes** [comment]
Me uno a tu causa ya somos 2

![untitled2](https://f.cloud.github.com/assets/2059256/613866/cdfb41fc-ce0e-11e2-853b-f830fc7af3cc.png)

En un momento me desconecte y luego PUFF nada
http://www.reignofdarkness.net/wow/foros/t1749/<<< ya habia creado este post

**Comment by Drogoth2** [comment]
Yo tengo el mismo problema con mis pjs

**Comment by unaigaizka69** [comment]
AM TMB SE ME HAN DESAPARECIDO LOS PJ

**Comment by WarSxNes** [comment]
cierren el post ya paso xD
