### ISSUE TITLE
Vuelta al daño bajo del brujo Destru tras la caída de hoy

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.0.6a#1249]
Hola buenas:

Bueno escribo otra vez este post, porque después de la caída que ha habido hoy en el servidor (en la cual parecía que la gente había perdido sus pjs), me he encontrado a la vuelta que el brujo destrucción (mi pj es Evilknight) a vuelto a estar como antes de que Redneo lo arreglara.

Esto lo se porque lo he comprobado en duelos, con el muñeco de entrenamiento y lo he corroborado con otros brujos del servidor.

Así que por favor si podéis volver a ponerlo como lo dejó Redneo os lo agradecería. 

Si hace falta pongo los datos como la otra vez para que se vea todo. 

Un saludo y gracias

**Comment by redneo** [comment]
http://www.reignofdarkness.net/wow/foros/t1737/?t=1737

**Comment by Drogoth2** [comment]
Vale si me parece bien que se estén arreglando las clases pero lo que digo, porque lo he visto puesto en el foro, es que esto ha pasado después de la caída en la que parece ser que se han perdido todos los arreglos que hiciste redneo.

Por eso lo digo, por saber si podrás volver a meter el daño tal y como estaba esta semana pasada, en la cual el brujo  estaba con el daño bien.

Se que ha sido una putada con mayúsculas lo que ha pasado, ya no con respecto a este post sino en general, todo el curro tirado por la borda.

Un saludo
