### ISSUE TITLE
¡Han sido los orcos! ¡Lo juro!

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1251]
http://es.wowhead.com/quest=11670 <<< quest bug
http://es.wowhead.com/npc=25477 <<< EMPIEZA - TERMINA

---

http://es.wowhead.com/item=34871 <<< tiene que darte esto

Y luego estos dos van dentro de la bolsa que te da en 34871
http://es.wowhead.com/item=34869
http://es.wowhead.com/item=34870

---

http://www.wowhead.com/npc=25430 <<< para luego usarlo en uno de estos cuando lo mates

---

**BUG** 
La NPC que te da la quest. Supuestamente ya te la dio pues marca que esta esperando que la entregues con el icono "?" pero en realidad nunca te la ha dado. Si llegas por primera vez ahi con ella te daras cuenta que sin nunca haber hablado antes con ella ya te esta esperando con esta quest.

Se supone que primero debe dartela haces lo que te pide y luego va a entregarla.

**_nomas como recordatorio_**
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1252
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1243
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1242

**Comment by redneo** [comment]
Ya la da como tendría que ser.

**Comment by WarSxNes** [comment]
Hehehe... ahora la quest esta bug xD...

Ya entre a la cueva... intente ponerme el traje de H-Gorda y no me lo dio osea no me dejo ponermelo, hace como que te lo pones pero nop nada...
Bueno de cualquier forma intente matar al boss que me pide matar. Lo mate y no me conto. Luego quise ponerle el estandarte de las H-Gordas y nada no conto.

**Comment by redneo** [comment]
Supongo que está solucionado, no se si te tienes que disfrazar de orcA para hacer las cosas, pero tu lo haces por si las moscas.

**Comment by WarSxNes** [comment]
Ok lo del disfras ya funciona 
![wowscrnshot_060713_113138 - copy](https://f.cloud.github.com/assets/2059256/625648/94cde7b0-cfa6-11e2-9db8-421225dbfbc1.jpg)

Ahora el problema creo que va a ser lo del estandarte
![wowscrnshot_060713_113428](https://f.cloud.github.com/assets/2059256/625651/a7c2f784-cfa6-11e2-9e40-c68c0a3c0cd5.jpg)

---

Voy a borrar la cache y wtf... y voy a intentar de nuevo ya regreso a contarles...

**Edito:**

>  ok, no te vallas a enojar.... pero en un post anterior habia mensionado sobre el respaw puff... adivina que me paso.
> Pues ahora mismo estan llegando ALIS a montones a esta zona. y no me dejan probar la quest. .. (supoganmos que el server tubiera una poblacion como la del oficial esto seria un caos con el respaw actual xD )
> 
> gosh ... mala suerte la mia me lo volvieron a ganar qq
> 
> ok los que andan por aqui me dijieron que les funciono... haber si alfin me dejan probarlo a mi... 

Al FIN logre completarla 1hora 12 minutos mas tarde alfin me dejaron matarlo lol...

wow 1 hora para completar una quest haha... >.< 

> _tube que borrar la cache y wtf OjO con eso_
