### ISSUE TITLE
¡Oh no! ¡Los renacuajos!

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1252]
http://es.wowhead.com/quest=11560

http://es.wowhead.com/npc=25201<<< objetivo,,, hay muy pocos en la zona y necesitas 20 de ellos, y habemos 3 personas con la misma quest en este mismo instante y nos andamos peleando por los renacuajos. Y solo hay 6 o 8 de ellos.

---

**_nomas como recordatorio_**
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1251
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1243
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1242

**Comment by redneo** [comment]
He puesto 7 más (en las jaulas que he encontrado) habiendo un total de 24 (siguen siendo pocos?)

**Comment by WarSxNes** [comment]
Bueno, creo que talvez sean suficientes. El problema seria el respaw o tiempo para reapareser. Hayer por ejemplo handabamos 3 con la misma quest y nos estabamos peleando por los renacuajos. claro fue pura casualidad.

Pero teniamos que esperar (no estoy seguro por que no tome tiempo) talvez unos 5 o 10 minutos para que volvieran a aparecer. Yo tube que dejar que estos 2 locos hicieran la quest primero para que alfin yo la pudiera completar.

Tube que esperar un total de casi 1 hora para completarla. Pues la quest te pide 20 hay unos dentro de la cueva pero uff al nicel 71 creeme es muy dificil entrar ahi sin morir. Pero creo que el respaw seria bueno reducirlo un poquito ponle 3 minutos.

**Comment by redneo** [comment]
AYER ANDABAMOS TUVE AL FIN TUVE!!!!!

Está a 5 minutos por defecto
