### ISSUE TITLE
Estofado de orca suculento

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1253]
http://es.wowhead.com/quest=11564

---

http://es.wowhead.com/npc=25204 <<<<< hay muy pocos de estos en la zona y son los que tiran las cosas para la quest.

Son muy pocos y estan muy retirados uno de otro. Tienes que conseguir 7 entotal y solo hay 4. Serian 5 pero es que uno esta atorado entre la montaña bajo el agua y no le puedes pegar. Segun wowhead parece que deberia de haber un poco mas.

---

**_nomas como recordatorio_**
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1242
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1243
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1251
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1252

**Comment by redneo** [comment]
Habia 6 ahora hay 16

**Comment by WarSxNes** [comment]
confirmado ahora hay mas.. 

---

;p sin querer le di al boton cerrar xD, ahi te dejo el privilegio

**Comment by redneo** [comment]
Lo puedes cerrar tu si va bien...
