### ISSUE TITLE
Misión [Vigilando desde lejos]

### ISSUE THREAD

**Issue by kevinilo** [RoDNet/Bugtracker-Infinium-4.0.6a#1254]
La misión consiste en hablar con 3 montaraces y avisarles de no se que historia
El caso es que hay un montaraz que no me da la opción de avisarle (ver fotos)
![bien](https://f.cloud.github.com/assets/4630033/617664/ca4c67b4-ce9c-11e2-9428-9ebd25eff6ee.png)
![mal](https://f.cloud.github.com/assets/4630033/617665/ca6d0b9a-ce9c-11e2-8564-1e84470d136b.png)
Os adjunto también el link de wowhead: http://es.wowhead.com/quest=313

**Comment by redneo** [comment]
arreglado
