### ISSUE TITLE
Misión [Rivales Acérrimos]

### ISSUE THREAD

**Issue by kevinilo** [RoDNet/Bugtracker-Infinium-4.0.6a#1255]
Es una misión muy secundaria, yo os lo pongo de todas formas para informaros:
![rivales acrrimos](https://f.cloud.github.com/assets/4630033/618882/29d6b51e-cebf-11e2-8e45-b09c2848ae24.png)
En el mapa me sale el signo de interrogación, pero no encuentro el barril para terminarla
Ya he hecho la misión anterior, la de distraer a Jarven, pero no tenia cogida esta, entonces no se si es por esto por lo que no puedo completarla.
http://es.wowhead.com/quest=310/rivales-acerrimos

**Comment by redneo** [comment]
By Leiaza (3,070 – 6·39) on 2011/01/11 (Patch 4.0.3) Report  
It was removed in 4.0.3 patch

http://www.wowpedia.org/Quest:Bitter_Rivals

Procedo a borrarla de los questgivers.
