### ISSUE TITLE
El destornillador ultrasónico

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1256]
http://es.wowhead.com/item=34984 <<< Item que inicia la quest 7%
http://es.wowhead.com/npc=25477 <<< TERMINA

Bien el caso es que ya llevo rato matando todo el que se me atravieza, mas y sin contar que ya hice una quest donde me pedia matarlos, y no se si te recuerdas de una quest donde tenias que recolectar piezas de chatarra.

Bueno el caso es que llevo 2 quest donde tube que matarlos para completar dichas quest. Y aparte los mate solo para intentar ver si lo tiraban y pues nada que lo tiran.

**segun wowhead MoP**
http://es.wowhead.com/npc=25753<< 7% ----- que lo tire y nada ya acabe con todos
http://es.wowhead.com/npc=25752<< 2% ----- este le sigue he igual nada no lo tira
http://es.wowhead.com/npc=25758<< 1.6%
http://es.wowhead.com/npc=25793<< 1.1%

O es que tengo mala suerte, o esta mal el loot. Haber si pueden ver que anda mal.

**como recordatorio**
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1251
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1243

**Comment by redneo** [comment]
Lo he puesto al 20% de loot, testado con el 100 y si que lo sueltan, asi que con 20, lo tendrian que soltar...

**Comment by WarSxNes** [comment]
Yap.. confirmado lo tiro.
