### ISSUE TITLE
Destrozar los núcleos, (Monte Hyjal)

### ISSUE THREAD

**Issue by Varga9** [RoDNet/Bugtracker-Infinium-4.0.6a#1257]
A la quest solo le falta para terminarla el Yunque Crepuscular, que debería encontrarse en el primer pasillo conforme pasas la entrada.

http://es.wowhead.com/quest=25577/destrozar-los-nucleos#comments

Saludos

**Comment by redneo** [comment]
Habia dos puestos por ahí, se han puesto 7 más, en esa cueva faltan muchos npcs, que supongo te haran falta en siguientes misiones.
