### ISSUE TITLE
¡Utiliza el Vibro-Motor 5000!

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1258]
http://es.wowhead.com/quest=11723 << quest bug
http://es.wowhead.com/npc=25780 << EMPIEZA - TERMINA

---

1 http://es.wowhead.com/item=34981 <<< debe de usarlo en 70.0 - 36.4
- http://es.wowhead.com/npc=25794

2 http://es.wowhead.com/npc=25629 <<< despues del temblor que hace npc=25794

---

**BUG**
Cuando intentas usar el control item=34981 solo tira un mensaje que debes usarlo en sumidero del sur. Y no pasa nada. Los objetivos son usar el control y matar a la cucaracha que sale ;p

---

**recordatorio**
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1256
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1251
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1243

**Comment by redneo** [comment]
Arreglada, si va bien lo cierras Tu!

**Comment by WarSxNes** [comment]
confirmado ya funciona 99.9% ahora explico xD

**nota**
0.01% es por que tube que pararme justo en el mero centro del agujero. Supongo que si fuera la vida real ese agujero seria profundo y deberias de usarlo cerca de el y no dentro. Para los futuros jugadores se les hara algo dificil saber que deberan pararse en el centro del agujero.
