### ISSUE TITLE
Monitoring the Rift: Sundered Chasm

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1259]
http://www.wowhead.com/quest=11582 <<< quest bug

![wowscrnshot_060613_135731](https://f.cloud.github.com/assets/2059256/620709/fbca4dca-ceeb-11e2-969d-a153894bc89e.jpg)
![1231234](https://f.cloud.github.com/assets/2059256/620749/01bdb496-ceed-11e2-8b3f-bcea1eacdfae.png)

Como veras en el registro de carbonite muestra que no me conto la quest. Se la salto.
Esta quest es algo importante si quieres subir a exaltado con los Kirin'Tor

 *15,100 experience
 *150 reputation with Kirin Tor

No es mucha cosa, pero algo es algo xD.

---

**BUG**
Cuando terminas la quest anterior, automaticamente creo que la otra se acepta, y te muestra como ya completada. Creo que sin querer la complete y se salto a la siguiente sin contarmela ni dio exp. ni repu.

**Comment by redneo** [comment]
Arreglado, ya la puedes coger y hacer. Cierra el ticket cuando lo hayas hecho.

**Comment by WarSxNes** [comment]
xD bueno, creo que para mi mala suerte como ya complete la tercera quest de esta mini-cadena ya no me muestra la segunda quest.

Voy a ver si con otro PJ la logro ver... ya regreso a comentar.

---

**Edito**
Funciona 100% confirmado xD. cierro entonces
