### ISSUE TITLE
Abducción

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1260]
http://es.wowhead.com/quest=11590
http://es.wowhead.com/item=34691 <<< item de quest.

Esta imagen la tome yo pero al moverme se pierde el enlace y no pasa nada.
![wowscrnshot_060613_143527](https://f.cloud.github.com/assets/2059256/620924/fc7577da-cef1-11e2-9fda-1b62dd98774b.jpg)

![s](http://wow.zamimg.com/uploads/screenshots/thumb/105573.jpg) << algo asi deberia de ver se.

---

Me encontre con este ahi sentado lol y que crees este deberia ser el de la quest. Pero OJO este seria despues de haber completado la quest. Osea antes de la quest no deberia de estar ahi. Despues de la quest aparece ahi sentado. Que seria? le falta un aura no? Bueno es lo demenos.
![wowscrnshot_060613_143649](https://f.cloud.github.com/assets/2059256/621019/333ad664-cef4-11e2-9d8b-aab23d3ecd73.jpg)

---

![wowscrnshot_060613_143716](https://f.cloud.github.com/assets/2059256/620928/04cdd562-cef2-11e2-8c5b-140c7db9c176.jpg)
Anticipo a decir que las quest de esta zona han de estar bug xD luego las reporto despues que arreglen esta por que no puedo seguir ahi me quede.

**Comment by redneo** [comment]
Ahora se hace bien... 

Toma esto. Vuelve a Alto de Berilo y úsalo sobre un hechicero de Berilo cuando su muerte se acerque. Eso le inmovilizará el tiempo suficiente para que puedas traérmelo para interrogarle.

**Comment by WarSxNes** [comment]
Es cierto... Es cierto!!! funciona... :P que tonto... xD ok cierro entonces.
