### ISSUE TITLE
El arte de la persuasión

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1264]
http://es.wowhead.com/quest=11648 <<< quest bug
- http://es.wowhead.com/npc=25480 <<< EMPIEZA el empezar es el que esta bug _(me explico?)_
- http://es.wowhead.com/npc=25480 <<< TERMINA

http://es.wowhead.com/item=34811 << item de quest
http://es.wowhead.com/npc=25478 << objetivo de la quest

![h](http://wow.zamimg.com/uploads/screenshots/thumb/92325.jpg)

**BUG**
Para empezar, por las carreras no preste atencion y esta auto-aceptable y sin querer la e completado.

Como consecuencia no me dio exp. ni me dio reputacion con los Kirin'Tor. Ni tampoco me quedo registrada >.< bueno eso para empezar.

**nota**
segun los comentarios de wowhead dicen que debes de usar entre 5 y 6 veces el item que te da la quest sobre el npc objetivo para interrogarlo y asi completar la quest. Y el bug esta en que se salta en el sentido de aceptarla y solo aparece para completarla.

De lo que resta de la quest no sabria decir por que nunca la pude hacer. Asi que cuando la arreglen seria bueno que la revisen.

**Comment by redneo** [comment]
Arreglado

**Comment by WarSxNes** [comment]
CONFIRMADO.... funciona 100% ... despues de darle una buena .. solto la sopa o.0??? xD hehe
