### ISSUE TITLE
Langosta de roca

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1266]
![f](http://wow.zamimg.com/uploads/screenshots/thumb/343504.jpg)
http://es.wowhead.com/quest=26442 <<< quest bug
http://es.wowhead.com/npc=5494 >>> EMPIEZA - TERMINA
http://es.wowhead.com/item=58809 <<< objetivo de la quest

**BUG**
Las langosta estas fuera de sus jaulas y no les puedes hacer CLICK para cogerlas/tomarlas.

![wowscrnshot_060813_114913](https://f.cloud.github.com/assets/2059256/627970/6cb741a0-d06d-11e2-9301-44f9fb98c4b9.jpg)

> **recordatorio**
> https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1243

**Comment by redneo** [comment]
Arreglado, puede que tengas que limpiar temporales para coger las jaulas que si que estan.

**Comment by WarSxNes** [comment]
CONFIRMADO funciona al 100%
