### ISSUE TITLE
Guante Sangui del Sacer esta bug

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1268]
![wowscrnshot_060813_211149](https://f.cloud.github.com/assets/2059256/628510/1d49663e-d0bd-11e2-91eb-d6333c7dce03.jpg)
![wowscrnshot_060813_211214](https://f.cloud.github.com/assets/2059256/628511/1d610d5c-d0bd-11e2-869e-3f1204249310.jpg)
![wowscrnshot_060813_212213](https://f.cloud.github.com/assets/2059256/628512/1d8af914-d0bd-11e2-939b-447abf63182e.jpg)
![wowscrnshot_060813_212236](https://f.cloud.github.com/assets/2059256/628513/1d91aba6-d0bd-11e2-9c0b-e81f9658836e.jpg)

**Comment by redneo** [comment]
esto... para mi que le falta este spell: http://es.wowhead.com/spell=44297

Como a este, a todos los guantes supongo que por el estilo... a lo mejor los puedo sacar a saco, a ver un segundo que indague...

**Comment by redneo** [comment]
Escoba voladora presta,
Vieja escoba mágica,
Escoba mágica presta,
Escoba mágica destartalada,
Guanteletes de placas de tinieblas de Gladiador sañoso,
Guanteletes escamados de Gladiador sañoso,
Guanteletes de placas de Gladiador sañoso,
Guanteletes de anillas de Gladiador sañoso,
Guanteletes de cota guarnecida de Gladiador sañoso,
Guanteletes eslabonados de Gladiador sañoso,
Guanteletes de malla de Gladiador sañoso,
Guantes de pellejo de dragón de Gladiador sañoso,
Guantes de pellejo de kodo de Gladiador sañoso,
Guantes de pellejo de vermis de Gladiador sañoso,
Guantes de cuero de Gladiador sañoso,
Manoplas de seda de Gladiador sañoso,
Guantes de tela lunar de Gladiador sañoso,
Guantes de satén de Gladiador sañoso,
Manoplas de tejido vil de Gladiador sañoso,
Guantes ornamentados de Gladiador sañoso,
Glifo de Piroexplosión,
Glifo de Cono de frío,
Glifo de Escudo de maná,
Glifo de Aliento de dragón,
Glifo de Ralentizar,
Glifo de Conjuros,
Cáliz de los reyes de la montaña,
Campanillas de viento kaldorei,
Guanteletes de anillas de Gladiador sanguinario,
Guantes de pellejo de dragón de Gladiador sanguinario,
Guanteletes de placas de tinieblas de Gladiador sanguinario,
Manoplas de tejido vil de Gladiador sanguinario,
Guantes de pellejo de kodo de Gladiador sanguinario,
Guantes de cuero de Gladiador sanguinario,
Guanteletes eslabonados de Gladiador sanguinario,
Guanteletes de malla de Gladiador sanguinario,
Guantes de tela lunar de Gladiador sanguinario,
Guantes ornamentados de Gladiador sanguinario,
Guanteletes de placas de Gladiador sanguinario,
Guanteletes de cota guarnecida de Gladiador sanguinario,
Guantes de satén de Gladiador sanguinario,
Guanteletes escamados de Gladiador sanguinario,
Manoplas de seda de Gladiador sanguinario,
Guantes de pellejo de vermis de Gladiador sanguinario,
Guantes ornamentados de Gladiador sañoso,
Guanteletes de malla de Gladiador sañoso,
Guantes de pellejo de vermis de Gladiador sañoso,
Guantes de pellejo de kodo de Gladiador sañoso,
Guanteletes de anillas de Gladiador sañoso,
Guantes de cuero de Gladiador sañoso,
Guantes de tela lunar de Gladiador sañoso,
Guanteletes eslabonados de Gladiador sañoso,
Manoplas de seda de Gladiador sañoso,
Guanteletes de cota guarnecida de Gladiador sañoso,
Manoplas de tejido vil de Gladiador sañoso,
Guantes de satén de Gladiador sañoso,
Guanteletes de placas de Gladiador sañoso,
Guantes de pellejo de dragón de Gladiador sañoso,
Guanteletes escamados de Gladiador sañoso,
Guanteletes de placas de tinieblas de Gladiador sañoso,
Corcho de pesca de cristal,
Boceto: diamante de espíritu de las Sombras ardiente

Arreglados

**Comment by WarSxNes** [comment]
WoW WOW wow !!!!! todos esos lol,,,, --- confirmado.... funciona almenos el que llevo puesto ya funciona al 100%
![wowscrnshot_060913_083948](https://f.cloud.github.com/assets/2059256/629049/9aa0e8c4-d11b-11e2-98bd-bb3a279984fa.jpg)
