### ISSUE TITLE
[Logro] ¿Amigo o enemigo?

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1270]
Mato a los 15 pavos antes de los 3 minutos pero no salta logro ninguno.
Aqui dejo el link: http://es.wowhead.com/achievement=1254

**Comment by redneo** [comment]
Para ese logro necesitas este spell: http://es.wowhead.com/spell=25285 no se como arreglarlo...
