### ISSUE TITLE
Bonus 4 piezas pvp sacerdote healer

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.0.6a#1272]
Buenos días.

Actualmente la última bonificación por llevar equipo pvp de sacerdote en la especialización de healer no funciona. No puedo enlazarlo desde el wowhead porque han cambiado la bonificación a este set.

La bonifación en cuestión es: al utilizar palabra de poder escudo sobre el propio sacerdote debería suprimir temporalmente durante 4segundos los efectos que reducen tu velocidad de movimiento.

Enlazo:

http://imageshack.us/photo/my-images/23/wowscrnshot060913131938.jpg/

Sin embargo como se aprecia en la siguiente imagen, al tener el efecto de enfriado y aplicarme a mi mismo la palabra de poder escudo, sigo teniendo la movilidad reducida:

http://imageshack.us/photo/my-images/812/wowscrnshot060913132037.jpg/

Sino se pueden ver las imagenes, avisadme y las volveré a subir.

<a href="http://imageshack.us/photo/my-images/94/wowscrnshot060913131938.jpg/" target="_blank"><img src="http://imageshack.us/a/img94/2162/wowscrnshot060913131938.th.jpg" border="0"/></a>

<a href="http://imageshack.us/photo/my-images/812/wowscrnshot060913132037.jpg/" target="_blank"><img src="http://imageshack.us/a/img812/8846/wowscrnshot060913132037.th.jpg" border="0"/></a>

Gracias.

**Comment by redneo** [comment]
http://www.wowhead.com/item=64795

El bonus: http://old.wowhead.com/spell=33333 pero segun mis datos hace:
Description: Cuando lanzas Palabra de poder: escudo sobre ti, los efectos de reducción de la velocidad de movimiento se eliminan de forma temporal durante $96219d.

Que tendria que ser... http://es.wowhead.com/spell=96219 que lo que diga wowhead, con los datos que tengo yo son....Description: Se suprimen las reducciones de velocidad de movimiento.

Ahora, tengo que probar ese spell :S

Edito... la spell 96219 te pone el aura, pero no quita las reducciones de movimiento... si quieres lo puedo poner para que "funcione" pero vas a poner otro ticket poniendo que no quita las reducciones.

Puesto al spell 17 que salte siempre el spell 96219 para que testeis si mengua las reducciones de movimiento, si es así, ya pondre que salte solo si tienes el tier pvp de sanacion.

**Comment by paellaencol** [comment]
:O Funciona ya a la perfección y te hace ir a velocidad normal durante esos 4 segundos ignorando las penalizaciones presentes, además solo salta si se tiene equipado las 4 piezas del set de sanación.

Gracias, cierro esto ya entonces.

Edito: el nombre del buffo temporal que salta es "Holy walk".

**Comment by redneo** [comment]
Vaya, no contaba que quitase la penalizacion :D
