### ISSUE TITLE
reputacion de el alba argenta

### ISSUE THREAD

**Issue by otakus1986** [RoDNet/Bugtracker-Infinium-4.0.6a#1275]
wenas no se si esta bug o soy yo pero agarre unas misionde de alba argenta en tirra de la peste los npc tenian letra amarilla. aja fino complete la mision cuando entrego no me dan la reputacion T_T . y para sabe donde vende el tabardo de el alba argenta. espero que me ayuden 

gracias

**Comment by Wiinter** [comment]
No hay tabardo de Alba Argenta, almenos no uno que se puedo conseguir ingame. Hay muchas quests que no tienen porque dar repu con una facción determinada. Recientemente he subido esa reputación y te recomiendo que o bien hagas las misiones de las tierras de la peste, así podrás reportar todas aquellas que están bug , o sino tienes la opcion de la Mazmorra de Tierras de la Peste del Oeste: Scholomace. Es de nivel 50-55 diría y es muy facil de solear.

P.D: Puede ser que las quests que cogieras debieran dar reputación, por tanto te recomiendo que consultes esas quests en http://es.wowhead.com y si no dan lo que deberían, las reportes.

Espero haberte ayudado

**Comment by otakus1986** [comment]
gracias ire a revisar
