### ISSUE TITLE
kill me!!!

### ISSUE THREAD

**Issue by searumgay** [RoDNet/Bugtracker-Infinium-4.0.6a#128]
Soy searum y me gusta q me den por atras

Enjoy!!!

**Comment by Dekadencee** [comment]
Pues nada, denunciado a Github... a ver si dejas de interferir en el trabajo de los demás que yo no tengo porque andar leyendo tus tonterías, los problemas personales los hablas con él, pero no me ensucies el bugtracker de mi servidor con estos mensajes porque la que tiene que andar luego cerrando soy yo...

Esto no es un chat!
