### ISSUE TITLE
[Mision] Haz los honores 

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1280]
No me deja usar el objeto, orbe de las estrellas (http://es.wowhead.com/item=62054) sobre el mecanismo antiguo.

Aqui te dejo el link: http://es.wowhead.com/quest=27669

**Comment by redneo** [comment]
Ya funciona el orbe, pero no completa la mision, ni poninedo link a un spell que tendria que terminar la misión. Hay un demonio en medio de la sala para matar.

**Comment by Wiinter** [comment]
Ahora no puedo entregar la mision a ningun Harrison Jones de la zona
