### ISSUE TITLE
Arqueología

### ISSUE THREAD

**Issue by jandrox** [RoDNet/Bugtracker-Infinium-4.0.6a#1282]
Hola, faltan dos razas de los objetos de arqueología, los Tol'vir y otro más que no se cual es :P y no aparecen en el mapa para encontrarlos, deberían aparecer en Uldum y otros sitios de lvl por encima de 80.

**Comment by DatJetto** [comment]
Tol vir si aparece, lo que pasa que tienes que tener MUCHA suerte para que te salgan las palas en Uldum ( comparten continente entero las palas de Kalimdor y Eastern Kingdoms  ) de manera que es excavar mucho en Kalimdor para que la pala salga :3 , la otra que dices no es nada, está así y es un logo sin importancia xD

**Comment by jandrox** [comment]
Toda la razón, al final apareció una pala en uldum, ya creia que era un fallo de mi vista jeje
Puedes cerrarlo ;)
