### ISSUE TITLE
[Misión] Cabalgando sobre el cohete rojo

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1285]
No te deja subir a unos cohetes que hay detrás del faro para que destruyas el barco qe te dice la mision

Aqui te dejo el link de la quest: http://es.wowhead.com/quest=12432

Decir que la quest unicamente se puede coger si Bahia Ventura pertenece a la Horda y lo he compravado y funciona bien en ese aspecto :)

**Comment by redneo** [comment]
http://www.youtube.com/watch?v=hKM38kSJwyo

Lo he hecho a lo cutre, tendria que funcionar

**Comment by Wiinter** [comment]
Arreglada
