### ISSUE TITLE
(Misión) Traidores entre nosotros

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1290]
La misión en de la alianza y es en la isla de Theramore, hay que hacer click encima de unos soldados y se supone que debes desenmascararlos pero al hacer click no hace nada.

http://es.wowhead.com/quest=27210

**Comment by redneo** [comment]
Arreglada aunque no me ha gustado como ha quedado :S

**Comment by Leizar999** [comment]
Funciona.
