### ISSUE TITLE
(Misión) Creo que tiene hambre

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1291]
En esta misión se supone que vas con una prole cozalote recién nacida y tienes que darle de comer con unos trozos de carne de basilisco en el norte de vega de tuercespina, pero allí no hace nada, el npc que está asociado a esta misión son unos murlocs que hay al sur, la solución sería cambiar en la base de datos el creature id de uno por otro:

http://i665.photobucket.com/albums/vv19/Leizar999/WoWScrnShot_060913_105606_zps1558e49b.jpg

La misión en wowhead es esta:

http://es.wowhead.com/quest=26739

**Comment by redneo** [comment]
No se ve el pantallazo, de todas formas arreglada, no se si cuando se caiga el server... funciona con http://www.wowhead.com/npc=689

**Comment by Leizar999** [comment]
Ok. Gracias.
