### ISSUE TITLE
(Interface) No sale objetos completados en party

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1292]
Estando en grupo con un amigo haciendo la misma misión, al marcar un objetivo me sale los bichos que necesito para completar la misión pero no los de mi compañero, puedo ver cuales tiene que matar si no estoy en su misma misión pero no cuantos necesita para acabarla.

**Comment by redneo** [comment]
Eso es un problema de comunicación entre el cliente y el servidor... de ese tipo de fallos hay muchos, y sinceramente, ese es de los menos importantes.

Esperemos que ese tipo de cosas, que son pequeñas tonterias, pero que molan, se solucionen con la versión 434

**Comment by Leizar999** [comment]
A ver si hay suerte :)
