### ISSUE TITLE
(Npc que sale del agua)

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1293]
Me ha pasado que cuando vas a vega de tuercespina las pirañas salen del agua persiguiéndote, eso es un fallo pero me imagino que será del emulador, no se si tendrá arreglo, pero lo posteo aquí para ver si se puede hacer algo, gracias.

**Comment by redneo** [comment]
Los npc suelen tener 3 tipos de ambiente donde se suelen mover. A saber
Tierra
Agua
Aire

Normalmente los que tienen Agua van mal cuando estan en el agua y se les pone que esten en todos los ambientes. Es un poco feo, pero efectivo.

**Comment by Leizar999** [comment]
ok, cierro entonces.
