### ISSUE TITLE
[ Paladin > Holy Radiance ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1295]
De nuevo tras la reposición de los valores originales, radianza sagrada vuelve a curar 5-7k por tick, debiendo ser mucho menor la sanación.

http://es.wowhead.com/spell=82327

**Comment by redneo** [comment]
de 1765 que me curaba a mi por tick ha pasado a 863, no se si está bajo o no...

**Comment by paellaencol** [comment]
He probado ahora esa facultad con un paladin sagrado y actualmente está funcionando de la siguiente manera: 863 de sanación base + 7,7% de poder con hechizos.

Mi pregunta es: no debería escalar en torno a un 67,5% del poder con hechizos?

Sino en la actualidad se convierte en una cura prescindible en pve, ya que no habra mucha diferencia en usarla llevando equipo de azules o épicos.

**Comment by DatJetto** [comment]
67% ? wtf esta spell apenas coge Spellpower ya que casi el 50% de lo que debe curar en Holy, es sanación base.
De manera que si es 700 o 800 y algo base, la sanación completa no supera por mucho los 2k por tick en un paladín bastante equipado y con bastante intelecto.
