### ISSUE TITLE
(Misión) Abducción de ogro

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1296]
Hay una misión en Feralas, en la que tienes que capturar a un ogro con un orbe, pero al tener al ogro al 30% no se captura, no cuenta como completada la misión:

http://es.wowhead.com/quest=25344/abduccion-de-ogro

**Comment by redneo** [comment]
Ahora ya va.

**Comment by Leizar999** [comment]
Gracias.
