### ISSUE TITLE
[ Priest > Mind Spike ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1297]
Tras la vuelta a los valores originales, después de que Redneo arreglara púa mental, la cual duró unas pocas horas con sus valores correctos, vuelve a pegar más de lo que debe.

http://es.wowhead.com/spell=73510

**Comment by redneo** [comment]
Esto... creo que estas del todo confundido.

**Comment by ghost** [comment]
Ya tiene problemas psicológicos con las puas xd (nada más en broma, y solo dire que sigue igual a como lo dejo redneo).

**Comment by DatJetto** [comment]
He estado pelando antes con un sacerdote y me daba 10k de púa mental sin crítico, cuando el crítico tiene que ser eso aproximadamente...

**Comment by ghost** [comment]
Pues si tienes la fórmula Gromelger, compartertela así sabemos cuanto tiene que pegar en realidad.

**Comment by redneo** [comment]
0.836*SP
