### ISSUE TITLE
[ Baradin Hold > Argaloth ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1299]
Argaloth: 
http://www.wowhead.com/npc=47120

Este boss no tiene problemas de tipo encuentro, el problema está en que cuando pasan 5 minutos, la rabia no se activa, facilitando la derrota de este boss si no se cuenta con un nivel de equipamiento y habilidad mínimo para enfrentarlo en el tiempo requerido.

Habilidades del boss:
http://www.wowhead.com/npc=47120#abilities
Berserk: Se activa a los 5 minutos ( 300 segundos )
http://www.wowhead.com/spell=47008

**Comment by redneo** [comment]
Meck, no lo puedo cambiar ya que está programado :(

**Comment by DatJetto** [comment]
Ohh :(
