### ISSUE TITLE
[Hunter > Spec: Marksmanship > Spell > Ready, Set, Aim...]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#13]
-Preparen, apunten... http://es.wowhead.com/spell=82925
Se acumula 5 veces para dar: 

¡Disparo de puntería!   ( Debe ser instantáneo y no costar foco )
http://www.wowhead.com/spell=82928
Bug: Daño bajo , se castea. 

Fórmula correcta; 200 % ranged weapon + (RAP*0.724)+776 )

**Comment by searum** [comment]
el instant cast esta fix, el daño bajo... no se, a cuanto esta tengo que mirar bien

**Comment by DatJetto** [comment]
Lo unico que hace es suprimir el coste de foco, pero se castea.

**Comment by searum** [comment]
pega correctamente... no se que esperas que meta, 50k? XD
