### ISSUE TITLE
Npc>Rompevientos>Bastión del Crepusculo

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#1300]
Este npc http://es.wowhead.com/npc=47151 tira este hechizo: http://es.wowhead.com/spell=87870 que como se ve en la imagen... lo tira demasiado y es imposible no morir.

Si se pudiera arreglar el hechizo, o desactivarlo, o sacar el npc sería mucho mejor.

![prueba](https://f.cloud.github.com/assets/4663665/637654/c550c902-d2a8-11e2-958f-3a3fbd0fc003.jpg)

**Comment by redneo** [comment]
Antes lo tiraba en un intervalo de  14 a 16 segundos.

Ahora cuando le queda poca vida, cada 14 segudos a 40 segundos.

Caida del server needed.

**Comment by ghost** [comment]
Muchas gracias redneo, aunque si lo miras lo tira cada medio segundo xd.

**Comment by redneo** [comment]
Veamos, ese npc tiene dos spells.
http://es.wowhead.com/spell=87875 Que lanza cada medio segundo un vortice http://es.wowhead.com/spell=87880 que hace pupita, ese es el que toqué.

http://es.wowhead.com/spell=87870 que ese no lo  he tocado

**Comment by ghost** [comment]
Ok, la proxima que vaya a raid lo probaré para cerrar el issue.

**Comment by paellaencol** [comment]
Ayer mismo pudimos probar este en npc. La facultad esa nos la tiró una sola vez cuando ya tenía poca vida, la primera vez morimos porque no llegamos a tiempo a stunnearlo. La segunda vez que fuimos usó esta habilidad también únicamente cuando ya tenía poca vida, pero estuvimos más atentos y se pudo cortar bien con stun.

**Comment by redneo** [comment]
Y la tira a un pj al azar no al tank. Cuando querais, cerrais el tickets si lo creeis oportuno.

**Comment by ghost** [comment]
@redneo cerrado xd
