### ISSUE TITLE
Bugueros de bg

### ISSUE THREAD

**Issue by Drogoth2** [RoDNet/Bugtracker-Infinium-4.0.6a#1301]
Bueno creo que la imagen lo dice todo
![dibujo](https://f.cloud.github.com/assets/3939699/637836/5a659870-d2ad-11e2-9743-d620244d7767.jpg)

**Comment by Wiinter** [comment]
Creo qe esto no va aqui, sino en denuncias del foro

**Comment by redneo** [comment]
Anda que... a ver cuando te dan unas clases de photoshop para hacer las denuncias de modo anonimo :P

**Comment by Wiinter** [comment]
Cierra Tema plis
