### ISSUE TITLE
[Mision] Piratear el Wibson

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1302]
No se puede hacer nada, está la unidad Cental Wibson pero no estan los items para piratearla. No está ni el que te da la qest ni el que se tiene qe conseguir por ahi cerca.

Aqui te dejo el link de la misión: http://es.wowhead.com/quest=27778

**Comment by redneo** [comment]
Fixed! muahahahaha como me ha gustado, pena que no haya encontrado el spell que hace que el pj se ponga a pegar hachazos!

**Comment by Wiinter** [comment]
Arreglada
