### ISSUE TITLE
[Misión] Robocarnicero

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1304]
Se trata de recoger carne de basiliscos en Tanaris usando un control remoto que te dan para la misión una vez el basilisco esté muerto, pero accionas y no pasa nada, incluso habiendo despojado el npc.

http://es.wowhead.com/quest=25112

**Comment by redneo** [comment]
Costó, pero arreglada!

**Comment by Leizar999** [comment]
Funciona!
