### ISSUE TITLE
[ Razas > Incompatibilidad ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1306]
He estado leyendo las notas del parche 4.0.6 y dice: 

*Ahora el rasgo racial huargen Huida oscura tiene un tiempo de reutilización de 2 minutos, en vez de 3, y ya no figura en el tiempo de reutilización global. Además, ahora el bonus de velocidad de movimiento se acumula a los bonus existentes pero no se puede activar mientras Sprint o Carrerilla están activos (y estos no se pueden activar mientras Huida oscura esté activa).

Esto no se está cumpliendo de manera que los personajes Huarguen Pícaro y Druida pueden alcanza una velocidad conjunta muy superior a la del resto de personajes, cuando no debería ser así:

Huída oscura: http://es.wowhead.com/spell=68992
Sprint: http://es.wowhead.com/spell=2983
Carrerilla: http://es.wowhead.com/spell=1850

Creo que tampoco puede usarse cuando esto está activo: 
http://es.wowhead.com/spell=55016

**Comment by redneo** [comment]
Arreglado
