### ISSUE TITLE
(NPC de misión) Se necesitan empastes

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1308]
http://es.wowhead.com/quest=26887

La misión en general va bien, lo único que hay una zona detrás en la que hay un montón de npc pero no se mueven, y los que se mueven no lotean nada.

los que no lotean los empastes ni ningún tipo de objeto son http://es.wowhead.com/npc=44763

y los que no se mueven son http://es.wowhead.com/npc=44762

**Comment by redneo** [comment]
Cuando caiga el server veras la razón de porqué no lotean.
