### ISSUE TITLE
[Logro] Tol Barad

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1311]
Nose porque pero hay dos zonas qe no se completan, Bloque D y el Agujero

No te puedo linkear el logro a wowhead. Porque en wowhead no existe tal logro no se porqué.

**Comment by ghost** [comment]
Pues si te refieres al logro de exploración... pues yo lo tengo, así que debe de funcionar.

**Comment by Wiinter** [comment]
Ah si??? Pues lo probaré :D Es que he pasado varias veces por ahi y nada

**Comment by Wiinter** [comment]
Funciona, pero soy medio retra y no lo compruebo bien
