### ISSUE TITLE
[Misión] Por aquí por allá

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1312]
En esta misión hay que recoger chatarra esparcida, pero no hay chatarra para recoger, con lo que no se puede completar la misión.

http://es.wowhead.com/quest=25075

**Comment by redneo** [comment]
Cuando caiga el server habrá 14 por alli tiradas.

**Comment by Leizar999** [comment]
Gracias.
