### ISSUE TITLE
[Misión] El arma totem siniestro

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1313]
Se dejan los totems en el suelo cerca de los cocodrilos pero los totems solo siguen al cocodrilo y no lo atacan.

http://es.wowhead.com/quest=27336

Gracias.

**Comment by redneo** [comment]
Creo que ya funciona, me lo confirmas?

**Comment by Leizar999** [comment]
Esta la hizo una de mi hermandad y yo andaba ayudando, no tengo la cadena de misiones pero ella si, en cuanto podamos la probamos a ver si va.
