### ISSUE TITLE
[Misión] Carroña de carroñeros

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1314]
Es la segunda de una serie de misiones que tienes que recoger carne con un robot, la primera que reporté de los basiliscos se arregló y funciona perfectamente, en este caso hay que matar a los pájaros de alas rojas de los huesos en Tanaris.

http://es.wowhead.com/quest=25111

Gracias.

**Comment by redneo** [comment]
Arreglada y la siguiente

**Comment by Leizar999** [comment]
Funciona!!
