### ISSUE TITLE
[Misión] Secretos en el oasis

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1315]
La misión consiste en encontrar un oasis en el desierto, y debe de haber un bicho en el agua, que al hacer click o similar aparecería, pero no hay nada y por tanto no se puede completar.

http://es.wowhead.com/quest=25032

**Comment by redneo** [comment]
Fixed

**Comment by Leizar999** [comment]
Va perfecta, gracias.
