### ISSUE TITLE
[Misión] Una idea genial

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1316]
Tienes que cazar un insecto de una cueva, se le lanza un trozo de carne y se supone que va a por ella y puedes cazarlo con una cuerda, pero lanzas el trozo de carne y no hace nada. Si se me permite una sugerencia si no se puede hacer que pille la carne que matando al bicho cuente. Saludos.

http://es.wowhead.com/quest=24951

**Comment by redneo** [comment]
Arreglado lo pruebas y cierras si funciona?

**Comment by Leizar999** [comment]
Eres un crack, si que va y cuenta.
