### ISSUE TITLE
[Mazmorra] Profundidades Roca Negra

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1317]
Cuando llegas a la Sala donde esta Coren durante el evento de la Cerveza no puedes continuar porque no puedes abrir la puerta siguiente de ninguna manera. Supuestamente debería explotar al dar unas cervezas al enano ese Sinroca

**Comment by redneo** [comment]
http://es.wowhead.com/item=11602#comments

Arreglado, emborracha al tipo que a mi me ha funcionado

**Comment by Wiinter** [comment]
Arreglado, ya abre la puerta
