### ISSUE TITLE
[Misión] Conseguir carne fresca con carne putrefacta

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1320]
Esta misión es en el cráter de Un Goro, en el asentamiento de la alianza, se tiene que tirar un trozo de carne que te dan a los dinosaurios cercanos y atraerlos a unos fosos con pinchos, he intentado la misión pero pasan por encima y no les hace nada, pero si yo me tiro muero al instante.

http://es.wowhead.com/quest=24697#.

Saludos.

Edito. He visto que funciona pero con los Ravasaurios y se completa al tirarles carne solamente.

**Comment by redneo** [comment]
Cierras el ticket entonces?

**Comment by Leizar999** [comment]
Por supuesto, todo correcto.
