### ISSUE TITLE
Domar pet ''BUG''

### ISSUE THREAD

**Issue by Sagittariu5** [RoDNet/Bugtracker-Infinium-4.0.6a#1321]
Hola, pues soy un cazador muy dedicado a la colección de pets raras y que nadie posea, o que no muchos usen, cuestión de gustos. a lo que voy en la mazmorra de ''La meseta de la Fuente del Sol''.
http://es.wowhead.com/zone=4075/meseta-de-la-fuente-del-sol#.
Hay una pet mas precisamente un dragohalcón de la variedad filosol que según wowhead y petopía es perfectamente tameable, lastimosamente hablé con un gm que me confirmó que está bug el tamear este pet, no sé si puedan arreglaro por favor , se los agradecería mucho es la unica pet que me falta en variedad :c 
http://es.wowhead.com/npc=25867#screenshots

PD: Es imposible tamearle en ninguna de las ramas de talentos. TnT

**Comment by redneo** [comment]
Ya la he tameado con mi cazador.

Creo que hay muchas mas por el estilo, serias capaz de reportarme las que no se pueden tamear, las que necesitan de especialización y se tamean sin ella y esas cosas?

Gracias de antemano

**Comment by Sagittariu5** [comment]
Las hay por su puesto, pero esta es la que más le va a mi cazador por el skin, claro puedo ayudarte y lo haré ahora no sé si quieras que te diga las pets que no están y deberían de estar en esta versión y las que están reemplazadas por otras que no deberían estar allí.

Ahora en efecto has arreglado el bug de domesticar, muchísimas gracias, :3  pero hay un problemita al domar la bestia es posible que salte un pequeño visual, no se perciben la tabla de talentos, esto se arregla borrando caché(comprobado) nada mas que decir adjunto dos fotos de mi nueva adquisición.

http://i.imgur.com/5BIiJeg.jpg
http://i.imgur.com/AqSlcJz.jpg

**Comment by redneo** [comment]
Sí porque en el cache del juego, tienes como que esa mascota no es domesticable, tienes que limpiarlo.

Lo que te digo es que seguro que hay muchas mascotas como esa que teoricamente se podrian domesticar, pero no se pueden, y me consta que hay otras que tendrias que tener la especialización de Maestria en bestias pero se pueden domar sin tenerla.

**Comment by DatJetto** [comment]
Redneo te adjunto las pet que he comprobado se pueden Tamear en SV y MM cuando SOLO deberían ser disponibles en BM:

Can de núcleo: http://es.wowhead.com/pet=45#tameable
Silítidos: http://es.wowhead.com/pet=41#tameable

si encuentro alguna otra posteo :)

**Comment by Sagittariu5** [comment]
Bueno ya comprobé en su totalidad a todas las mascotas exóticas, que son las que se consiguen en BM.
- Gusano
- Rinoceronte
- Bestia espíritu
- Can del Núcleo
- Demosaurio
- Quimera
- Araña de esquisto

Todas van bien, pero cabe recalcar que solo probé puntería, SV ni idea pero yo asumo que todo debe estar en orden ahora cierro tema y paso abro otra issue para reportar otro fallo de pets :)
