### ISSUE TITLE
[Misión] Cristales de poder

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1322]
Se trata de recolectar por el cráter de un goro diversos cristales, el problema es que hay escasez de ellos y los que encuentras no se pueden despojar, solo puedes despojar algunos y si quieres completar la misión tienes que esperar en el sitio donde aparecen para recolectar en lugar de ir buscando por el mapa.

http://es.wowhead.com/quest=24720

Saludos.

**Comment by redneo** [comment]
Cuando caiga el server y puede que tras limpiar temporales, los que no se abren, tendrian que hacerlo

**Comment by Leizar999** [comment]
Gracias!!
