### ISSUE TITLE
[ Druid > Rejuvenation ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1325]
Rejuvenecimiento:
http://es.wowhead.com/spell=774

Esta habilidad está algo subida, cura más de base de lo que debe.
Cura base 1307.
Los cálculos los haremos DESNUDO y sin talentos.

![wowscrnshot_061313_165840](https://f.cloud.github.com/assets/2728817/649083/fb67562e-d43c-11e2-8721-9125e3258c4c.jpg)

![wowscrnshot_061313_172231](https://f.cloud.github.com/assets/2728817/649096/0f0b1ed6-d43d-11e2-8bb1-41a5a3ea08df.jpg)

Aquí vemos como cura un poco más de loque debe, 7 puntos insignificantes, veamos qué sucede después.

Nos ponemos set para ver como escala. OJO SOLO EQUIPO, NADA DE TALENTOS.

![wowscrnshot_061313_172319](https://f.cloud.github.com/assets/2728817/649101/2fe2c92e-d43d-11e2-8f91-69e410407661.jpg)

5535 de poder con hechizos y 3686 de intelecto.

De 2k que debería sanar, sana 3,3k.

Si ya nos ponemos talentos en heal y demás pues llegas a los 7k por tick.

**Comment by redneo** [comment]
Tenia un multiplicador de 0.37604 lo he puesto a 0.134 que es lo que dice drd

Comparado con renovar, sana MAS.

**Comment by DatJetto** [comment]
Sana lo que debe, cierro :)
