### ISSUE TITLE
[ Druid > Revitalize ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1326]
Revitalizar:

Rango1: http://old.wowhead.com/spell=48539
 Rango2: http://old.wowhead.com/spell=48544

Pongo el Tooltip para 4.0.6.

When you periodically heal with your Rejuvenation or Lifebloom spells, you have a 10/20% chance to instantly regenerate 2% of your total mana. This effect cannot occur more than once every 12 sec.

In addition, you also grant Replenishment when you cast or refresh Lifebloom.

Replenishment - Grants up to 10 party or raid members mana regeneration equal to 1% of the maximum mana per 10 sec. Lasts for 15 sec.

---

Tiene 2 fallos:
- 1- Este efecto no tiene Cooldown, de manera que puede activarse cuando quiere regenerando mucho más maná del debido.
- 2- Solo debería activarse con Rejuvenecimiento y Flor de vida, pero sin embargo se activa con Crecimiento salvaje, Tranquilidad ( curas en área, facilitando la obtención de maná en el druida desproporcionadamente )

---

Con estos hechizos SI debe activarse:
- Flor de vida: http://es.wowhead.com/spell=33763
- Rejuvenecimiento: http://es.wowhead.com/spell=774

Con estos NO debe activarse, pero actualmente lo hace:
- Crecimiento Salvaje: http://es.wowhead.com/spell=48438
- Tranquilidad: http://es.wowhead.com/spell=740

**Comment by paellaencol** [comment]
No todos los bugs del druida son beneficiosos, algunos le son bastante perjudiciales. 

La facultad "floración" del druida actualmente sigue sin funcionar:

https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/677

**Comment by nicerdicer** [comment]
en contraargumento a lo que expones, no se con que ejemplos respaldas lo que expones pero estoy con mi druida resto delante, ejecutando todas y cada una de las habilidades que expones y te puedo decir que:
- Crecimiento Salvaje y tranquilidad las acabo de usar y no me han aplicado la Reposición, de hecho solo me la ha aplicado la flor de vida, en el momento en el qu ese termina, y en teroia reseteando el efecto con nutrir y recrecimiento flor de vida nunca deberia acabar, por lo que reposición casi nunca salta.
- Spamenado constantemente Flor de vida y Rejuvenecimiento, mi maná se ha consumido en cuestion de segundos, y tambien añadiendo algun crecimiento salvaje y en maná regenrado según lectura de Recount por flor de vida, solo ha ocurrido 3 veces.
- Y bueno como dice Paellaencol, el talent de floración que aporta una sacación en masa extra, no funciona... 

Repasa tus calculos antes de reportar falsos bugs y hacer perder tiempo al Staff

**Comment by redneo** [comment]
http://old.wowhead.com/spell=48539 y http://old.wowhead.com/spell=48544 no tenian CD, lo he puesto a 12, como dicen los comentarios.

Si salta con una u otra spell, me fio de vosotros que no tengo ganas de pasar numeros a spells y al reves. :P

**Comment by redneo** [comment]
Alivio presto, ahora cura... 1 sola vez, ya que no puedo ponerlo mas... tenia multiplicador de 0.15_sp y le he puesto 0.5_sp para compensar.

**Comment by nicerdicer** [comment]
Con 5.7K de sp - talento http://old.wowhead.com/spell=17113 [Rejuvenecimiento Mejorado] el cual aumenta un 15% el efecto de Alivio presto - y una sanación base con rejuvenecimiento de 18K en toda su duración, Alivio Presto solo me sana 11K (11.115), si no estoy equivocado, Alivio presto consume el efecto de Rejuvenecimiento o Recrecimiento curando de golpe la cantidad de sanacion equivalente a un efecto entero de uno de esos dos hechizos, y aun mejorandolo, no llega a sanar lo que cura rejuvenecimiento de por si, que son Ticks de 4 -5K durante 7 segundos, como ya he dicho 18K aprox. Digo esto para darnos cuenta que o el multiplicador no ha subido o la spell no esta bien, por que no creo que 11K de alivio presto con 15s de cooldown me compensen mucho.

Y bueno, ya que estamos, http://old.wowhead.com/spell=51181 [Don de la Madre tierra] juraria que rejuvenecimiento, al ser lanzado cura un 15% de su sanación total instantaneamente, sin embargo, esto no ocurre, ¿Alivio presto tambien debe compensar eso?.

**Comment by DatJetto** [comment]
A ver ha habido un error por mi parte no comentando qué parte de la spell no funcionaba:
- '' When you periodically heal with your Rejuvenation or Lifebloom spells, you have a 10/20% chance to instantly regenerate 2% of your total mana. This effect cannot occur more than once every 12 sec. '' 

Esa es la que no tenía CD y se activaba con Tranquilidad y Crecimiento salvaje.

Flor de vida si activa perfectamente Reposición y eso no está mal. 

Ahora procederé a ver Ingame el cambio :) y comento.

**Comment by DatJetto** [comment]
Comento, La recuperación de maná del druida se ha normalizado a la perfección :)
