### ISSUE TITLE
[Misión] Recarnificación

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1329]
No se puede apuntar a los goblins petrificados por consiguiente no se les puede recarnificar.

Aqui dejo la mision: http://es.wowhead.com/quest=14194

**Comment by redneo** [comment]
Arreglada, con sus textos que si alguien quiere traducirlos...http://www.wowpedia.org/Quest:Refleshification

**Comment by Wiinter** [comment]
Arreglada
