### ISSUE TITLE
[Misión] Mortero de primera 

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1330]
No van los morteros y no hay suficientes nagas para conseguir los 60 que pide la mision

Aqui dejo el link http://es.wowhead.com/quest=14471

**Comment by redneo** [comment]
Los morteros ya tiran las bombas, cuando caiga el server a lo mejor cuentan... :S

**Comment by Wiinter** [comment]
Se puede lanzar, pero no cuentan y además qe desde la colina solo se puede ver a un naga

**Comment by Wiinter** [comment]
Matas a los nagas sin necesidad de mortero. "Arreglado"
