### ISSUE TITLE
[Mision] Entablar amistad con los gigantes

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1332]
No te deja hablar con Gormungan, que es el que te completería la misión supuestamente.

Aqui dejo el link: http://es.wowhead.com/quest=14377

**Comment by redneo** [comment]
COJO.... NARICES, no veas lo que me ha costado, arreglada y testada.

Si alguien me quiere traducir la conversación encantado estaré de meterla

**Comment by Wiinter** [comment]
Arreglada
