### ISSUE TITLE
[Mision] Cuando la ciencia ataca

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1333]
No te deja completar la quest. 

Lo de apagar el fuego del laboratorio y de los goblins funciona bien.

Aqui dejo el link: http://es.wowhead.com/quest=14308

**Comment by redneo** [comment]
Arreglado, de paso he puesto que de la siguiente.

**Comment by Wiinter** [comment]
Arreglado
