### ISSUE TITLE
[Mision] Cohete Raptor

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1334]
Abres la jaula pero no puedes hacer nada al raptor experimental ni él hace nada.

Aqui dejo el link: http://es.wowhead.com/quest=14422

**Comment by redneo** [comment]
Ummm no se como hacerlos que se te suban encima... la dejo para otro momento

**Comment by redneo** [comment]
Paso de comerme la cabeza, al abrir la jaula cuenta, si no lo hace deja y vuelve a coger la mision

**Comment by Wiinter** [comment]
Arreglado
