### ISSUE TITLE
[ Descenso de Alanegra > ¿Y Maloriak? ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1336]
Hoy hemos ido a Descenso a continuar el resto de la raid que dejamos el otro día y derrotamos a Atramedes, cuando llegamos a la sala de Maloriak, no estaba.

El npc que falta es Maloriak: http://es.wowhead.com/npc=41378

Desceno Alanegra: http://es.wowhead.com/zone=5094

**Comment by crowel** [comment]
Me parece que produce crash al servidor por eso no está.
Un saludo.
