### ISSUE TITLE
[Pet] Palomilla 

### ISSUE THREAD

**Issue by Sagittariu5** [RoDNet/Bugtracker-Infinium-4.0.6a#1337]
Según alguien mencionó en general no se puede domesticar ahora mismo esta pet(gracias que si tengo la mía sana y salva.)  xD

He ido y lo he comprobado, y efecto no tiene la banderita de domesticar como dices tú,
sería bueno que lo arreglaras es una pet muy básica para hunters que recién empiezan.
Cabe destacar que esta tiene la particularidad de exótica lo cual no debería ser así.
http://i.imgur.com/9nQS9fo.jpg 

http://es.wowhead.com/npcs=1?filter=fa=37 

Lo he intentado específicamente con esta.
http://es.wowhead.com/npc=27421

Gracias de antemano :')

**Comment by redneo** [comment]
Cuando caiga el server se podran tamear sin necesidad de tener la maestria.

**Comment by Sagittariu5** [comment]
Muchas gracias, todo solucionado :9
