### ISSUE TITLE
Problemas con mi PJ, me desaparece el hit.

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.0.6a#1340]
Buenas noches.

Estoy teniendo problemas con mi índice de golpe, en la rama de reprensión, desde que me creé el personaje (el personaje en cuestión es un paladín elfo de sangre "Paellaencol". Siempre he tenido un 6,5% de hit menos, y en ocasiones directamente 0%.

Aunque en ocasiones he conseguido, tras cambiar muchas veces de talentos cambiando equipo y apagando y reiniciando el wow, tener el índice de golpe que me corresponde, desgraciadamente esos casos son uno de cada diez.

<a href="http://imageshack.us/photo/my-images/89/wowscrnshot061313213853fk.jpg/" target="_blank"><img src="http://imageshack.us/a/img89/34/wowscrnshot061313213853fk.th.jpg" border="0"/></a>

http://imageshack.us/photo/my-images/89/wowscrnshot061313213853fk.jpg/

Agradacería si me lo pudieran arreglar, ya que actualmente no puedo hacer dps casi nunca con este personaje debido a este error. Fallo ataques contra ardillas...

Edito: acabo de ver en la imagen que tampoco me está contando la pericia que me corresponde, debería tener 10 puntos más por llevar el glifo de Sello de verdad puesto. Ahora también me esquivan las ardillas.

Edito de nuevo: tras reloguear unas veces más, he conseguido que ahora tenga un punto porcentual más de hit. Como ven esto es muy variable, a veces puedo ir de dps en pve y otras por culpa del bug he de ir de healer.

**Comment by Sagittariu5** [comment]
En efecto me sucede mucho con mi caza, tanto ha sido así que en hecho reforjes cambios de abalorios, y renueve de gemado, y encantamiento, pero al paracer es un posible bug visual, pienso que podria ser si llevas algo transfigurado :/

**Comment by paellaencol** [comment]
El problema es que no es un bug visual. Fallo de verdad, de hecho no tengo nada transfigurado.

**Comment by ghost** [comment]
Paellaencol, no sé si sabes ni tampoco sé si este es tu problema, pero por si las dudas, te lo comento, si tienes partes reforjadas, al reloguear se "deshace" el efecto de las reforjas, para volverlas a tener, tienes que quitarte todo el set y reloguear, ahí volveras a tener los stats que deberías con las reforjas.

Y lo del glifo, puede que simplemente este bug y no funcione, no necesariamente tiene que estar vinculado al problema que mencionas.

**Comment by paellaencol** [comment]
Entendería lo del reload, porque a veces lo arregla, pero no en este caso ya que para intentar "arreglar" el problema estoy cambiando de equipo a heal y a dps constantemente. Por ejemplo he entrado ahora mismo después de un rato, y ya me ha vuelto a contar el hit, lo malo es que me lo contabiliza cuando quiere.

De todas maneras, gracias!
