### ISSUE TITLE
[Misión] El Ramo de la muerte

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1342]
En esta misión tienes que matar un grupo de sangrepétalos jóvenes y te debería de contar la misión, son 6 los que tienes que matar, van en grupo pero al hacerlo no cuentan.

http://es.wowhead.com/quest=24687

**Comment by redneo** [comment]
Ya cuentan.

**Comment by Leizar999** [comment]
Gracias, cierro.
