### ISSUE TITLE
[Misión] Los grabados de los glifos

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1344]
En Silithus tienes que ir a las cuevas de silítidos a leer como un pincho que hay en cada una, el pincho está y sale una opción para clickar cuando le das, pero no cuenta, sale algo así como leer este grabado y por mas que le das no hace nada.

http://es.wowhead.com/quest=8309

**Comment by redneo** [comment]
Cuando caiga el server tendria que funcionar.

**Comment by Leizar999** [comment]
Gracias, cierro.
