### ISSUE TITLE
[Misión] La llamada

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1345]
En Silithus, tienes que ir a un sitio donde hay huesos en el suelo y con un item que te dan debería de salir un bicho al que luego hay que matar, al entrar en wowhead pone que está descatalogada por Blizzard, pero sería interesante poder tenerla ya que te la dan y así habría una menos bugueada.

http://es.wowhead.com/quest=8315/la-llamada

Gracias.

**Comment by redneo** [comment]
Funcionando

**Comment by Leizar999** [comment]
Gracias, cierro.
