### ISSUE TITLE
[Misión] Las palabras de desdedida de Lou

### ISSUE THREAD

**Issue by kevinilo** [RoDNet/Bugtracker-Infinium-4.0.6a#1348]
Es la continuacion de "Viviendo la Vida", tienes que espiar a 4 matones que estan detras de la granja, pero no pasa nada:
![image](https://f.cloud.github.com/assets/4630033/654700/0738d16a-d502-11e2-9674-832424261321.png)
http://es.wowhead.com/quest=26232

**Comment by redneo** [comment]
Tendria que funcionar cuando caiga el server, cierra el tracker si es así

**Comment by kevinilo** [comment]
Arreglado
