### ISSUE TITLE
[ Druid > StarFire ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1351]
Fuego estelar: http://es.wowhead.com/spell=2912
El problema principal está en su CastTime, o tiempo de casteo, el cual es muy inferior al que debería ser.

Actualmente se castea base en 2.17 sec, cuando debería ser el cast time de 3.2

Desnudo, Celeridad 0

![wowscrnshot_061413_193223](https://f.cloud.github.com/assets/2728817/655647/878e1dc8-d518-11e2-9714-647e9be9b7d4.jpg)

Casteo en 2.17s de 3.2s

![wowscrnshot_061413_193232](https://f.cloud.github.com/assets/2728817/655648/8ed70cf2-d518-11e2-86de-bd909fa76f5f.jpg)

**Comment by redneo** [comment]
Me parece raro ya que los datos lo coge de los dbc... voy a mirar que me sale...
:s

ID - 2912 Fuego estelar

Description: Inflige $s1 p. de daño Arcano al objetivo.$?s78674[ Genera $s2 p. de energía solar.][]
Category = 0, SpellIconID = 1485, activeIconID = 0, SpellVisual = (1264,0)
Family SPELLFAMILY_DRUID, flag 0x00000000 00000000 00000004

SpellSchoolMask = 64 (MASK_ARCANE)
DamageClass = 1 (SPELL_DAMAGE_CLASS_MAGIC)
PreventionType = 1 (SPELL_PREVENTION_TYPE_SILENCE)

Attributes: 0x00010000 (SPELL_ATTR_NOT_SHAPESHIFT)
AttributesEx2: 0x00080000 (SPELL_ATTR_EX2_NOT_NEED_SHAPESHIFT)
AttributesExG: 0x00010000 (SPELL_ATTR_EXG_UNK16)

Stances Not: FORM_TREE, FORM_MOONKIN
Skill (Id 574) "Equilibrio"
    ReqSkillValue 1, Forward Spell = 0, MinMaxValue (0, 0), CharacterPoints (1, 0)Spell Level = 8, base 8, max 0, maxTarget 0
EquippedItemClass = 0 (CONSUMABLE)

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 5) "Long Range":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 40, MaxRangeFriendly = 40

CastingTime (Id 28) = 3,20

**Comment by DatJetto** [comment]
Intenta ponerle algo más de tiempo de casteo para que se compense :$ la diferencia es de 1,03 sec. Puedes ponerle 4,20 o así para ver si aumenta bien...

**Comment by redneo** [comment]
No puedo acceder a esos datos :S
