### ISSUE TITLE
[ Druid > Starsurge ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#1352]
Oleada de estrellas: http://es.wowhead.com/spell=78674

Esta spell tiene el daño bastante bajo, cuando debería ser la spell más poderosa del druida equilibrio apenas pega 5-7k sin crítico.

---

Junto al Talento Shooting Stars: 
- Rango 1 http://old.wowhead.com/spell=93398
- Rango 2 http://old.wowhead.com/spell=93399

Descripción:

You have a 2/4% chance when you deal damage with your Moonfire or Insect Swarm to instantly reset the cooldown of your Starsurge and reduce its cast time by 100%. Lasts 8 sec.
- El cual debería reiniciar el CD de Oleada de Estrellas y hacer su lanzamiento instantáneo.
  - NO QUITA CD.
  - SI LO HACE INSTANTÁNEO

Spells que activan el Proc: 
- Enjambre de insectos: http://old.wowhead.com/spell=5570
- Fuego lunar : http://es.wowhead.com/spell=8921
  
  Dato: SHOOTING STARS NO TIENE CD INTERNO.

**Comment by redneo** [comment]
El daño ahora esta ajustado (antes tambien lo estaba).

He estado mirando el spell http://old.wowhead.com/spell=93398, efectivamente no quita el cd, tan solo te pone el aura http://old.wowhead.com/spell=93400
