### ISSUE TITLE
[Misión] Desafío de honor

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1353]
Pones la bandera encima los transforma en una espada y en un escudo y no te deja atacarles ni nada.

Aqui dejo el link:http://es.wowhead.com/quest=12939

**Comment by redneo** [comment]
Ya tendria que ir, solo si les llamas con la bandera.

**Comment by Wiinter** [comment]
Arreglada
