### ISSUE TITLE
[Misión] Por donde vinieron

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1356]
No estan los cristales. Nose si es por la fase o que... Es otra misión de los Caballeros de la Espada de Évano de la Cámara de las Sombras

Aqui dejo el link de la quest: http://es.wowhead.com/quest=13171

**Comment by redneo** [comment]
Mision capullita... tienes que accionar los cristales que estan al lado del tipo que da la misión.

Esos cristales, te sumonean un npc (spell 58665) 

Tienes que ir con el fantasma donde los cristales y accionarlos

Esta hecho todo o al menos eso creo (faltaria de meter conditions para que no saliese el gossip de los ojos) cuando caiga el server pruebas.

**Comment by Wiinter** [comment]
El cristal no sumonea ningun fantasma qe te siga ni nada.

**Comment by Wiinter** [comment]
Arreglada
