### ISSUE TITLE
[Misión] El mejor amigo de un no-muerto

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1357]
No estan los canes. Nose si es por la fase o que... Es otra misión de los Caballeros de la Espada de Évano de la Cámara de las Sombras

Aqui está el link: http://es.wowhead.com/quest=13169

**Comment by redneo** [comment]
Esta como la anterior que te he respondido depende de los ojos de dominio. La pruebas cuando caiga...

http://es.wowhead.com/object=193058

**Comment by Wiinter** [comment]
Arreglada
