### ISSUE TITLE
[Misión] El honor es para los blandengues

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1358]
No estan los oteadores inquietos. Nose si es por la fase o que... Es otra misión de los Caballeros de la Espada de Évano de la Cámara de las Sombras

Aqui está el link: http://es.wowhead.com/quest=13170

**Comment by redneo** [comment]
Mas de lo mismo http://es.wowhead.com/object=193058 necesario

**Comment by Wiinter** [comment]
Arreglada
