### ISSUE TITLE
[Misión] El primer experimento de azsharita

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1361]
Se puede conseguir el laxante pero a la hora de hablar del gitante, no puedes.

Aqui dejo el link de la misión: http://es.wowhead.com/quest=14385

**Comment by redneo** [comment]
Arreglada

Como bonustrack la siguiente tambien está arreglada :D

**Comment by Wiinter** [comment]
Arreglada, pero la ultima quest al hablar con el gigante tira el server.

**Comment by Wiinter** [comment]
La ultima tambien funciona bien
