### ISSUE TITLE
Items = BUG

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#1364]
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1309 << relacionado a este post.

> Por casualidad mientras hacia el reporte del post anterior descubri que estos items estan BUG.

![wowscrnshot_061413_132559](https://f.cloud.github.com/assets/2059256/656644/ce1799f4-d531-11e2-86fe-ff6d300a44d7.jpg)

> Ok ANTES Y DESPUES de ponerme el anillo simple.

![wowscrnshot_061413_133524](https://f.cloud.github.com/assets/2059256/656656/2879ec80-d532-11e2-8503-042342064888.jpg)

> DESPUES DE QUITARME el anillo sin cerrar wow y sin reloguear.
- nota: observen que el H. dmg y el H. Crit. regresaron a la normalidad.

---

![wowscrnshot_061413_134025](https://f.cloud.github.com/assets/2059256/656713/0a760f82-d534-11e2-8581-1d8e3057f2be.jpg)

> ese de ahi es solo un item.

![wowscrnshot_061413_135117](https://f.cloud.github.com/assets/2059256/656719/5c805d6e-d534-11e2-849b-a14df4327880.jpg)

> bien ahi muestro los 4 items, y ninguno de ellos funciona.

**ITEMS BUG**

http://es.wowhead.com/item=61958 << cabeza
http://es.wowhead.com/item=42985 << hombro
http://es.wowhead.com/item=62040 << espalda
http://es.wowhead.com/item=48691 << pechera
- ningun de esos que te enliste funciona.

**Comment by redneo** [comment]
Hay alguno más que no funcionaba:
38691,
61931,
61935,
61936,
61937,
61942,
61958,
62023,
62024,
62025,
62026,
62027,
62029,
62038,
62039,
62040

Ahora tendrian que ir (cuando caiga el server).

**Comment by WarSxNes** [comment]
**Houston... We have a Problem...!!!**

![redneo](https://f.cloud.github.com/assets/2059256/658489/966db668-d5e6-11e2-9f84-0c531e74300f.jpg) segun desde tu ultimo comentario ya callo el server.

![wowscrnshot_061513_112943](https://f.cloud.github.com/assets/2059256/658521/b0f433e0-d5eb-11e2-90e1-2be146aa5d32.jpg)

> almenos este ITEM funciona.

---

![wowscrnshot_061513_114607](https://f.cloud.github.com/assets/2059256/658522/0a02a368-d5ec-11e2-84ff-ce9f175b5637.jpg)

Siguen BUG:

http://es.wowhead.com/item=42985 << hombro
http://es.wowhead.com/item=48691 << pechera

> Los otros dos no los confirmo aun por que se supone que conforme subes de nivel se van incrementando los stats de dichos items. Asi que cuando suba de nivel regreso a confirmarlos.

**Comment by redneo** [comment]
42947,
42949,
42950,
42951,
42952,
42984,
42991,
42992,
44092,
44095,
44097,
44098,
44099,
44100,
44101,
44102,
44103,
44105,
44107,
48677,
48683,
48685,
48687,
48689,
48691,
48718,
59526

Arreglados

**Comment by WarSxNes** [comment]
Yeap!!!... confirmado subieron cuando pase al siguiente nivel y cuando los intercambie con mis otros PJs
