### ISSUE TITLE
[Misión] ¡No estoy muerto aún!

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1367]
No deja completar porque el npc que completa la misión no se encuentra. Debería estar en el Martillo de Orgrimm, el barco de la Horda que vuela por Corona de Hielo.

Aqui dejo el link de la misión : http://es.wowhead.com/quest=13229

Diría que faltan muchos npcs en el barco.

**Comment by redneo** [comment]
ya estan todos los npcs del barco, lo cual me lleva a mirar otros transportes...

**Comment by Wiinter** [comment]
Completada
