### ISSUE TITLE
[Mazmorra] Las profundidades de roca negra

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1371]
El bug consiste en que cuando llegas a el Lyceum, que es una antesala que da al jefe final, hay que conseguir unas antorchas para encender unas hogueras, las antorchas las da:
( vigilante de las llamas de forjatiniebla: http://es.wowhead.com/npc=9956 ) un enano vestido de rojo, con espada y escudo que suele aparecer en el centro, este NPC no da esa antorcha con lo cual no se pueden encender las hogueras y llegar al final de la mazmorra ni conseguir el logro.

http://es.wowhead.com/item=11885#comments

Gracias.

**Comment by redneo** [comment]
Ya lo suelta al 100%

**Comment by Leizar999** [comment]
Gracias, cierro.
