### ISSUE TITLE
[Misión] Creo que tiene hambre

### ISSUE THREAD

**Issue by kevinilo** [RoDNet/Bugtracker-Infinium-4.0.6a#1376]
Tienes que dar de comer a la prole del cazalote, la cual la puedes invocar con un objeto.
No se si los basiliscos me tienen que soltar trozos de carne o el mismo se los come, el caso es que no pasa ninguna de las 2 cosas.
![image](https://f.cloud.github.com/assets/4630033/659404/1d53d3e6-d692-11e2-8fe0-7cacf9f6ae75.png)

http://es.wowhead.com/quest=26739

**Comment by redneo** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1291?source=cc
