### ISSUE TITLE
[Misión] Pro liberación

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1391]
Abres las jaulas para liberarlos pero no ocurre nada.

Aqui te dejo el link de la quest: http://es.wowhead.com/quest=14297

**Comment by redneo** [comment]
arreglado

**Comment by Wiinter** [comment]
Cuando abres las jaulas, tiras el server.

**Comment by redneo** [comment]
Creo que ya no tendria.

**Comment by Wiinter** [comment]
Arreglada
