### ISSUE TITLE
[Misión] El Pináculo del aprendizaje

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1395]
No esta el npc para completar la quest.

Aqui dejo el link: http://es.wowhead.com/quest=14413

Además que falta el otro npc del alto de esa montaña que empieza la quest, http://es.wowhead.com/quest=14300

**Comment by redneo** [comment]
Puesto el npc

**Comment by Wiinter** [comment]
Arreglada
