### ISSUE TITLE
[Misión] La traición a los Faucenegra

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#1397]
Te transformas, vas a hablar con el lider de los Faucenegra, pero no puedes hablar con él, no sale nada.

Aqui dejo el link: http://es.wowhead.com/quest=14435

**Comment by redneo** [comment]
Ya puedes hablar con él.

**Comment by Wiinter** [comment]
Arreglada
