### ISSUE TITLE
[NPC] Corruptor Vil

### ISSUE THREAD

**Issue by Velcositro** [RoDNet/Bugtracker-Infinium-4.0.6a#1398]
NPC: es.wowhead.com/npc=21300

Bug: Deberían soltar el objeto Máscara dañada (http://es.wowhead.com/item=31384) que empieza una misión, he matado unos 50 de ellos y ninguno me lo ha dado.

**Comment by redneo** [comment]
Aunque ahora mismo no puedo acceder a wowhead, cuando caiga el server tendria que soltarlo

**Comment by Velcositro** [comment]
Si lo sueltan, gracias por arreglarlo tan rápido.
