### ISSUE TITLE
[Paladin Represion > Daño muy bajo]

### ISSUE THREAD

**Issue by awsawsaws** [RoDNet/Bugtracker-Infinium-4.0.6a#140]
El paladin despues del cambio de core sufrio una baja de daño considerable en todas sus spell,  golpeando un muñeco de entrenamiento no logro sacar mas de 30k, que  solamente logro con una macro

aqui un video de prueba
http://youtu.be/fnZdKYH23SA

estas son las spell

Sentencia: http://es.wowhead.com/spell=20271

Exorcismo: http://es.wowhead.com/spell=879

Veredicto Templario: http://es.wowhead.com/spell=85256

Martillo de Colera : http://es.wowhead.com/spell=24275

Golpe Cruzado : http://es.wowhead.com/spell=35395

La macro que utilizo es la siguiente

Furia de Forjainquina http://es.wowhead.com/item=59461

Cólera Vengativa : http://es.wowhead.com/spell=31884

Guardián de Los Antiguos Reyes: http://es.wowhead.com/spell=86698

Distintivo de Victoria de Gladiador Sanguinario: http://es.wowhead.com/item=64689

Inquisición: http://es.wowhead.com/spell=84963

 En el video no se activa ni Inquisición ni el Distintivo de Gladiador Sanguinario por eso no logro
los 30k que mencione que lograba sacar, pero activandose todo eso logro sacar los 30 k.

 Espero sirvan estos datos me tomo un buen rato hacerlo.

**Comment by HexR-zz** [comment]
Po ya verá las piñas que vas a meter en la siguiente actualización machote, vas a llorar de la emoción
