### ISSUE TITLE
[Quest>Horde] 447

### ISSUE THREAD

**Issue by Navalagamella** [RoDNet/Bugtracker-Infinium-4.0.6a#1406]
Es una quest en la zona de inicio de los goblins, puedes completar todos los objetivos, pero en el último cuando el robot Gastbot entra al edificio en llamas, no arde y no deja completar la misión. 
Es algo muy molesto debido a que si no completas esta quest, no puedes continuar y quedas atrapado en Kezan.
http://es.wowhead.com/quest=14125/447

**Comment by redneo** [comment]
Ahora a mi me la ha completado, testadlo por favor a ver si es así

**Comment by Navalagamella** [comment]
Pues si, esta mañana mismo he intentado completarla y si, ha funcionado.

**Comment by redneo** [comment]
Si está bien, cierra el ticket por favor!
