### ISSUE TITLE
Problema Al recojer Items

### ISSUE THREAD

**Issue by nagatto123** [RoDNet/Bugtracker-Infinium-4.0.6a#143]
cuando intento recojer algun item mi presonaje se quea como trabado solo queda agachado y no muestra la ventana de item que recoji ni nada es un problema por que para muchas misiones tengo que recojer cosas ayua pls!!!

**Comment by searum** [comment]
descarga esto http://downloads.reignofdarkness.net/cataclysm/ReignOfDarkness.exe

lo metes en la carpeta del wow e inicias el wow con ello.
