### ISSUE TITLE
Bug en Guarida de Alanegra, la mazmorra es una zona fantasma.

### ISSUE THREAD

**Issue by Kantiano** [RoDNet/Bugtracker-Infinium-4.0.6a#144]
Buenas, mi nombre es Kantiano, el jueves día 22 de Noviembre, a las 6:25 Pm ( hora española ), hice la mazmorra de Lvl 60 Guarida de Alanegra, el objetivo era conseguir el set Tíer 2 y coleccionarlo, pues considero que las T2 son las armaduras mas bonitas del WoW. Entre en la Mazmorra y me llevo la sorpresa de que no hay ni mobs y tampoco están los  Bosses.

Adjunto imágenes:

<p><img src="http://img5.imageshack.us/img5/8465/wowscrnshot112212172029.jpg" alt="wowscrnshot112212172029.jpg" /></p>

<p><img src="http://img526.imageshack.us/img526/8198/wowscrnshot112212172031.jpg" alt="wowscrnshot112212172031.jpg" /></p>

<p><img src="http://img38.imageshack.us/img38/5231/wowscrnshot112212172051.jpg" alt="wowscrnshot112212172051.jpg" /></p>

P.D. Me gustaría si es posible una solución, pues es una Mazmorra muy bonita que da la Tíer 2 y encima puedes matar a Nefariant el hijo de Alamuerte. 

Gracias por la atención. 

ATT: Kantiano.

**Comment by searum** [comment]
Instance spawneada. cierro issue
