### ISSUE TITLE
[Mision > Alianza > Luchando por respirar]

### ISSUE THREAD

**Issue by Filoloco91** [RoDNet/Bugtracker-Infinium-4.0.6a#145]
Al intentar interactuar con los hombres hundidos no hace nada el personaje, aunque aparece que quedan 3 minutos para subir y salvarlos. Al llegar fuera de la orilla ese estado se quita y no ocurre nada. 

Link de la misión: http://es.wowhead.com/quest=14395#comments

**Comment by Arkale** [comment]
A mí me pasa lo mismo. Es en la zona de los huargen. Cuando regresas a la orilla, desaparece la pegatina pero no te cuentan como rescatados.

<p><img src="http://img607.imageshack.us/img607/493/wowscrnshot112312115328.jpg" alt="wowscrnshot112312115328.jpg" /></p>

**Comment by searum** [comment]
este issue ya esta cerrado para la siguiente rev!
