### ISSUE TITLE
[Monedero de campeón] 

### ISSUE THREAD

**Issue by hell37** [RoDNet/Bugtracker-Infinium-4.0.6a#1457]
al cobrar la recompensa de este objeto http://es.wowhead.com/item=45724 al abrir la recompensa, los primeros 3 días no me dio nada, ni oro ni tampoco sellos de campeón, http://es.wowhead.com/currency=241, al 4 día ya me dio un sello de campeón pero, el sello de campeón apareció en la bolsa de inventario en vez de la pestaña de monedas junto con las demás

![wowscrnshot_062313_133008](https://f.cloud.github.com/assets/4789611/692582/c355c252-dc34-11e2-8aff-8a9a5abe9e8c.jpg)

**Comment by DatJetto** [comment]
No se añade como currency , sino como un objeto normal (?)

**Comment by hell37** [comment]
Así es como lo muestra la imagen, se debería añadir en la pestaña de monedas con las demás, en cambio apareció en la mochila

**Comment by WarSxNes** [comment]
Puedo hacer una pregunta? por que cerraron el post?

Si no ha sido reparado xD..... Ademas ya lo habia reportado yo hace como 1 mes vean https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/1171 <<< ahi trato de convencer a redneo haber se los puede arreglar pero dice que no puede... y bueno no quedo de otra que cerrar el hilo ._.

> POR CIERTO: quien esta ahora de moderador aqui? llevo dias sin ver alguna respuesta de algun moderador.... 
> acaso la gente esta reportando en vano o.0?
