### ISSUE TITLE
[Hunter > Spec: Marksmanship > Spell > Aimed shot - proc - Fire!]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#146]
Spell Aimed shot con Fire!

[IMG]http://i49.tinypic.com/344azr8.jpg[/IMG]

Al saltar el proc de 5 stacks [Fire!] Disparo de puntería se Castea Andando (?) como se puede comprobar en la imagen debiendo ser instantáneo, la semana pasada se le aplicó un arreglo el cual hacía lo que debía, no se por qué ahora se castea. 

Fire!: http://es.wowhead.com/spell=82926
Aimed shot: http://es.wowhead.com/spell=19434
Aimed shot instantáneo: http://www.wowhead.com/spell=82928

http://i49.tinypic.com/344azr8.jpg

**Comment by searum** [comment]
fixed!
