### ISSUE TITLE
[Hunter > Spec: Marksmanship > Spell > Improved Steady Shot & Termination]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#147]
Improved Steady Shot: http://www.wowhead.com/spell=53224
Termination: http://old.wowhead.com/spell=83489

http://i45.tinypic.com/2zhjlgi.jpg

Cada disparo firme activa Disparo firme mejorado con un aumento de un 0% de celeridad en el aura ( debería ser 15% y activarse cada 2 Disparos Firmes Seguidos.)

La celeridad al parecer es pasiva, solo al activar el talento ya el tiempo de lanzamiento de todos los casteos baja. 

Termination: http://old.wowhead.com/spell=83490

en Disparo firme http://www.wowhead.com/spell=56641 restaura 15p. todo el tiempo pudiendo estar al enemigo al 100% de su salud. 
Cobra shot funciona correctamente, restaura 15p. de foco al estar al 25% o menos.

**Comment by searum** [comment]
fix
