### ISSUE TITLE
[Misión] Dragona, desencadenada

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#1475]
Misión: Dragona, desencadenada
http://es.wowhead.com/quest=27701

Usa el hacha de elementium para romper las cadenas que atan a Lirastrasza.

```
Lirastrasza liberada
```

Objeto provisto:
    El hacha de elementium

Problema: Intento liberar a la dragona con el hacha pero no la libera.

Si a alguien le funciona actualmente que lo comente porfavor.

Video del correcto funcionamiento http://www.youtube.com/watch?v=qkdTp-8MQzQ

Un saludo,

**Comment by ghost** [comment]
Clic derecho para hablar con la dragona... y misión completada.

**Comment by crowel** [comment]
Cierto es, gracias Lv, yo mandandome a dark decenas de clicks alrededor de la dragona con el objeto jajaj.
Un saludo.
