### ISSUE TITLE
Bug mision: Evacua la plaza de los Mercaderes

### ISSUE THREAD

**Issue by frustrix** [RoDNet/Bugtracker-Infinium-4.0.6a#1486]
La mision consiste en abrir 3 puertas y sacar unos aldeanos pero todas las puertas estan abiertas y no se puede hacer lo cual hace que no podamos jugar porque no avanzas ya que no hay mas misiones

Personaje: Frustrix
Hora 18:14
Clase: Huargen
Zona: Plaza de los mercaderes

**Comment by DatJetto** [comment]
Esto... acércate a la puerta y clícala, seguro que si podrás
