### ISSUE TITLE
[Shaman > Spec: Elemental > Overdamage]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#149]
http://i46.tinypic.com/2eowkno.jpg

Mi personaje tiene 3193 de temple > 33.53% reducción de daño a los jugadores

Y los chamanes verdecitos , como este, sin set pvp y tampoco pve avanzado dado que con bufos tiene 90k de maná ( poco ) me está pegando de 30k con sus spells ( demasiado )

Ruego revisen el daño de 
http://es.wowhead.com/spell=421
http://es.wowhead.com/spell=51505
http://es.wowhead.com/spell=403
http://es.wowhead.com/spell=8050

Ya que hacen demasiado daño almenos las 3 primeras. No dispongo de chamán para testear dicho daño pero por los duelos y arenas estas spells son las más significativas. 

Edit: 7/12/2012

Talentos que puedan aplicar más daño de lo debido: 
Chamanismo
*http://old.wowhead.com/spell=62099
Furia Elemental
*http://old.wowhead.com/spell=60188
Maestría elemental
*http://old.wowhead.com/spell=16166
Llamada de las llamas
*http://old.wowhead.com/spell=16160
Precisión Elemental
*http://old.wowhead.com/spell=30674
Flujos de Lava
*http://old.wowhead.com/spell=51482

**Comment by HexR-zz** [comment]
A ver si algún chamán se anima a reportar algo.

**Comment by DatJetto** [comment]
No reportan porque les gusta ser Op :camel: y hacer pvp desequilibrado y hacer raid solos :3

**Comment by asfo** [comment]
¿Ya checaste también los talentos y todo eso?, luego hacen muchos favores talentos, trinkets y demás cosillas extras...En el oficial un chaman elemental te tumba en 5 segundos por su Lava Burst y el Electro Shock o algo así, la verdad no recuerdo los nombres, pero mi ex compañero de arenas en Cataclysm hacía muchísimo daño y no estaba muy armado realmente...

**Comment by HexR-zz** [comment]
Aparentemente sí tienen un daño exagerado, a continuación pongo un link a un vídeo de un chamán muy bien equipado (llega hasta 40% de reducción de daño por temple.7200 de daño de hechizo) y que como dice en el vídeo enseña sus críticos más altos. Comparando un issue anterior que subió smoke, un chamán le pego 55k con ráfaga de lava con un equipo más bajo que el del vídeo. Por lo tanto sí que habría que revisar el daño de sus hechizos ofensivos, al menos ráfaga de lava. Por otra parte en el vídeo tiene 122k de vida que sin buffs será más o menos 118k de vida, mientras que en la foto addonexus tiene 102k. Es decir, la diferencia de equipo es muy significativa, el chamán del vídeo saca como mucho 34k y los demás críticos por debajo de la marca de los 30k, mientras que addonexus saca 30k con un equipo más bajo a uno con 33% de reducción de daño.  Estaría bien que subieseis fotos de los demás hechizos ofensivos para comparar con el vídeo. 

Edito y añado otro detalle más:
En el segundo 31 del vídeo comienza una pelea con un guerrero que tiene 105k de vida, es decir, su equipo es bajísimo (algunas piezas sanguinarias: 1 set y 2-3 offset) por lo tanto su temple también es bajísimo, como mucho tendrá un 10-12% reducción de daño por temple. Aún así con esa poca reducción, el chamán del vídeo no supera los 30k con él. Sin embargo en la foto se ve claro que se llega a 30k con 33% de reducción de daño.

http://www.youtube.com/watch?v=sJWlQ0ovthM

**Comment by DatJetto** [comment]
Adonnexus en ese momento no llevaba temple :C ni set, tenía unos 80k de maná ( una basura ) sin bufos y con sus bufos de intelecto de abalorios 90, frente a mis 135k de vida y 33% de temple, a un verdecito le saca 70k xD

**Comment by HexR-zz** [comment]
En efecto. Si puedes poner datos de otros hechizos ayudaría para tener más información

**Comment by Dekadencee** [comment]
Daños corregidos por Hex satisfactoriamente, en la próxima revisión serán aplicados
