### ISSUE TITLE
[Hunter > Spec: Marksmanship > Spell > Chimera Shot]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#15]
-Disparo de quimera  ( Reinicia serpiente y te cura un 5% de tu salud total )
http://es.wowhead.com/spell=53209
Bug: Daño bajo / Cura de más

Fórmula correcta: 100% Ranged Weapon + (RAP*0.752) +1680

**Comment by adrianrp1988** [comment]
Reparado en la próxima rev
