### ISSUE TITLE
[Arenas > Cloacas de Dalaran]

### ISSUE THREAD

**Issue by HexR-zz** [RoDNet/Bugtracker-Infinium-4.0.6a#150]
Al empezar el enfrentamiento, si un jugador se queda arriba, inmóvil, no funciona el push/knowback para que baje y permita que se acabe el combate.

**Comment by asfo** [comment]
I know how to fix that xD...Haha :P si me uno a RoD se los arreglo >__<

**Comment by HexR-zz** [comment]
Sería todo un placer ;D!

**Comment by searum** [comment]
mañana lo miro, que he estado haciendo bosses estos dias

**Comment by searum** [comment]
fix
