### ISSUE TITLE
[Misión] El ancestro Mana'loa

### ISSUE THREAD

**Issue by Leizar999** [RoDNet/Bugtracker-Infinium-4.0.6a#1518]
Tienes que ir a hablar con una piedra que hay mas allá de donde te dan la misión, el tema es que por mucho que pulses no te da la opción para completar la misión.

http://es.wowhead.com/quest=12030

Gracias.

**Comment by lamaza** [comment]
aqui no se reporta nada mas man. Ve al bugtracker 4.3.4

**Comment by Leizar999** [comment]
Ya podían corregir el enlace en la web, minimo eso ya que la gente se molesta en reportar :(
