### ISSUE TITLE
bug mineria

### ISSUE THREAD

**Issue by coste23** [RoDNet/Bugtracker-Infinium-4.0.6a#152]
cuando se farmea mineria cada 1 de 6 mineadas da un punto y tengo por entendido que cada mineada da de a punto si pueden hacer el favor de rebizar si hay algun error de datos. gracias

**Comment by DatJetto** [comment]
Eso no es así :c depende de la calidad del objeto respecto a tu nivel, si está en calidad verde subirá pocas veces pero en Amarillo y Naranja sube siempre o casi siempre.
