### ISSUE TITLE
bug arqueologia 

### ISSUE THREAD

**Issue by coste23** [RoDNet/Bugtracker-Infinium-4.0.6a#153]
pueden poner en funcionamiento arqueologia ya que no lo esta y las excavaciones no aparecen en el mapa. gracias.

**Comment by Dekadencee** [comment]
Estamos programando totalmente la profesión, estará disponible dentro de poco y totalmente blizzlike.

Un saludo ^^

**Comment by Dekadencee** [comment]
La tenemos actualmente programada a un 80% nos faltan pocos detalles, hoy o los siguientes dias cercanos, la terminaremos y la implementaremos.

**Comment by searum** [comment]
ya la ha arreglado deka ! ale closed
