### ISSUE TITLE
Bug, El abalorio de Forjainquina no funciona correctamente.

### ISSUE THREAD

**Issue by Kantiano** [RoDNet/Bugtracker-Infinium-4.0.6a#156]
Hola buenas. El bug del <p><a href="http://es.wowhead.com/item=59461/furia-de-forjainquina">Furia de Forjainquina</a></p> es el siguiente:

<p><img src="http://img696.imageshack.us/img696/2932/wowscrnshot112412034650.jpg" alt="wowscrnshot112412034650.jpg" /></p>

<p><img src="http://img705.imageshack.us/img705/2056/wowscrnshot112412034657.jpg" alt="wowscrnshot112412034657.jpg" /></p>

Como se puede apreciar en las imágenes, el tiempo de reutilización  es de 2 minutos, sin embargo lo amplia a 5 minutos.

Agradecería una posible solución. Muchas gracias por la atención.

**Comment by HexR-zz** [comment]
Además, se puede activar independientemente de las cargas que tengas, a pesar de que necesite 5 cargas para poder activarse.

**Comment by HexR-zz** [comment]
ya se arreglo creo
