### ISSUE TITLE
Algunos bugs en Templo Oscuro

### ISSUE THREAD

**Issue by Arkale** [RoDNet/Bugtracker-Infinium-4.0.6a#158]
Cuando matas a Sombra de Akama (http://es.wowhead.com/npc=22841) la puerta queda cerrada. Adjunto imágenes:

<p><img src="http://img266.imageshack.us/img266/6818/wowscrnshot112712223822.jpg" alt="wowscrnshot112712223822.jpg" /></p>

<p><img src="http://img707.imageshack.us/img707/16/wowscrnshot112712223826.jpg" alt="wowscrnshot112712223826.jpg" /></p>

Supongo que por esta razón no se puede acceder a Madre Shahraz, Consejo e Illidan.

Por otro lado Esencia Inquina (http://es.wowhead.com/npc=23420) ni se inmuta cuando nos acercamos. Por ahora no hemos encontrado nada más en Templo Oscuro. Espero haberos podido ayudar con el reporte. Un saludo.

**Comment by searum** [comment]
funciona perfectamente, iniciasteis el evento con akama? akama se mueve a la posicion una vez muerta la sombra y te abre la puerta xD

**Comment by HexR-zz** [comment]
Según tengo entendido la mitad de su banda se quedó fuera. Aún así, al parecer, incluso hablando con Akama, había 3-4 NPCs(de los que rodean a la sombra) que no se podían matar, no sé si a ti te habrá pasado lo mismo. Si no, fue problema de esa banda
