### ISSUE TITLE
Bug talento Sacerdote Shadow

### ISSUE THREAD

**Issue by Britanico** [RoDNet/Bugtracker-Infinium-4.0.6a#159]
Buen día,

Lo que sucede es lo siguiente:

El talento Masoquismo del sacer sombra esta bug ya que al utilizarlo el sacer sufre daño con palabra de las sombra: muerte, pero no recupera el mana según lo que dice el talento mencionado, acontinuación les dejo las evidencias de lo anterior dicho:

http://www.subirimagenes.com/otros-wowscrnshot112812105-8150807.html
http://www.subirimagenes.com/otros-wowscrnshot112812105-8150810.html
http://www.subirimagenes.com/otros-wowscrnshot112812105-8150812.html
http://www.subirimagenes.com/otros-wowscrnshot112812105-8150814.html

**Comment by searum** [comment]
fix
