### ISSUE TITLE
[Hunter > Gliphs > Mortal Shot ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#16]
Glifo de disparo mortal:  Si Disparo mortal no mata al objetivo, el tiempo de reutilización se reinicia instantáneamente pero no se puede reiniciar más de una vez cada 6 s.

http://es.wowhead.com/item=45732
Bug: No se reinicia el tiempo de reutilización si el objetivo no muere.

**Comment by aerz** [comment]
Gracias por el reporte, faltaba el script completo del glifo.
Implementado en el reino de pruebas y reparado.

Cierro reporte.
