### ISSUE TITLE
Talento Béstias exóticas Cazador Bestias

### ISSUE THREAD

**Issue by Fumapasto** [RoDNet/Bugtracker-Infinium-4.0.6a#162]
El talento béstias exóticas no funciona correctamente ya que mi personaje fumayerba de nivel 85 cazador de rama bestias no es capaz de domar muchas bestias que se suponen domables al tener este talento, como el rinoceronte.

**Comment by HexR-zz** [comment]
Has probado a domar otra bestia exótica que no sea ese rinoceronte? Puedes poner un link a wowhead del rinoceronte al que intentas domar? Gracias por reportar

**Comment by DatJetto** [comment]
Si que se pueden domar rinocerontes, yo tengo uno.
