### ISSUE TITLE
posible crash

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.0.6a#164]
echar un vistazo a magueridon parece que crashea el server,los mobs de la mazmorra tienen 35 puntos de vida.hemos echo 2 intentos i dos desconexiones,las desconexiones no han sido al matar el boss quiza sea alguna habilidad del boss,

**Comment by DatJetto** [comment]
Adjunta Id  de los npc o algo :camel:

**Comment by Dekadencee** [comment]
Crash confirmado, muchísimas gracias por el reporte nos pondremos con ello lo antes posible, el crash es al castear uno de sus hechizos.

Un saludo ^^

**Comment by searum** [comment]
creo que ya esta solucionado! xD
