### ISSUE TITLE
[MISIÓN] "Ways of the Light" (Elfo de la Sangre - Paladin)

### ISSUE THREAD

**Issue by Izeltzu** [RoDNet/Bugtracker-Infinium-4.0.6a#167]
Hoy me he creado un Elfo de la Sangre Paladín, y en la misión de aprender "Sello de Rectitud" y practicarlo, lo he aprendido y usado pero el marcador no sube, se que no es muy grave pero lo digo para que lo sepáis.

 Salu2 Izeltzu :)

**Comment by Izeltzu** [comment]
Bueno, estuve mirando y lo que dice la quest con lo que hay que hacer no es que coincidan pero ya la logre completar.

**Comment by HexR-zz** [comment]
Tienes instalado el parche que está en la web, en una de las noticias?

**Comment by Izeltzu** [comment]
No, no, si ya lo solucione. Pero gracias, si lo tenia instalado.
