### ISSUE TITLE
Gran dentosangre

### ISSUE THREAD

**Issue by Faked** [RoDNet/Bugtracker-Infinium-4.0.6a#169]
Tiene una espada muy chula, pero, que no debería lleva xD

es.wowhead.com/npc=547/gran-dentosangre

[IMG]http://i46.tinypic.com/11iipud.jpg[/IMG]

**Comment by HexR-zz** [comment]
Jajajaja mira qué chulo va el puerco jajaja

**Comment by DatJetto** [comment]
JAJAJJAJA irua el cochino to op con sus espaditas

**Comment by searum** [comment]
a mi me mola que tengan espada... no la quite por eso xd

**Comment by Walkum** [comment]
xDDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by Dekadencee** [comment]
Solucionado
