### ISSUE TITLE
[Druida- > Restauracion - > forma de arbol

### ISSUE THREAD

**Issue by k4b3z0n** [RoDNet/Bugtracker-Infinium-4.0.6a#17]
.

**Comment by searum** [comment]
Necesito mas datos, no juego y no se que spells son las que se dan como instant ni nada... si pudieras.. :)

**Comment by searum** [comment]
esta bien, no te aumenta un 120% a lo q tu tengas, si tienes 20k de armor no te va a dar un 120% sumado a esos 20k.. ni un tanke de pandaria lo tiene asi. XD
