### ISSUE TITLE
bug talentos picaro

### ISSUE THREAD

**Issue by coste23** [RoDNet/Bugtracker-Infinium-4.0.6a#170]
buenas por favor rebizar cada uno de los talentos del picaro estan bug  algunos capa de la sombra no quita los daños , ultima llave cuando se activa me hago daño con 361 puntos cada 1 segundo.

**Comment by HexR-zz** [comment]
No podemos revisar 1 por 1 los talentos del pícaro, tienes que decirnoslo tú, comprueba in-game con alguien cuáles son los talentos que funcionan y cuáles no. Con 3 llave me imagino que te refieres a la rama de talentos que está más a la derecha no?

**Comment by Dekadencee** [comment]
Cerrado por insuficiencia de información, trata de hacer los reportes más completos especificando las spells
