### ISSUE TITLE
bug talentos del paladin 

### ISSUE THREAD

**Issue by coste23** [RoDNet/Bugtracker-Infinium-4.0.6a#171]
los talentos del paladin la gran mayoria estan bug poder de ataque esta muy reducido. rebizar uno por uno en cada una de las ramas.

**Comment by HexR-zz** [comment]
No podemos revisar 1 por 1 los talentos del paladín, como te h dicho en el otro reporte. Comprueba con alguien in-game cuáles funcionan y cuáles no y nos lo pones aquí, a nosotros nos encantaría devolverle al paladín la fuerza que siempre ha tenido, pero teneís que decirnos qué le falla

**Comment by asfo** [comment]
El paladín su poder de ataque se redujo, hasta en el oficial le hicieron un nerf al poder de ataque ;)...Deberías checar bien todo :D

**Comment by Dekadencee** [comment]
Cerrado por insuficiencia de información, trata de hacer los reportes más completos especificando las spells
