### ISSUE TITLE
[Vendedores > Devolución]

### ISSUE THREAD

**Issue by HexR-zz** [RoDNet/Bugtracker-Infinium-4.0.6a#176]
Los objetos PvP al venderlos de nuevo al vendedor no te devuelve el honor que te ha costado. Además, creo que provoca wowError (digo 'creo' porque he vendido 3 objetos, el último me ha saltado wowError, el objeto era Runa de Deber http://es.wowhead.com/item=21568)

**Comment by Dekadencee** [comment]
Fixed!
