### ISSUE TITLE
[Npc - Items Hermandad

### ISSUE THREAD

**Issue by k4b3z0n** [RoDNet/Bugtracker-Infinium-4.0.6a#18]
.

**Comment by macols77** [comment]
Los items que aparece en wowhead son los que de verdad vende o ha cambiado en pandarian?

Un saludo

**Comment by k4b3z0n** [comment]
son los que realmente vende phantons, si te fijas solo son hasta lvl 85, la cuestión es que es difícil sacarlos xd porque la mayoría pide lvl 20 de hermandad. por cierto como has estado? xd tanto tiempo

**Comment by macols77** [comment]
He estado y estoy estudiando, pero cada vez encuentro mas tiempo para meterme (sera que me organizo mejor jeje) asi que espero que me veais mas a partir de ahora.

Gracias por reportar  :)

P.D: por cierto, quien eres? Uu
