### ISSUE TITLE
Bug, la habilidad de Ozruk Escudo de púas de elementium no funciona correctamente.

### ISSUE THREAD

**Issue by Kantiano** [RoDNet/Bugtracker-Infinium-4.0.6a#180]
Buenas, los EnaJenaDoS intentamos hacer la mazmorra heroica El Nucleo Petreo, cuando llegamos al boss Ozruk, el enfrentamiento fue bien, pero uso la habilidad Escudo de púas de elementium y aplico un daño instantáneo de 200 k, volvimos a repetir para comprobar si hicimos algo mal en el encuentro pero la segunda vez aplico un daño instantáneo de 198 k de daño.

Adjunto Link del boss y de la habilidad:

http://es.wowhead.com/npc=42188

http://es.wowhead.com/spell=78835

Adjunto imagen :

<p><img src="http://img203.imageshack.us/img203/9779/wowscrnshot120112180031.jpg" alt="wowscrnshot120112180031.jpg" /></p>

<p><img src="http://img515.imageshack.us/img515/3533/wowscrnshot120112180118.jpg" alt="wowscrnshot120112180118.jpg" /></p>

P.D. Espero que esta información este completa y ayude, a lo mejor puedo estar equivocado y ese es el daño real que hace, pero tengo mis dudas. Gracias por la atención ^^.

ATT: Kantiano.

**Comment by DatJetto** [comment]
Se supone por lo que he leido que te hace daño solo al atacar a Orzuk y es stackeable x5 haciendo 600 per stack, pero creo que lo que os tiró fue http://es.wowhead.com/spell=78807 Trizar que eso si hace daño y la cosa es alejarse mucho, son 3 sec de cast, da tiempo a alejarse supongo :camel:

**Comment by Dekadencee** [comment]
Efectivamente como Jetto especifica, el hechizo que se corresponde con el daño que reportas es Trizar (http://es.wowhead.com/spell=78807) que efectivamente infringe de 188500 a 211500 p. de daño a todos los enemigos en un radio de 15 m.

Es decir, es totalmente normal que se produzca ese daño por lo tanto cierro issue.

Nobstante gracias por el reporte y agradezco a la guild EnaJenaDoS el trabajo que estais haciendo jugando raids y reportando los bugs de las mazmorras.

Un saludo ^^
