### ISSUE TITLE
OVER y NERF del Guerrero

### ISSUE THREAD

**Issue by Skullex7595** [RoDNet/Bugtracker-Infinium-4.0.6a#183]
Bueno aquí traigo unas fotos que demuestran que algunas habilidades están Nerf ( por decir la mayoría de skill) y alguna Over.

Habilidades sin Talentos

Embate
Esta un poco nerfeada pero por lo menos pongo fotos de como es el daño medio de esa habilidad ( su mínimo y máximo) que también demuestra la media de su crítico. También os quiero decir que todas las fotos no son iguales (grito de batalla) para que veáis que no es por el addon que tengo que también calcula todas tus estadísticas.
http://imageshack.us/photo/my-images/10/wowscrnshot120812090901.jpg/
http://imageshack.us/photo/my-images/96/wowscrnshot120812091437.jpg/
http://imageshack.us/photo/my-images/855/wowscrnshot120812091442.jpg/
http://imageshack.us/photo/my-images/22/wowscrnshot120812091452.jpg/
http://imageshack.us/photo/my-images/13/wowscrnshot120812091504.jpg/

Desgarrar
Este DoT como la anterior esta un poco nerfeada pero también hay un problema es que desgarrar tiene que tener siempre 1 tick crítico en 1 un debuff vamos que de 6 tick 1 debe ser crítico (algunas veces no sale).
http://imageshack.us/photo/my-images/809/wowscrnshot120812091015.jpg/
http://imageshack.us/photo/my-images/593/wowscrnshot120812091527.jpg/
http://imageshack.us/photo/my-images/593/wowscrnshot120812091713.jpg/

Atronar
Esta habilidad si que esta muy nerfeada ya que lo podéis ver vosotros mismo no llega ni a la zuela de los zapatos de la media que pone.
http://imageshack.us/photo/my-images/823/wowscrnshot120812091001.jpg/
http://imageshack.us/photo/my-images/401/wowscrnshot120812091721.jpg/

Golpe Heroico
El Golpe Heroico es una habilidad que pega pero aquí esta por lo menos de 1k de daño menos.
http://imageshack.us/photo/my-images/72/wowscrnshot120812091100.jpg/
http://imageshack.us/photo/my-images/839/wowscrnshot120812091729.jpg/

Lanzamiento Heroico
El Lanzamiento es muy necesario para seguir un buen DPS si tu objetivo se te escapa pero esta un poco nerfeadilla.
http://imageshack.us/photo/my-images/209/wowscrnshot120812090944.jpg/
http://imageshack.us/photo/my-images/62/wowscrnshot120812091736.jpg/

Machaque Colosal
Nueva habilidad que implementaron en el cata esta un poquito subida pero que muy poquito por no decir que esta muy equilibrada. Pero por si acaso os dejo el daño medio que debería de hacer comparandolo con mi equipo.
http://imageshack.us/photo/my-images/541/wowscrnshot120812091024.jpg/
http://imageshack.us/photo/my-images/338/wowscrnshot120812091741.jpg/
http://imageshack.us/photo/my-images/819/wowscrnshot120812091802.jpg/

Lanzamiento Destrozador
También esta Nerf esta habilidad pero la usaran mas para quitar inmunes así que con esta no tengan prisas.
http://imageshack.us/photo/my-images/822/wowscrnshot120812100747.jpg/
http://imageshack.us/photo/my-images/845/wowscrnshot120812091836.jpg/

Torbellino
La habilidad más preciada del guerrero en la expansión WOTLK ahora en el cata nerfeada y aquí un poquito más.
http://imageshack.us/photo/my-images/404/wowscrnshot120812091143.jpg/
http://imageshack.us/photo/my-images/831/wowscrnshot120812091907.jpg/

Rajar
Un poco de lo mismo que lo demás.
http://imageshack.us/photo/my-images/843/wowscrnshot120812091157.jpg/
http://imageshack.us/photo/my-images/254/wowscrnshot120812091920.jpg/

**Comment by HexR-zz** [comment]
Muchísimas gracias. Así es como se hace un reporte :D!

**Comment by Faked** [comment]
Pero estas testeando con equipo, has calculado el AP que te otorga dicho equipo?

**Comment by HexR-zz** [comment]
Lo debe calcular el AddOn directamente, tendrá la fórmula del daño y con ponerle los stats ya te lo saca ajustadito.

**Comment by asfo** [comment]
HexR te recuerdo, los AddOns calculan de forma en la que no es 100% seguro.

Sinceramente, en el oficial, un warrior dependía mucho de si usaba bien sus gemas en combinación a los talentos...Yo apenas pueda ;) me conectaré ya al servidor para si es posible, ayudar en las reparaciones :P y probar todo :D...Aparte claro, de mi área en la web :D...

Mientras tanto, analiza bien la situación de las gemas + talentos + equipo + glifos sin el AddOn y trata de checar si va de la mano...

**Comment by DatJetto** [comment]
En la descripción de Desgarrar no especifica que tenga que tener un tick crítico :c no se de dnde sacas eso , prueba otras spell como Ataque de la victoria y cosas así que creo que curan más o pegan demasiado.

**Comment by HexR-zz** [comment]
La cura de ataque de victoria va bien, el daño no, de tener que pegar 9k pega 3.7k (Desde el PJ que lo he probado) 
Asfo, tienes toda la razón por eso he probado muchas de estas habilidades contra personajes sin armadura ni temple y ya haré un listado detallado, algunas van bien y otras se quedan muy atrás, sobre todo en la rama de armas

**Comment by Skullex7595** [comment]
el Addon que tengo te calcula dependiendo de las estadísticas que tengas como talentos buffos gemas encantamientos así que es un 100% seguro que lo haga y lo de que desgarrar tenga un tick crítico eso es un fallo mio pero lo pone a base de mi crítico

**Comment by HexR-zz** [comment]
estoy ajustando todos los hechizos, así que, al guerrero también le llegará, cierro
