### ISSUE TITLE
[Mazmorra > Camara de los origenes ]

### ISSUE THREAD

**Issue by HexR-zz** [RoDNet/Bugtracker-Infinium-4.0.6a#184]
La puerta que hay antes de Anraphet (2º Boss) no se abre sola, en El Arca de las Luces (habitación).

**Comment by searum** [comment]
Has hecho el evento del enano? te abre la puerta, spawnea un miniboss a uno de los lados, lo matas, spawnea otro... cuando termines de matarlos continua el evento y te abre la puerta, entonces podras matar a anraphet :)

**Comment by HexR-zz** [comment]
No. Era la primera vez que iba, pregunte pero me dijeron que estaba bug. Y postee. Ni me fijé si sacaba minibosses.
