### ISSUE TITLE
Mision: A la caza de Sylvanas

### ISSUE THREAD

**Issue by Ottozx** [RoDNet/Bugtracker-Infinium-4.0.6a#185]
hace poco estuve haciendo esta mision q me da lorna crowley en gilneas cuando estan los renegados etc etc X_X, el punto es que me mandaba a buscar a un tal tobias mantoniebla, el cual esta a las afueras de la casa donde ella esta, pero no se le puede hablar, no se mueve ni nada, y despues de un momento desaparece.
intente cancelando la mision una y otra vez pero nada pasaba, tanto que me tuvo que ayudar un MJ a  completar la mision.

![WoWScrnShot_120812_215944.jpg](https://f.cloud.github.com/assets/2999233/2180/2d776924-41ad-11e2-81bf-c55bc32d5c93.jpg)
esa es la unica foto que tngo, ella es lorna crowley( conozcanla ;) jajajaja ), y pues no tngo screenshot de tobias porque ............ps................desaparecio ._.

**Comment by searum** [comment]
arreglado en el siguiente update
