### ISSUE TITLE
[Mision > Alianza > Hacia la mansion de Cringris]

### ISSUE THREAD

**Issue by jesan94** [RoDNet/Bugtracker-Infinium-4.0.6a#186]
No se puede completar
La reina no esta y no se puede completar la mision.

http://es.wowhead.com/quest=14465/hacia-la-mansion-de-cringris

![Dibujo.JPG](https://f.cloud.github.com/assets/3002645/2555/5e4eeb62-4234-11e2-9204-43129bff785d.JPG)

**Comment by yuglar** [comment]
Confirmo el reporte.
todos los npc desaparecen cuando aceptas la misión
In game me han comentado que suicidándote se soluciona el problema, lo he probado pero en mi caso no ha funcionado.

![WoWScrnShot_121012_140923.jpg](https://f.cloud.github.com/assets/3007747/3440/db286f50-42ca-11e2-99e8-006a2c7dfd4f.jpg)

**Comment by searum** [comment]
fix en el siguiente update
