### ISSUE TITLE
[Spell > Ataque de victoria]

### ISSUE THREAD

**Issue by HexR-zz** [RoDNet/Bugtracker-Infinium-4.0.6a#189]
Ataque de victoria se activa cuando matas serpientes del cazador y no debería.

Edit: Aunque esté cerrado, Ataque de victoria SÍ se debe activar cuando matas las serpientes del cazador.

**Comment by DatJetto** [comment]
+1 para este post, lo iba a poner ahora mismo xD

**Comment by Skullex7595** [comment]
Tampoco debería contra elementales de agua del mago escarcha, demonios del brujo, lobos del chamán mejora, esbirro no muerto del caballero de la muerte, antárboles del druida equilibrio.
La única mascota que debería darte el Ataque de Victoria son las mascotas del cazador (quitando las trampas XD)

**Comment by DatJetto** [comment]
no se si los totems del chamán activan también este efecto pero estaría bien que se revisara :3

**Comment by HexR-zz** [comment]
Creo que no

**Comment by Skullex7595** [comment]
nop con los totems tampoco funciona porque es un objeto no una mascota
