### ISSUE TITLE
[ Guild > Guild Seller ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#194]
Cuando tu hermandad obtiene un cierto nivel puedes comprar cosas en este npc 
http://es.wowhead.com/npc=46602 
el cual actualmente no vende nada y debería vender todo esto:
http://es.wowhead.com/items?filter=cr=129:166;crs=0:4;crv=46602:0

http://i48.tinypic.com/ifpdli.jpg

**Comment by searum** [comment]
fix
