### ISSUE TITLE
[2] Buena racha bug

### ISSUE THREAD

**Issue by Faked** [RoDNet/Bugtracker-Infinium-4.0.6a#196]
Hola, ya hice un reporte anterior sobre este talento, pero tiene otro, fallo, se activan Misiles arcanos, una habilidad que no tendria que saltar

No puedo poner el link al talento porque ya no existe

http://i50.tinypic.com/34rynb9.jpg Descripcion del talento

Y me gustaria que revisaran cada cuanto salta  este talento para Piroexplosion instantanea, es algo bajo

PD: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/39 Por un fire no nerf

**Comment by HexR-zz** [comment]
FIXED
