### ISSUE TITLE
Bug hechizo flor de vida 

### ISSUE THREAD

**Issue by deiver9696** [RoDNet/Bugtracker-Infinium-4.0.6a#197]
Bueno lo que pasa es que el hechizo flor de vida esta bug y esa una desventaja para nosotros los druidas y mas para mi que soy de la rama restauracion
![Bug druida](https://f.cloud.github.com/assets/3053230/15271/e52de046-4727-11e2-86df-0070aabaf8e7.png)

**Comment by HexR-zz** [comment]
Está bug por qué?

**Comment by deiver9696** [comment]
No cura lo que tiene que curar cuando se acomula 3 veces el hechizo

**Comment by DatJetto** [comment]
es un Hot, no se cuanto quieres que te cure, 3k por pulso?  de todas formas entraré con mi druida a mirar :c y ahora opino más profundamente

**Comment by deiver9696** [comment]
Entonces el hechizo tiene que curar lo mismo cuando se acumula 1 vez y  3 veces ?  me parece ilógico que se acumula 3 veces y cure lo mismo tendria que curar mas bno  no se si estare equivocado  ![Imagen2](https://f.cloud.github.com/assets/3053230/15525/b800b3c6-477e-11e2-9044-7830ba5fb01b.png)

**Comment by HexR-zz** [comment]
Vaaale eso tenías que decir, que aunque se acumule no aumenta la curación o la frecuencia de curas... Has comprobado que no te cure más rápido?

**Comment by deiver9696** [comment]
No eso no

**Comment by DatJetto** [comment]
Ves, si explicas las cosas bien te entendemos :3

**Comment by deiver9696** [comment]
Se :) espero lo arreglen pronto  que es un  hechizo principal de un druida heal

**Comment by searum** [comment]
fix
