### ISSUE TITLE
Closed.

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#199]
-----.

**Comment by Faked** [comment]
Por favor, contad el equipo que llevais, que eso tambien suma mucho daño

**Comment by DatJetto** [comment]
Por favor, todo el mundo sabe que el intelecto se suma automáticamente a esas spell en cuanto cambie algún buff o pieza de set ._.

Oseaser - > con equipo pega 4800-4900 ( dado que es una fórmula y te dice el rango de Spell power que debe pegar ) en cuanto cambia un buff o cualquier cosa los numeros varían a mayor al obtener ventajas y disminuyen al obtener desventajas :C

**Comment by HexR-zz** [comment]
Has comprobado que cambia cuando tte quitas o pones equipo?

**Comment by DatJetto** [comment]
pues claro que baja cuando te quitas el set ._. pruebalo con cualquier pj y mira el daño que debe hacer va bajando o subiendo a medida que te equipas

**Comment by Dekadencee** [comment]
¿Ya está solucionado?
