### ISSUE TITLE
[Item

### ISSUE THREAD

**Issue by k4b3z0n** [RoDNet/Bugtracker-Infinium-4.0.6a#20]
}

**Comment by Dekadencee** [comment]
¿Muestra algun texto de error o algo en el juego? Nos ayudaria bastante si nos lo dices.

Un saludo y gracias por el reporte ^^

**Comment by k4b3z0n** [comment]
"Ya no puedes transportar mas objetos de estos"

lo mismo indica al tratar de despojar items del jinete

**Comment by searum** [comment]
arreglado

**Comment by macols77** [comment]
donde esta el fix :0
