### ISSUE TITLE
[Druid > Spec: Balance > Spell > Starfire]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#202]
Fuego estelar: http://es.wowhead.com/spell=2912
debería pegar unos 6.8k - 7k pero está pegando de 11k  un daño bastante alto teniendo encuenta que se suman  +4000 de daño 
http://i48.tinypic.com/1zq5ys1.jpg 

También su Cast time está bug; pone que se castea en 3.09 sec pero se castea en 1.5 aprox.

**Comment by HexR-zz** [comment]
Pff ya decía yo que esto pegaba mucho

**Comment by DatJetto** [comment]
Con la spec en Balance sacas 50k de critico al palito xD
