### ISSUE TITLE
[Druid > Spec: Restoration > Spell > Lifebloom ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#205]
Flor de vida: http://es.wowhead.com/spell=33763
![t5noyo 1 ](https://f.cloud.github.com/assets/965653/29895/33e06a70-4ddf-11e2-8ad2-606502390e9a.jpg)
![k51wty 1 ](https://f.cloud.github.com/assets/965653/29896/408e9f26-4ddf-11e2-90e9-af4d183794b3.jpg)

Cuando estalla flor de vida debería sanar unos 7k sin embargo sana 10mil

**Comment by asfo** [comment]
¿Qué relación tiene este bug con este: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/197 ? Debido a que al parecer, en tu reporte no se muestra mucho el reporte anterior.

**Comment by DatJetto** [comment]
La relación es que Cuando estackeas 3 veces lifebloom no aumenta la sanación en el reporte 197, debiendo aumentarse per stack ( 3 stacks max ) y el mio es que cuando termina el efecto del HoT sana más de lo que debe.
