### ISSUE TITLE
Bug Worgen mision "otra vez entre humanos"

### ISSUE THREAD

**Issue by SantosG13** [RoDNet/Bugtracker-Infinium-4.0.6a#21]
Pues al llegar a la mision "otra vez entre humanos" no puedo moverme e ir a completar la mision, y me e encontrado con mas jugadores en el mismo punto que yo y no pueden moverse tampoco

**Comment by searum** [comment]
Ya esta arreglada, en la proxima actualización lo tendreis disponible!

**Comment by SantosG13** [comment]
muchas gracias, cuando sale la proximal actualización?

**Comment by searum** [comment]
Espero que el domingo ya este, pero tal vez la adelantemos

**Comment by SantosG13** [comment]
perfecto muchas gracias

**Comment by Dekadencee** [comment]
Cierro el reporte ya que está lista para la siguiente actualización.
