### ISSUE TITLE
Fallo en mision bosque de elwin

### ISSUE THREAD

**Issue by jaime0510** [RoDNet/Bugtracker-Infinium-4.0.6a#210]
![Imagen1](https://f.cloud.github.com/assets/3056816/15632/6f92bd90-47a2-11e2-93d3-d9c7ccc8ded8.png)

tengo la garra del gnoll y no me completa la mision. !

gracias por su atencion

**Comment by DatJetto** [comment]
Por favor, almenos di que misión es :C

**Comment by jaime0510** [comment]
http://es.wowhead.com/quest=176

**Comment by searum** [comment]
Funciona correctamente, borra la carpeta cache.
