### ISSUE TITLE
Fuego de Alma (spell warlock destruction)

### ISSUE THREAD

**Issue by GorThauR** [RoDNet/Bugtracker-Infinium-4.0.6a#216]
Quema el alma del enemigo, lo que inflinge 6044 p. de daño de fuego.

-Quemar alma + Fuego de alma: Lanzamiento instantáneo.

Bug 1: Al usar quemar alma + fuego de alma hay veces en las que no lanza el hechizo (osea, está cargado y cuando lanzas dice "no puedo lanzar ese hechizo aún" y no lo lanza) sobre todo me pasas vs bosses de mazmorra aunque también contra algún bicho me ha pasado. 

cómo debería de ser:

Al usar quemar alma + fuego de alma debería lanzar instantaneamente el hechizo a cualquier enemigo siempre.

bug 2: Con cosechar alma (spell que se usa para conseguir las almas en brujo) a veces deja un CD de 5 minutos a fuego de alma no pudiendo lanzarse el hechizo.

Cómo debería de ser:

El cocechar alma no debería influir en el cd de ninguna spell del brujo

-Diablilo potenciado:

La descarga de fuego de tu diablillo tiene un 2% de probabilidad de provocar que tu siguiente lanzamiento de fuego de alma sea instantáneo en 8 segundos. (te salen 2 barras a tu alrededor para indicarte que está activado).

bug 3: se activa correctamente el buffo, te salen las dos barras a tu alrededor pero hay algunos enemigos (sobretodo me ha pasado vs bosses de mazmorra aunque también bichos) a los que no se los lanza, exactamente igual que en el bug 1. "no puedo lanzar ese hechizo aún".

como debería de ser: Debería lanzar el hechizo durante 8 segundos a cualquier enemigo.

**Comment by DatJetto** [comment]
Eso me pasa lo mismo con mi Aimed Sho! por proc, que dice no tienes enfoque xD, ahora subo unas fotos con mi problema :3
