### ISSUE TITLE
Glifo de PIedra de salud

### ISSUE THREAD

**Issue by GorThauR** [RoDNet/Bugtracker-Infinium-4.0.6a#219]
Piedra de salud: Crea una piedra de salud que cura inmediatamente el 45% de la salud base de quien la ha creado. 

-Para el ejemplo siguiente, mi salud es 106.784. 45% de 106784 es 48052.8. Sanación de base sin glifo está bien.

![piedra de salud 1](https://f.cloud.github.com/assets/2894762/22057/692a25f0-49e7-11e2-9850-73bdc728a809.png)

-Bug: Glifo de piedra de salud: Aumenta un 30% de la sanación de tu hechizo piedra de salud.

30% de 48052.8 = 14415,84. (debería curar 62,467) Sin embargo, me sigue curando lo mismo que sin el glifo.

![piedra de salud 2](https://f.cloud.github.com/assets/2894762/22066/f7cd1aba-49e7-11e2-8447-c131145a9dce.png)

-Piedra de salud + Quemar alma = Aumenta la salud total en un 20% durante 8 segundos.

Lo que sana es el 20% de la piedra base 20% de 48052 =  9610 (sana 57662)

![piedra de salud quemar alma](https://f.cloud.github.com/assets/2894762/22084/f88377aa-49e8-11e2-8031-ded85e248bd2.png)

Lo que debería sanar es piedra base + glifo:

48052 +30% = 62467 + 20% (12493) = 74960 por lo cual se cumple el bug del glifo también.

**Comment by searum** [comment]
fixed
