### ISSUE TITLE
Juerguistas ivernales

### ISSUE THREAD

**Issue by Faked** [RoDNet/Bugtracker-Infinium-4.0.6a#222]
He estado revisando en todas las tabernas de Ventormenta y Forjaz y no aparecen, sin ellos no se puede completar los logros.

http://es.wowhead.com/npc=15760/juerguista-invernal

**Comment by aerz** [comment]
Estan spawneados en Forjaz cerca de Papa invernal y en varios puntos de la horda, habría que revisar si son las posiciones exactas del evento una por una, pero por lo demás si que es posible completar el evento.

Un saludo :)
