### ISSUE TITLE
Problema al iniciar wow  ayudenme 

### ISSUE THREAD

**Issue by deiver9696** [RoDNet/Bugtracker-Infinium-4.0.6a#224]
No puedo iniciar wow 
![image](https://f.cloud.github.com/assets/3053230/22875/45930334-4a17-11e2-84c5-3c817d593a38.png)
![image](https://f.cloud.github.com/assets/3053230/22876/4a71fb62-4a17-11e2-8cf2-576385788970.png)
![image](https://f.cloud.github.com/assets/3053230/22878/4f2da912-4a17-11e2-9533-7fbbb855b32b.png)

Prodian ayudarme a solucionar este problema

**Comment by asfo** [comment]
Tienes un archivo corrupto o perdido, el wow-update-13164.MPQ, no se si puedas descargarlo pero creo que si se podía, si no al rato podría alguien quizá pasártelo y con eso se arregla

**Comment by Dekadencee** [comment]
Esto debería ir en nuestros foros y no en el bugtracker ya que no es un error del servidor si no de tu cliente.
