### ISSUE TITLE
Talento Llamas abrasadoras 

### ISSUE THREAD

**Issue by lks06** [RoDNet/Bugtracker-Infinium-4.0.6a#227]
Talento Llamas abrasadoras no Funciona cuando se junta las 5 cargas y despues uso latigazo de lava no se consumen las 5 cargas. 
![WoWScrnShot_122012_015441](https://f.cloud.github.com/assets/3086718/23733/23685d60-4a65-11e2-9589-19f8c6f99335.jpg)

**Comment by searum** [comment]
fix
