### ISSUE TITLE
Sacerdote > Spell > Palabra de las Sombras: Muerte 

### ISSUE THREAD

**Issue by xilopipe** [RoDNet/Bugtracker-Infinium-4.0.6a#228]
Descripción de Spell: (tal como yo la veo)
Palabras de las Sombras: muerte.
"Una palabra de vínculo oscuro que inflinge 422p. de daño de las Sombras al objetivo. Inflige 3 veces ese daño a los objetivos con menos de un 25% de salud". Si el Objetivo no muere a causa de Palabra de las Sombras: muerte, el taumaturgo recibe daño equivalente a la cantidad de daño infligida a su objetivo"

Fallo: (3 bugs)
No inflinge el daño triplicado en los objetivos con menos de 25% de vida. (FOTO 1)
No se recibe el daño equivalente, si el objetivo no muere. (FOTO 2)
No se recibe daño alguno cuando se daña con menos del 25% de vida y el objetivo no muere. (FOTO 3)

Pruebas: (capturas de pantalla)
Foto 3
![WoWScrnShot_122012_023237](https://f.cloud.github.com/assets/3086691/23745/7dc687f8-4a67-11e2-8fb8-db11a2c1bc7e.jpg)

Foto 2
![WoWScrnShot_122012_021750](https://f.cloud.github.com/assets/3086691/23746/7dc88878-4a67-11e2-86b8-4ba172c71ac6.jpg)

Foto 1
![WoWScrnShot_122012_021512](https://f.cloud.github.com/assets/3086691/23747/7de14110-4a67-11e2-9fb7-30c4b869f243.jpg)

**Comment by DatJetto** [comment]
Que de Addons, que de colores xD que bonito todo

**Comment by xilopipe** [comment]
Si algún Mj ve mi post, le agradecería que me dijera como etiquetar los reportes! Gracias

**Comment by searum** [comment]
fix
