### ISSUE TITLE
[Bastión del Crepúsculo / Bot > NPC > Rompevientos ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#231]
Este npc [http://es.wowhead.com/npc=47151] lanza una descarga de tornados en AoE  (área) cada tornadito pega de 25k y te dan 3 o 4 cada segundo, siendo imposible curar una raid tal cantidad en apenas 1 sec Wipe xD
Estas parecen ser las spell
http://es.wowhead.com/spell=87880
http://es.wowhead.com/spell=87875

Según la spell y lo que he creido entender, todo el channelcast pega 25k dado que es un pull y hay más mobs tendría 
sentido 

http://i46.tinypic.com/fc1mqc.jpg
<a href="http://tinypic.com?ref=fc1mqc" target="_blank"><img src="http://i46.tinypic.com/fc1mqc.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by HexR-zz** [comment]
Edito. 
Confirmo que está bug.

**Comment by DatJetto** [comment]
Esque no puedes castear, te mete knock back y no puedes hacer nada xD

**Comment by crowel** [comment]
Si pegan muchisimo esos elementales

**Comment by searum** [comment]
fix
