### ISSUE TITLE
[ BG > Mapas ] 

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#232]
En BG muchas veces por una insignficante elevación de tierra que no debería afectar, esta tapa totalmente la visibilidad del objetivo, cuando no debería ser así, en Warsong Gulch por ejemplo, estoy delante del enemigo y no consigo verle a pesar de que está en mis narices, las únicas partes que deberían tapar la visión serían las columnas, paredes, casas y troncos del mapa :( 
http://i45.tinypic.com/ixe7b7.jpg
<a href="http://tinypic.com?ref=ixe7b7" target="_blank"><img src="http://i45.tinypic.com/ixe7b7.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by asfo** [comment]
El sistema de colisión está siendo reescrito para la siguiente versión según indicó Dekadence, mientras se libera dicha versión y se comprueba la solución cierro el tema.

Gracias por el reporte :). :+1:
