### ISSUE TITLE
bug arqueologia humedales

### ISSUE THREAD

**Issue by coste23** [RoDNet/Bugtracker-Infinium-4.0.6a#233]
por favor corregir el bug en arqueologia en tumba de barbaferrea el telescopio siempre apunta a un filo de montaña y el artefacto pues para cojerlo es complicado.
![WoWScrnShot_122012_134535](https://f.cloud.github.com/assets/2788656/25233/90bcf1c6-4ad5-11e2-83d2-0e52bc3645b2.jpg)

**Comment by Dekadencee** [comment]
Reporte repetido: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/246
