### ISSUE TITLE
energia del picaro se acaba demasiado rapido y abanicos de cuchillos picaro animacion bug

### ISSUE THREAD

**Issue by coste23** [RoDNet/Bugtracker-Infinium-4.0.6a#234]
el abanico de cuchillos lanza 4 cuchillos de forma asi 3 hacia el lado izquierdo y 1 a lado derecho segun el hechizo lanza simultaneamente en todas las direcciones  en pocas palabras se deberia ver alrededor del picaro los cuchillos.

**Comment by DatJetto** [comment]
XDDDDDD me cago en la mar, la energía está bien :c solo tienes que saber administrarla y la animación también está bien ._.

**Comment by asfo** [comment]
La animación no es problema del servidor en dado caso que estuviese "dañada", sería cuestión de el mismo juego, así que no podemos hacer nada.

La energía de los pícaros está bien, como dice @DatJetto debes saber administrarla.

Cierro.
