### ISSUE TITLE
Fallo votaciones desde la pagina web

### ISSUE THREAD

**Issue by jaime0510** [RoDNet/Bugtracker-Infinium-4.0.6a#235]
![Imagen1](https://f.cloud.github.com/assets/3056816/25157/55f8fb42-4ad1-11e2-8de7-b3b7259d65ee.png)
![Imagen2](https://f.cloud.github.com/assets/3056816/25159/62865af8-4ad1-11e2-96cb-d4050151a848.png)

Y eso me sale en todas las paginas de votacion :/ No se si solo me pase a mi pero es frustrante y ya pasaron 24 horas desde que vote ayer

**Comment by asfo** [comment]
Como les comenté en el tema del foro, ayer tuvimos un problema con el sistema y hemos estado investigando y ya dimos con el fallo y se está solucionando.

Esperamos en unas horas esté completamente funcional de nueva cuenta.
