### ISSUE TITLE
bug arqueologia  al lado del arrecife mortal norte de la vega de tuercespina

### ISSUE THREAD

**Issue by coste23** [RoDNet/Bugtracker-Infinium-4.0.6a#236]
el telescopio me muestra el artefacto sobre un arbol cuando se titila en verde pero para pasar el arbol  necesito una motosierra para tumbarlo por favor corregir este problema
![WoWScrnShot_122012_134126](https://f.cloud.github.com/assets/2788656/25223/e65c8d68-4ad4-11e2-8dc0-9b75259fd07d.jpg)

**Comment by Dekadencee** [comment]
Reporte repetido: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/246
