### ISSUE TITLE
bug picaro reponerse

### ISSUE THREAD

**Issue by coste23** [RoDNet/Bugtracker-Infinium-4.0.6a#237]
el reponerse no esta funcionando cuando mato un pjs con puntos de combo, solo esta funcionando cuando los puntos de combo se los aplico mientras el pj esta vivo de lo contrario el reponer no usa esos puntos para no desperdiciarse por favor revisar ese talento. gracias

**Comment by HexR-zz** [comment]
Estás seguro que si está muerto se pueden reponer? Pon algo oficial que lo certifique

**Comment by asfo** [comment]
http://es.wowhead.com/spell=73651/reponerse <-Está funcionando, no puedes utilizar los puntos de combo en un personaje muerto para aprovecharlos y reponerte. Debe ser mientras estás peleando para que puedan gastarse debido a que al momento de morir, se supone los puntos de combo han quedado inutilizados.

Cierro hasta que alguien compruebe lo contrario.
