### ISSUE TITLE
bug arqueologia tierras de la peste

### ISSUE THREAD

**Issue by coste23** [RoDNet/Bugtracker-Infinium-4.0.6a#238]
![WoWScrnShot_122012_152900](https://f.cloud.github.com/assets/2788656/25468/f1568b1a-4ae3-11e2-987d-848caf835a58.jpg)
bug en esta parte de arqueologia señala el telescopio la montaña para el artefacto

**Comment by Dekadencee** [comment]
Reporte repetido: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/246
