### ISSUE TITLE
Maestría Paladín Protección BUG

### ISSUE THREAD

**Issue by xefirot** [RoDNet/Bugtracker-Infinium-4.0.6a#24]
La maestría del paladín protección funciona de una menara incorrecta. El % de probabilidad de bloqueo no aumenta aun teniendo un indice maestría alto, si no que aumenta el daño bloqueado desorbitadamente. Posee un 5% invariable de probabilidad de bloqueo y 1300% de daño bloqueado.

La forma correcta sería 30% de daño bloqueado permanente (no aumenta). 5% probabilidad de bloqueo fijo + el % correspondiente por el índice de maestría.

**Comment by k4b3z0n** [comment]
con razon en pvp maximo se les pega 2k xd

**Comment by xefirot** [comment]
Um eso no creo que tenga que ver, estamos hablando de una probabilidad de bloqueo de un 5%. Solo se bloquean 1 de cada 20 golpes.

**Comment by Dekadencee** [comment]
Hoy han sido fixeadas todas las maestrías, mañana mismo estarán disponibles en el servidor ^^
