### ISSUE TITLE
fallo gestion de cuentas 

### ISSUE THREAD

**Issue by jaime0510** [RoDNet/Bugtracker-Infinium-4.0.6a#240]
![Imagen1](https://f.cloud.github.com/assets/3056816/25832/e5eacdbc-4af8-11e2-8a20-8d5958b56425.png)

esto me aparece cuanto intento acceder a gestion de cuentas y cambiar mi clave ayer juge en un cafe internet y quise cambiar mi contraseña pero no he podido ahora corro el riesgo de que me roben la cuenta :/ por favor darme una solucion rapido

![Imagen12](https://f.cloud.github.com/assets/3056816/25843/4651f18a-4af9-11e2-96a6-489592648ddd.png)

Luego intento entrar a opciones de privacidad y me aparece esto

![image](https://f.cloud.github.com/assets/3056816/25844/5606df00-4af9-11e2-81d3-1b42615c919c.png)

espero tener una solucion antes de perder mi cuenta 

Gracias

**Comment by asfo** [comment]
Estamos trabajando en todo esto, pero por desgracia Dekadence no ha podido pasarme en mi parte el FTP por lo que yo no he podido hacer nada. Espero Dekadence se de una vuelta por aquí y vea esto. Mientras tanto habrá que esperar a que resuelva por su parte esta situación, sin embargo, no te preocupes que si tu no puedes cambiar la contraseña nadie más podrá y solamente sería vía web, puedes jugar tranquilo :).

**Comment by jaime0510** [comment]
Pero si me borran los personajes ? es que hay gente muy mala :/ tu no me la puedes cambiar por comandos ? estaria dispuesto a compartir mi contraseña contigo
