### ISSUE TITLE
Contraseña perdida fallo web gestion cuentas

### ISSUE THREAD

**Issue by jaime0510** [RoDNet/Bugtracker-Infinium-4.0.6a#241]
asfo con respecto a mi anterior post no me puedes cambiar tu la contraseña de mi cuenta via comandos ? es que es posible que me borren los personajes o me borren obtejos de ellos por favor estaria dispuesto a compartir mi contraseña contigo

**Comment by asfo** [comment]
No es necesario que reabras un tema. Nadie puede acceder a tu cuenta en WoW si no se la sabe. Por lo tanto si cerraste WoW pedirá que introduzcan la contraseña y por lo tanto si no la tienen no hay cuidado, sin contar que vía web no se podrá cambiar por el problema. Así que no hay cuidado. Tranquilo, confía en mi. Cierro.
