### ISSUE TITLE
Problemas con los sacerdotes

### ISSUE THREAD

**Issue by Frozentri** [RoDNet/Bugtracker-Infinium-4.0.6a#244]
el poder himno de esperanza( http://www.wowhead.com/spell=64904/hymn-of-hope ) no esta funcionando .  El talento masoquismo ( http://old.wowhead.com/spell=88995 ) tampoco regenera mana eni poder palabra meurte ni por daño. el talento arcangel ( http://old.wowhead.com/spell=87151 ) si da el daño conrepondiente por cad stack de buff, pero no regenera el mana que debiera por dichos stack, apenas regenera el 5% inicial.

**Comment by searum** [comment]
todo fix
