### ISSUE TITLE
Bug Arqueología

### ISSUE THREAD

**Issue by daniellm91** [RoDNet/Bugtracker-Infinium-4.0.6a#246]
Buenas, hace unos días ando dándole duro a la arqueología, pero ya tengo un problema pues que me no me deja seguir de manera más eficiente.. ya que tengo 11 de las 12 zonas que puedo explorar donde los objetos y están ubicados en lugares como montañas y arboles que de por si los pjs no nos podemos ubicar en ellas, cada una de esas 11 zonas las he revisado varias veces  y pues ocurre lo mismo. muchas gracias pues por la atención y ojala pueda reparar esto rápido.

Att: Zeigetsu

**Comment by Dekadencee** [comment]
Saludos Zeigetsu, efectivamente existe dicho problema debido al sistema de mapas actual, actualmente nuestro emulador en desarrollo versión 0.6 ya contiene un nuevo sistema de mapas capaz de detectar estas cosas.

Voy a reiniciarte todas las zonas, pero arqueologia fué desarrollada similarmente al oficial, los puntos se generan aleatoriamente dentro del area roja, así que es posible que vuelva a fallar.

En la próxima versión, al disponer del nuevo sistema de mapeo ya podemos localizar si el punto es accesible, así que será corregido en la próxima actualización.

Un saludo y disculpa las molestias, pero sin los nuevos maps no podemos hacer nada.

**Comment by daniellm91** [comment]
Dekadencee gracias por la atención pero pues acabándome de enterar de esta respuesta ingame, pues tengo las mismas zonas bug es decir, dichas zonas no parecen haberseme reiniciado, muchas gracias por todo saludos.

**Comment by Paketon** [comment]
Yo tambien tengo una zona bug. La pongo por si ayuda a quitarla del medio ya.... y si no a esperar a la siguiente actu.
![Arqueo](https://f.cloud.github.com/assets/3197965/45851/5c6afb58-57ea-11e2-9c15-fd5842488c7e.jpg)
![Arqueo2](https://f.cloud.github.com/assets/3197965/45852/63d82730-57ea-11e2-9ea8-0ce25dd7b2fb.jpg)

**Comment by asfo** [comment]
Para problemas que relacionen este bug, pongan ticket. 

Cierro debido a que tengo entendido en la próxima versión debería estar solucionado y se estará dando solución vía tickets.
