### ISSUE TITLE
[Hunter > Spec: General > Spell > Tranquilizing Shot]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#25]
Disparo tranquilizante
http://es.wowhead.com/spell=19801
Bug: Puede lanzarse todo el rato, aunque el enemigo no tenga nada debufable.
Solo podría lanzarse en caso de que se pudiera remover algún bufo

**Comment by adrianrp1988** [comment]
Reparado en la próxima Rev :D
