### ISSUE TITLE
Mazmorra de lord cuervo bug!

### ISSUE THREAD

**Issue by Astamtun** [RoDNet/Bugtracker-Infinium-4.0.6a#253]
Bueno lo que pasa es que cuando pongo la la dificulta de la mazmorra 5 heroico entro como si  nada me explico como si no  hubiera portal no aparece la imagen ni la barra cargando es como si yo pasara derecho como si no hubiera puerta no se si me haga entender y el mi pj no pasa de de ahy como lo muestra la imagen de abajo.  La otra dificultad si me deja entrar normalmente.

![WoWScrnShot_122112_154920](https://f.cloud.github.com/assets/3102233/28254/024e620e-4be2-11e2-91ff-4b6210a944ff.jpg)

**Comment by DatJetto** [comment]
Necesitas reputación con Bajo arrabal y comprar la llave para desbloquear el modo HC de las mazmorras, por favor :c leed e informaros.

**Comment by asfo** [comment]
Cierro hasta que haya comprobado alguien más que esté en problemas dicha mazmorra. Por ahora, el mismo ScreenShot nos deja ver que es problema del usuario.

**Comment by DatJetto** [comment]
Yo con mi personaje puedo entrar perfectamente a dicha mazmorra ya que tengo la llave de echo voy varias veces en semana a matar Lord Cuervo.

**Comment by asfo** [comment]
Entonces se queda cerrado. Gracias por los avisos :) :+1:
