### ISSUE TITLE
Chaman > Spell> Rafaga de lava> Elemental

### ISSUE THREAD

**Issue by Nepptum** [RoDNet/Bugtracker-Infinium-4.0.6a#256]
Revisen esta spell saca mas de lo que deberia casi el triple

http://es.wowhead.com/spell=51505

![WoWScrnShot_122212_154758](https://f.cloud.github.com/assets/3106443/28631/2f0480c2-4c68-11e2-857f-5ea5170c9797.jpg)

**Comment by DatJetto** [comment]
WTFFFF 69k de maná y mete casi 20 sin apenas buff D: que miedo.
Te está metiendo  9k así sin critico ._.

**Comment by Nepptum** [comment]
con buff saca 22k de vida incluso 25k

**Comment by HexR-zz** [comment]
El dummy es nivel 82, es golpe crítico, con rama elemental y talentos de bonus de golpe crítico llega de sobra
