### ISSUE TITLE
Mago- Elfo de Sangre - Misiles arcanos

### ISSUE THREAD

**Issue by Groldeath** [RoDNet/Bugtracker-Infinium-4.0.6a#258]
La primer quest especial para mago anda bug, dice que salgas y utilices 2 veces la abilidad misiles arcanos contra los muñecos de practica, total les disparo con ellos y no pasa nada, no me cuenta la quest ni nada
![WoWScrnShot_122112_143148](https://f.cloud.github.com/assets/3106548/28685/c2ad8346-4c77-11e2-8e58-3ceebd6adcf2.jpg)

**Comment by HexR-zz** [comment]
Pon el link de wowHead de la misión por favor y el de los rayos arcanos también

**Comment by HexR-zz** [comment]
FIXED
