### ISSUE TITLE
Bug botines

### ISSUE THREAD

**Issue by Leosi** [RoDNet/Bugtracker-Infinium-4.0.6a#260]

**Comment by DatJetto** [comment]
Usas el lanzador del servidor?, esa podría ser la causa :$

**Comment by Leosi** [comment]
Claro,me va todo perfectamente,aunque no se si se arreglará después solo porque tengo la descarga por el 6%

**Comment by DatJetto** [comment]
Quizá es por eso que no tienes el juego descargado :$ ha habido problemas similares, supongo que con la descarga se te pasará.

**Comment by Leosi** [comment]
Espero que sí.

**Comment by Leosi** [comment]
Ya está arreglado.
