### ISSUE TITLE
Mision huargen bug

### ISSUE THREAD

**Issue by jaime0510** [RoDNet/Bugtracker-Infinium-4.0.6a#262]
![Imagen2](https://f.cloud.github.com/assets/3056816/29098/f327a2d6-4d26-11e2-8dab-b1b0b6e34d91.png)

![Imagen3](https://f.cloud.github.com/assets/3056816/29101/0a9b5764-4d27-11e2-8921-8567d13b5e6a.png)

Como pueden obserbar el Npc que deberia llevarme hasta la casa de sylvanas no se mueve no se le puede hablar nada. Entonces era para que la arreglen por que es una de las pocas misiones bug que tiene esta raza.

**Comment by Dekadencee** [comment]
Reporte duplicado: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/148 seguimos su avance a través del anterior
