### ISSUE TITLE
Garganta grito de guerra

### ISSUE THREAD

**Issue by jaime0510** [RoDNet/Bugtracker-Infinium-4.0.6a#263]
![Imagen1 2 ](https://f.cloud.github.com/assets/3056816/29106/7418e562-4d27-11e2-8bb9-d013e7a4bdf5.png)

Como pueden observar hay una persona que tiene la bandera pero en el mapa no aparece entonces es dificil saber donde esta para poder defenderla haber si la pueden arreglar

**Comment by DatJetto** [comment]
es Garganta grito de guerra, no de fuego xD  -> Warsong Gulch

**Comment by asfo** [comment]
Ok, estuve checando más o menos qué pasa...Pero para mejorar la investigación ¿podrías indicar si en el mini mapa se muestra? (Usa me parece CTRL+SHIFT+M, es un pequeño mapa abajo a la derecha)

**Comment by DatJetto** [comment]
Shift + M  y no asfo, no se muestra, yo siempre tengo ese minimapa activo y nada :(

**Comment by asfo** [comment]
Sale :D...Gracias por la respuesta :)

**Comment by searum** [comment]
fix
