### ISSUE TITLE
bug en guardias 

### ISSUE THREAD

**Issue by jaime0510** [RoDNet/Bugtracker-Infinium-4.0.6a#264]
![image](https://f.cloud.github.com/assets/3056816/29137/e59c8f1a-4d2f-11e2-872b-251f467cb46b.png)

![image](https://f.cloud.github.com/assets/3056816/29138/f3bad20a-4d2f-11e2-9a1a-d7118e1fe052.png)

en vez de decir en que lugar esta el instructor de cada clase dice el instructor de profesiones, y si le da en profesiones tambien dice de profesiones.

**Comment by Dekadencee** [comment]
Reporte duplicado, cierro y seguimos desde el anterior: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/44
