### ISSUE TITLE
Arqueología

### ISSUE THREAD

**Issue by Centinela-zz** [RoDNet/Bugtracker-Infinium-4.0.6a#269]
Lo primero es felicitar por el gran funcionamiento general de esta profesión. El único problema es que a veces el lugar de excavación sale dentro de una montaña o en algún punto inalcanzable por lo que se buguea la zona y pierdes un lugar de excavación en el continente que estés. Mi pj "Caesar" tiene 2 zonas bugueadas y el de mi señora "Artemise" tiene todo un continente...

Así pues, sería ver si se puede Reiniciar las zonas de ambos pjs y sugeriría poner un NPC junto al trainer que te lance una spell que te reinicie las zonas o una herramienta en la Web, para que no haya que estar rescatando a todos los que suban la profesión.

Muchísimas gracias.

**Comment by DatJetto** [comment]
Gran sugerencia por el momento :) la secundo; te remito este post para que veas lo que contestó Dekadence: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/246

**Comment by Centinela-zz** [comment]
Pues a esperar a que reseteen las zonas de esos 2 pjs y ver si las sugerencias son factibles para ser menos pesaditos con el tema

**Comment by Dekadencee** [comment]
Fixed!
