### ISSUE TITLE
Entrada de Zul´Gurub bug

### ISSUE THREAD

**Issue by GorThauR** [RoDNet/Bugtracker-Infinium-4.0.6a#271]
Hay una pequeña puerta para entrar, una vez que la pasas debería estar el haz de teletransporte a la mazmorra, pues ese haz no está, así que no te lleva a la mazmorra. (Zul Gurub está al norte de vega de tuercespina a la derecha)

Cómo debería de ser: El haz te transporta a la mazmorra

![zul gurub](https://f.cloud.github.com/assets/2894762/30511/7a0d28d2-4ea5-11e2-8ef8-051d9b92ddcb.png)

**Comment by Centinela-zz** [comment]
La entrada no está bug. En esta versión del juego Zul'Gurub no existe... Está en transición entre la antigua y la que aparece en la 4.3. Ahora mismo la mazmorra está tal y como debería estar... No está porque no existe

**Comment by asfo** [comment]
Si esto es verdad, cierro, en caso contrario háganme saberlo y reabro.

**Comment by DatJetto** [comment]
Centinela tiene razón, salvo el parche que se añade en 4.1 con un nivel de objeto 353 Hc pasando de ser banda de Wow Classic a una mazmorra en Cataclysm, en 4.0.6 solo puedes acceder al recinto, pero no a la mazmorra, Habrá que esperar a que añadan las versiones para poder entrar y conseguir estos objetos tan jugosos :3
