### ISSUE TITLE
Zona bug pesca: Uldum

### ISSUE THREAD

**Issue by Faked** [RoDNet/Bugtracker-Infinium-4.0.6a#272]
Al ir a pescar a Uldum, una vez el pez a picado el anzuelo al ir a sacarlo se queda como si no hubiera capturado nada y a los 5 segundos mas o menos sale: Tu pez a escapado

Y no, el pez no se me escapa, porque lo hago casi instantaneo
Y no, no estoy bug yo, pues he probado lo mismo y en Ventormenta de me funciona

**Comment by jandrox** [comment]
No es un bug, te falta nivel ;)

**Comment by asfo** [comment]
¿Alguien puede corroborar el comentario superior? Así puedo cerrar el reporte.

**Comment by DatJetto** [comment]
Si, claro, Esto no es un bug, esque intentas pescar en zonas cata, donde el nivel de los peces es 80-85 que se corresponde con la habilidad en pesca comprendida entre 425 - 525 
Rasganorte 350 - 450
Terrallende 275 - 375
Kalimdor y Reinos del este 0 - 300
