### ISSUE TITLE
Bug de Golpe Letal+Glifo de Socorro Oscuro (Overheal del 7%)

### ISSUE THREAD

**Issue by RodMadmel** [RoDNet/Bugtracker-Infinium-4.0.6a#273]
Según el tooltip facilitado por Blizzard, Golpe Letal "Concentra poder oscuro en un golpe que inflige un 185% de daño con arma más 499 p. a un enemigo y te sana un 15% del daño que has recibido durante los últimos 5 s (un mínimo de un 7% de tu salud máxima)."

Ejemplo: Si no recibes daño> Vida máxima por valor de 110.000>El 7% es 7.700.

Existe un Glifo llamado Socorro Oscuro que consiste en "Provocar que tu facultad Golpe Letal siempre restaure al menos un 15% de tu salud máxima cuando se utilice junto a Presencia de Escarcha o Presencia Profana."

Ejemplo: Si no recibes daño>Presencia Profana/Escarcha>Glifo de Socorro Oscuro activado> Vida máxima por valor de 110.000> El 15% es 16.500.

El problema que nos ocupa hoy es que dicha sanación no responde a lo estipulado en el glifo.

Realidad: Si no recibes daño>Presencia Profana/Escarcha>Glifo de Socorro Oscuro activado> Vida máxima por valor de 110.000> La sanación recibida asciende a 24.500 (El 22% de 110.000).

El fallo o error de la curación sólo supone un 7%. (Diferencia entre 24.500 y 16.500: 8.000)

Si el DK va con con el talento Amenaza de Thassarian (Cuando blandes dos armas de una mano, tus facultades Golpe letal, Asolar, Golpe de peste y Golpe de Escarcha tienen un 100% de aplicar daño y efectos de impacto con el arma de mano izquierda), la sanación es doble.

Aquí dejo una screen en la que muestra la doble sanación, en concreto la que resulta ser un 22% de la vida máxima:

http://i50.tinypic.com/50qz5d.jpg

Gracias.

Un saludo,

Madmel.

**Comment by DatJetto** [comment]
Glifo de socorro oscuro -> http://es.wowhead.com/item=68793
 para 4.0.6 La sanación minima de tu Golpe letal pasa a ser 15% de tu salud total

Golpe letal -> http://es.wowhead.com/spell=49998 

para 4.0.6:  150% daño con arma + formula ap y te sana ( minimo 7% de tu total health ) 15% del daño recibido los 5 sec antes de usarlo. 

Amenaza de Thassariam -> http://es.wowhead.com/spell=66192 
para 4.0.6 ver descripción arriba :D 
-La sanación no ha de ser doble al llevar 2 armas, solo 1 sanación.

**Comment by HexR-zz** [comment]
Vale nada, con suerte para la próxima rev está solucionado, ahora lo confirmo.

**Comment by RodMadmel** [comment]
He relogueado frente a un enemigo y la sanacion es la misma. ;)

**Comment by HexR-zz** [comment]
Fixed, closed
