### ISSUE TITLE
problmas en misiones

### ISSUE THREAD

**Issue by Tranzas** [RoDNet/Bugtracker-Infinium-4.0.6a#274]
desde ya agradeciendo todo el trabajo que hacen para hacer funcionar esto, quisiera reportar problemas en misiones "arde nena arde", de riscovinto ya que el incinerador no interactua con las cajas a destruir por lo que no pueden ser destruidas y por lo tanto no se puede cumplir la mison.
ademas en "astranar en llamas" los 15 focos de fuego que hay que apagar no aparecen para poder utilizar el agua...

eso, saludos y muchas gracias....

**Comment by asfo** [comment]
Por favor, haz un reporte por cada misión, así mismo anexa un link a las misiones en WoWHead usando:
htttp://old.wowhead.com y por último si enrolla algún NPC especial también linkealo en caso de tener el problema.

Cierro este.
