### ISSUE TITLE
bug huevos misteriosos 

### ISSUE THREAD

**Issue by juanito123** [RoDNet/Bugtracker-Infinium-4.0.6a#276]
hay un problema para conseguir la montura del protodraco verde y dos objetos mas que se pueden obtener mediante los huevos misterioso que se pueden comprar en la cuenca de sholozar pero cuando uno los compra dicen 3 dias y al dia siguiente 0 segundos uno los intenta abrir pero no se puede.

![IMG_0060 1 ](https://f.cloud.github.com/assets/3128150/31441/84894956-4f83-11e2-975f-ec126b94c4fe.JPG)

**Comment by asfo** [comment]
Espera los 3 días y si no se abren...Avísanos...

Por cierto, las capturas de pantalla se toman con la tecla:
Impr Pant Pet Sys (o ImpPnt o relacionado).

**Comment by juanito123** [comment]
no me abrieron ..

**Comment by asfo** [comment]
Ok, marco como "Loot".

**Comment by ninotauro** [comment]
El huevo se abre a los 7 dias, lo de a  los 3 dias es un error visual. =D en todos los servers anda =
