### ISSUE TITLE
[Mazmorra > La cumbre del vórtice]

### ISSUE THREAD

**Issue by HexR-zz** [RoDNet/Bugtracker-Infinium-4.0.6a#278]
El primer Jefe tiene unos torbellinos que se van moviendo (unos 6-8) que lanzan unos rayos que quitan 25k
todos a la vez, según el vídeo de abajo, deberían quitar 11k más o menos, tanto el vídeo como el reporte son en dificultad heróica. 

http://es.wowhead.com/npc=43878/gran-visir-ertan
http://www.youtube.com/watch?v=yjnLpOW90xo

**Comment by daniellm91** [comment]
Nosotros no hemos tenido problemas con esa mazmorra, ni en dificultad normal, ni mucho menos en dificultad heroica. asi que la verdad no veo la cuestion del bug con respecto al daño, eso a mi parecer

**Comment by HexR-zz** [comment]
Ok, gracias por compartir tu experiencia, entonces como si fuese un error puntual.
