### ISSUE TITLE
[Mazmorra > Trono de las Mareas]

### ISSUE THREAD

**Issue by HexR-zz** [RoDNet/Bugtracker-Infinium-4.0.6a#279]
Según entras en la sala que hay 2 tentáculos si los clickeas deberían de quitarse para poder acceder a los bosses laterales. Pero no sucede nada cuando los clickeas..

**Comment by DatJetto** [comment]
Hex esos tentáculos se quitan cuando matas los bosses siguientes, yo he conseguido completar la mazmorra perfectamente. :)

**Comment by HexR-zz** [comment]
Y cómo accedes a los bosses siguientes? Porque en lo que parece un ascensor para bajar hay como una capa sólida que no deja ni subir ni bajar ni para donde haya que ir.

**Comment by DatJetto** [comment]
Claro que si que sube, después de derrotar al primer boss accedes al ascensor esperas un poco y subes, matas los otros 2 bosses creo que hay, bajas otra vez y ya no hay tentáculos y terminas la mazz.
