### ISSUE TITLE
Vendedor de Sastreria / Paterns Bug

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.0.6a#28]
El vendedor de patrones de sastreria no permite comprar los patrones aun teniendo los items necesarios para la compra dice siempre no puedes llevar mas objetos de esos gracias :)

**Comment by Dekadencee** [comment]
Reporte duplicado: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/20
Lo cerramos este y seguimos el error desde dicha issue.

Un saludo y gracias por el reporte ^^
