### ISSUE TITLE
[Priest > Spec: Shadow > Spell > Mind Flay]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#280]
Tortura mental: 
http://old.wowhead.com/spell=15407
Test con Satanik probando las spells, Tortura mental está un poco subida se aprecia como me pega 3,3k /  5k  / 8k de critico sin buff de daño, solo el orbe y la forma de sombras. 
Mi temple actual 3193 ( 33,53 % reducción ) 
http://i46.tinypic.com/34y92sk.jpg
http://i45.tinypic.com/2ahduvb.jpg
En el video vemos como un Priest mejor equipado que satanik y full buff  saca 2k a un druid feral de 110k  ( no tendrá mucho temple ) y un hunter de 125k en torno a 1.9 - 2,5k 
http://www.youtube.com/watch?v=kL3PP2fJ-Jg
Priest Full buff Sañosa 2k a una maga con temple, y al principio del video se ve dando 3k a un druida de 100k de vida  ( nada de set  casi )
http://www.youtube.com/watch?v=CgGiGq2I2Q8

**Comment by xilopipe** [comment]
Oie DatJetto deja de hacer spam diciendo que todos los hechizos del sacer estan bugs.. esos calculos en base a videos no sirven ni que supieras todas las estadísticas de ambos jugadores  y el contexto de la batalla tampoco podrías usar eso para extrapolarlo a tu caso..
