### ISSUE TITLE
[Priest > Spec: Shadow > Spell > Devouring Plague]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#281]
Peste devoradora, por favor, enfermedades de sacerdote más over; No gracias.
http://i47.tinypic.com/28stx5s.jpg
http://i46.tinypic.com/21afxs.jpg

El video: http://www.youtube.com/watch?v=CgGiGq2I2Q8
podemos ver como le saca a un pícaro 3:08  del debuff 537p. de la spell y 1k cuando da 2 ticks seguidos.

**Comment by searum** [comment]
....
