### ISSUE TITLE
[Priest > Spec: Shadow > Spell > Shadow Word: Pain]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#282]
Palabra de las Sombras: Dolor 
Dolor me da a mi cuando me saca tanto daño xD
http://old.wowhead.com/spell=589

http://i50.tinypic.com/2n24pqh.jpg
http://i46.tinypic.com/spdug0.jpg

En el video se ve como de 2 ticks saca 1200 - 1500  marca su addon al lado y de ticks normales 600 aprox / 3:10
http://www.youtube.com/watch?v=CgGiGq2I2Q8

**Comment by xilopipe** [comment]
Oie DatJetto deja de hacer spam diciendo que todos los hechizos del sacer estan bugs.. esos calculos en base a videos no sirven ni que supieras todas las estadísticas de ambos jugadores y el contexto de la batalla tampoco podrías usar eso para extrapolarlo a tu caso.

**Comment by searum** [comment]
lo mismo q el anterior, este issue no vale para nada.
