### ISSUE TITLE
[Priest > Spec: Shadow > Spell > Vampiric Touch]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#283]
Toque Vampírico;
http://www.wowhead.com/spell=124465
Daño elevado; 
http://www.youtube.com/watch?v=CgGiGq2I2Q8 está dando casi 3k con buff  y 6k de ''tic doble'', muestra su addon
- Satanik pega 5k sin buff apenas http://i49.tinypic.com/34dolr7.jpg
- y 10k de critico casi :D http://i47.tinypic.com/2i0658z.jpg

**Comment by xilopipe** [comment]
Oie DatJetto deja de hacer spam diciendo que todos los hechizos del sacer estan bugs solo porque según tú te pegan duro, seguramente no tienes temple, estas mal equipado y quien te hizo ese daño si!!!  ¬¬

**Comment by DatJetto** [comment]
Tio que pesao eres, Soy full sañoso 3193 de temple ( 33.53 % reduccion ) tengo 134803 de vida base ._. seguro que no estoy bien equipado :C

**Comment by searum** [comment]
son datos invalidos, si quieres curratelo mas y da datos decentes
