### ISSUE TITLE
[Priest > Spec: Shadow > Spell > Mind Spike]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#285]
Púa mental; 
http://www.wowhead.com/spell=87178

spell que quita todas las maldiciones y enfermedades , se stackea 3 veces con un  30%/60%/90% de crítico para tu próxima púa mental. 

http://www.youtube.com/watch?v=DvuX7y1WVow
Saca 10 - 11k de critico a la gente que va equipada y me pega 8 sin critico xD
http://i45.tinypic.com/b8lhl4.jpg
lo mejor es el critico! que te saca 24k de media y en el video le saca a la gente verde eso mismo :(
http://i46.tinypic.com/2zdy7oo.jpg

**Comment by xilopipe** [comment]
Oie DatJetto deja de hacer spam diciendo que todos los hechizos del sacer estan bugs.. esos calculos en base a videos no sirven ni que supieras todas las estadísticas de ambos jugadores y el contexto de la batalla tampoco podrías usar eso para extrapolarlo a tu caso.

**Comment by DatJetto** [comment]
Mira lo que me saca a mi satanik que va sanguinario-sañoso sin buff y yo voy full sañoso, me está pegando 24k casi y en el video la priest más o menos del mismo set, 11k a gente con temple y 23k a gente sin temple.

**Comment by Kaz00** [comment]
Eso no es cierto,yo no soy sacerdote, pero creo que no esta subido y mostrando videos ami parecer no das información clara ya que ese daño también podría estar manipulado por el server en el que jugara esa persona, para bien o para mal.Para mi los que mas hacen es el chamán y el cazador..
No veo que debas hacer tantos post para intentar tirar a una clase por los suelos,(no se por que te molesta :S no esta para nada OP).

**Comment by DatJetto** [comment]
daño también podría estar manipulado por el server en el que jugara esa persona <- Son videos del oficial, donde el daño está como debe ser... 

No es tirar una clase por los suelos, el sacer te pone las pegatinas, se va y mueres y si te empieza a spamear pua mental pues te mata en 0.2, básicamente el testeo lo he hecho con mi amigo priest porque sabe que está subido tampoco es un subidón como el del chamán elemental pero pega de más, y es apreciable
