### ISSUE TITLE
0 FPS en bg

### ISSUE THREAD

**Issue by GorThauR** [RoDNet/Bugtracker-Infinium-4.0.6a#287]
Buenas, me ha pasado ya unas cuantas veces que cuando entro en bg se me ponen los FPS a 0. Algunas personas más me ha dicho que le pasa. Se congela la pantalla y alomejor el personaje da un paso cada 30 segundos...

No he podido sacar screen pero los fps se me ponen a 0.

**Comment by asfo** [comment]
Deberías comprobar los AddOns, el chequeo de tus gráficas y la capacidad...Debido a que en BGs es digamos un lugar donde tu cliente emula a  varios jugadores al mismo tiempo con el entorno en un punto cerrado consume digamos un poco más de memoria y conexión para estar en dicho lugar sin perder la conexión al mundo ajeno a la BG, se que suena extraño, pero es una situación que en las zonas PvP esto sucede.

Trata de bajar todo al mínimo, quita tus addons y comprueba de nueva cuenta.

**Comment by GorThauR** [comment]
He probado sin addons, la gráfica y la capacidad no creo que sean ya que en otros servers no me ha pasado nunca :S y tampoco me pasa siempre, creo que me debería pasar siempre si fuera gráfica o capacidad imagino. los gráficos están al mínimo.

He podido sacar un screen (decir que cuando entré en la bg iban 200-400)
![0 fps](https://f.cloud.github.com/assets/2894762/34680/aec1bfae-5132-11e2-9afe-88aa27161129.png)

**Comment by jandrox** [comment]
A mi tb me ha pasado, no tanto como lo de fps a 0 pero si se me ha ralentizado hasta volverse injugable dando unos saltos de pantalla exagerados,eso si, solo algunas veces, he probado a usar otro ordenador y he comprobado que el problema seguía con lo que descarté problemas de requisitos del juego.

Un saludo.

**Comment by asfo** [comment]
Estamos checando esta situación y hemos llegado a una teoría de que podría ser nuestro .exe, en este caso, lo repararemos y les haremos saber.

**Comment by DatJetto** [comment]
Dadle un reinicio a la máquina :c que se despeje un poco

**Comment by Dekadencee** [comment]
Yo lo he testeado y no da problema ninguno :/

**Comment by searum** [comment]
pues como nadie dice nada lo doy por fixeado
