### ISSUE TITLE
Talento succion de alma (soul siphon) bug

### ISSUE THREAD

**Issue by jazzberri** [RoDNet/Bugtracker-Infinium-4.0.6a#29]
Es curioso, el talento funciona perfecto en 5 de las 6 pruebas que yo deduzco que se pueden hacer para saber si esta bug. No funciona cuando en el objetivo hay 3 efectos o más de la rama afliccion y justo uso drenar alma, me explico:

con 1 efecto sí que aumenta el daño de drenar alma, con 2 efectos también lo aumenta, con 3 efectos o más no lo aumenta.

1 efecto de la rama afliccion =  aumento de daño de 6% a la hablidad drenar alma o aumento 6% a drenar vida
2 efectos de la rama afliccion = aumento de daño de 12% a la hablidad drenar alma o aumento 12% a drenar vida
3 efectos o más de la rama afliccion = aumento de daño de 18% a la hablidad drenar alma o aumento 18% a drenar vida. 

No funciona el aumento del 18% a drenar alma, a drenar vida Sí.

Por si sirve de algo no aumenta el daño de drenar alma al 18%, lo aumenta en 12.

http://old.wowhead.com/spell=17805#comments

**Comment by adrianrp1988** [comment]
Reparado en la proxima Rev
