### ISSUE TITLE
Bug Brujo ( Crear Pozo de almas )

### ISSUE THREAD

**Issue by Redxx** [RoDNet/Bugtracker-Infinium-4.0.6a#290]
Link Wowhead: http://es.wowhead.com/spell=29893

Crea un Pozo de alma. Los miembros de la banda pueden hacer clic en el Pozo de alma para obtener una piedra de salud.

El Pozo de alma dura 2 min.

---

cuando se realiza el ritual aparece el circulo para invocar el pozo de almas pero cuando le dan los players , no aparece el pozo de almas , tan solo el circulo del ritual

**Comment by asfo** [comment]
Esto ya está reportado. Cierro.
