### ISSUE TITLE
Bug Brujo ( Invocar Demonio )

### ISSUE THREAD

**Issue by Redxx** [RoDNet/Bugtracker-Infinium-4.0.6a#292]
## Link Wowhead : ( no lo encuentro ) es el "libro " donde elijes al demonio a invocar.

invoca al demonio elegido

BUG:Invocar demonio desaparece de las barras de accion cada vez que , conectas o desconectas , mueres , vuelas etc.

**Comment by GorThauR** [comment]
Otros bugs que tiene son:
- Para invocar un demonio tienes que invocarlo 2 veces, porque la primera vez no te aparece la barra de acción del demonio.
  -Cuando subes a montura, cambias de mapa o reinicias el juego, a veces, si tienes un demonio X invocado aparece Y en vez de X.

**Comment by luislpv22** [comment]
Corregido.
