### ISSUE TITLE
Cd interno de abalorios bug

### ISSUE THREAD

**Issue by F4NT4SM4** [RoDNet/Bugtracker-Infinium-4.0.6a#296]
los abalorios pasivo de cataclysm la gran mayoria anda bug con los cd interno
mencionare aqui los abalorios que he encontrado bug que se activan a los 5 segundos al acabarse el buff sin respetar el cd interno

Corazon de ira:http://es.wowhead.com/item=65072#dropped-by 
CD Interno:1:40 

Peso aplastante: http://es.wowhead.com/item=65118/peso-aplastante
CD Interno: 1:15

Campana de resonancia enfurecedora: http://es.wowhead.com/item=59326/campana-de-resonancia-enfurecedora
CD Interno: 1:40

Torrende de poder(Enchanter):http://es.wowhead.com/spell=74242/encantar-arma-torrente-de-poder
CD Interno: 45

Sangre de Isiset:http://es.wowhead.com/item=56414/sangre-de-isiset
CD interno:1:45

solo tengo esos abalorios y enchanter para revisarles los cd interno los otros abalorios no los tengo en mis pj y no pude revisar si estaban bug o no
Revise los cd interno con un addon llamado forteXorcist

**Comment by HexR-zz** [comment]
Cómo sabes que tienen cds internos?

**Comment by F4NT4SM4** [comment]
todos los abalorios pasivos que no se activan con click tienen cd interno cada uno con tiempo diferente tiempo y gracias al addon forteXorcist pude identificar el tiempo de reutilizacion de cada uno de los abalorios que tienen mis pj

**Comment by DatJetto** [comment]
Exacto, todos los trinkets no activables tienen CD interno, por ejemplo; abalorio pvp ya sea de AGI / STR / SP se activa casi siempre debiendo tener un CD de 30 sec o así creo recordar, si no, iria todo el mundo siempre con 963p. de esas estadísticas.

**Comment by HexR-zz** [comment]
Pero no van por probabilidades? Es decir, cada golpe que pegas tiene X% de probabilidades de que salte? Voy a bajarme el addon y a mirarlo, no es que no me fíe, pero como es contrario a lo que yo pensaba me choca un poco. Pero es muy bueno aprender siempre de otros ^^

**Comment by DatJetto** [comment]
Claro Hex, cada golpe que pegas tiene % pero fuera del CD, Imagina;
*Abalorio con CD de activar ->  2min CD -> +1600 Stat
*Abalorio con CD interno -> No CD + 960 Stat ( según lo pones tu ) 
Das un golpe , se activa, 20 sec de abalorio efectivo, en esos 20 sec, das 30 golpes, alguno por cojones activa el abalorio, +960 Stat para siempre. 

Sale rentable usar el de 2min ? No :c 

Por eso tienen CD interno para que no se active siempre y no vallas con 2k de fuerza / intelecto / agilidad por bg siempre :c que 2k de un stat es mucho xD

**Comment by HexR-zz** [comment]
vaaaale vale vale, voy a echarle un ojo al addon y les meto los cds ;)

**Comment by DatJetto** [comment]
Te vendría bien echarle un ojo a esto e_e http://es.wowhead.com/items=4.-4?filter=minle=316;maxle=372;minrl=83;maxrl=85;cr=166:80:2;crs=4:8:1;crv=0:0:0;eb=1#0-2

Lo he resumido lo más que he podido e_e , hay algunos trinket que no son de 4.0.6 pero por el nivel aparecen :C

**Comment by HexR-zz** [comment]
http://es.wowhead.com/spell=92346

Mirad, aquí por ejemplo, si os fijáis abajo pone probabilidad de proc 10% y Reutilización 0. Me imagino que si tienes la suerte de que cuando te salta la proc la vuelves a reactivar pues.. enhorabuena y felicidades ... :S, cómo se configura el addon para que me saque los cds que te han salido a ti? O qué versión te has bajado tú? Porque yo tengo la 4.0.6 y no me saltan esos cds ni activando en opciones cds de buffs de items

**Comment by DatJetto** [comment]
Claro, es una spell de un abalorio, las spells no tienen icd ( cd interno ) , el icd lo lleva el item

**Comment by HexR-zz** [comment]
Listo
