### ISSUE TITLE
bug descarga de relampagos

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.0.6a#298]
wenas, testeado un poco el chami elemental creo q encontre el esceso de dps que mete
lazando  1 sola descarga de relampagos y me salta 2,3 o 4 daños producidos por este hechizo,

http://i50.tinypic.com/4lo7si.jpg

parece que el dps del hechizo esta bien lo escesivo es que la maestria salta siempre(solo con este hechizo)y haveces no 1 sino 3 veces salta la maestria con una sola descarga llegando a meter 50k de una descarga de relampagos

**Comment by searum** [comment]
ya esta fix
