### ISSUE TITLE
bug hechizo chaman

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.0.6a#299]
el hechizo desatar elemnetos no funciona

http://es.wowhead.com/spell=73680

de los 5 habilidades que puede poner un chaman al arma que salta cuado utilizas desatar elementos
solo; funciona http://es.wowhead.com/spell=51730 pero curando un 33% de lo que deveria (yo curo 2000 en la descripcion pone que cura 6000).
las otras 4 no;

http://es.wowhead.com/spell=8232 deveria de hacer un 125% del daño del arma y aumetar la velocidad de ataque cuerpo a cuerpo en los siguiente 6 golpes durante 12segundo

[Sin problemas aparentes (revisar comentario)][Editado por: @Asfo]
http://es.wowhead.com/spell=8024 deveria de hacer un daño de fuego istantaneo al target y aumenta el prosimo daño de fuego un 20% no lo hace

http://es.wowhead.com/spell=8033/arma-estigma-de-escarcha deveria de hacer un daño de 3500 segun la descripcion y poner un defuf al target que disminulle su velocidad un 50% durante 5 seg

http://es.wowhead.com/spell=8017 deveria de hacer que el enemigo te atacara durate 5 segundos

**Comment by ghost** [comment]
http://es.wowhead.com/spell=8024 A mí sí que me lo hace con Cagatotems, otra cosa es que haga exactamente un 20% extra de daño el siguiente hechizo de fuego, que no lo he testeado, pero sí que me lo hace el daño de fuego instant y ponerme el buffo de 20% de daño extra con hechizos de fuego

**Comment by 50megas** [comment]
sorry por postear 2 veces ,pensava que al final no lo hice

#385
