### ISSUE TITLE
Talento Erradicacion pequeño bug

### ISSUE THREAD

**Issue by jazzberri** [RoDNet/Bugtracker-Infinium-4.0.6a#30]
Veamos, el talento funciona pero en ved de darme 20% de celeridad como dice me esta dando 21,88.

Es un pequeño bug en realidad porque no salta mucho por la poca probabilidad pero lo reporto por si le quereis dar un ojo.

http://old.wowhead.com/spell=47197#comments

**Comment by adrianrp1988** [comment]
mmmm que raro, tienes algun ss o algo??

**Comment by jazzberri** [comment]
no se que es ss.

**Comment by adrianrp1988** [comment]
screenshot

**Comment by adrianrp1988** [comment]
he testeado ingame y todo me va bien asi que cerrare este issue, si tienes Screenshots pasalos y les hecho una mirada
