### ISSUE TITLE
bug glifo de picaro 

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.0.6a#300]
el glifo http://es.wowhead.com/item=42967 (algo cambiado por estar en la 5.0) mete desmasiado,
segun la desgripcion deja un sangrado  del 40% del daño del hemorrage durante 21 segundos(me imaguino que sera ese 40% repartido en tick cada 3 seg, durante 21 seg) 

no como pasa ,que mete un 60% de daño de hemorragia cada 3 segundos y aprate puede salir critico el sagrado, llegado a meter lo mismo q el hemorragia cada 3 segundos

ejemplo el de la foto que meto un hemorragia de  de 10.000 y el daño del sagrado completo es de 60.000 ^^
http://i46.tinypic.com/idrxud.jpg

**Comment by DatJetto** [comment]
El DoT que deja hemorragia te pega lo que dice el DoT, siendo un daño físico debería reducirse por la armadura y el temple, esto no ocurre D: 
Por ejemplo; te da con hemorragia y dice recibiendo 4000p. cada segundo, cada segundo te da 4000p. debiendo reducirse.

**Comment by 50megas** [comment]
los sagrados es normal que no le afecte la armadura de simpre a sido asi y creo q el temple si le afecta en bg e metido dot a gente  sin temple de 15k a otros full temple no pasa de 6k pero no lo e testeado,solo esperiencia en bg

**Comment by 50megas** [comment]
weno me puesto a testear y si le afecta el temple y con temple no esta tan over xd
de 1000 y 2000 y si el hemorrage critico pos el doble en teoria. puede que este bien asi

**Comment by DatJetto** [comment]
Pues a mi el Dot me saca 9k de critico :C

**Comment by HexR-zz** [comment]
Ok, arreglado para la próxima, close pls

**Comment by asfo** [comment]
Cierro. Reparado por HexR.
