### ISSUE TITLE
Bug - Huargen [A la caza de Sylvanas]

### ISSUE THREAD

**Issue by Detsu** [RoDNet/Bugtracker-Infinium-4.0.6a#307]
Hola, hay un bug en una parte de los huarguen, donde tienes que hablar con un huarguen que hay cerca una vez te han dado la misión, pero no me deja hablar con él, no me da esa opción

Pongo Link: http://es.wowhead.com/quest=24902/a-la-caza-de-sylvanas

**Comment by daniellm91** [comment]
esta mision no esta bug, por lo menos uno se encuentra con el huargen fuera de la catedral y el indica que tenemos que seguirlo, asi el salta ese muro y lo seguimos y damos continuidad a la mision, espero le sirva, es acercarse a el nada maás

**Comment by Faked** [comment]
Hola, si está bug, pero ya ha sido reportada, manda ticket para que te la completen

**Comment by asfo** [comment]
Cierro por multi-reportes.
