### ISSUE TITLE
Talento abrazo de las sombras (shadow embrace) bug

### ISSUE THREAD

**Issue by jazzberri** [RoDNet/Bugtracker-Infinium-4.0.6a#31]
Visualmente sobre el mob se ve que se acumula 3 veces pero calculando el daño se ve que solo aumenta el daño un 10% pero segun entiendo deberia ser un 15% debido a que cada stack da un 5% y son 3 stacks.

http://old.wowhead.com/spell=32392#comments

**Comment by adrianrp1988** [comment]
He testeado y no veo que ocurra tal cosa...
