### ISSUE TITLE
Mision Cuestion de glotonería

### ISSUE THREAD

**Issue by jandrox** [RoDNet/Bugtracker-Infinium-4.0.6a#312]
La misión "Cuestión de glotonería de Marismas de Zangar que te proporciona la vigía Leesa'oh, no se puede hacer ya que los restos de comida no se pueden seleccionar.

Link: http://es.wowhead.com/quest=9702

Un saludo.

**Comment by Alejo0701** [comment]
algunos no se dejan coger y los que se dejan obetner son poos y no hacen respawn haciendo imposible conseguirlos y completar la quest

**Comment by redneo** [comment]
Hay dos tipos, unas setas http://es.wowhead.com/object=182256#. y una especie de tronco http://es.wowhead.com/object=182031 salen seguro en los troncos, he cambiado para que tambien salgan en la seta, borra temporales antes de comprobarlo.
