### ISSUE TITLE
Bug del Stat [Pericia] al reforjar.

### ISSUE THREAD

**Issue by RodMadmel** [RoDNet/Bugtracker-Infinium-4.0.6a#317]
Al usar Reforja con un Item, por ejemplo le quitas Celeridad y le añades Pericia. Al reloguear, la Pericia está a 0, y no reconoce ni la Reforjada ni la que ya tenian los objetos per se. 

Aquí dejo screen: http://i49.tinypic.com/291ozr7.jpg

Un saludo.

**Comment by asfo** [comment]
Podría ser inclusive un bug visual, por que el reforjar cambia las estadísticas en la base de datos en el objeto...Por lo tanto no es comprobable al 100% del lado del cliente. Habría que revisar del lado del servidor si la base de datos contiene dicho cambio.

**Comment by HexR-zz** [comment]
mira en tus estadísticas ti tu pericia varía cuando te equipas/desequipas el objeto que te da el problema. Si cambia, es sólo un error visual

**Comment by RodMadmel** [comment]
Ya no es el objeto en cuestión sino que pierdo la pericia tanto de los reforjados como de los no reforjados...

**Comment by Dekadencee** [comment]
Reporte duplicado lo seguimos desde el reporte anterior: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/361
