### ISSUE TITLE
Bug Votaciones

### ISSUE THREAD

**Issue by albcp** [RoDNet/Bugtracker-Infinium-4.0.6a#319]
No se puede votar, cuando vas a la pagina de votaciones te redirige automáticamente a la principal

**Comment by asfo** [comment]
Las votaciones se realizan de manera directa utiliza este tema en los foros para saber más: 
http://reignofdarkness.net/wow/foros/t178/

Por ahora se mantendrán así hasta nuevo aviso.

Cierro.
