### ISSUE TITLE
Misión [La última de su raza] Bug

### ISSUE THREAD

**Issue by RodMadmel** [RoDNet/Bugtracker-Infinium-4.0.6a#323]
Una vez llegas a la osa en cuestión, al montarla y llevarla al pueblo brunnhildar, no se completa. En la cueva donde se encuentra el oso no hay ni un sólo mob, así que es un tanto extraño.

Aquí dejo screen: http://i48.tinypic.com/15p0gev.jpg

Esta es otra misión importante, ya que inicia la cadena para ser exaltado con Los Hijos de Hodir y desbloquea el intendente, el cual vende dos bonitos mamuts.

Un saludo.

**Comment by RodMadmel** [comment]
Misión: http://es.wowhead.com/quest=12983
NPC Objetivo: http://es.wowhead.com/npc=29563
Iten de mision: http://es.wowhead.com/item=42838

**Comment by HexR-zz** [comment]
Fixeado! los NPCs de las cuevas están pero no los podéis ver los jugadores porqueee no les da la gana xD en un ratillo los arreglo.

**Comment by RodMadmel** [comment]
¿Y la misión? ¿Se completará? XDDD

**Comment by HexR-zz** [comment]
Se completará ;)

**Comment by RodMadmel** [comment]
WOLOLOLOLOOO :D

**Comment by RodMadmel** [comment]
¿Está ya implementada? La acabo de probar, y ahora el oso en el que me monto no tiene la armadura de antes, pero de igual modo no hay nadie más en la cueva, y la llevo al punto que me indica en el mapa, y no salta como "Completada".
