### ISSUE TITLE
No se encuentra Npc--> Cadena de misiones ICC

### ISSUE THREAD

**Issue by daniellm91** [RoDNet/Bugtracker-Infinium-4.0.6a#325]
Bueno, buenas noches, me gustaria reportar que la npc "Forestal Oscura Vorel"(http://es.wowhead.com/npc=37780) no se encuentro en dalaran y pues es la primera para una cadena interesante de misiones en icc, la mision que esta da es la de " Dentro de la ciudadela helada" (http://es.wowhead.com/quest=24506) muchas gracias por la atencion.

Zeigetsu.

**Comment by HexR-zz** [comment]
ok got it
