### ISSUE TITLE
Cadena de misiones Forjando una alianza

### ISSUE THREAD

**Issue by jandrox** [RoDNet/Bugtracker-Infinium-4.0.6a#326]
La misión inicial Forjando una alianza no se puede hacer ya que no se puede hablar con el rey Jokkum (coords. 65/60 de Cumbres Tormentosas) ya que aparece como hostil y no da lugar a hablar con el sino que ataca si te acercas.

Link: http://es.wowhead.com/quest=12924

Un saludo.

**Comment by HexR-zz** [comment]
En la siguiente actualización será amistoso, si las misiones dan problema crea otro issue pls, graciaas
