### ISSUE TITLE
Talento abrazo de la muerte (death's embrace) medio bug

### ISSUE THREAD

**Issue by jazzberri** [RoDNet/Bugtracker-Infinium-4.0.6a#33]
Veamos, este talento tiene que hacer 2 cosas, una la hace y la otra la hace pero mal xD.

La parte que hace mal es la de aumentar lo que cura la habilidad drenar vida cuando el brujo tiene un 25% de salud o menos.

Deberia sanarle un 3% de la vida total del brujo mas lo que cure de por si drenar vida hasta que llegue a tener 25% de vida. (Esto interpreto yo al leer el talento)

con mi brujo drenar vida cura 1995 en cada tick y teniendo menos del 25% de la vida deberia curarme 2994 de vida a mayores en cada tick de drenar vida ya que esta cantidad es el 3% de mi vida total que es 99800.

Resumiendo, con 25% o menos de vida drenar vida deberia curarme 2994 + 1995 pero esta curandome 4998 + 1995 por lo tanto haciendo la cuenta me esta curando un 5% extra de mi vida total en ved de un 3%.

http://old.wowhead.com/spell=47200#comments

**Comment by adrianrp1988** [comment]
Testeado, funciona correctamente
