### ISSUE TITLE
Misiones [¡Fiesta de pollos! y ¡Se dieron a la fuga!] Bug

### ISSUE THREAD

**Issue by RodMadmel** [RoDNet/Bugtracker-Infinium-4.0.6a#332]
No hay pollos donde deberían estar. Simply: No pollo, no way.

Screen: http://i50.tinypic.com/xlkz9w.jpg

Saludos!

**Comment by DatJetto** [comment]
Bien, la iba a poner ahora xD que me he jartado de hacer quest pa repu y me he quedado en venerado ahí casi exaltado t_t y las quest de repu tan bug

**Comment by RodMadmel** [comment]
Yo ya soy Exaltado con los pulgosos éstos, sólo queda arreglar la cadena de quests que al final te llevan a la cueva a matar el élite ese feo y pasarse al bando Oráculo. :P

**Comment by DatJetto** [comment]
cómo subiste la repu? :c yo hice casi todas menos las bug... que son las diarias, las de la tormenta y los vientos de coger 3 la pudiste hacer? :c

**Comment by RodMadmel** [comment]
Sí, me acerqué al pilar ese, lo rodeé y contó. Ah, y tambien va la de la Matriarca y el agua el pilar torquesol creo que se llama.

**Comment by DatJetto** [comment]
Esa el agua no me dejaba cogerla... me dejaré los dedos en el agüita del pilar a ver...

**Comment by RodMadmel** [comment]
Aquí te dejo una screen donde pienso y creo recordar que casteé la recogida del agua:

http://i50.tinypic.com/2rm74eh.jpg

Por probar... xD

**Comment by HexR-zz** [comment]
machooo pon los links de las misiónes pls!! que así voy de cabeza a la db y no me entretengo busscando cuál es la quest

**Comment by RodMadmel** [comment]
Jajaja ok ok, si me lo pones en una refresco los demas posts, si empiezas a buscar las vas a encontrar todas igual xD

**Comment by RodMadmel** [comment]
Misión Fiesta de pollos: http://es.wowhead.com/quest=12702
Misión Se dieron a la fuga: http://es.wowhead.com/quest=12532
NPC Objetivo: http://es.wowhead.com/npc=28161/pollo-fugitivo

**Comment by RodMadmel** [comment]
HexR, cualquier cosa que pueda hacer mejor o más efectivo avísamelo, si total: todo lo que mejore  nos facilitará la vida a tí y a mí. xD

**Comment by HexR-zz** [comment]
Pues ale, pollitos everywhere! De acuerdo Madmel, gracias por los reportes ^^
