### ISSUE TITLE
Misión [Rejek: Primeras manchas de sangre] Bug

### ISSUE THREAD

**Issue by RodMadmel** [RoDNet/Bugtracker-Infinium-4.0.6a#333]
Matas al mob en cuestión, activas la espada, castea, y no ocurre nada más. He probado en varios mobs, y casteado el item mogollón de veces y nada. No hay manera.

Screen: http://i50.tinypic.com/23vg589.jpg

Saludos!

**Comment by HexR-zz** [comment]
link misión pls :(

**Comment by RodMadmel** [comment]
Misión: http://es.wowhead.com/quest=12734
Objetivo Avispa: http://es.wowhead.com/npc=28086
Objetivo Gorila: http://es.wowhead.com/npc=28096
Objetivo Miembro susurraneblina: http://es.wowhead.com/npc=28109

**Comment by RodMadmel** [comment]
Revísame esto :p 

https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/337

**Comment by searum** [comment]
fix
