### ISSUE TITLE
Misión [Un viaje complicado] Bug

### ISSUE THREAD

**Issue by RodMadmel** [RoDNet/Bugtracker-Infinium-4.0.6a#334]
Se supone que al entregarte la misión te dan un item, concretamente el Cuerno de caza de Zepik. Sin este objeto, es imposible invocar al npc y entregar la misión para seguir con la cadena. PD: No te dan el item. xD

Screen:  http://i49.tinypic.com/250l0ex.jpg

Salu2

**Comment by HexR-zz** [comment]
Pon el link de la misión que debería darte el ítem y el del ítem por favor.

**Comment by RodMadmel** [comment]
NPC que te da la misión y el objeto (En primera instancia): http://es.wowhead.com/npc=28082
Misión: http://es.wowhead.com/quest=12536
NPC que te da el objeto (En caso de pérdida o robo): http://es.wowhead.com/npc=28138
Objeto: http://es.wowhead.com/item=38512

**Comment by HexR-zz** [comment]
Listo, cuando se coja la quest en el siguiente parche lo darán

**Comment by RodMadmel** [comment]
Así da gusto: Yo reporto, y vosotros arreglais. :P
