### ISSUE TITLE
Misión [Un casco de héroe] Bug

### ISSUE THREAD

**Issue by RodMadmel** [RoDNet/Bugtracker-Infinium-4.0.6a#335]
La 1ª parte de esta misión va bien, se consiguen los explosivos sin problemas, lo malo es al matar un Vigía de tormenta y usar los explosivos sobre él, no ocurre nada.

Screen: http://i49.tinypic.com/vyaavb.jpg

Salosdu!

**Comment by HexR-zz** [comment]
Pon el link del bicho a wowHead pls

**Comment by RodMadmel** [comment]
Enlace al NPC: http://es.wowhead.com/npc=28877
Enlace al Item: http://es.wowhead.com/item=39667

A partir de ahora reportaré ya v2.0 gracias por el aviso, total no me cuesta y así os cunde más ;)

**Comment by HexR-zz** [comment]
fixed, pero cuando se actualice, ten en cuenta que la cabeza no la vas a poder lootear hasta que desaparezca el cuerpo del gigante (60segundines), no sé por qué pasa esto peroo así es :S

**Comment by RodMadmel** [comment]
No problem.
