### ISSUE TITLE
Misión [Pura diversión] Bug

### ISSUE THREAD

**Issue by RodMadmel** [RoDNet/Bugtracker-Infinium-4.0.6a#337]
Aquí te dan un láser pa cepillarte el ojo azul de Zauron, lo que pasa es... bueno, la screen lo dice todo:

http://i48.tinypic.com/15xmxp3.jpg

Qué pexá de reportar... xD

**Comment by HexR-zz** [comment]
Pero si lo matas te cuenta? Eso es que le falta el displayID nada más

**Comment by HexR-zz** [comment]
po ale ficed

**Comment by RodMadmel** [comment]
No, si no muere! :S  Ahí está, en que el npc targeteable aparece amistoso! xD No se puede matar, le quitas 2k usando el objeto y se autoregenera. No entras ni en combate.

**Comment by HexR-zz** [comment]
a valee que sale amistoso okok, pues también estará arreglado para la próxima actualización, además de completarse esta vez, que tampoco funcionaba. Gracias por esos reportes v2.0 xD

**Comment by RodMadmel** [comment]
A mandar.
