### ISSUE TITLE
Talento Quemar alma. Semilla de corrupcion

### ISSUE THREAD

**Issue by jazzberri** [RoDNet/Bugtracker-Infinium-4.0.6a#34]
Este talento no funciona directamente.

Al activar la skill quemar alma y acto seguido lanzar semilla de corrupcion lo que deberia ocurrir es que al explotar semilla de corrupcion esta deberia de poner corrupcion a todos los enemigos afectados por semillar de corrupcion al explotar.

En este video se ve que afecta a 2 objetivos que ademas el pj del video targetea y en ambos se ve como ha dejado puesto en ellos corrupcion.

http://old.wowhead.com/spell=86664

http://www.youtube.com/watch?v=raX7hIqVIK4        a partir del 1:20 xD

**Comment by adrianrp1988** [comment]
Reparado en la proxima Rev
