### ISSUE TITLE
[ Hunter > Mastery > Wild Quiver ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#342]
Carcaj  salvaje: http://old.wowhead.com/spell=76659
Disparo de carcaj salvaje: http://old.wowhead.com/spell=53254

La maestría del Hunter Marksmen no funciona, nunca lanza un proyectil extra con 80% weap damage

**Comment by Dekadencee** [comment]
Hoy han sido fixeadas todas las maestrías, mañana mismo estarán disponibles en el servidor ^^
