### ISSUE TITLE
Mago Fuego (Piroexplosion bug , talento Buena Racha)

### ISSUE THREAD

**Issue by cacox** [RoDNet/Bugtracker-Infinium-4.0.6a#343]
Hola les queria comentar que el talento "Buena Racha" esta bug , debido a que cuando se castea "Piroexplosion" con la "Buena Racha" activada realiza un daño de 3k (daño normal) y cuando se lanza normalmente en mi caso hace 12k (daño normal). porfavor arreglen este bug es indispensable ese poder para mi

**Comment by Faked** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/39

**Comment by HexR-zz** [comment]
estará arreglado
