### ISSUE TITLE
Bug Pnj Uldum (Exageracion de salud)

### ISSUE THREAD

**Issue by jaime0510** [RoDNet/Bugtracker-Infinium-4.0.6a#344]
![image](https://f.cloud.github.com/assets/3056816/43629/6306a090-568f-11e2-9c4c-51e26428706e.png)

Como pueden ver este Pnj tiene 250.000 mil veces la salud que deberia tener, su salud se asemeja a la de un Boss o elite de istance.

http://es.wowhead.com/npc=48043/ladron-pigmeo

**Comment by HexR-zz** [comment]
zanqiu
