### ISSUE TITLE
Misión [Tres amigos del Bosque] Bug

### ISSUE THREAD

**Issue by Arkatla** [RoDNet/Bugtracker-Infinium-4.0.6a#346]
Hola, bueno el fallo con la misión "Tres amigos del Bosque" en Vallefresno es que Bolyun, el personaje con quien se debería terminar la misión no aparece, solamente aparece el icono en el mapa de que ahi deberia de poderse completar la misión pero por mas tiempo que se espere el personaje no aparece.

![WoWScrnShot_010413_144156](https://f.cloud.github.com/assets/3188434/44191/1f5e7ba6-56b2-11e2-93a5-d825136ea80d.jpg)

![WoWScrnShot_010413_145948](https://f.cloud.github.com/assets/3188434/44192/2424dd56-56b2-11e2-8b24-b5a7b78a0d73.jpg)

Así es como debería de aparecer

http://es.wowhead.com/quest=13976

**Comment by searum** [comment]
fix para siguiente update
