### ISSUE TITLE
Talento afliccion eterna (everlasting aflicction) bug

### ISSUE THREAD

**Issue by jazzberri** [RoDNet/Bugtracker-Infinium-4.0.6a#35]
Veamos, el talento con todos sus puntos dice que las habilidades drenar vida, drenar alma y poseer tienen 100% de probabilidad de reiniciar la duracion del hechizo corrupcion en el objetivo.

No reinicia la duracion de corrupcion ninguna de las 3 habilidades por lo tanto bug 100% el talento.

http://old.wowhead.com/spell=47203#see-also-ability

**Comment by adrianrp1988** [comment]
Reparado en la próxima Rev
