### ISSUE TITLE
problema con la cuenta URGENTE

### ISSUE THREAD

**Issue by juanito123** [RoDNet/Bugtracker-Infinium-4.0.6a#350]
hola perdona las molestias ya he publicado como 3 vces lo mismo , es sobre mi cuenta que no me deja entrar y tu me dices que publique en em foro pero no me deja publicar nada por eso escribo mi problema a qui , por favor atiendeme  , mi pj se llama cataclyms si quieres mas info comenta por favor GRACiAS POR TU ATENCION *

**Comment by searum** [comment]
pero... por qué no te deja entrar? te han cambiado el pass o algo?

**Comment by juanito123** [comment]
nose  lo raro en esque la clave y el usuario son correctos pero no me deja entrar, tu eres un jugador o un gm ? si eres jugador podrias hablar  con un gm en el juego  y le podrias decir que paso con mi pj y mi cuenta GRACIAS intenta hanlar con helky

**Comment by HexR-zz** [comment]
Qué error te da para no dejarte entrar?

**Comment by juanito123** [comment]
ya por fin me dejo entrar , y no era ningun error nose que fuera :S
