### ISSUE TITLE
Misión [La caverna del maestro] Bug (No deja entregar)

### ISSUE THREAD

**Issue by RodMadmel** [RoDNet/Bugtracker-Infinium-4.0.6a#354]
NPC al que entregar: Andormu http://es.wowhead.com/npc=20130
Misión: http://es.wowhead.com/quest=10279

No la deja entregar alegando: No cumples los requisitos necesarios para esa misión. (Mensaje de chat)

**Comment by verchdragon** [comment]
asi estoy yo  pero quieren que haga otro  tema del mismo  Bug :-1:  no le veo caso  espero  nos resuelvan pronto

**Comment by redneo** [comment]
Arreglada.
