### ISSUE TITLE
Talento pandemia (pandemic) bug

### ISSUE THREAD

**Issue by jazzberri** [RoDNet/Bugtracker-Infinium-4.0.6a#36]
Este talento tiene 2 partes:

la 1º parte no se testearla (sorry) pero hay un comentario en ingles en wowhead que dice que tiene que hacer esta parte.

la 2º parte la he testeado y esta bug, dice asi: con los 2 puntos en el talento tiene un 100% de probabilidad de reiniciar la duracion de afliccion inestable cuando el objetivo tiene 25% de salud o menos pero esto no lo hace.

http://old.wowhead.com/spell=85100#comments

**Comment by DatJetto** [comment]
La primera parte es ver cuanta reutilización tiene la spell sin el talento y cuando pones el talento ver si tiene 5 sec menos según lo que pone en el talento, de todas formas , la reducción de reutilizaciones suele estar bien :camel:

**Comment by adrianrp1988** [comment]
Reparado en la proxima Rev
