### ISSUE TITLE
Reforjar (Ind. de Golpe)

### ISSUE THREAD

**Issue by Paketon** [RoDNet/Bugtracker-Infinium-4.0.6a#361]
Buenas.  Hace ya tiempo reforje para llegar al 5% de ind de golpe famoso. Lo deje cerca del 5% y al tiempo vi que fallaba mas de lo normal. Y sin tocar nada mas vi que estaba en 3,7% sin cambiar ningun reforjado. 
Hoy he borrado todo lo que tenia reforjado con el rogue. He rejorjado 3 cosas y tomado foto para que se vea que llego a mas de 5%. He desconectado y vuelto a entrar y me ha vuelto a bajar al 3.7%
Y los 3 items que reforje salen con el Ind. de golpe que le he puesto extra, pero parece que no lo aplica.
![WoWScrnShot_010613_110847](https://f.cloud.github.com/assets/3197965/45856/1ffaf032-57eb-11e2-9776-1e0821414e5b.jpg)
![WoWScrnShot_010613_111023](https://f.cloud.github.com/assets/3197965/45857/2a3baf5a-57eb-11e2-99d5-94d22cd2a15f.jpg)

No se si solo pasa con este pj y I.Golp. o con todo.

**Comment by 50megas** [comment]
ami tambien me pasa eso con el indice de golpe al reforjar, ingluso las piezas q medavan indice de golpe no me davan , es como si al reforjar a indice luego al logear perieras el indice de los item o sea un bug visual como lei en el foro.

luego testeare si tenemos el 5% de indice o no con un dumy

**Comment by 50megas** [comment]
ya lo testee y no es un bug visual perdemos el indice,luego cuelgo la foto que voi a comer.

<a href="http://tinypic.com?ref=34g36n6" target="_blank"><img src="http://i48.tinypic.com/34g36n6.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

como se puede ver la bajada de indice es real

**Comment by GorThauR** [comment]
mmm he testeado con mi brujo y tb me pasa :S lo dejé cerca de 15% y me sale 12 :S

**Comment by 50megas** [comment]
me quitado los reforges a indice, me quedado con 1,2 de indice e logueado y tenia 3,2 ,tocara refojar a otra cosa y engemarse a indice mientras se corrige

**Comment by 50megas** [comment]
weno testeado los reforges,parece ser que en(celerida,critico,indice de golpe,pericia),cuando logeas se desacen ,pero ala vista del equipo sigue reforgado,recuperas todo lo que te quitaste al refojar y pierdes lo que te pusiste

**Comment by Dekadencee** [comment]
Reporte duplicado lo seguimos desde su reporte anterior: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/361
