### ISSUE TITLE
Wowerror al finalizar arenas

### ISSUE THREAD

**Issue by Paketon** [RoDNet/Bugtracker-Infinium-4.0.6a#362]
Pasa bastante cuando se acaba una arena salta wowerror. No he logrado ver nada común todas las veces que pasa :S 
Aun así si ganas te da los puntos correctamente y te cuenta como ganado. 

También reporto de paso que ayer en una arena que no entro la otra pareja nos quedamos yo y mi compa solos... y no salia automáticamente dándonos por ganada la arena.
Salí yo primero y me contó como perdida y a mi compa como ganada. Otro día tampoco se presentaron los contrarios pero si salio nada mas empezar y nos contó como ganada a los 2.

Saludos ^^

**Comment by aerz** [comment]
El fallo con el cliente sseguramente sea de tu instalación, pregunta a tus amigos si a ellos les sucede lo mismo.
Si les pasa igual, entonces tendríamos que revisar esa parte, si no, reinstala tu wow o actualiza los drivers de tu tarjeta gráfica.

Saludos.

**Comment by Dekadencee** [comment]
Reporte duplicado, lo seguimos desde el reporte anterior: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/82
