### ISSUE TITLE
bug glifo de roge

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.0.6a#365]
el glifo http://es.wowhead.com/spell=92579/glifo-de-ceguera no funciona.

deveria quitar los daños en tiempo para que no se rompa la cegera pero no lo hace

un glifo muy util para los picaros  en pvp

**Comment by DatJetto** [comment]
añado la spell: http://es.wowhead.com/spell=91299

**Comment by searum** [comment]
fix
