### ISSUE TITLE
Bug quest Vida de la muerte

### ISSUE THREAD

**Issue by chipi666** [RoDNet/Bugtracker-Infinium-4.0.6a#369]
En tierras Altas crepusculares la quest Vida de la muerte los mob que se tienen que matar para completar la quest aparecen verdes y no se pueden atacar.
![WoWScrnShot_010613_090700](https://f.cloud.github.com/assets/3199832/46129/e2f770e0-5824-11e2-8e15-cfa2c1ef7cb7.jpg)

**Comment by chipi666** [comment]
Hola yha pueden cerrar este problema ya que no ocupas matarlos :p sorry me fui con las indicaciones de la quest, saludos...

**Comment by asfo** [comment]
Cierro por reporte equivocado y a petición del usuario.
