### ISSUE TITLE
Talento abrazo demoniaco (brujo) bug

### ISSUE THREAD

**Issue by jazzberri** [RoDNet/Bugtracker-Infinium-4.0.6a#37]
Este talento con sus 3 puntos deberia aumentar en un 10% el aguante del brujo cosa que si hace pero creo que el la vida o salud que aumenta esta mal, me explico:

el 4% de 4701 es 188 y sumandole esto a 4701 suma 4890 que si que sale eso pero el fallo viene ahora

Segun he leido aquí http://es.wow.wikia.com/wiki/Atributos#Cataclysm 1 punto de aguante son 10 puntos de vida, por lo tanto 188 de aguante son 1880 de salud / vida y si mi vida sin el talento es 103738 acto seguido le doy 1 punto de talento y me sube 2646 de vida algo falla porque debería haber subido solo 1880 como dije anteriormente.

No sé de donde viene el fallo, quizás se este calculando mal a cuanto equivale 1 punto de vida en el emulador, no sé, es una opinión.

http://old.wowhead.com/spell=18699#see-also-ability

**Comment by adrianrp1988** [comment]
este talento lo que hace es incrementar la stamina en un 10%, no los HP, por lo que creo que esta bien el talent

**Comment by jazzberri** [comment]
Tienes razón, he leido fatal el talento y por lo tanto he confundido aguante con vida total pero comprobandolo ahora de nuevo bien creo que sigue bug igual asique reedito el post.

**Comment by adrianrp1988** [comment]
tienes que tener en cuenta los puntos de hp que da el stamina, no recuerdo bien como era, pero si recuerdo que varian

**Comment by macols77** [comment]
Haber, vamos a aclarar este tema:
Suponiendo que tu tienes 4701 puntos de aguante y según la web que has puesto que pone lo siguiente: Proporciona 10 puntos de salud por cada punto de Stamina (EXCEPTO los primeros 20 puntos de Stamina que propocionan 1 punto de salud).
Bien ahora volvemos a los 4701 y le aplicamos el 10% (1 punto en ese talento es el 10%) que es 470,1 y ahora a el total de los puntos de aguante le sumamos el 10%, es decir, 4701 + 470,1 = 5171,1p. de aguante.

Ahora vamos a calcular la vida que te tiene que dar, sabiendo que los 20p primeros de aguante valen 1 punto;
5171,1 - 20 =5151,1
5151,1 \* 10 = 51511 + 20 = 51531p. de vida.
Esto es el total de vida que te tiene que dar todo tu aguante.
Ahora si solo lo hacemos lo que te tendría que dar el 10%, es decir, 470,1 seria: 4521p de vida.

Según lo que he leído y con tus datos ese tendría que ser el resultado.

Un saludo^^^

P.D: Ahora que he seguido leyendo, en la web que has pasado (http://es.wow.wikia.com/wiki/Atributos#Cataclysm) pone lo siguiente:
- El talento Demonic Embrace (Demonology, tier 1) proporciona +3% de bonus de stamina por cada punto de talento, máximo 5.

Entonces yo ya no se a quien creer, si a wowhead o a esa web o yo que se.. No tengo actualmente cliente por lo cual no puedo comprobar ninguna de las cosas que he dicho antes.

**Comment by coste23** [comment]
buenos dias eh la profesion ARQUEOLOGIA esta bug por favor la pueden corregir muchas gracias.

**Comment by macols77** [comment]
Abre una issue con toda la informcion relaccionada con arqueologia para poder arreglarlo; funcionamisnto, materiales, donde se encuentra, etc

Un saludo
