### ISSUE TITLE
Bestias espirituales deshabilitadas

### ISSUE THREAD

**Issue by Sagittariu5** [RoDNet/Bugtracker-Infinium-4.0.6a#375]
Bueno,principalmente no se cuales seran las que esten deshabilitadas pero Alanys me dijo que Skoll   no estaba por lo tanto tenia que reportarlo ya que para un caza las experiencias de conseguir sus rares con esfuerzos como consegui los 2 que tengo que me tomo mucho rastrearlos aunque ya les pille el truco es seriamente frustrante y tambien parace ser que los sitios de respawn aleatorios de aquellas bestias tampoco no estan ya que reviven en el mismo sitio o 10 metros de el por favor yo morire feliz si pudieran habilitarlo aqui la info

http://es.wowhead.com/npc=35189#.

**Comment by asfo** [comment]
Te recuerdo que hay ciertas bestias que tienen un respawn muy largo. Se comprobará la información y se dará solución en caso de que se encuentre con problemas.

**Comment by DatJetto** [comment]
a Skoll lo he visto bastantes veces y no tiene un respawn muy alto que digamos :C

**Comment by asfo** [comment]
Cierro, se irá investigando entonces por reporte concreto de cada bestia. 
Skoll queda fuera de la lista al saber que se encuentra por @DatJetto
