### ISSUE TITLE
Transfiguración

### ISSUE THREAD

**Issue by Paketon** [RoDNet/Bugtracker-Infinium-4.0.6a#377]
Cuando transfiguras un set por ejemplo pones sanguinario en un sañoso, al pasar raton por encima no te salen las partes del set que tienes en realidad, solo lo que has transfigurado. Supongo que lo correcto es que te salga lo que en realidad tienes.
Tambien da algun problema al borrar una transfiguracion, a veces lo borra y al reloguear te vuelve a aparecer alguna parte ke habias reseteao. Pero insistiendo se queda como kieres xD

**Comment by asfo** [comment]
El caso de transfiguración es:
1.-Te salga el set "cambiado", el icono si es a lo que te refieres, debería salirte el original, sin embargo al ser una implementación "poco blizzlike" por la versión supongo no se le dará la importancia por ahora.
2.-No se entiende eso, ¿borras el objeto y luego te reaparece?...

**Comment by Paketon** [comment]
No..... creo ke lo he explicado bien XD
Transfiguras unas hombreras. Te cansas de la forma ke le distes y quieres ke vuelva a la original. Vas a borrar la transfiguracion (no ningun objeto) para ke vuelva a esa forma. Algunas veces lo hace correctamente y el objeto se keda en su apariencia normal. Pero otras tras reloguear vuelve a la forma transfigurada que quisiste quitar.

**Comment by searum** [comment]
a esto no se le da soporte, a partir de la 434
