### ISSUE TITLE
talento que no funciona

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.0.6a#382]
el talento de chaman ,de la rama mejora  http://old.wowhead.com/spell=77701 no funciona bien.

si bien, si aumenta el 30% del daño de latigazo de lava;lo que no hace es consumir los dot de llamas abrasadoras,para asi aumenta un 20% el daño de latigazo de lava por dot ,llegado al 100% mas de daño con 5 dot y eliminandolos.

**Comment by searum** [comment]
fix
