### ISSUE TITLE
exceso de heal del chaman mejora

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.0.6a#383]
weno queria comentar que las curas en  especial  http://es.wowhead.com/spell=77472 para la rama mejora cura demasiado un 30% o mas  de lo que deveria.

en otras versiones del servidor con similar equipo ,me curaba 20k y 30k de critico,pero  a pasado a 30k y criticos 46k y con el talento http://es.wowhead.com/spell=77472 y  que te las puedes hechar istantaneas cada 12 a 15 segundos, siempre que estes pegando a alguien. me parece demasiado

foto sin critico

<a href="http://tinypic.com?ref=2chkr52" target="_blank"><img src="http://i45.tinypic.com/2chkr52.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

foto con critico

<a href="http://tinypic.com?ref=2rnapuc" target="_blank"><img src="http://i48.tinypic.com/2rnapuc.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by DatJetto** [comment]
pf debe cuarte unos 16k y te da 30 JAJAJ

**Comment by HexR-zz** [comment]
Debería ir arreglado en el mismo lote que el escudo de tierra, no obstante, este issue lo dejo abierto para comprobarlo en el próximo parche. Gracias por reportar

**Comment by asfo** [comment]
@HexR Cierro. Si sigue con problemas, se reabrirá o abrirán uno nuevo ;)
