### ISSUE TITLE
Hechizo de Hermandad [Piedra Presta] Bug

### ISSUE THREAD

**Issue by RodMadmel** [RoDNet/Bugtracker-Infinium-4.0.6a#384]
Piedra presta: http://es.wowhead.com/spell=83944
Screen de la Piedra "No" Presta: http://i46.tinypic.com/f9ny3d.jpg

http://cdn.memegenerator.net/instances/400x/33098877.jpg

**Comment by asfo** [comment]
Ya está reparado y será implementado en la próxima actualización.

Cierro.
