### ISSUE TITLE
Explorar mapa Los Baldios Sur

### ISSUE THREAD

**Issue by pablolabbe** [RoDNet/Bugtracker-Infinium-4.0.6a#386]
No se puede explorar la instancia que se encuentra en los baldios sur para poder obtener el logro de exploración del mapa en cuestion

http://es.wowhead.com/zone=491   Horado Rajacieno no se puede explorar

**Comment by RodMadmel** [comment]
Este tema ya se encuentra posteado en https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/313.

Gracias por tu aporte. ^^

**Comment by Dekadencee** [comment]
Reporte duplicado lo seguimos desde el reporte anterior https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/313
