### ISSUE TITLE
cuna del invierno

### ISSUE THREAD

**Issue by aperionn** [RoDNet/Bugtracker-Infinium-4.0.6a#388]
hola, solo quier reportar que en cuna del invierno la quest " Gigantes Machacadores" esta bug, 
si te da la mision el pnj, pero al ir al lugar donde hay quie matar a los Gigantes machacahielo y valedor machacahielo, estos no aparecen.

por su apoyo muchas gracias

saludos desde mexico.

**Comment by asfo** [comment]
¿Por qué abriste un tema y lo cierras tu mismo? S: ¿está o no está bug?

No reabro hasta la comprobación del usuario.
