### ISSUE TITLE
Mago [Piroexplosión instantanea] Skill

### ISSUE THREAD

**Issue by Faked** [RoDNet/Bugtracker-Infinium-4.0.6a#39]
La skill http://es.wowhead.com/spell=11366/piroexplosion , cuando se activa el talento Buena racha pega mucho menos de lo que debería pegar

Captura de imagen:

Piroexplosion critica NO INSTANTANEA
http://i46.tinypic.com/jzjsx4.jpg

Piroexplosion normal INSTANTANEA 
http://i45.tinypic.com/34pal3o.jpg

Además, cada vez que salta ''Buena racha'' Aparece ''has aprendido una nueva habilidad: piroexplosion'' y cuando haces el ataque vuelve a salir

**Comment by Aixxa** [comment]
doy fe de ello, da bastante problema la verdad... solo va mal con cada buena racha que es lo extraño... es como si disparase alguna de rango inferior ( en plan woltk ) o algo asi

**Comment by skyrex321** [comment]
Incluso en Woltk pegabas mas con Pyro Instant... xd  el dmage de Pyro instant en critico debe  estar alrededor de 18-19k no 7-8k como esta ahora... y eso con temple...

**Comment by andrixx** [comment]
Cierto ami me pasa lo mismo creo que lo que pasa es que se buguea y se tira un rango bajo, pueden ver que dice que has aprendido Piroexplocion en el chat... siempre pasa eso.

**Comment by xilopipe** [comment]
El mismo bug de casi todos los servers privados xd

**Comment by HexR-zz** [comment]
FIXED
