### ISSUE TITLE
Set Brutal de arenas

### ISSUE THREAD

**Issue by Frozentri** [RoDNet/Bugtracker-Infinium-4.0.6a#393]
deberian poner a disposición de los jugadores los set de pvp de nivel 70. Me he paseado por todos los vendores y no logro encontrarlos.

**Comment by asfo** [comment]
Estos sets están eliminados hasta la versión 4.2.0 me parece, o en la versión de la transmogrificación regresan (no se si es la 4.2.0, 4.1.0 o cual :P).

Cierro al ser solo una sugerencia, sugerencias al foro.
