### ISSUE TITLE
Druida: Cambio de forma

### ISSUE THREAD

**Issue by avangers321** [RoDNet/Bugtracker-Infinium-4.0.6a#394]
apartir del 4.0.6 el cambio de forma no deberia quitar las relentizacion aplicadas sobre el druida. pero veo que aqui los druidas se los quitan como si nada.

**Comment by asfo** [comment]
http://www.wowhead.com/spell=768 Lee al final...
"The act of shapeshifting frees the caster of movement impairing effects."
Traducción:
"El cambio de forma libera al taumaturgo de los efectos de reducción de movimiento."

http://es.wowhead.com/spell=768

Y no ha sido modificado desde que se anexo al Druida....
PD: Todas las formas tienen el mismo efecto. Cierro por hasta obtener una respuesta del usuario.

**Comment by avangers321** [comment]
si bien se pueden quitar los efectos de reduccion, no puedes quitarse los las congelaciones como el nova de escarcha que congela durante 7 a 8 seg, o congelacion del elemental de agua que congela durante 8 seg, o el cono frio que congela durante 4 seg, que e visto en bgs en mas de una ocasion quitarselos como si nada con el cambio de forma.

**Comment by asfo** [comment]
Cualquier efecto que realentice al druida a excepción de stuns completos son removidos, ningún efecto que no sea stun simplemente no se queda en el druida cuando hace transformación y es inmune a polymorph.

Así mismo, los spells de realentización y stuns en personajes aplicados su tiempo es reducido, si un stun normalmente en un NPC dura 10 segundos, en un jugador podría durar 5 o 6 por poner un ejemplo...

**Comment by avangers321** [comment]
pero los que e nombrado no son efectos de relentizacion son efectos de frenado dejando al jugador inmovil al = que el enraizado del totem del chaman.

**Comment by asfo** [comment]
Es a lo que voy, cualquier cosa que le elimine el movimiento y no sea stun, cuenta para que se elimine. Por ejemplo, si le ponen una trampa congelante, el Druida no se puede mover, pero si el druida no está detenido con un stun, puede hacerlo cambiando de forma.

**Comment by avangers321** [comment]
no es asi :S, esto es lo que dice en el parche 4.0.6, http://es.wow.wikia.com/wiki/Parche_4.0.6
Cambios de forma: tomar o dejar un cambio de forma ya no cancela los efectos de enraizamiento. Sigue cancelando los efectos de ralentización de movimiento. segun mi modo de entender cancela las relentizaciones mas no los frenados y si revisa en casi todos los servidores 4.0.6 ningun druida va a poder quitarse ningun efecto de frenado de movimiento.

**Comment by asfo** [comment]
Enraizamiento sería como las raíces que ponen los shamanes y los druidas si no estoy mal, en dado caso pondrían algo así como "congelamiento" también quizá, debo investigar ;).

**Comment by avangers321** [comment]
ok, gracias

**Comment by DatJetto** [comment]
*Cambios de forma: tomar o dejar un cambio de forma ya no cancela los efectos de ENRAIZAMIENTO. Sigue cancelando los efectos de ralentización de movimiento.
Es decir, no cancela los efectos que aplican /Root/ en el druida, en wow el efecto / Rooting /  se entiende como enraizamiento cualquier tipo  de hechizo que te haga quedarte quieto en el sitio, impidiendo el movimento.
A continuación especifica, que sí elimina las ralentizaciones como Disparo de conmoción / Seccionar / Ralentizar.

**Comment by asfo** [comment]
Yo ya chequé esto y si los elimina, por lo que lo mantendré cerrado, comprobado en el oficial cuyo efecto sigue siendo el mismo tal y como está en pelea contra un mago.
