### ISSUE TITLE
[Hunter > Spec: General > Spell > Camouflage]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#4]
-Camuflaje http://es.wowhead.com/spell=51753  
Edit: 19 / 1 / 13 

Descripción:  
Te camuflas, mezclándote con tu entorno, lo que evitará que puedan seleccionaros como objetivo de ataques a distancia a tu mascota y a ti. También reduce el alcance al que pueden detectarte las criaturas enemigas y os proporcionará sigilo mientras no os mováis.

Puedes colocar trampas bajo este efecto, pero cualquier daño que inflijáis tú o tu mascota cancelará el efecto.

------------------------------------------------------------------------------------------------->

Cuando lanzas estas spells se elimina el aura de camuflaje, no debiendo ser así

1 - Bengala: http://es.wowhead.com/spell=1543

2 - Cualquier trampa;
http://es.wowhead.com/spell=34600
http://es.wowhead.com/spell=1499
http://es.wowhead.com/spell=13809
http://es.wowhead.com/spell=13813
http://es.wowhead.com/spell=13795

Curar la pet, http://es.wowhead.com/spell=136

3 - Los aspectos:
http://es.wowhead.com/spell=13165 Halcón
http://es.wowhead.com/spell=5118 Guepardo
http://es.wowhead.com/spell=82661 Zorro

4 - Empezar a Castear Spells:

Disparo de puntería: 
http://es.wowhead.com/spell=19434

Disparo firme:
http://es.wowhead.com/spell=56641

Disparo de cobra:
http://es.wowhead.com/spell=77767

5 - Cuando la pet pone un buff de área como 
*Rugido de valor: http://es.wowhead.com/spell=93435
*Aullido furioso: http://es.wowhead.com/spell=24604
El camuflaje tanto para ti como para la pet se va, no debiendo irse. 

6 - Cuando le pegan a tu pet, el camuflaje de tu pet ha de irse, el del cazador no, sin embargo, cuando la pet o yo hacemos daño, ahí si ha de quitarse para ambos.

**Comment by adrianrp1988** [comment]
Fix
