### ISSUE TITLE
Camuflaje cazador bug

### ISSUE THREAD

**Issue by xefirot** [RoDNet/Bugtracker-Infinium-4.0.6a#402]
La habilidad de camuflaje del cazador cumple bien su objetivo de ocultación, pero cuando está en ese modo no puede ser atacado, se puede targetear pero no lo reconoce como objetivo.

http://imageshack.us/photo/my-images/202/wowscrnshot011013202535.jpg/

**Comment by DatJetto** [comment]
uff no se ve nada @_@ prueba con http://tinypic.com/

**Comment by xefirot** [comment]
Si haces click encima de la imagen se amplia

**Comment by Faked** [comment]
Te camuflas, mezclándote con tu entorno, lo que evitará que puedan seleccionaros como objetivo de ataques a distancia a tu mascota y a ti, reduce el alcance en que pueden detectarte las criaturas enemigas y os proporcionará sigilo mientras no os mováis.

A DISTANCIA, eso es cuerpo a cuerpo

**Comment by xefirot** [comment]
A ver hijo mio... que parece que no has pillado de que va esto...en la imagen, que por tu comentario no has entendido, se ve que yo le doy duelo a un compañero que es cazador y este estando en camuflaje NO SE LE PUEDE PEGAR. El bug está en que NO SE LE PUEDE ATACAR AUN HABIENDO SIDO DETECTADO E INCLUSO ESTAR A MELEE.

**Comment by DatJetto** [comment]
Faked, camuflaje funciona de tal manera que solo pueden seleccionarte y pegarte a melee, para romper el camuflaje, aparte de spells en AoE, el problema viene cuando, a melee no te deja pegarle al cazador xD

**Comment by jandrox** [comment]
Ya que va del camuflaje del cazador, poner tb que cuando usas el camuflaje con npcs, estos no solo te ven sino que parece que aumentas la amenaza para que te ataquen todos  :(

Un saludo.

**Comment by searum** [comment]
arreglado
