### ISSUE TITLE
Druida: Cambio de forma

### ISSUE THREAD

**Issue by avangers321** [RoDNet/Bugtracker-Infinium-4.0.6a#403]
Si bien se pueden quitar los efectos de reduccion de movimiento, no puedes quitarse las congelaciones como el nova de escarcha que congela durante 7 a 8 seg, o congelacion del elemental de agua que congela durante 8 seg, o el cono frio que congela durante 4 seg, o el choque de escarcha del chaman que congela durante 3 seg creo, que e visto en bgs en mas de una ocasion quitarselos como si nada con el cambio de forma.

**Comment by asfo** [comment]
Cierro. Reporte duplicado: #394
