### ISSUE TITLE
CD [Muerte y descomposición] estipulado: 7 días.

### ISSUE THREAD

**Issue by RodMadmel** [RoDNet/Bugtracker-Infinium-4.0.6a#405]
Buena, resulta que hoy me he encontrado con que mi Muerte y descomposición http://es.wowhead.com/spell=43265 no la puedo usar... hasta la semana que viene:

http://i48.tinypic.com/k3km4g.jpg

Un saludo! Seguid así!

**Comment by DatJetto** [comment]
simplemente LoL

**Comment by RodMadmel** [comment]
^^

**Comment by GorThauR** [comment]
al brujo le pasa con el fuego de almas también, pero cds de 5 minutos (tiempo de reutilización 1,32 segundos)

**Comment by RodMadmel** [comment]
¿Qué pasa? ¿Vienes a fardar de CD o qué? xD

**Comment by RodMadmel** [comment]
Este problema se solucionó sólo, tal vez al cambiar de talentos o glifos.
