### ISSUE TITLE
Curacion de los Healers

### ISSUE THREAD

**Issue by avangers321** [RoDNet/Bugtracker-Infinium-4.0.6a#410]
Deberian revisar la curacion de los healers ya que se estan curando mas de la cuenta, me parece increible q 6 a 7 tengamos q estar detras de 1 healer, sin moverle la vida y q el mana ni se les mueva, y si hay 2 se hace mision imposible. Deberian bajarles la curacion ya que el set pvp esta hecho para dar cierto equilibrio para el pvp debido a q no dan demasiado espiritu en comparacion al set pve. pero solo les dan numeros grandes siendo su gaste de mana infimo.

**Comment by asfo** [comment]
Si no hay pruebas de esto, con análisis e investigación a fondo no se puede hacer nada ya que se toma como una simple queja...

Cierro hasta que haya pruebas contundentes de este problema.

**Comment by asfo** [comment]
Y siguen las peleas...Ya estoy checando eso a ver qué pasa y si es cierto, así que dejaré esto cerrado, elimino comentarios para seguir el reporte en manera cerrada.
