### ISSUE TITLE
Caballero de la Muerte [Pet Profano] BUG

### ISSUE THREAD

**Issue by pimpeter** [RoDNet/Bugtracker-Infinium-4.0.6a#412]
SImplemete al sacar la pet, no sale su barra de habilidades y no hace nada, está bug.
![WoWScrnShot_011213_223819](https://f.cloud.github.com/assets/3254254/62342/8032611e-5d00-11e2-83fa-a5aa9014b5d1.jpg)
![WoWScrnShot_011213_223830](https://f.cloud.github.com/assets/3254254/62343/8058ad2e-5d00-11e2-9fc7-9f7d52c6c5cf.jpg)
![WoWScrnShot_011213_223838](https://f.cloud.github.com/assets/3254254/62344/80781b32-5d00-11e2-995c-eebaf35c57ad.jpg)

**Comment by asfo** [comment]
Creo que esto ya estaba reportado...¿Alguien podría confirmarme?...(No puedo por la mugre aplicación de GitHub T_T)

**Comment by DatJetto** [comment]
Si, está reportado.

**Comment by asfo** [comment]
Ok, cierro este...Seguimos con el anterior.

Gracias @DatJetto
