### ISSUE TITLE
Bug de la habilidad de Galopada Salvaje del Huarguen

### ISSUE THREAD

**Issue by Zak3** [RoDNet/Bugtracker-Infinium-4.0.6a#413]
basicamente lo que pasa es que cuando intentas utilizar la habilidad te dice no puedes usar eso aqui ,pero tampoco hay un instructor de equitacion en las capitales donde se pueda aprender aprendiz jinete(ya lo he comprobado)

**Comment by Zak3** [comment]
http://es.wowhead.com/spell=87840

**Comment by asfo** [comment]
¿En qué zona tratas de usarla?, recuerda que en lugares dónde no puedes montarte es lo mismo que con dicho spell si no estoy mal, por lo tanto si no puedes utilizarla en lugares abiertos, sería un error válido, en dado caso sería solo error de que no conocías que no se puede montar en ciertas áreas.

**Comment by Redxx** [comment]
eso pasa cuando aun no eres Lv20  , o cuando estas en espacios cerrados . el bug es que aparece el icono de galopada salvaje antes de que se pueda utilizar .pero a partir del 20 funciona 100%

**Comment by DatJetto** [comment]
A ver, criatura del señor, la montura se aprende al 20 al igual que la equitación, no es un bug, esque es así.

**Comment by pimpeter** [comment]
ve a ventormenta, al 20 lo enseña una gnoma que esta donde los grifos

**Comment by Dekadencee** [comment]
Existe un bug visual como afirma Redxx en lo que "Galopada Salvaje" aparece antes de tiempo, pero efectivamente tras llegar a nivel 20 funciona correctamente.

Un saludo ^^

**Comment by pimpeter** [comment]
> Gracias por todo,
> 
> Saludos
