### ISSUE TITLE
[ Warrior ; Aturdimiento y rendimiento decreciente ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#415]
Blizzard, anunció en su parche 4.0.6 un pequeño nerf, del guerrero que no se cumple el cual te hace peder mucho tiempo VS warriors.

http://es.wow.wikia.com/wiki/Parche_4.0.6
-Ahora Cargar comparte rendimiento decreciente con los efectos de aturdimiento.

¿Qué es el rendimiento decreciente?
- El rendimiento decreciente es una disminución del tiempo de CC usados por los usuarios, de manera que; por ejemplo: 
  Druida ciclón; Te causa el inmune 8 segundos, lo castea de nuevo y son 5 sec, lo castea de nuevo y son 3, lo castea de nuevo y es 1, al siguiente es inmune y no lo puedes volver a lanzar con éxito hasta pasado un rato, lo mismo con la Polimorfia del mago y el Fear del brujo, cada vez disminuye su tiempo de efecto. 

El bug que reporto es que Cargar, con sus talentos de mejora alcanza 3 sec de Stun, hasta aquí bien, después el Warrior tiene otros efectos de /Stun/ y /Fear/ como 

Derribar: http://old.wowhead.com/spell=85388 la cual debería reducirse el tiempo de stun.
Arremetida de conmoción: http://www.wowhead.com/spell=54132 debería reducir el tiempo de stun. 
Pudiendo quedar inmovilizado por un guerrero casi 10 segundos. con una buena combinación.

**Comment by asfo** [comment]
Ahora bien te diré, el tiempo que va un spell contra otro, no es el mismo, es decir:
Si yo uso "Derribar", el stun marca X segundos, luego Y y al final Z para después dar inmune por ejemplo, pero si yo stuneo con otra vía, el stun permanece en este spell decreciendo, es decir, si en Derribar me quedan 5 segundos en el Cooldown aplicado, otro spell puede ir variando y el Derribar mantendría su cooldown actual.

Cada spell se le reduce únicamente a él, el cooldown. Pondré un ejemplo bien claro para entenderme:
Si yo soy Priest y uso "Control mental" el cooldown si no estoy mal está en 8 segundos aplicados, pero si lo reuso baja a 5 por ejemplo, pero si aplico Fear, empieza en 6 segundos y luego 4, si yo lanzo Fear hasta que esté en 1 segundo, Control mental debería seguir en 5 segundos. No afecta el uno al otro por lo que a lo que estoy entendiendo, tu reporte refiere a que se deberían combinar para reducir los tiempos ¿no?.

**Comment by DatJetto** [comment]
1. Un Stun nunca acaba en inmune, ya que el Cooldown y los stunes de las propias habilidades no lo permiten.
2. Tú usas el término Cooldown para referirte al tiempo de efecto de ese hechizo según se te entiende y no es así, es para referirse a la recarga de las habilidades. 
3. El rendimiento decreciente haría que Cargar te stunease 3 sec y el derribar / arremetida en los próximos 10 sec, aplicara otros 3 sec de stun en vez de 5.

**Comment by asfo** [comment]
1.-Si se puede volver inmune. Comprobado vía oficial.
2.-El término cooldown siempre se refiere al tiempo de recarga de una habilidad, es decir "antes de poder volver a utilizarla".
3.-Sigo preguntando ¿estás relacionando que los stuns deberían ir decreciendo sus cooldowns aplicados como debuffs uno con otro?, ¿o por separado?, por que funcionan por separado.

**Comment by DatJetto** [comment]
El stun inmune me refiero en 1 guerrero  pegando a otro pj, no 4 guerreros pegando  a 1 pj , entonces claro que sí sería inmune, independientemente este efecto en el servidor no sucede.

Creo que no me has entendido bien. 
3. No tiene nada que ver los Cooldown de las spells en este asunto y no sé por qué los metes, hablamos de rendimiento decreciente, que es totalmente distinto, la cosa es, que cada vez que el Guerrero X te mete Cargar y después Derribar, derribar tiene que reducir su tiempo de efectividad de 5 sec a 3s , de la misma manera que si el Guerrero Y te da otra vez con cargar ( mientras tienes o acabas de pasar el efecto derribar con unos 10 sec de margen ), el rendimiento decreciente debería ir a 1 sec y si te mete Derribar, entonces pasaría a estado de inmunidad frente a esas habilidades.

**Comment by asfo** [comment]
No se cómo lo entiendes tu pero te estoy diciendo el cooldown aplicado, es decir, un cooldown no es obligatoriamente a un spell del personaje si no que cooldown generalmente se refiere al tiempo de recarga de una habilidad como te lo dije, supón que tu aplicas una maldición con un warlock a un warrior, entonces esta tiene 8 segundos aplicados,esos 8 segundos se les conoce como "cooldowns aplicados como debuff" o en mi conocimiento así lo llamabamos luego en el oficial (en palabras cristianas, tiempo que aún le queda al debuff aplicado). 

Es a lo que te digo, el tiempo de un spell en el debuff no se reduce conforme a otro. Supón que un rogue (picaro) utiliza un stun, este cooldown en el debuff está con 5 segundos, si el rogue aplica otro stun, no tiene que reducirse el cooldown del debuff de este por que un spell es ajeno a otro.

¿Ahora si me entiendes?.

**Comment by DatJetto** [comment]
Sí, pero que son notas de Guerrero, no de otra clase, por eso te digo; 
Lee tú mismo las notas del parche: http://eu.battle.net/wow/es/game/patch-notes/4-0-6
que no es invención mía xD , que es lo que hay en el oficial y lo reporto para que el server sea blizz.

**Comment by asfo** [comment]
Si, si, ya lo leí, no te preocupes pero ahorita probaré supongo la revisión de lo que yo te comento y cierro en caso de que trabaje y dejo abierto en caso de que no funcione.
