### ISSUE TITLE
bug escudo de tierra

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.0.6a#417]
wenas ,parece que haveis metido algunos cambios  ,me alegro mucho^^

pero hay uno que creo que  esta mal, http://es.wowhead.com/spell=974 cura de normal 13k y 20k de critico y
si lleva talentos de +15% de cura como es mi caso me cura 16k y 24k de critico, demasiado.

con critico:
<a href="http://tinypic.com?ref=6fsief" target="_blank"><img src="http://i50.tinypic.com/6fsief.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

sin critico:
<a href="http://tinypic.com?ref=foexie" target="_blank"><img src="http://i45.tinypic.com/foexie.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by asfo** [comment]
¿Checas tu incremento de SP correctamente e incremento por habilidades?, es decir, ve a WoWHead y checa el algoritmo impuesto (o la fórmula) y comprueba promedio tu healing con el ;).
$?a63279[1586*1.2)][(1586])

**Comment by 50megas** [comment]
apenas me entero xd y no creo que pueda calcularlo ( si me pones algun enjemplo que entienda encatado lo intento y asi en mas bug que encuentre), solo que me parece que curaba mucho ,anterior en el servidor me curaba 10k y 20k de critico y medio servidor se quejaba de que esta bug y me llamaban bugero en bg (por eso lo posteo), y lo bajaron a 3500 y 5000 de critico y haora lo subieron mas que antes.

hay chamis que me dicen que es lo que tiene que curar,pero en el cata oficial  no tube chaman y no lose,simplemete queria prevenir nuevas oleadas de chamis bug

**Comment by DatJetto** [comment]
Dios, valla burrada, Asfo, por mucho SP, date cuenta que es un Buff a 9 cargas  cada vez que te pegan aunque sea 200p o 6k es 20k de healing por toque que te den encima reitero son 9 cargas..., si vas pvp , poca gente te va a pegar 20k salvo algunas spell de CD como Disparo de quimera o Puntería del caza en mi caso, te van a dar poco más de eso, esque encima es SPAMMABLE, y creo que esto es obvio pero, se supone que es una ayuda al healing del chami, no su sanación principal con Cadena, Oleada etc etc..

Debería sanarte - 3-4k y de critico 6-7k con un set decente épico

**Comment by HexR-zz** [comment]
Puff, qué decir, perdón. Esto se me ha escapado a mí. Lo acabo de ver, al igual que #383 Ahora mismo lo arreglo y espero que se apliquen los cambios cuanto antes.

**Comment by HexR-zz** [comment]
Llevas glifos de algo? de curas o lo que sea?

**Comment by 50megas** [comment]
yo llevo el glifo que aumeta la curacion de escudo un 20% creo recordar y un +15% de curararme mas con taletos

**Comment by HexR-zz** [comment]
FIXED
