### ISSUE TITLE
Logros de hermandad bug

### ISSUE THREAD

**Issue by jaime0510** [RoDNet/Bugtracker-Infinium-4.0.6a#418]
![image](https://f.cloud.github.com/assets/3056816/65597/d2cce820-5e83-11e2-8efa-87c17ff06cc2.png)
![image](https://f.cloud.github.com/assets/3056816/65598/d84eaaa4-5e83-11e2-96e0-c8a634257e74.png)
![image](https://f.cloud.github.com/assets/3056816/65599/dbc68454-5e83-11e2-8f04-b7c881b9bc4a.png)
![image](https://f.cloud.github.com/assets/3056816/65600/dd96d004-5e83-11e2-83a1-d1a6fee0e75e.png)
![image](https://f.cloud.github.com/assets/3056816/65601/dfa45862-5e83-11e2-9cfa-c2b466c28768.png)
![image](https://f.cloud.github.com/assets/3056816/65602/e2df73ae-5e83-11e2-99ce-9a7092af8f09.png)
![image](https://f.cloud.github.com/assets/3056816/65603/ec20e556-5e83-11e2-91ab-5fcca0cbf383.png)

Y la lista es muy larga. En las imagenes de JcJ veran que en las casillas no hay ninguna marcada entonces es imposible si yo como jugador tengo mas de 1000 muertes con honor. Sumadas las muertes con honor de los demas miembros de hermandad.

**Comment by Dekadencee** [comment]
El sistema de hermandades tenemos que reformarlo por completo, nobstante muchísimas gracias por los 2 reportes, nos servirán mucho a la hora de verificar si sigue ocurriendo o no :)

Un saludo ^^

**Comment by Dekadencee** [comment]
Reporte duplicado lo seguimos desde el anterior: https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/416
