### ISSUE TITLE
Vendedores de Joyeria

### ISSUE THREAD

**Issue by krayonte** [RoDNet/Bugtracker-Infinium-4.0.6a#42]
Los vendedores de suministros de joyeria a partir del nivel 75 deberian vender "Engarce de joyero", pongo 3 ejemplos de vendedores en wowhead:
http://es.wowhead.com/npc=33602
http://es.wowhead.com/npc=28721
http://es.wowhead.com/npc=50165
Si no los venden, la joyeria se atasca en el nivel 485 sin poder subir si no es con objetos que necesiten "Engarce de joyero" .
Gracias y saludos

**Comment by Dekadencee** [comment]
¿Porque la cierras? ¿Funcionan en realidad?

**Comment by krayonte** [comment]
Hay un NPC en orgrimar que los vende
http://es.wowhead.com/npc=50482

**Comment by Dekadencee** [comment]
Pero aunque uno de ellos los venda, si los otros deben venderlo es bug igualmente, gracias por el reporte reabrimos y a la cola :P

**Comment by Dekadencee** [comment]
Corregido
