### ISSUE TITLE
Bug Barra de Mascotas del Cazador

### ISSUE THREAD

**Issue by jandrox** [RoDNet/Bugtracker-Infinium-4.0.6a#420]
Hola , mi problema es que cuando hago modificaciones en la barra de mascotas o incluso cuando activo alguna habilidad de las mascota directamente en el libro de hechizos para que la active automáticamente, no se guardan los cambios, y cuando desaparece por usar una montura o la desconvoco, al volver a llamarla o aparecer desaparecen los cambios que he realizado.
Otro problema con la barra es que en las BGs cuando muero, al volver a la vida mi mascota esta a mi lado, pero no aparece la barra de mascotas ni puedo desconvocarla o llamar a otra, tan solo he podido hacer esto, usar una montura y al bajarme ya aparece de nuevo la barra de mascotas con lo que es la única manera de interactuar con mi mascota de nuevo.

Un saludo.

**Comment by DatJetto** [comment]
Reportado en https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/339

**Comment by asfo** [comment]
Cierro, seguimos desde el anterior.
