### ISSUE TITLE
diablillo potenciado. Talento brujo destrucción.

### ISSUE THREAD

**Issue by GorThauR** [RoDNet/Bugtracker-Infinium-4.0.6a#424]
Diablillo potenciado: La descarga de fuego de tu diablillo tiene un 4% de posibilidades de hacer que tu próximo fuego de alma sea instantáneo.

Bug:

Tu fuego de alma es instantáneo durante 8 segundos, osea, puedes lanzar los fuegos de alma que tu haste te deje tirar.

**Comment by searum** [comment]
fix
