### ISSUE TITLE
Quemadura de las sombras. Talento brujo destrucción.

### ISSUE THREAD

**Issue by GorThauR** [RoDNet/Bugtracker-Infinium-4.0.6a#425]
Quemadura de las sombras: Inflinge instantáneamente 8289 p. de daño de las sombras. Si el objetivo muere hasta 5 segundos después de Quemadura de las sombras y aporta honor u experiencia, el taumaturgo obtiene 3 fragmentos de alma. Solo se puede usar contra enemigos que tengan 20% o menos de su vida.

Bug:

Al matar a un enemigo con quemadura de las sombras no obtienes ningún fragmento de alma.

Cómo debería de ser:

Recibes 3 fragmentos de almas si el enemigo muere 5 segundos después de haber usado el hechizo.

**Comment by searum** [comment]
fix
