### ISSUE TITLE
Talento bug "Lider de la manada" (Druida feral)

### ISSUE THREAD

**Issue by sardeski** [RoDNet/Bugtracker-Infinium-4.0.6a#428]
Talento bug "Lider de la manada" (Druida feral)

*****_El buff de 5% de critico aumentado está ok; pero los criticos cuerpo a cuerpo no restauran ni salud, ni mana.**_*****

Líder de la manada
Requiere Druida (Feral, Guardián)
Requiere nivel 46
Requiere Forma felina, Forma de oso
Cuando estás en forma de oso o felina, aumenta un 5% la probabilidad de golpe crítico de todos los miembros del grupo o banda en un radio de 100 m.

Además, tus golpes críticos cuerpo a cuerpo hacen que te sanes un 4% de tu salud y que obtengas un 8% de tu maná. Solo puede suceder una vez cada 6 s.

**Comment by searum** [comment]
fix
