### ISSUE TITLE
Runas del Dk bug

### ISSUE THREAD

**Issue by nakran13** [RoDNet/Bugtracker-Infinium-4.0.6a#429]
(Solo lo he comprobado con los talentos de sangre, aunque supongo que para todos es igual.) Cuando realizo dos ataques de sangre y las runas se quedan en espera unos 10s aproximadamente. Si hacemos un ataque con la habilidad "golpe letal" la reutilización de las Runas de Sangre vuelve a 10s, con lo cual si antes teníamos que esperar 10s.... ahora podremos quedarnos sin atacar casi asta 20s

**Comment by DatJetto** [comment]
no entiendo el reporte :c

**Comment by RodMadmel** [comment]
DatJetto, DatJetto... xD https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/379

**Comment by asfo** [comment]
Cierro, seguimos del #379
