### ISSUE TITLE
Talento Atronado guerrero protección

### ISSUE THREAD

**Issue by krayonte** [RoDNet/Bugtracker-Infinium-4.0.6a#43]
Talento "Atronado" guerrero Proteccion NO FUNCIONA.
http://img16.imageshack.us/img16/8493/atronado.jpg

**Comment by DatJetto** [comment]
pon enlace de wowhead y más información :camel:

**Comment by krayonte** [comment]
La habilidad "Atronar" aplicada a objetivo/s deberia poner un maximo de 3 stacks que aumentara cada uno un 10% el daño de "Ola de choque".
1 stack = +10% de daño de Ola de choque
2 stack = +20% de daño de Ola de choque
3 stack = +30% de daño de Ola de choque
Los stacks acumulados desaparecerian del objetivo despues de usar "Ola de choque" o pasados los 30 seg del debuff de Atronar.
Atronar  http://old.wowhead.com/spell=6343#modified-by
Atronado http://old.wowhead.com/spell=80980
Perdon por no haberme explicado bien.

**Comment by adrianrp1988** [comment]
Reparado en la próxima Rev
