### ISSUE TITLE
[Pet] Mage

### ISSUE THREAD

**Issue by NeKroZ** [RoDNet/Bugtracker-Infinium-4.0.6a#433]
El elemental de Agua del Mago actualmente tiene muy poca vida, 24k.

**Comment by adrianrp1988** [comment]
podrias proporcionar datos adicionales por favor
una formula por ejemplo

**Comment by asfo** [comment]
¿Pruebas para corroborar esto?

**Comment by NeKroZ** [comment]
Nada mas que llegue al lv 85 posteo una pic de la pet y como deberia ser

**Comment by searum** [comment]
fix
