### ISSUE TITLE
valle de alterac (bg)

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.0.6a#434]
la vida de los miniboss es muy baja  http://subefotos.com/ver/?963802baad0ca78cdd176ead9a2c574eo.jpg#codigos

la vida del boss final tambien  http://subefotos.com/ver/?137dbdae336576dfe70c85b4f8bd6dbdo.jpg#codigos al tener tan poca vida se puede hacer la bg entera en 4 minutos 

los guardias de las torres tambien tienen muy poca vida unos 2000 que con hacer un area se mueren

**Comment by asfo** [comment]
De hecho, se supone, es la "normal", por así decirlo, el caso son los buffs que tiene y que debes lograr quitarle al jefe para poder hacerlo, nótese en los screenshots que los sigue teniendo y estos no funcionan.

**Comment by DatJetto** [comment]
Aparte, esque es la vida que tenía en  WOTLK, en cata debería tener bastante más :C

**Comment by asfo** [comment]
Si, claro, por eso lo mantengo abierto, solo falta saber la hp sin buffs

**Comment by Oscarin** [comment]
los jugadores tambien se benefician del bufo del boss i te puedes poner con 500000 de vida i hacer mucho daño si permaneces con drek thar o el enano de la alianza http://subefotos.com/ver/?3e369c60c95a7c0acbe6c18c343f8b44o.jpg

**Comment by Dekadencee** [comment]
¿Alguien puede decirme la id del buff?

**Comment by Oscarin** [comment]
nose si te servira esto

http://es.wowhead.com/spell=45829/

http://es.wowhead.com/spell=45831

http://es.wowhead.com/spell=45828

http://es.wowhead.com/spell=45830

ai otro fallo en la zona de inicio de la alianza,que mientras esta en modo preparacion antes de comenzar la bg se pueden montar los alianzas en la montura dentro de la cueva de inicio
