### ISSUE TITLE
Bug en Reforjar

### ISSUE THREAD

**Issue by Cicgnar** [RoDNet/Bugtracker-Infinium-4.0.6a#435]
El bug consiste en que cuando reforjas una pieza y logueas, tus características regresan a como te las ponía el equipo sin reforjar

**Comment by Cicgnar** [comment]
Capturas:

Primero, estado inicial

http://i117.photobucket.com/albums/o50/Cicgnar/1_zps20a93fd8.jpg

Segundo, justo tras reforjar

http://i117.photobucket.com/albums/o50/Cicgnar/2_zpsec4de423.jpg

Tercero, tras loguear con la pieza aún reforjada

http://i117.photobucket.com/albums/o50/Cicgnar/3_zps8caf78e2.jpg

**Comment by asfo** [comment]
Ya había sido reportado. Gracias de igual manera.

Cierro.
