### ISSUE TITLE
bug a el devolver un item

### ISSUE THREAD

**Issue by aeternus** [RoDNet/Bugtracker-Infinium-4.0.6a#437]
buenas quiero reportar un bug al devolver un item compre un escudo soñoso con mi pj estombar y después decidí devolverlo para poder compradme otro item cuando lo fui a devolver me salio wow erros cuando devolvi el item al volver a entrar al juego no tenia el escudo ni los puntos de arenas con los que había comprado el ítem si me pueden ayudar con eso les agradezco muchas gracias

**Comment by asfo** [comment]
Ya fue arreglado esto y será implementado en la próxima actualización.

Cierro
