### ISSUE TITLE
Gemas Penetracion de hechizos

### ISSUE THREAD

**Issue by villarta91** [RoDNet/Bugtracker-Infinium-4.0.6a#444]
Las gemas de penetracon de hechizos en vez de subirla la bajan, los objetos que tienen esta caracteristica al contrario van perfectamente, pero las gemas lo bajan

**Comment by asfo** [comment]
Creo que esto ya estaba reportado, ¿alguien me puede confirmar?

**Comment by ghost** [comment]
Si, mira, aquí he visto un post donde se menciona lo del tema de las gemas de Penetración con hechizos:
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/363

**Comment by asfo** [comment]
Gracias @Zaska . Cierro, seguimos desde #363
