### ISSUE TITLE
Talentos druida Heal Bug

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#446]
Buenas, lo primero antes de nada, no pondré enlaces de wowhead porque he buscado los talentos y como son de los viejos no existen ya :S Aún así os pondré la descripción del talento con lo que está mal.

[Editado por: @Asfo]
## 1º  [Maestro en cambio de forma][Sin problemas aparentes]

Se supone que mientras estés en forma de humanoide o forma de árbol, aumenta tu sanación un 4%, y no lo hace. El resto de cosas que especifica para las demás ramas sí.
## 2º  [Toque potenciado]

Aumenta un 10% la sanación directa de tus hechizos Toque de sanación, Recrecimiento y Nutrir y otorga a esos hechizos un 100% de probabilidad de reiniciar la duración de tu Flor de vida en los objetivos.

Sí que aumenta la sanación de esos 3 hechizos un 10% pero no reinicia la duración de flor de vida aplicada sobre ese/esos objetivo/s.
## 3º  [Don de la Madre Tierra]

Aumenta la sanación infligida cuando se acaba tu flor de vida un 5% y provoca que tu hechizo Rejuvenecimiento también sane instantáneamente un 5% del total de su efecto periódico.

La sanación de flor de vida sí que la aumenta, aunque no creo que la sanación temporal esté bien. http://es.wowhead.com/spell=94447
Pero el rejuvenecimiento no cura un 5% del total de su efecto periódico.
## 4º  [Árbol de vida] http://es.wowhead.com/spell=33891

Tal como dice, mejora ciertos hechizos al estar en forma de árbol de vida, pues bien, aquellos hechizos que mejora, hay 2 que los convierte en lanzamiento instantáneo que son Recrecimiento( http://es.wowhead.com/spell=8936 ) y Raíces enredadoras( http://es.wowhead.com/spell=339 ), pero sólo son de lanzamiento instantáneo cuando no te mueves, porque si te estás moviendo no te deja lanzarlos. 

Espero que puedan mirarlo tan pronto como sea, ya que creo que son unos talentos que se usan bastante.

**Comment by asfo** [comment]
De lo primero ¿podrías ponernos pruebas?, ya que 4% no es muy notable en ciertas ocasiones y podría confundirse.

**Comment by ghost** [comment]
Vale, lo acabo de comprobar, sí que funciona lo del 4% extra, pero que yo recuerde en el ofi se quedaba el iconito de que te lo aumentaba, como en forma de gato por ejemplo:
![WoWScrnShot_012213_105513](https://f.cloud.github.com/assets/3328374/85811/db4c9b84-6479-11e2-8e3c-3b3c1a0d7112.jpg)

Bueno, por si alguno tiene la duda del testeo, aquí dejo un par de fotos del antes y el después de poner ese talento:
Antes 
![WoWScrnShot_012213_104812](https://f.cloud.github.com/assets/3328374/85814/ff11be3c-6479-11e2-83d7-0dc91fc54863.jpg)

Después
![WoWScrnShot_012213_105323](https://f.cloud.github.com/assets/3328374/85816/0760a54e-647a-11e2-9a98-4b11f03e1027.jpg)

**Comment by searum** [comment]
fix

**Comment by ghost** [comment]
Lo has compilado ya? Porque el talento Toque potenciado si que chuta ya, pero lo del arbol de vida y Don de la madre tierra aún no funcionan correctamente

**Comment by searum** [comment]
lo de arbol de vida tienes q pararte un pliki y castear, he estado mirando y de momento no se... no voy a pararme con eso q es una tonteria.. lo otro ya esta fix, faltaba una parte

**Comment by ghost** [comment]
Eso hago tranqui, pero que yo recuerde se podía castear moviéndose jaja, sobretodo porque se vuelven esos dos hechizos que te linkee " instantáneos " El recrecimiento y las raíces. Pero aguanto =P jaja
Okis, faltaba lo de la cura instant de rejuvenecimiento al echarse, no?
Ahora te pongo en otro Issue otra cosa bug, que este está cerrado xD
