### ISSUE TITLE
[SPELLS] Damage Issue

### ISSUE THREAD

**Issue by NeKroZ** [RoDNet/Bugtracker-Infinium-4.0.6a#447]
He visto Varios errores en los siguientes Hechizos

1.) La consagracion del paladin, por ejemplo a lv 28, hace 200 dmg por pulso, con un stun y la consagracion es un kill seguro

2.) El Totem (Healing Stream Totem) cura demasiado, a lv 28 (1200 hp) cuando deberia curar 11 ptos,

3.) La maestria del shaman, (que duplica los hechizos) esta activa en el shaman incluso si no estas en lv 80 y compraste la maestria (doble lighting bolt etc)

4.) El Rogue en Subtley y su emboscada (1200 dmg) al lv 28, cant be!

5.) el Druida Feral y su Mordedura feroz con 5 ptos 1600 dmg OMG <<

**Comment by DatJetto** [comment]
La consagración del paladín siempre hace el mismo daño, al 85 sigue dando 200 y poco, y eso si lo he notado lo del druida feral, con mi druida ( equipo heler y talentos ) en gato pego 8k al palito sin critico de mordedura, un feral equipado le puede dar como 40k? :camel:

**Comment by NeKroZ** [comment]
Lo de la mordedura y el dmg es a lv 28, es imposible, porque casi ningun caracter tiene 1600 de HP en ese lv

**Comment by searum** [comment]
todo fix
