### ISSUE TITLE
Bug bomba de humo pícaro

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#451]
Buenas, la bomba de humo del pícaro no funciona correctamente debido a que los que están dentro te pueden atacar, y los que están fuera te pueden ver, y curar al que está dentro, siendo enemigos todos. 

He probado en un duelo para que vean el resultado al tirar bomba, que se supone que no te pueden ni targetear para pegarte:
![WoWScrnShot_012213_121428](https://f.cloud.github.com/assets/3328374/86018/1516b6a0-6485-11e2-912f-3c3c0f4a4ffa.jpg)

Dejo el link de wowhead a continuación:  http://es.wowhead.com/spell=76577

**Comment by DatJetto** [comment]
Ver tu pj lo pueden ver, lo que no pueden es seleccionarte para pegarte, los aliados dentro de la nube de humo si pueden seleccionarse y curarse, te pueden dar con ataques en área, como Ventisca o Filotormenta.

Pero si estás en grupo, puedes detectar a la unidad, es igual que el camuflaje del cazador, si estás en grupo te pueden seleccionar, y etc. Intenta duelear sin grupo :)

**Comment by ghost** [comment]
Aquí tienes la foto sin grupo para que veas que atacan igualmente ;)
![WoWScrnShot_012213_162333](https://f.cloud.github.com/assets/3328374/86704/279bea52-64a8-11e2-9dc3-db97f4b30e4a.jpg)
Luego busco un vídeo donde se aprecie bien la bomba de humo, porque los de dentro tampoco se pueden curar según vi yo en el ofi

**Comment by searum** [comment]
ya lo arregle anoche falta compilarlo
