### ISSUE TITLE
Glifo de brujo de Drenar alma

### ISSUE THREAD

**Issue by jandrox** [RoDNet/Bugtracker-Infinium-4.0.6a#458]
Se supone que al tener este glifo recuperas un 10% de mana tras matar a un oponente que genere experiencia u honor, pero no se genera nada :(

link: http://es.wowhead.com/spell=58337

Un saludo.

![WoWScrnShot_012113_034229](https://f.cloud.github.com/assets/3144712/87217/c3b04220-64b8-11e2-86be-b09ff2f38cca.jpg)

**Comment by searum** [comment]
fixed
