### ISSUE TITLE
Mazmorra de banda el templo oscuro 

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.0.6a#460]
el boss esencia del sufrimiento http://es.wowhead.com/npc=23418 no se activa i no se puede pegarle.

**Comment by asfo** [comment]
¿Ya limpiaron lo anterior?, recuerda que debe haber un orden de seguimiento para poder hacerlo y matar todos los fantasmitas de la cámara...

De igual manera, lo comento en caso de que si lo hayan echo, solo confirmen esto para seguir con el reporte ;)

**Comment by Oscarin** [comment]
no seguimos el orden,nos dejemos por matar a la sombra de akama  que porcierto la acavo de matar haora i no hace nada,solo se queda parado i le puedes pegar asta que se muere.despues de matar a la sombra de akama volvi a mirar el boss de la camara i seguia sin activarse

http://subefotos.com/ver/?f12c1df0f8bbc384863b38eca301b0c7o.jpg#codigos
