### ISSUE TITLE
Mago Fire: Buena racha

### ISSUE THREAD

**Issue by avangers321** [RoDNet/Bugtracker-Infinium-4.0.6a#461]
al momento de castear piroexplosion saco minimo 20500 a 22000 sin criticos, pero al momento que se activa "Buena racha, mi piroexplosion instantanea (http://es.wowhead.com/spell=48108/piroexplosion), sin critico solo bordea los 3500" lo cual esta bajo, si comparamos a la relacion entre la piroexplosion casteanda y la instantea esta muy bajo el que salta con buena racha.

**Comment by ghost** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/39

**Comment by HexR-zz** [comment]
FIXED
