### ISSUE TITLE
Bug Asolar (Caballeros de la Muerte)

### ISSUE THREAD

**Issue by lished** [RoDNet/Bugtracker-Infinium-4.0.6a#464]
En la expansion anterior 3.3.5 Asolar consumía las enfermedades del objetivo y con un glifo ya se podía solucionar ese problema, pero en cataclysm Asolar no consume enfermedades eso quedo eliminado en esta versión, lo cual del problema es que al aplicar asolar a un objetivo cualquiera sea consume las enfermedades.

http://es.wowhead.com/spell=49020  Ahí se ve en la descripción del hechizo que no consume enfermedades y en vídeos también puedo afirmar que no consume enfermedades.

**Comment by searum** [comment]
fix
