### ISSUE TITLE
bien alimentado

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.0.6a#466]
es un bug que lleve 4 bufos de ese tipo 90 de indice de golpe i aguante,fuerza i aguante... 
http://subefotos.com/ver/?8c4ae98ebb8c81dbac7078043e1ddeaco.jpg#codigos

**Comment by DatJetto** [comment]
JAJAJ que cheto.
Añado para la redundancia: Solo puedes llevar un bufo de ''bien alimentado'' / el que te hayas puesto más recientemente /

**Comment by searum** [comment]
fix
