### ISSUE TITLE
dk escarcha

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.0.6a#467]
antes eran los dk sangre los que se curavan mucho pero esque haora son los dk que no son sangre como este jugador que lleva talentos en escarcha i va segundo en curacion con un millon i un millon cienmil de daño.
http://subefotos.com/ver/?78d3c65a6bd8e36fba1c012c7726be51o.jpg#codigos

**Comment by searum** [comment]
esto ya esta reparado, tengo que actualizar
