### ISSUE TITLE
Bug en la pet guardia vil del brujo demonologia

### ISSUE THREAD

**Issue by manuanza** [RoDNet/Bugtracker-Infinium-4.0.6a#47]
Yo queria reportar el bug en la pet del brujo demonologia el guardia vil el cual no saca lo que tendria que sacar . pega de a 500 o 700 por golpe cuando tendria q skar mucho mas de 2 k

**Comment by searum** [comment]
Pruebas o algo? Repetimos que adivinos no somos y no vamos a poner nada custom a gusto de los jugadores.

Vuelve a reportarlo cuando tengas más datos.

Faltan enlaces.
