### ISSUE TITLE
golpe de la victoria bug?

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.0.6a#470]
no soi un muy entendido en guerreos, pero me parece que la habilidad http://es.wowhead.com/spell=34428/ataque-de-la-victoria cura algo demas teniendo puesto el glifo http://es.wowhead.com/item=43431

con critico:

<a href="http://tinypic.com?ref=111mjrp" target="_blank"><img src="http://i50.tinypic.com/111mjrp.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

sin critico:

<a href="http://tinypic.com?ref=2j0cd48" target="_blank"><img src="http://i45.tinypic.com/2j0cd48.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by searum** [comment]
es asi, esta bien esa spell y el glifo :\
