### ISSUE TITLE
Drenar alma de brujo

### ISSUE THREAD

**Issue by jandrox** [RoDNet/Bugtracker-Infinium-4.0.6a#474]
La habilidad drenar alma del brujo no genera ningún fragmento de alma, aunque los npcs den experiencia u honor :(
Imagino que por eso el glifo, como puse en el post #458, tampoco genera el maná.

Link: http://es.wowhead.com/spell=1120

Un saludo.

**Comment by searum** [comment]
debe dar 1 o 3? es solo al matar no?

**Comment by searum** [comment]
fix
