### ISSUE TITLE
Bug Golpe letal (Caballero de la muerte)

### ISSUE THREAD

**Issue by bloodfire** [RoDNet/Bugtracker-Infinium-4.0.6a#476]
Tras haber hecho un reinicio hace 12 horas aproximadamente, Se ha bugeado un poder del caballero de la muerte (http://es.wowhead.com/spell=49998) cuyo fin es curar como minimo 7% de la salud maxima, Con el glifo Socorro oscuro (http://es.wowhead.com/item=68793) se supone que este hechizo curara un minimo de 20% de la salud. Lo que ocurre con este hechizo es que despues del reinicio, transformo su curacion para mal, despues de curar eventualmente 18k ahora simplemente cura 23 puntos de salud. Cosa que afecta tanto al pvp como al pve.

Anexo pruevas

![image](https://f.cloud.github.com/assets/3310395/98096/13530dd8-6713-11e2-9afa-55a604b36450.png)
![image](https://f.cloud.github.com/assets/3310395/98097/1789bf5a-6713-11e2-9907-f366cd8b15f4.png)

Espero puedan solucionar el problema pronto.

Gracias

**Comment by searum** [comment]
fix
