### ISSUE TITLE
Bug Golpe letal Caballeros de la Muerte)

### ISSUE THREAD

**Issue by lished** [RoDNet/Bugtracker-Infinium-4.0.6a#477]
![WoWScrnShot_012513_230340](https://f.cloud.github.com/assets/3359233/99490/1a21038c-6771-11e2-989d-618e16c3bb14.jpg)
Bueno básicamente cura demasiado http://es.wowhead.com/spell=49998/golpe-letal por algún motivo en combate o no se cura mas que hacerlo en un dumming

Pruebas:

![WoWScrnShot_012513_220635](https://f.cloud.github.com/assets/3359233/99315/bebdc3e2-6755-11e2-8931-c94d8b0d1222.jpg)

![WoWScrnShot_012513_220640](https://f.cloud.github.com/assets/3359233/99317/e96dbcbe-6755-11e2-97e7-d0910ff187e8.jpg)

![WoWScrnShot_012513_220645](https://f.cloud.github.com/assets/3359233/99318/f11c2414-6755-11e2-8c84-077970d1f0bd.jpg)

![WoWScrnShot_012513_220658](https://f.cloud.github.com/assets/3359233/99319/f7ad5eb0-6755-11e2-940f-90026d166c33.jpg)

xd

**Comment by searum** [comment]
fix
