### ISSUE TITLE
puntos de talento perdidos

### ISSUE THREAD

**Issue by frostking** [RoDNet/Bugtracker-Infinium-4.0.6a#479]
he perdido todos los puntos de talento que me he ganado a lo largo de los niveles
![WoWScrnShot_012613_091511](https://f.cloud.github.com/assets/3338941/99730/07b35866-67b3-11e2-8dbf-c77e65901310.jpg)

**Comment by searum** [comment]
bug visual, reinicia talentos y se arregla
