### ISSUE TITLE
Bug talentos chaman trueno ensordecedor y Fulminacion

### ISSUE THREAD

**Issue by Qud** [RoDNet/Bugtracker-Infinium-4.0.6a#480]
Estos dos talentos. Trueno ensordecedor debria otorgar mana y generar una carga de escudo de relampagos adicional, asta un maximo de 9, y no hace ninguna de estas cosas, luego, Fulminacion, que sigue al anterior talento, no podemos usarlo, ya que sin cargas extras no nos vale de nada lanzar choque de tierra. Gracias.

**Comment by searum** [comment]
http://i50.tinypic.com/2saj6zp.jpg

Reporta bien, trueno ensordecedor si funciona al menos la parte del mana, puedes comprobarlo esta testeado ahora mismo en infinium con 1 punto de talento 30% de chance. con 2 puntos 60% de chance, no recuperas siempre...

Fulminacion explica bien el fallo porque si no jugamos y no conocemos el talento poca ostia podemos hacer.

**Comment by searum** [comment]
fix
