### ISSUE TITLE
Kezzik el asediador vendedor experto de arena 

### ISSUE THREAD

**Issue by lks06** [RoDNet/Bugtracker-Infinium-4.0.6a#482]
le faltan los hombros 

![1](https://f.cloud.github.com/assets/3086718/100567/a89b79a4-6829-11e2-9b21-f24dc705577a.JPG)

**Comment by 50megas** [comment]
como comentan faltan las hombreras de chaman http://es.wowhead.com/item=33742

**Comment by searum** [comment]
fix
