### ISSUE TITLE
Bug > reseteo en puntos de arena

### ISSUE THREAD

**Issue by Keough** [RoDNet/Bugtracker-Infinium-4.0.6a#483]
Buenas, deseo reportar un error que ha ido ocurriendo consecutivamente con cada reseteo que se da o caída del server, va ocurriendo esta semana recién desde que arreglaron los talentos del dk y demás. Los puntos de arena que son límite (al menos mío) de 1350/1350, al momento del reseteo vuelve a 0/1350 osea que puedo hacer y acumular mas puntos.
Lo mismo esta pasando con los talentos, que se te borran y en algunos casos se arregla cambiando de rama nada mas, pero en otros a subir todos de nuevo.
Ese sería uno de los errores que han estado ocurriendo esta semana y varios players han abusado y siguen abusando de él, ya que cuando avisan del reinicio de server, se alocan y comienzan a pedir arenas por general para que al momento de reiniciar vuelvan a 0/1350 y se armen.

**Comment by Dekadencee** [comment]
Creo que ya está solucionado, necesito confirmación

Un saludo ^^

**Comment by Keough** [comment]
ok ok si es que llega haber otra caída del server, le confirmo n.n.
Gracias :D

**Comment by Dekadencee** [comment]
Fixed!

**Comment by Keough** [comment]
yeaaaah ahora si se ve que corre normal :D cualquier cosa posteo de nuevo. Gracias n.n

**Comment by Dekadencee** [comment]
Perfecto, si cualquier cosa no dudes en postear, a veces podemos tardar dependiendo de lo facil que nos sea encontrar el error, pero tarde o temprano lo acabamos arreglando todo ;) así que cualquier cosa por mínima que sea ya a sabes donde estamos ^^
