### ISSUE TITLE
[ IMPORTANTE ] > Reset de Talentos.

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#484]
Cada vez que el servidor se cae los talentos se reinician, teniendo que estar constantemente rebuildeándolos y gastando dinero.

Es muy muy molesto estar constantemente así

Anteayer entré y no había talentos, los repuse normal, ayer igual y dicen si reseteas la spec se arregla, reseteé mis 2 spec y hoy al volverme a conectar tampoco tenía talentos...

**Comment by asfo** [comment]
¿Alguien más con este problema?

**Comment by Dekadencee** [comment]
Todo el mundo, estamos ya solucionandolo

**Comment by Dekadencee** [comment]
Creo que ya está solucionado, necesito confirmación

**Comment by Dekadencee** [comment]
Fixed!
