### ISSUE TITLE
Bug talento chaman trueno ensordecedor

### ISSUE THREAD

**Issue by Qud** [RoDNet/Bugtracker-Infinium-4.0.6a#485]
el talento http://db.mmo-champion.com/s/88765/rolling-thunder/ trueno ensordecedor del chaman no genera cargas, si otorga mana, pero no genera cargas, y comprobado si con el glifo escudo de relampagos http://db.mmo-champion.com/s/55448/glyph-of-lightning-shield/ interferia en ste talento, pero tanto con el y sin el no me genera cargas, y he probado lanzando y lanzando descargas de relampago como un idiota. Gracias.

**Comment by searum** [comment]
fix
