### ISSUE TITLE
[Skills] Pyro Instant Mage Fire 

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.0.6a#486]
Aun siendo el que mas usa el mago fuego y esperando mucho tiempo para que me pudieran arreglar y lo agradezco de verdad que al final funcionase la pyro del mago fuego esta un poco salida de limites ... ya que como veréis en las capturas siguientes :

Pyro Casteada no critica 
![Pyro casteada sin critico](https://f.cloud.github.com/assets/2746480/101175/193eb314-68ad-11e2-8d54-72c2d25b7970.PNG)

Pyro Casteada Critica 
![Pyro Critica Casteada](https://f.cloud.github.com/assets/2746480/101180/347c1450-68ad-11e2-82c9-85555bd41c12.PNG)

Pyro Instantanea No Critica
![Pyro Instant No critica](https://f.cloud.github.com/assets/2746480/101207/e5b794fe-68af-11e2-9eb8-bb1d44f91cfc.PNG)

Pyro Instantanea Critica VS 3k de temple
![Pyro Instant](https://f.cloud.github.com/assets/2746480/101181/7a336f2a-68ad-11e2-8e6f-38c493ea8d84.PNG)

Pyro Instantanea Critica VS Full PvE
![Pyro Instant Sin equipo](https://f.cloud.github.com/assets/2746480/101182/8f4abaee-68ad-11e2-986d-f98da41fbe0b.PNG)

Por lo tanto para el buen funcionamiento del server reporto la habilidad y pido una revisión de esta para que se puedan fixear correctamente .

**Comment by searum** [comment]
fix
