### ISSUE TITLE
Bug honor

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#488]
Buenas, ahora mismo al salir de bg fui a mirar el honor que tenía y tenía 379, cuando antes de entrar tenía casi 2k. Le ha pasado a todos, debe de haber algún fallo que reinicia el honor al salir de la bg ganada o perdida y te pone el honor que has obtenido desde 0 :S

**Comment by Dekadencee** [comment]
¿Esto te ocurrió en Cumbres Gemelas (Twin Peaks) verdad?

**Comment by searum** [comment]
fix

**Comment by ghost** [comment]
Sí, fue ahí xD Pero ya está solucionado ;)
