### ISSUE TITLE
[NPC

### ISSUE THREAD

**Issue by k4b3z0n** [RoDNet/Bugtracker-Infinium-4.0.6a#49]
los npc que vender Tier no tienen todos los items, es decir solo vende tier11 normal y no hero, no tiene abalorios, anillos etc

http://www.wowhead.com/npc=46556/jamusvaz

**Comment by asfo** [comment]
Según WoWHead los items que vende son nivel 384+, es decir, versión 4.3. Por lo tanto, comprobando los items en venta de WoWHead no debería vender hasta la versión 4.3 que es cuando se incluyen.

Cierro.

**Comment by asfo** [comment]
Corroboro con la siguiente información:
http://www.wowhead.com/item=78836 

Por si quedan dudas. En la línea:
http://old.wowhead.com/npc=46556/

Se demuestra que en 4.0.1 no vendía nada que es cuando es implementado.
