### ISSUE TITLE
Problema con Cólera Sagrada

### ISSUE THREAD

**Issue by darkpriest85** [RoDNet/Bugtracker-Infinium-4.0.6a#491]
http://es.wowhead.com/spell=57466/colera-sagrada

No hace absolutamente nada de daño, es como si no arrojara nada

![WoWScrnShot_012813_131650](https://f.cloud.github.com/assets/3408456/103996/ea42f31a-6972-11e2-8015-7b8f949965dd.jpg)

**Comment by asfo** [comment]
Combat Log por favor (Registro de combate), quizá el bug sea el NPC.

**Comment by darkpriest85** [comment]
![WoWScrnShot_013013_160550](https://f.cloud.github.com/assets/3408456/113119/749686fa-6b3d-11e2-973f-1dc38dd540ff.jpg)
![WoWScrnShot_013013_160611](https://f.cloud.github.com/assets/3408456/113128/0783ad44-6b3e-11e2-9814-2c85cb157c0f.jpg)
![WoWScrnShot_013013_160641](https://f.cloud.github.com/assets/3408456/113130/26512dbe-6b3e-11e2-912a-3b9333d25458.jpg)

**Comment by darkpriest85** [comment]
Allí está el registro de combate, y no sale absolutamente nada.

**Comment by asfo** [comment]
Si, haha, ya lo revisamos ;)...Solo hace falta que un desarrollador del núcleo lo arregle ;) para eso paciencia :P...Esperemos @searum lo arregle rápido ya que este error si es algo medio crítico

**Comment by searum** [comment]
Esta spell va bien, Demons & Undead. Por tanto... si no es demonio o undead esa spell no te vale para nada.

**Comment by crowel** [comment]
No es asi este hechizo tiene que hacer daño a todos los objetivos sean el tipo que sean luego lo de los demonios es a parte si es demonio o no muerto los aturde a parte de hacer el daño, este spell esta inutilizable totalmente.

**Comment by darkpriest85** [comment]
Tiene razón crowel, Searum el hechizo hace daño a todos, que adicionalmente le da stun a los undead y demons es un efecto a parte.
