### ISSUE TITLE
Bug > Druida > Innervate

### ISSUE THREAD

**Issue by Keough** [RoDNet/Bugtracker-Infinium-4.0.6a#492]
Buenas tardes, hace poco con los arreglos que han estado haciendo y todo, surgió un problemita con el talento Innevate ( estimular ) que ahora solo cura 13.426 en total, teniendo un talento que hace que me cura 30%. Dejo las imágenes para que revisen
![WoWScrnShot_012813_125646](https://f.cloud.github.com/assets/3309071/104037/2a1869a0-6975-11e2-97a1-c28dabaed1b8.jpg)

![WoWScrnShot_012813_125706](https://f.cloud.github.com/assets/3309071/104040/39da8b66-6975-11e2-982a-a05a3e5a75fd.jpg)

**Comment by searum** [comment]
fix

**Comment by Keough** [comment]
wenaa searum thnks xD
