### ISSUE TITLE
Talento druida heal  [Desenredo] BUG

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#494]
Buenas, el siguiente talento de druida heal, que es de los que t edan al seleccionar la rama restauración está bug.

Su descripción:
El druida elimina todas las raíces y efectos de frenado al cambiar de forma

El único link "decente" que encontré en wowhead es el siguiente, aunque es distinto en la Pandariam :S

http://es.wowhead.com/spell=96429

Espero que os sirva.

Falla cuando te hechan raíces, lo que son efectos ralentizadores si que los elimina.

**Comment by Keough** [comment]
en el cataclysm no cambiaron eso? hasta donde recuerdo al druida han modificado varias cosas con las expansiones. Y ese talento ya no existe -.- fue removido en el 4.1 según lo que veo xD
Ahora con trinket u otros poderes te puedes sacar raíces y efectos de frenado xD

**Comment by asfo** [comment]
A ver, si es un talento, debería estar en WoWHead, inclusive en "old.wowhead.com", pero no lo veo, sinceramente, en este caso, no podríamos tomar "cartas en el asunto" si las cosas que nos ponen son "ilógicas" o "aparentemente inexistentes", prueba la WoW Wiki a ver qué dice y pásanos el link ;)

**Comment by Keough** [comment]
Creo que se refiere mas a la versión TBC, donde cambiando de forma de quitabas toda amarrada, congelada o cualquier poder que te haga moverte mas lento, pero eso en el Cataclysm no existe, osea no es un bug ni nada por el estilo.

**Comment by ghost** [comment]
Buscando estoy en old.wowhead.com pero no lo veo xD En WowWiki, lo encontré:
http://www.wowwiki.com/Druid_abilities 
http://www.wowwiki.com/?search=Disentaglement

De todos modos aquí pongo una imagen para que veais que sí que está en restom
![WoWScrnShot_012913_104800](https://f.cloud.github.com/assets/3328374/106454/2359d78c-69f9-11e2-89f7-2001cefbdd58.jpg)

**Comment by Kr4v3n5** [comment]
prestandole ropa al men aca esta la info de la spell
http://www.wowwiki.com/Disentanglement

**Comment by searum** [comment]
fix
