### ISSUE TITLE
bug de talento de hunter  [Disparo firme mejorado]

### ISSUE THREAD

**Issue by fraijait** [RoDNet/Bugtracker-Infinium-4.0.6a#496]
este talento da la habilidad de que cuando el hunter usa 2 veces seguidas el disparo firme aumenta tu celeridad, sin embargo no sucede. y esta es una habilidad que todo hunter usa, lo cual representa una gran desventaja. Espero que lo solucionen pronto

**Comment by searum** [comment]
fix
