### ISSUE TITLE
[Hunter > Spec: General > Spell > Trap Launcher]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#5]
Lanzador de trampas : http://es.wowhead.com/spell=77769 

No te permite lanzar;
http://es.wowhead.com/spell=34600
http://es.wowhead.com/spell=1499
http://es.wowhead.com/spell=13809
http://es.wowhead.com/spell=13813
http://es.wowhead.com/spell=13795

**Comment by adrianrp1988** [comment]
Reparado en la próxima Rev
