### ISSUE TITLE
Bug Habilidad Pirofrio Mago 

### ISSUE THREAD

**Issue by Albertus167** [RoDNet/Bugtracker-Infinium-4.0.6a#500]
Hola la habilidad de Pirofrio en teoria tiene que quitar 11212p de daño durante 12 segundos 
pero cuando ataco a uno le quita solo 7 cada 1 segundos que hacen 84p durante 12 segundos es muy poco http://es.wowhead.com/spell=44614/descarga-de-pirofrio
en el juego pone que quita 11212p de daño cada 12 segundos con glifo y de normal 10556p de daño

**Comment by DatJetto** [comment]
Será 11212p. durante 12 segundos, porque darte 11k per sec es imposible xD

**Comment by Albertus167** [comment]
no hombre ya lo se si la habilidad es asi 11k durante los 12 segundos 
con glifo 11212p. durante 12 segundos

**Comment by asfo** [comment]
¿Por qué cerraste el reporte?, ¿ya está resuelto?
