### ISSUE TITLE
BUG EN HERMANDAD 

### ISSUE THREAD

**Issue by vanesa34** [RoDNet/Bugtracker-Infinium-4.0.6a#508]
Hola cree una hermandad con una pj llamada pinipon la hermanda se llama poetas violentos y todo iba bien hasta q cayo el server y tras eso se desconfiguro todo y , pasa lo siguiente la pinipon que es la q tiene el gm no ve nada mas que dos pestañas de las 6 que tiene el banco y , aunque coloque los permisos para el resto de rangos y todos vean las pestañas(menos la guild master ) cuando el server vuelve a caer se borran los datos y se borran los permisos por lo que cada vez que cae el server tengo q volver a dar los permisos y cualquier pj de cualquier rango puede ver las 6 pestañas menos la mia q tiene le guild master si es posible porfavor arreglen a q pinipon pueda ver todas las pestañas , y para que no se borren los permisos de  los rangos cada vez que cae el server .

**Comment by vanesa34** [comment]
hola con otra personaje que tengo soy honorable con mi hermandad y la hermandad es nivel 25 el guild vendor deberia tener ya el yelmo y capa de hermandad que aumenta expe al matar bichos y son de leveo y no la tiene por que se supone q esa recompensa la tienes por el nivel de hermandad y basta con ser amistoso yo soy honorable y no me la vende .... tambien queria decir que tampoco tiene el guild vendor la opcion de comprar las pestañas 7 y 8 del banco ....

**Comment by ninotauro** [comment]
hay varias hermandades que les pasa el mismo problema, yo en la que estoy en la horda no puedo ver mas que una pestaña de las que tiene y no es por el rango =S

**Comment by vanesa34** [comment]
me alegro que comentes el post para q los gm tengan conocimiento q no solo pasa en una sino en varias hermandades y le pongan solucion a eso y al guild vendor que no tiene las cosas que deberia tener segun nivel de hermandad o reputacion

**Comment by crowel** [comment]
Mismo problema hoy cuando se cayo el server se reiniciaron todos los rangos y yo que soy el maestro de la hermandad no puedo ver las pestañas

**Comment by vanesa34** [comment]
Nuevo bug la ventaja de hermandad  llamada fuente de ingresos no funciona por que no  genera el % extra de dinero que va a parar al banco de guild cuando la gente despoja dinero o vende algo a los pnj se supone deberia generar un % extra de oro que va a parar al banco de hermandad cada vez que despojas algo de un mob o vendes algo a un pnj y no lo genera por favor miren eso tambien

**Comment by Dekadencee** [comment]
Con la fuente de ingresos te refieres al CashFlow?

**Comment by Dekadencee** [comment]
Fixed!

**Comment by vanesa34** [comment]
me refiero a q no da el dinero que da por la ventaja de hermandad a no ser que estes en grupo con alguien de la hermandad y deberia darlo estes o no en grupo con alquien el % que se genera adicional y que va directo al banco de hermandad igual que tampoco funciona el guild vendor que no vende los item que deberia vender

**Comment by vanesa34** [comment]
ahora con la guild master pinipon veo mas pestasñas pero sigo sin ver la ultima pestaña del banco
