### ISSUE TITLE
[Priest > Spec: Shadow > Spell > Mindblast]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#51]
Explosión mental:
http://es.wowhead.com/spell=8092
Daño de la spell muy elevado.

**Comment by xilopipe** [comment]
El daño no de explosión mental NO esta elevado, la acumulación de 3 orbes de las sombras aumenta su daño un 30%
(la función de orbe de las sombras cambió con los nuevos parches y en wowhead aparecen igual)
