### ISSUE TITLE
[Priest > Spec: General > Spell > Power word: Shield]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#52]
Palabra de poder: Escudo
http://es.wowhead.com/spell=17

Revisar la spell, parece que aguanta bastante más de lo que debe.

**Comment by casicasi** [comment]
mm  yo diria  todo lo contrario soy sacer disci i como pone en el link absorve 19428 sin embargo lo activas i absorve 16397 sobre tener 2 puntod de talentos en el ke deverin aumentar 20% mas 
![WoWScrnShot_123112_154214](https://f.cloud.github.com/assets/3159341/36653/67ad738a-535b-11e2-91c7-f92530968437.jpg) . a i el glifo lo deverian de repasar tampoco cura cuando te echas el escudo 
http://es.wowhead.com/search?q=Palabra+de+poder%3A+escudo bueno espero ke lo revisen mi comentario es en disciplina en sombras no se como esta

**Comment by searum** [comment]
si quereis hacer el reporte como dios manda y lo miramos

**Comment by asfo** [comment]
Comprobado en una curiosa prueba que hice hoy que está correctamente.  Se deja cerrado.
