### ISSUE TITLE
montura no aparece 

### ISSUE THREAD

**Issue by carlospg93** [RoDNet/Bugtracker-Infinium-4.0.6a#521]
![20121231_154716-1](https://f.cloud.github.com/assets/3454691/120493/40fb5b06-6cf8-11e2-9c9a-83ba8c25d1fd.jpg)

**Comment by Dekadencee** [comment]
Reporte incompleto, si no te molestas en dar detalles, tán solo en hacer spam en el foro y encima sólo pones una foto sacada con el movil a la pantalla (para la próxima pulsa "Impr Pant petsis") la cuál no consigo descifrar el enigma, como comprenderás poco podemos hacer.

Si no os molestais en reportar como es debido, no se como quereis que nos molestemos nosotros...
