### ISSUE TITLE
revisar maestria pala heal

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.0.6a#527]
wenas agradeceria a algun pala heal, que testeara su maestria, ya que yo no tengo paladin.

El otro dia echando duelos escuche que la maestria del pala heal,siempre pone un escudo de adsorcion igual,mire y eran de 5k y algo, hoy meda por mira en wowhead http://es.wowhead.com/spell=76669 y segun pregunto a un pala tank en al version que estamos es un 10% durante 8 segundos.

ejemplo: un pala se cura 20k y envez de ponerle un escudo de 2k, le pone de 5k

ejemplo: un pala se cura 5k y envez de ponerse un escudo de 500,le pone de 5k

y ya lo que veo muy over es http://old.wowhead.com/spell=82327 que si cura 8k cada segundo durante 10seg(que nolose exacto ,que como repito no tengo pala)en vez de poner 10 escudos 800 de daño en esos 10seg,pone 10 escudos de 5k.
 segun la maestria pone escudos a curas directas,esto es una cura directa?ami me parece una cura en tiempo

no puedo aportar datos exactos ya que no tengo pala,pero espero se mire o algun pala heal lo teste con datos exactos.

pd:agradecimiento especial a eso 0 palas de 111 jugadores online ,que me likearon la maestria y las habilidades, las 3 veces que pregunte por el general ^^

**Comment by F4NT4SM4** [comment]
si la maestria del pala heler esta bug la absorcion siempre es 5k lo cual no deberia
att: Aztral

**Comment by searum** [comment]
fix
