### ISSUE TITLE
Recetas de Sastrería

### ISSUE THREAD

**Issue by Aixxa** [RoDNet/Bugtracker-Infinium-4.0.6a#53]
Resulta que la compra de recetas de Sastrería mediante paños oníricos esta dañada, al comprar indica que no se pueden obtener más veces esa receta como si se tuviera ya de serie

Id Paño onírico : 54440

Link : http://es.wowhead.com/item=54440

En el link en la pestaña " moneda para " pueden observarse dichas recetas...

Un saludo y gracias ^^

**Comment by Aixxa** [comment]
he visto que ya estaba reportado, perdón

**Comment by Dekadencee** [comment]
Reporte duplicado: RoDNet/Bugtracker-Infinium-4.0.6a#20
Lo cerramos este y seguimos el error desde dicha issue.

Un saludo y gracias por el reporte ^^
