### ISSUE TITLE
OverDamage Chaman elemental

### ISSUE THREAD

**Issue by k4b3z0n** [RoDNet/Bugtracker-Infinium-4.0.6a#54]
http://img822.imageshack.us/img822/4407/wowscrnshot111012004946.jpg

si se fijan en la imagen, estoy full sañoso, tengo 2700 de temple osea 29% de reducción de daño, estabamos testeando con chamaco los spells del chaman elemental, me pego 55k y estamos hablando de un chaman sanguinario, ni siquiera sañoso, eso quiere decir q un verde le estaria pegando aprox 70k sin sudar.

para que lo chequen =)

Gracias

**Comment by searum** [comment]
No me vale un reporte asi, lo cierro porque en realidad no especificas ni spell ni das links a wowhead ni se que coño esta bug, solo te quejas de overdamage, que si, es posible.. pero adivino no soy y no tengo tiempo para estar haciendome chamanes y pegando a gente...

**Comment by k4b3z0n** [comment]
osea no viste la imagen que ahi decia Rafaga de lava, creo que leer o mirar no es dificil

**Comment by macols77** [comment]
Es verdad que aparece en la foto @k4b3z0n pero nos ayudas mucho si especificas el hechizo en wowhead (o almenos su ID) y cuanto debería quitar.

Gracias por reportar :)
