### ISSUE TITLE
Configuración de las pestañas de la hermandad

### ISSUE THREAD

**Issue by lllalvarolll** [RoDNet/Bugtracker-Infinium-4.0.6a#552]
Hola. Soy el maestro de una hermandad. 
Cuando pongo todas las configuraciones de cuantos montones se pueden retirar (según el rango que tengas) de las pestañas del banco, pierdo toda la configuración que había realizado anteriormente al desconectarme del juego. Cuando vuelvo a entrar, los montones que se pueden retirar se ponen a 0, es decir, como si no hubiera tocado nada.

**Comment by crowel** [comment]
Si, ami tambien me pasa espero que se pueda mirar es muy molesto tener que cambiarlo cada vez al entrar.
Un saludo.
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/508

**Comment by Dekadencee** [comment]
Fixed!
