### ISSUE TITLE
Sello de Perspicacia (Paladin)

### ISSUE THREAD

**Issue by Saskhaek** [RoDNet/Bugtracker-Infinium-4.0.6a#554]
El sello dice que cada vez que se golpea al enemigo y el sello esta activo, hay una probabilidad de recuperar un  4% de mana y aparte, cuando desatas su energia con sentencia recuperas un 15% de mana.

```
                               ¿Cual es el problema?
```

El problema de esta facultad es: No recupera un 4% de mana, recupera una cantidad inferior.

Y el segundo problema de esta facultad es: Con el sello activo y usando sentencia, supuestamente me debe de recuperar un 15% de mana y me recupera una cantidad inferior, en algunas ocasiones no me recupera mana y en otras si. Tiene probabilidad, pero deberia ser 100%

**Comment by searum** [comment]
fixeado
