### ISSUE TITLE
Bug Alquimia

### ISSUE THREAD

**Issue by chipi666** [RoDNet/Bugtracker-Infinium-4.0.6a#558]
Hola, estoy subiendo la profesión de alquimia ya llevo 76p y no se a abierto mas recetas para comprar creo que tiene un problema me podrían ayudar anexo imagen, saludos...

![WoWScrnShot_020613_185929](https://f.cloud.github.com/assets/3199832/134391/397a09b6-70d3-11e2-9824-59901e207c88.jpg)

**Comment by Keough** [comment]
revisa esta guia -> http://www.guiaswow.com/alquimia/guia-alquimia-alchemy-1-525.html xD
tal vez subas rápido y sin problemas con eso >_<

**Comment by 50megas** [comment]
cual es el bug? por que  te salen pociones en rojo y amarillo osea que puedes seguir suviendo alquimia perfectamente, y si es el  istructor que no te deja aprender esas recetas es por el filtro que lo tienes puesto para que salga todo lo que no aprediste ,pero te falta nivel para aprenderlo
