### ISSUE TITLE
error de los socket de los item epicos de peleteria

### ISSUE THREAD

**Issue by alfergo** [RoDNet/Bugtracker-Infinium-4.0.6a#567]
personaje :rekete          Hola he creado con la profesion de peleteria el coselete de la furia de la naturaleza y el latigazo de relampagos y al insertar las gemas hace un ruido raro y no se insertan en ninguna de las dos piezas y no puedo mejorarlas

**Comment by Diezape** [comment]
me ocurre lo mismo, desde hace tiempo. Gracias Searum por arreglarlo...por adelantado...XD

**Comment by searum** [comment]
fix!
