### ISSUE TITLE
[CRITICAL] Problemas en la red del servidor

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.0.6a#568]
wenas ya llevo un par  de semanas ,que cada pocos dias semequeda el wow como desconetado, pero sin desconectar uso alf+f4 entro de nuevo pero seme queda en conectando , al raro consigo entrar con mucha lag y me pasa 1 o 2 veces mas,hasta pasado 1 hora  o asi no semequita

pensaba que era mi internet que no es muy oficial que digamos xd, pero hoy ya me convecido que no era ya que estaba en una arena,se calleron mi compi y los otros 2 a la vez y ami me subio el lag ,les mate gane la arenas saque los puntos y a los 2 minutos me quede desconectado pero en el juego sin porder hacer nada.

destacar que cada vez que me paso callo unos 20 o 30 players online,pero hoy muchos mas eramos unos 100 y hoy a las 20:30 hay 28 conectado algo insolito desde hace muchos meses y muchos quejandose del lag y susurrando tienes lag?

tambien comentar que la wed tambien va muy lenta cuando pasa esto ,almenos hoy por si tiene algo que ver

intente postear esto en el foro pero no me dejaba seme deslogeaba y decia que no tenia permisos

**Comment by Dekadencee** [comment]
Estamos atravesando un problema de red actualmente, no sabemos si es un DDoS o un error de nuestro proveedor de servicios, estamos haciendo todo lo posible por restaurar los sistemas.

Hoy si, pero los demás días imposible, así que miraria también tu conexión a internet.
