### ISSUE TITLE
problemas de administracion

### ISSUE THREAD

**Issue by Kempachi** [RoDNet/Bugtracker-Infinium-4.0.6a#569]
Soy el Guild master y no me deja sacar el dinero del banco y no me deja tampoco comprar otra pestaña del banco de la hermandad

![Copia de WoWScrnShot_020713_225756](https://f.cloud.github.com/assets/3505863/137550/23684cf0-7173-11e2-85d4-68a55fcbeec6.jpg)
![Copia de WoWScrnShot_020713_225620](https://f.cloud.github.com/assets/3505863/137551/2505b1a6-7173-11e2-88d3-b68d75e68689.jpg)

**Comment by Dekadencee** [comment]
Fixed!
