### ISSUE TITLE
Chaman > Spec > Escudo de relampagos

### ISSUE THREAD

**Issue by Paketon** [RoDNet/Bugtracker-Infinium-4.0.6a#571]
Como muchos chamanes saben y se callan, este escudo no gasta sus cargas al golpear a un enemigo. Es infinito.

http://es.wowhead.com/spell=25020/escudo-de-relampagos

Lo note pegando a un chaman off para probar mi puñalada (cada vez pega menos... gracias a algunos llorones que odian que los rogues podamos matar y no solo stunear...)
Resulta que cuando le mate mire mi vida y estaba a la mitad. De 126ks a 66ks y sin que el chaman se moviera.... solo por el escudo de relampagos.

**Comment by 50megas** [comment]
hay un glifo para no quedarte sin cargas de escudo de relampagos, lo que si pienso que el escudo salta damasiado como ya comente en  #471

**Comment by DatJetto** [comment]
La función de saltar cada pocos segundos está bien, porque si tiro varias flechas una de cada 3-4 me da rayitos, la cosa es que el daño del escudo está alto, y en mejora te da el tick 2-3k y en elemental 5-6k, supongo que se ve aumentado desproporcionalmente por el Spell Power

**Comment by Paketon** [comment]
Bueno lo del glifo perdon por el fallo.... por no fijarme bien xD
Pero el daño coincido en que es una barbaridad. No vi el post, dani sorry :S
Con ese sobra, cerrar este.
