### ISSUE TITLE
bug encatamiento derrumblo 

### ISSUE THREAD

**Issue by lks06** [RoDNet/Bugtracker-Infinium-4.0.6a#578]
Tengo hachas de una mano encantadas con derrumblo y se me activa una sola tendria que activarse en las 2 Hachas.

![ghjh](https://f.cloud.github.com/assets/3086718/142695/801709da-730f-11e2-84a5-88475277ff80.JPG)

**Comment by ghost** [comment]
Antes sí se acumulaban, pero ahora creo que está bien lo de que no se acumulen, ya que es un poco... bestia que te salten los 2 enchants más el bordado de la capa lo cual serían 3k más de AP. En el ofi creo que sólo saltaba 1 también

**Comment by DatJetto** [comment]
Solo ha de saltar 1 encantamiento de derrumblo. Está correcto

**Comment by searum** [comment]
cierro
