### ISSUE TITLE
[ Hunter > Spell > Steady Shot > Focus Reg ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#581]
Disparo firme:
http://old.wowhead.com/spell=56641

Regeneración disparo firme:
http://old.wowhead.com/spell=77443

Tiene un minúsculo problema, el cual podría ayudar bastante al dps y a dejar esta spell 100% Blizzlike.

Actualmente en el servidor: Cuando lanzas disparo firme / Cobra y completas la barra de casteo, el disparo sale hacia el objetivo, impacta y ahí es cuando recupera el enfoque.
- Lo que debería pasar es lo siguiente: Casteamos Firme / Cobra y cuando completamos la barra de casteo, regenera +9 de enfoque, y el disparo sale hacia el objetivo posteriormente impactando.

Parece una tontería, pero cuando el objetivo está en range limit / 40 m /  y el disparo tarda en llegar ralentiza las reacciones del cazador al no tener foco y tener que lanzar varios firmes de ''sobra'' para hacer daño, pudiendo lanzar Quimeras o Arcanos.

**Comment by searum** [comment]
Venga jetto! no me seas pijooo!

Se mirara.

**Comment by DatJetto** [comment]
Sea, claro que prefiero que se arreglen muchisimos bugs antes que este, solo lo dejo para que se arregle en un futuro, es un bug minúsculo, pero un paso para la perfección xD
