### ISSUE TITLE
[ BG > Isla de la conquista > Bug de portales ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#582]
Casi todo el mundo abusa de este bug maldito , no lo he visto reportado así que me aventuré a tomar screens para que se acaben ya las *#@$'! discusiones del chat global  de eh eres un bugero saliste por la puerta antes de empezar, hay men no se qué. Pues ya está madafakas. 

1- El portal de la bg al iniciar no está visible, pero está, no debiendo , si te acercas puedes ser teletransportado antes de que la bg comience 

http://i47.tinypic.com/jt2ypf.jpg
El círculo rojo es la ubicación aproximada del portal ya que como es invisible, pues no se ve, viva la redundancia. 

Tu coges, te acercas y pum 

http://i50.tinypic.com/10sbr11.jpg
Te lleva fuera, donde debe de estar el otro portal, no puedes realizar la operación inversa, es decir, usar el de fuera para entrar a tu base ( antes de comenzar la bg, después si, creo... ).

Y  de ahí puedes ir a coger las bases antes que nadie y demás :D

**Comment by ghost** [comment]
Es así como dice, el portal es "invisible", y puedes usarlo tranquilamente antes de que comience el campo de batalla.

**Comment by Fabercastell** [comment]
Este bug persiste al dia 19/03/13 siendo utilizado por ambas facciones para tomar las bases al inicio de la BG
