### ISSUE TITLE
Experiencia de la hermandad atascada.

### ISSUE THREAD

**Issue by lllalvarolll** [RoDNet/Bugtracker-Infinium-4.0.6a#584]
Buenas tardes. Hace 2 días ya reporté este mismo tema. Parecía que se había solucionado pero, al día siguiente de solucionarse, se ha vuelto a quedar atascada la experiencia de la hermandad y ni siquiera ha llegado al máximo de experiencia que se puede obtener al día.

**Comment by DatJetto** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/574

**Comment by searum** [comment]
Cierro porque esta repetido el reporte
