### ISSUE TITLE
Misión [Amenaza desde el cielo]

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#585]
La misión Amenaza desde el cielo http://es.wowhead.com/quest=13812/amenaza-desde-el-cielo esta bug, el dragón Yertafauce http://es.wowhead.com/npc=33687 si está y puede ser matado, pero los Bombardero cultor http://es.wowhead.com/npc=33695 que deberían estar montando al dragon no estan.

**Comment by redneo** [comment]
arreglada, creo
