### ISSUE TITLE
Mazmorra/Raid bug Templo Oscuro

### ISSUE THREAD

**Issue by Albertus167** [RoDNet/Bugtracker-Infinium-4.0.6a#586]
Hola reporto la Mazmorra Templo oscuro que esta bug nos gustaria que se arreglara seremos pacientes siempre y cuando la arreglen :)

**Comment by searum** [comment]
pues si describes el bug lo podremos arreglar, seamos pacientes mientras esperamos que aprendais a reportar... 

pasate por aqui http://reignofdarkness.net/wow/noticia/34/
