### ISSUE TITLE
[Mage > Spell > Ice Lance > Fingers of Frost]

### ISSUE THREAD

**Issue by furria** [RoDNet/Bugtracker-Infinium-4.0.6a#589]
Pues el problema es muy simple.
Por un lado tenemos la "Lanza de Hielo" http://old.wowhead.com/spell=30455
Por otro lado a "Dedos de escarcha" http://old.wowhead.com/spell=83074

La mecánica en sí funciona correctamente, si tienes una carga de "Dedos de escarcha" y lanzas una lanza de hielo sale crítica o puedes lanzar "Congelación Profunda", el problema radica en que si tienes 2 cargas y tiras  una lanza, las consume ambas y no una sola como debería ser.

**Comment by adrianrp1988** [comment]
fixed
