### ISSUE TITLE
Quest. El gran atraco al banco

### ISSUE THREAD

**Issue by Nepptum** [RoDNet/Bugtracker-Infinium-4.0.6a#593]
http://es.wowhead.com/quest=14122/el-gran-atraco-al-banco#.

esa quest esta bug no deja completarla adjunto la imagen porfavor solucionenlo 

![WoWScrnShot_021113_172708](https://f.cloud.github.com/assets/3106443/146453/bb0cb4ba-7489-11e2-8ea9-376b389c32d4.jpg)

**Comment by searum** [comment]
me falta solucionar un crash en esta quest y meto el script!

**Comment by searum** [comment]
Solucionado! :D

**Comment by Nepptum** [comment]
muchas gracias searum
