### ISSUE TITLE
Problema banco de la guild

### ISSUE THREAD

**Issue by david-landin** [RoDNet/Bugtracker-Infinium-4.0.6a#594]
He comprado 4 pestañas y se me han bloqueado 2, soy el lider de la guild y debería poder entrar en todas (a los miembros no les pasa).
![Bug](https://f.cloud.github.com/assets/3536110/146629/aceb6672-7490-11e2-82c1-ebc93caa1a87.png)

**Comment by ninotauro** [comment]
tambien nos pasa en poetas violentos

**Comment by chayppi** [comment]
A mi tambien me ocurre, siendo MasterGuild compre la 2ª pestaña, y a partir del primer dia solo he podido acceder a una de las 2.

**Comment by Dekadencee** [comment]
Fixed!
