### ISSUE TITLE
Bug en la pet guardia vil del brujo demonologia

### ISSUE THREAD

**Issue by manuanza** [RoDNet/Bugtracker-Infinium-4.0.6a#60]
Fallo: La pet saca muy poco daño en comparación a lo que tendría que sacar, sacando 400 - 500 cuando tendria que sacar automatico por lo menos 1500 por golpe y con poderes bastante mas 

http://es.wowhead.com/spells=-3.9.761

**Comment by andrixx** [comment]
Muy cierto ademas tiene muy poca vida

**Comment by luislpv22** [comment]
Corregido.
