### ISSUE TITLE
[Sacerdote] Hechizo Explosion mental

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#601]
Este hechizo pega algo mas de la cuenta en mi caso 2k mas de lo que especifica el hechizo.
http://es.wowhead.com/spell=8092
Como os podeis fijar en mi hechizo marca casi 6k de daño y pego 8k.
![explosion mental](https://f.cloud.github.com/assets/3537253/148762/da3bbfd4-7510-11e2-8927-09a472bc7310.jpg)

Un saludo.

**Comment by lavik10** [comment]
Eso no es un error, debes tener en cuenta que tus stats influyen en el resultado final del spell.

**Comment by crowel** [comment]
Lavik si te fijas al equipar cualquier armadura y aumentar tus stats tambien aumenta el daño del hechizo en funcion de tus stats, si el hechizo me marca una cosa y hace tanto daño, es que hace daño de mas, cuando te salta un stat de un abalorio puedes fijarte que en la descripcion del hechizo te aumenta lo que el abalorio añade asi que los stats no influyen en el resultado final, siempre influyen en tiempo real.
