### ISSUE TITLE
[Sacerdote]Hechizo Proteccion contra las sombras

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#602]
El hechizo en cuestion es Proteccion contra las sombras no puedo poner el enlace de wow head lo siento, no aparece.

El problema es que al usar este spell te aparecen dos buff de protecion cuando solo tendria que salir un unico bufo, adjunto fotos.

![protecion contra las sombras](https://f.cloud.github.com/assets/3537253/148801/b343bf9c-7512-11e2-8301-d49290871e06.jpg)

![protecion contra las sombras 1](https://f.cloud.github.com/assets/3537253/148805/bb82e96c-7512-11e2-9e18-d75b8dac52ee.jpg)

**Comment by ghost** [comment]
Aca dejo el link a wowhead por si lo necesitan para arreglarlo http://old.wowhead.com/spell=27683

**Comment by ghost** [comment]
Si, sale doblemente, pero creo que te lo suma bien, no te lo suma x2

**Comment by crowel** [comment]
Nop, te sale doble uno de 195 que es lo que especifica el hechizo que debe sumar de resistencia a las sombras y otro 146 puntos a mayores

**Comment by searum** [comment]
ya esta arreglado

**Comment by crowel** [comment]
nicee, graciass
