### ISSUE TITLE
[Sacerdote] Hechizo Alarido psquico

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#603]
http://es.wowhead.com/spell=8122/alarido-psiquico
Este hechizo tiene un gran bug, su uso esta muy bien hace huir a los enemigos en el tiempo que tiene que ser el problema es que tambien los agarra con una red ..
Esto no deberia ser asi adjunto foto.
![alarido](https://f.cloud.github.com/assets/3537253/148830/96c3b2cc-7513-11e2-9d08-0942c7af189a.jpg)

**Comment by ghost** [comment]
Tengo entendido que esto lo han hecho aproposito con todos los tipos de "miedo", porque cuando alguien cae bajo el efecto de "miedo" y se pone a correr queda bugeado de bajo del mapa.

**Comment by crowel** [comment]
Si hai alguien que lo pueda confirmar doi por cerrado el issue

**Comment by ghost** [comment]
Bueno como el buscador del foro no funciona al parecer, te dejo lo que encontre:
Este es el reporte del bug de miedo de que cuando alguien es afectado por el cae al vacio #438.
Este es un reporte de la "red" al usar miedo #63 que el mismo searum (admin) cerro.
Aqui en foro alguien pregunta sobre la red y le responden que es para que no se caiga al vacio http://reignofdarkness.net/wow/foros/t433/.

**Comment by crowel** [comment]
Muchas gracias Lvmb muy completo la respuesta, asi da gusto^^ cierro el tema.
