### ISSUE TITLE
[Sacerdote] Hechizos Voluntad interna - Fuego interno

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#604]
Hola me gustaria preguntar/informar sobre estes dos hechizos como el titulo refleja.
http://es.wowhead.com/spell=588 fuego interno
http://es.wowhead.com/spell=73413 voluntad interna

Hasta ahora en los servidores que he jugado siempre he podido llevar los dos activados al mismo tiempo, pero cuando lo intento usar aqui si me pongo uno se me quita el otro, si me pudieran informar si es un bug o es así lo agradeceria ya que en el hechizo no especifica que no se pueda llevar uno de los dos.
Un saludo.

**Comment by ghost** [comment]
Esta bien, no se pueden usar juntos al mismo tiempo, si lees el enlace de "voluntad interna" que dejaste, veras que en la descripción del hechizo dice "Solo puedes tener activo Voluntad interna o Fuego interno."

**Comment by crowel** [comment]
Gracias por el comentario Lvmb^^
