### ISSUE TITLE
[Sacerdote] Talento Bug Explosión mental mejorada

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#605]
Este talento reduce el tiempo de lanzamiento de explosion mental un 1,5 segundos con los 3 puntos en el talento, esto es bien ahora vamos al fallo y con la forma de las sombras tu explosion mental tambien tiene un 100% de probabilidad de reducir todas las sanaciones realizadas al objetivo un 10% durante 10 sec, he probado un monton de veces el hechizo y nunca se activa la reduccion de sanacion y al tener los 3 puntos de talentos es un 100% entonces tendria que activarse siempre.
Adjunto una foto, un saludo.

![explosion mental mejorada](https://f.cloud.github.com/assets/3537253/148968/e7448112-7519-11e2-898b-b78c53985291.jpg)

**Comment by searum** [comment]
arreglado

**Comment by crowel** [comment]
Perfecto :) +1
