### ISSUE TITLE
[Paladin] Hechizo Colera Sagrada 

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#606]
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/491
 Problema con Cólera Sagrada como menciona Darkpriest
"No hace absolutamente nada de daño, es como si no arrojara nada"
http://es.wowhead.com/spell=119072
Veo que el otro track del bug se ha cerrado asi que vuelvo a abrir este con la confianza que se pueda reparar el hechizo.
Como menciona Searum que esta spell esta bien, debo de decir que esta mal , como el menciona si no es a no muerto o demonio no vale de nada, no es asi, este hechizo tiene que hacer daño y unos 4-6k aproximadamente a todos los objetivos sean el tipo que sean, luego lo de los demonios es a parte si es demonio o no muerto los aturde a parte de hacer el daño, este spell esta inutilizable totalmente, sobre todo para un paladín heal es imprenscidible para en arenas hacer algo de daño y este hechizo no lo hace, no es por llevar la contraria pero es de la manera que funciona el hechizo en un server que estea bien arreglado o en el oficial, un saludo.

**Comment by F4NT4SM4** [comment]
el hechizo hace daño a todos los objetivos y tambien aturde a los que sean no-mueto o demonios
en pala repre es util para matar serpientes de caza o sacar a alguien de sigilo
pero como esta bug..

**Comment by searum** [comment]
creo que ya la fixee hay que probar :)

**Comment by searum** [comment]
si, arreglado ^^

**Comment by crowel** [comment]
Hola searum el hechizo va perfecto el unico defectillo que veo que solo afecta a criaturas a jugadores no los aturde si son no-muertos o tienen algun demonio de mascota.
Gracias por tu trabajo.

**Comment by searum** [comment]
Es que eso es asi, a jugadores no-muertos no los afecta.. pero eso dejo de afectarlos hace muchas expansiones xD

**Comment by crowel** [comment]
Ah ok perdona, del servidor que vengo si se podia no sabia que estaba mal entonces :) gracias por tu tiempo
