### ISSUE TITLE
[Paladin] Hechizo Exorcismo

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#607]
Este hechizo sin glifo trata simplemente de un golpe, lo que me fijo es que despues de golpear sigue haciendo daño durante el tiempo, unos 5 segundos y no deberia ser asi, a no ser teniendo glifo pero no de la manera que está.
http://es.wowhead.com/spell=879
![exorcismo](https://f.cloud.github.com/assets/3537253/149351/3755db00-752a-11e2-98b1-22693c12c3c7.jpg)

**Comment by searum** [comment]
recuerda la versión en la que estas xD

ToolTip: Recibiendo $w2 p. de daño Sagrado cada $t2 s.

la spell es asi
