### ISSUE TITLE
[Paladin] Talento Maestría: Sanación iluminada

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#608]
Hola
http://es.wowhead.com/spell=76669
Tus hechizos de sanación directa también colocan un escudo de absorción sobre el objetivo por un 12% de la cantidad sanada que dura 15 s.

Cuando me curo con  destello de luz 12k de curacion me pone un escudo de 3006 de absorcion de daño, deberia de ser un 12% de los 12k de curacion, osea que tendria que absorber menos de lo que absorbe.

Cuando me curo con 19k de curacion me tendria que poner una parte proporcional a la cura que hice, un 12% si os fijais me hace un escudo de 3006 tambien me cure con cualquier cura siempre pone la misma absorcion de daño, en resumen esta mal la maestria del paladin sagrado.
Voi adjuntar dos fotos con las curas y el escudo que se crea para que podais ver el fallo.
Un saludo.
![destello luz](https://f.cloud.github.com/assets/3537253/149383/1f980202-752c-11e2-94cb-7128f34ec623.jpg)
![luz divina](https://f.cloud.github.com/assets/3537253/149386/26f07b74-752c-11e2-95e7-40817b2054b1.jpg)

**Comment by DatJetto** [comment]
No pones por ejemplo, que al sanar a otro, te pone el escudo a tí  y al objetivo también?
Radiancia Sagrada ( que es un hot ) pone escudo cada tick?

**Comment by crowel** [comment]
DatJetto, gracias por tu comentario, lo comprobe y es cierto sanas a otro y tambien te pone el escudo a ti, y respecto a radiancia sagrada no se pone siempre el escudo pero si se activa y segun la especificacion solo se tendria que activar con sanaciones directas.
Lo que tambien me fije y veo mas bien donde esta el problema es que el escudo aumenta la absorcion cuanto mas poder de hechizo/sanacion tienes y no deberia ser asi sino que tendria que ser un 12% de la cura que realices.

**Comment by crowel** [comment]
Siento poner un doble reporte acabo de encontrar mirando la lista un reporte como el mio, siento no haberlo visto antes adjunto link https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/527

**Comment by searum** [comment]
No os fieis de wowhead... es un 10% y ya lo tengo fix, ahora me falta mirar lo de holy radiance a ver que se puede hacer.

**Comment by searum** [comment]
El holy radiance he puesto para que no te de el buff y lo del objetivo tambien esta arreglado, al caster no le pone el escudo si este no es el objetivo

**Comment by crowel** [comment]
Hola queria comentar searum que ahora no se activa el escudo de la maestria ni curando a uno mismo ni curando a otro, no se me activa ni a mi ni a el, si le puedes echar un vistazo, gracias.
