### ISSUE TITLE
Druida heal árbol de vida

### ISSUE THREAD

**Issue by Nidala** [RoDNet/Bugtracker-Infinium-4.0.6a#609]
Al usar árbol de vida recrecimiento se vuelve instantaneo, cosa que funciona pero su bug está en que tienes que estar quieto para lanzarlo, cosa que no deberia pasar por que si es instantaneo deberáas poder lanzarlo mientras caminas.

**Comment by ghost** [comment]
Esto ya se lo comenté yo a Searum ;) Lee lo que pone:
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/446

PD: si te fijas en lo que puse, raíces también están igual =P Y cuando eso pon enlaces de wowhead jaja

**Comment by Dekadencee** [comment]
Bug repetido, lo seguimos desde el antiguo reporte https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/446
