### ISSUE TITLE
[Hermandad > Habilidades > Piedra Presta]

### ISSUE THREAD

**Issue by HexR-zz** [RoDNet/Bugtracker-Infinium-4.0.6a#61]
No reduce los 15 minutos de cd de la piedra de hogar

**Comment by asfo** [comment]
Quizá añadiendo estas líneas en el archivo: src/server/game/Spells/SpellEffects.cpp se repare...No se si sea de esta manera ya que no se si está el aura como tal, pero esperemos que funcione ;).

``` c
              case 8690:
                {
                    if(m_caster->HasAura(83944)) 
                        m_caster->ToPlayer()->ReduceSpellCooldown(900000,8690); 
                    break;
                }
```
