### ISSUE TITLE
Explosión Arcana - Mago Arcano.

### ISSUE THREAD

**Issue by IcarusLives** [RoDNet/Bugtracker-Infinium-4.0.6a#610]
La Explosión Arcana, ataque principal de la rama arcano del mago no hace nada de daño, su daño no se corresponde siquiera con el que la habilidad dice que hará. Es un ataque indispensable pues sin él la rama Arcano del mago es completamente disfuncional. Saludos.

**Comment by searum** [comment]
la acabo de fixear
