### ISSUE TITLE
[Debuff] Primeros Auxilios

### ISSUE THREAD

**Issue by NeKroZ** [RoDNet/Bugtracker-Infinium-4.0.6a#611]
El debuff de primeros auxilios [Recently Bandaged] que te imposibilita usar un Bandage por 1 min, no esta funcionando. esto es muy importante en las Arenas y BG. (poder usar libremente Primeros Auxilios repetidamente)

**Comment by DatJetto** [comment]
WTF a mi si me funciona... empieza a castear el vendaje y se para al momento, te gasta 1 venda pero no te cura.
