### ISSUE TITLE
daño excesivo totem

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.0.6a#618]
el totem http://es.wowhead.com/spell=8190 creo que hace un daño exagerado

el otro dia en arenas, un roge y yo con mi dk le damos a un chami elemental con heal , a los 20 seg estabamos muertos los 2 y eso que solo tiro la istantania por que con roge no puedo castear ,mire rejistro de combate y a mi dk con 3k de temple le metia 10k cada 2seg a eso le sumamos el daño escudo de relampagos unos 5k tambien cada 2 o 3 seg, nos matamos solos ,con un daño de 7,500 por segundo solo por plantar un totem y ponerse un escudo xd

tengo foto pero prefiero no ponerla, no se confundan el reporte de un bug con otra cosa

aqui  una foto de mi testeo con mi chami algo menos equipado,con criticos de 20k buff

<a href="http://tinypic.com?ref=2lke45e" target="_blank"><img src="http://i47.tinypic.com/2lke45e.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

un saludo

**Comment by searum** [comment]
Vale ya esta fix
