### ISSUE TITLE
Guardias Tol Barad

### ISSUE THREAD

**Issue by Faked** [RoDNet/Bugtracker-Infinium-4.0.6a#62]
Pongo el ejemplo de la horda, no se si en la alianza estarán igual.

Su daño es bajisimo, es ridiculo. 

http://es.wowhead.com/npc=48355/guardia-grito-infernal

No viene el daño que deben de pegar, pero si nos fijamos en los comentarios :+1: 

'' Sure, let these guys be a anti-gank control, but please blizzard, please remove their infinite CC / Silence / Knockdowns and 40k hits. Because running past that Horde location makes you die if you come too close.... ''

Se que estos no son pruebas concluyentes, pero en el oficial de un golpe te hacen delete..

Y bueno, esto es lo que meten a un TELA

http://i50.tinypic.com/wwan0g.jpg

**Comment by searum** [comment]
fix
