### ISSUE TITLE
Matar a Dormus el camellero no da titulo de "el camellero".

### ISSUE THREAD

**Issue by mywel** [RoDNet/Bugtracker-Infinium-4.0.6a#623]
Buenas, he conseguido el logro de "hay que jorobarse" con las figuritas de Uldum. Estaba llendo a farmear colatigo y mientras sobrevolaba el desierto vi una figura de camello y me acerque a recogerla, cual fue mi sorpresa que esta vez no se me habia deshecho en las manos. Esta en concreto me llevó a Feralas, donde he matado (solo) al boss Dormus el camellero y me ha dado la montura http://es.wowhead.com/item=63046 . Pero no me ha dado el titulo de "el camellero" que supuestamente tiene que dar  y en mi opinión es lo mas interesante del asunto.

Lo que quisiera saber es si podré conseguir el titulo y tambien, logicamente, si se arreglara esto para que todos los demas usuarios tambien puedan tener su titulo.
Un saludo.

**Comment by ghost** [comment]
Recien es en el parche 4.1 ese titulo/logro http://www.wowpedia.org/Scourer_of_the_Eternal_Sands nosotros estamos en la 4.0.6, si alguien puede cerrar el reporte.
