### ISSUE TITLE
reporte de bug de esquema

### ISSUE THREAD

**Issue by vanesa34** [RoDNet/Bugtracker-Infinium-4.0.6a#624]
buenas noches , me dirijo a ustedes hablo en plural pq no se quien lo leera para reportar el siguiente bug de un item , a ver mi sacerdotisa es encanter full y me dirigia alegremente en ventor a comprar recetas nuevas de encanter y resulta que compre un esquema en suministros de encanter que es para crear una pet del encantador que es una linda lamparilla , pues bien compre el esquema pero no me deja aprenderlo a pesar que soy 525 , pregunte por el general si a alguien mas le paso y un pj llamado beyonce me conto que tambien le ocurrio compras el esquema y le das a aprender y se queda como intentando aprendero pero no lo aprende se queda como si estubiera lagada plan que hace el intento pero no.. por favor arreglenlo para que podamos disfrutar ese esquema y crear mascotas de lamparillas , hay gente que como a mi nos gusta coleccionar pets u.u

**Comment by searum** [comment]
Puedes facilitarme enlaces a wowhead del item ? Muchas gracias

**Comment by ghost** [comment]
Esta receta tiene su contraparte en la horda, al transferirla pasa de ser Lámpara mágica a Linterna encantada y no se si en la horda tambien pasa el error expuesto aqui, asi que dejo enlaces de la versión alianza y de la versión horda.
Lámpara mágica (version alianza): http://es.wowhead.com/item=67312
Linterna encantada (version horda): http://es.wowhead.com/item=67308

**Comment by vanesa34** [comment]
gracias por vuestra atencion a ver si se arregla pronto

**Comment by searum** [comment]
fix
