### ISSUE TITLE
[Items > Mysterious Egg> No me da el Protodraco Verde] 

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.0.6a#625]
Hace 7 días ya, compre el Item: Huevo Misterioso ( Donde sale las Riendas del Protodraco Verde ) . Y lo que me sucede es que cuando lo iba a comprar me aparecía Duración: 3 Días, pero yo investigue en Internet y me decía que para que saliera tenia que esperar 7 días lo cual lo hice y ya lo que me aparece es Duración: 0 segundos y me aparece unas letras amarillas que me dice ''Algo sale del Huevo'', pero por mas de que le doy click secundario no me despoja nada entonces no se que hacer ni que pasa aqui les dejo una imagen:
https://f.cloud.github.com/assets/3613748/164224/8e952350-7884-11e2-82c8-9a906020b94a.jpg  No se si les dara bien la imagen por que es mi primera vez en esto, pero espero que me ayuden prontamente. Gracias por la atencion.

**Comment by ghost** [comment]
Si, son 3 días los que hay que esperar para abrir el huevo, dejo enlace del item por si hace falta http://es.wowhead.com/item=39878/huevo-misterioso, también hay un bug abierto sobre esto #276 .
(como anotación, en otro server que he jugado pasaba lo mismo, el huevo no funciona, pero si lo pones en la bolsa principal, la de 16 casillas que todos los pjs tienen al comenzar el juego, al cabo de 3 días el huevo se puede abrir sin problema, pero solo en esa bolsa, no servía si lo ponías en otra bolsa que no sea esa, perdón si aquí no sucede lo mismo).

**Comment by DatJetto** [comment]
Eso mismo, El Protodraco verde sale, de hecho yo lo tengo, pero necesitas tner los huevos en la mochila principal :D

**Comment by Hellythium** [comment]
A bueno, muchas gracias a los dos, les debo mucho ya mismo hago el cambio a ver si el miércoles me sale el proto, gracias a los dos.

**Comment by Hellythium** [comment]
Buenas, vuelvo a reabrir el caso. Es que lo que pasa es que ya los cambie a la bolsa principal, pero el nuevo problema es que me muestra Duración: 7 Días en vez de 3 Días aquí les dejo unos Screemshots para que vean lo que sucede cuando lo linqueo en el Chat y cuando lo señalo en la mochila: file:///C:/Archivos%20de%20programa/World%20of%20Warcraft/Screenshots/WoWScrnShot_021713_215739.jpg y la otra 
file:///C:/Archivos%20de%20programa/World%20of%20Warcraft/Screenshots/WoWScrnShot_021713_215941.jpg  

Espero que me ayuden y/o me solucionen el problema. Gracias por su atención y colaboracion
