### ISSUE TITLE
Ultimo boss Grim Batol

### ISSUE THREAD

**Issue by Naiira** [RoDNet/Bugtracker-Infinium-4.0.6a#629]
El último bos de la mazmorra en modo heróico Grim batol , esta bugueado , cada vez que se le baja un poco de vida , se le regenera la salud al completo.

**Comment by ghost** [comment]
No estoy seguro, creo que estes el último boss (por favor corríjanme si estoy equivocado) http://www.wowhead.com/npc=40484

**Comment by HexR-zz** [comment]
Sí, ese es el último boss. A pesar de que el reporte esté muy mal informado, te voy a explicar por qué no está bug. Este Jefe lanza de vez en cuando un meteorito: http://www.wowhead.com/spell=79466 Este meteorito si golpea a algún jugador del grupo le retiene en el sitio durante 6 segundos y cada segundo se cura 8k de vida. Es decir, que se curará 8_6=48k de vida por jugador que sea golpeado por el meteorito. Si tu grupo se queda quieto pegándole como una piñata y os da a los 5 el meteorito se curará 48_5= 240k a los 6 segundos, o lo que es lo mismo 8_5=40k por segundo durante 6 segundos 40_6=240k de vida. Así que, o tenéis un DPS total superior a 40k y podéis permitiros el lujo de comeros el meteorito o podéis fijaros en dónde caen los meteoritos y esquivarlos. Cierro Issue
