### ISSUE TITLE
Fear - Red

### ISSUE THREAD

**Issue by Faked** [RoDNet/Bugtracker-Infinium-4.0.6a#63]
Cada vez que le haces un fear a alguien se queda en una ''red'' en lo que dura el fear

Véase:

http://i45.tinypic.com/2crvwwy.jpg

No estoy seguro de que salga siempre, pero a veces se activa

**Comment by DatJetto** [comment]
Si, sale siempre con TODOS los efectos de pérdida de movimiento, no entiendo por qué :C lo iba a reportar pero ya lo has hecho tu xD :camel:
