### ISSUE TITLE
[Druida] Forma de lechúcico lunar (Equilibrio)

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#631]
Hola quisiera informar de un bug con la Forma de lechúcico lunar http://es.wowhead.com/spell=24858/forma-de-lechucico-lunar

Como especifica el hechizo una de las caracteristicas es que aumente un 10% el daño con hechizos lo que pasa es que solo aumenta 10 puntos no un 10%.
Muchas gracias, adjunto unas fotos demostrandolo.
![WoWScrnShot_021713_134959](https://f.cloud.github.com/assets/3537253/164937/0f840464-7901-11e2-8b83-c39410692ee7.jpg)
![WoWScrnShot_021713_135015](https://f.cloud.github.com/assets/3537253/164938/18d84df4-7901-11e2-816e-e80eaea18349.jpg)
Saludos!

**Comment by mywel** [comment]
Creo que lo que esta bug son esos números, ya que luego cuando pegas si se nota ese 10% mas de daño.

**Comment by crowel** [comment]
Gracias por tu comentario.^^ ojala.

**Comment by searum** [comment]
es fallo visual, aplica bien el % :)
