### ISSUE TITLE
[Druid > Spec: Balance > Starfall ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#632]
http://es.wowhead.com/spell=48505
Lluvida de estrellas;
efecto: http://es.wowhead.com/spell=50286

Bugs:
1- Cuando te silencian siguen apareciendo estrellas, debiendo parar en el tiempo del silencio.
2- Caen bastante más de 20 estrellas. ( las cuales deben de repartirse entre los enemigos que haya en los 40 metros de radio )
3- Las estrellas solo deben caer en los enemigos a los cuales tú estés en combate, sin embargo dañas a todo 40 metros a tu alrededor, si estás en sigilo o camuflaje, te saca de este.

**Comment by DatJetto** [comment]
He escuchado que atraviesa la pompa del escudo divino del paladín. procederé a testear mejor la spell :3 y añadir más cosas.

**Comment by ghost** [comment]
Si, lo 2º es cierto, yo ya dije que a mi me parecía que no salían 20 estrellas en total entre todos los enemigos, sino que al usarse les dabas con 20 estrellas a cada enemigo xD Lo cual normal que meta tanto... Y lo del pala creo que sí que lo vi, pero cierto es, hay que testearlo más. 

Lo del silence... Deberían quitarse? Porque no tengo ni idea :S

**Comment by DatJetto** [comment]
Si te silencian, las estrellas deben de parar de caer.
