### ISSUE TITLE
Mision Bug: ¡¿Un bazillón de macarrones?!

### ISSUE THREAD

**Issue by Areshan** [RoDNet/Bugtracker-Infinium-4.0.6a#635]
![WoWScrnShot_021713_170555](https://f.cloud.github.com/assets/3618584/165141/709bddf0-791d-11e2-8c91-a709f6a0609a.jpg)
Hola buenas! Perdón que moleste, pero estaba haciendo las misiones de la zona de inicio de los goblin... ( con mi goblin 85: Areshan ) y resulta que al hacer la de: 
¡¿Un bazillón de macarrones?!
Me ha mandado a otra instancia del juego dnd no veo al NPC al que tengo que entregar la misión ( por tanto estoy atrapado ) aunque si veo algunos NPC de esa zona. He probado a ir a Orgrimmar y alli no veo a los npc, ni al resto de jugadores, he entrado a un bg y nada, todos los mapas están vacios, ni npc ni jugadores. 
PD: He visto otro jugador atrapado como yo.

**Comment by searum** [comment]
Esa misión acabo de hacerla y va perfectamente.

El npc al que se lo tienes que entregar esta fuera de la casa, de tal forma que asi esta blizzlike.

http://www.youtube.com/watch?v=p_LlV_e8o80

**Comment by Areshan** [comment]
A mi no me va perfectamente jejeje, y como dije a otro jugador le pasó lo mismo que a mi, es al unico al que puedo ver; está en la misma instancia que yo porque está en la misma parte de la misma misión, él tampoco podía ver al NPC en cuestión. Ya se que está fuera de la casa, y voy a la zona ( donde me marca el mapa ) y esto es lo que veo:
![WoWScrnShot_021713_170358](https://f.cloud.github.com/assets/3618584/166562/ef01c542-79a9-11e2-82b3-c6394761da69.jpg)
Debería estar delante mio, pero ahi no está. solo veo a los trainer de clases. Y repito, si dejo la zona no veo a nadie más; ni NPC ni jugadores. Porfavor ayuda.

**Comment by Areshan** [comment]
He creado una goblin y he ido haciendo las misiones y me pasa lo mismo al llegar a esta misión en concreto, Sassy ( el NPC en cuestión) debería estar fuera de la casa pero no. tengo screenshot como prueba : (
![WoWScrnShot_021813_162145](https://f.cloud.github.com/assets/3618584/167648/0e58c816-79df-11e2-82dc-7cdc6138cdb6.jpg)

**Comment by Areshan** [comment]
Hola, buenos dias.
Mi personaje 85 sigue sin poder hacer nada hasta que no complete la misión o alguien me desbuguee, si me quedo en Kezan no veo al NPC al que debo entregar la misión ( como muestran las imagenes ). Si voy a Orgrimmar no veo a nadie, no veo ni el buzon de correo ni NPCs de subasta o banco. Por no ver no veo gente cuando entro a un campo de batalla, por favor... ¿Qué puedo hacer para recuperar este personaje? He probado a abandonar la misión pero eso no lo arregla. He creado otro goblin a ver si me pasaba lo mismo. Y también. ¿No se le ocurre a nadie que puedo hacer? ¿Abro otra incidencia contandolo de otra forma? ¿Intento migrar el personaje a este mismo servidor a ver si se desbuguea? Porfavor alguna respuesta.
