### ISSUE TITLE
Misiones diarias Faucedraco Bug

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#636]
1-Guerra total-> http://es.wowhead.com/quest=27747
   Error-> Los barriles no estan y asi no se puede completar.
2-Cómo domar a tu dragón-> http://es.wowhead.com/quest=28043
   Error-> Sacas las tripas del grifo pero no aparece el draco para completar la Quest.

**Comment by mywel** [comment]
Totalmente cierto lo que dice asassin y es una lastima porque la única forma de subir reputación con esta facción es con las diarias (aparte de con el tabardo). Para los que estamos empezando y no podemos hacer heroicas en condicciones, es molesto ver que el camino para conseguir objetos épicos, esta lleno de baches como este.  Pienso que serian misiones simples de solucionar, quizá no para que hagan lo mismo que en el oficial, pero si hacerles un apaño y que por lo menos se puedan completar.

**Comment by lexintor** [comment]
guerra total salen los barriles y cambia el puntero a una tuerca pero no pasa nada cuando se clikea,  como domar un dragon luchas con el dragon sale en amigo para montar  se en el pero no se puede ;)

**Comment by redneo** [comment]
arregladas
