### ISSUE TITLE
Monasterio Escarlata

### ISSUE THREAD

**Issue by gloris** [RoDNet/Bugtracker-Infinium-4.0.6a#640]
bueno en la actualidad estoy sacando logros y mats para subir prof por lo tanto mientras farmeaba paños de seda mágicos entre al Monasterio escarlata para sacar algún paño del tipo que fuese, y con lo que me encuentro después que entro es que la mazmorra esta completamente vacía.
Aquí una captura para que vean con lo que me encontré, así mismo están las demás salas:

![WoWScrnShot_021713_155955](https://f.cloud.github.com/assets/3620194/165418/37f93c04-7945-11e2-9ee0-f77ebd109a1e.jpg)

**Comment by Oscarin** [comment]
seguramente entraste en la estancia en modo heroico XD

**Comment by searum** [comment]
exactamente
