### ISSUE TITLE
talento  Extasis sacerdote disciplina

### ISSUE THREAD

**Issue by casicasi** [RoDNet/Bugtracker-Infinium-4.0.6a#650]
El talento ( Extasis ) como el titulo indica no aplica nada 
link a wowhead : http://es.wowhead.com/spell=47536

**Comment by searum** [comment]
acabo de probarlo y va perfecto, no tiene que aplicar nada tan solo tiene que darte mana.

http://db.mmo-champion.com/s/47535/rapture/
