### ISSUE TITLE
Bug Como domar a tu dragon.

### ISSUE THREAD

**Issue by juanmamalaga** [RoDNet/Bugtracker-Infinium-4.0.6a#652]
![WoWScrnShot_021913_164626](https://f.cloud.github.com/assets/3638339/171935/021b7300-7aac-11e2-88fd-ebd2cf181bac.jpg)
Al poner la carne de grifo en la zona de la quest los dragones no hacen nada.

**Comment by searum** [comment]
tratar de poner enlaces a wowhead.

**Comment by fofo901** [comment]
ahi estan searum D: en el 767

**Comment by redneo** [comment]
arreglado

**Comment by crowel** [comment]
hola, hoy intente hacer esta misión me va todo guay, uso el cebo, me monto en el dragon pero cuando me lleva por el aire a los 30 segundos - 1 minuto me tira al suelo(me desmonta) nose si a alguien le pasa esto o si estoy haciendo algo mal, lo intente 3 veces y el mismo resultado.
Un saludo.

**Comment by redneo** [comment]
SI, te desmonta, pero te da la mision como completa (creo)
