### ISSUE TITLE
CAzador bug Disparo firme mejorado

### ISSUE THREAD

**Issue by AShasK7** [RoDNet/Bugtracker-Infinium-4.0.6a#653]
pues pasa que el talento de la rama punteria no sirve ya que de acuerdo a su descripcion se deberia de aumentar la celeridad 15% cosa que no sucede http://es.wowhead.com/spell=53224/enfoque-firme.

P.D. el link es de la de pandarian pero basicamente es el talento bug en esta version.

**Comment by Dekadencee** [comment]
Reporte repetido, seguimos su estado desde el reporte anterior #580
