### ISSUE TITLE
Mazmorra Roca Negra

### ISSUE THREAD

**Issue by Naiira** [RoDNet/Bugtracker-Infinium-4.0.6a#654]
Hemos hecho la mazmorra roca negra completa y con el mismo grupo apuntandonos por medio del buscador y no ha dado las chapas de valor , pienso que quizas sea fallo de la mazmorra en si ya que  hace un par de dia la hicimos y si los dio. Gracias !

**Comment by searum** [comment]
entonces es un fallo puntual! lo cierro
