### ISSUE TITLE
Misión: Defender la Aldea Brisa Pura

### ISSUE THREAD

**Issue by heriailin** [RoDNet/Bugtracker-Infinium-4.0.6a#655]
Para completar esta misión http://es.wowhead.com/quest=9252, se deben matar los muertos vivientes que están en las barricadas. El bug radica en que estos no aparecen para poder completar la quest.

**Comment by searum** [comment]
Estan, puede que alguien los matara antes pero estan spawneados, los estoy viendo ahora mismo.
