### ISSUE TITLE
Barrera de hielo

### ISSUE THREAD

**Issue by Faked** [RoDNet/Bugtracker-Infinium-4.0.6a#66]
http://es.wowhead.com/spell=11426/barrera-de-hielo

No absorbe tanto como deberia (creo), hice un test hace tiempo con otro mago y absorbe mas el Escudo de mana..

Digamos que la barrera no aguanto ni un agostar (promedio de 6k) y la suya aguanto mas de 2 descargas de hielo

**Comment by searum** [comment]
funciona bien

**Comment by asfo** [comment]
Apoyo la noción de @searum por lo visto, en una prueba, funcionó con la absorbencia debida (puntitos menos, puntitos más pero nada notorio)
