### ISSUE TITLE
Mazmorra : La ciudad perdida de los Tol'vir

### ISSUE THREAD

**Issue by Naiira** [RoDNet/Bugtracker-Infinium-4.0.6a#661]
En el último bos , hay dos boses , fui hace dos dias y estaban los dos , volvi a ir hoy y siguen estando.
![WoWScrnShot_022013_210902](https://f.cloud.github.com/assets/3589001/177557/e58e511e-7b99-11e2-8bd3-c414c451b391.jpg)

**Comment by searum** [comment]
yo solo veo uno... :S
