### ISSUE TITLE
bug de sacer  proteccion contra las sombras

### ISSUE THREAD

**Issue by vanesa34** [RoDNet/Bugtracker-Infinium-4.0.6a#662]
el buffo de proteccion contra las sombras de sacer deberia servir no solo para buffarse el propio sacer si no como indica el propio buffo para buffar a los miembros de tu grupo o banda y esta bug solo sirve para el sacer y no buffa a los miembros de tu grupo por favor arreglen este bug de skills de sacer :S

**Comment by searum** [comment]
ya la tengo fix
