### ISSUE TITLE
Bug en joyería

### ISSUE THREAD

**Issue by Diezape** [RoDNet/Bugtracker-Infinium-4.0.6a#663]
Teniendo comprada la receta de Diamante de espíritu de las sombras ardiente no me permite aprenderla aún cumpliendo los requisitos. Sobra decir que soy joyero 525 con lo que debería poder aprenderla. Al intentar aprenderla inicia la animación de aprendizaje de recetas, pero no acaba nunca, y no la aprende.
Gracias por la atención.

**Comment by searum** [comment]
fix
