### ISSUE TITLE
no se genera la pagina de votos,da error el link

### ISSUE THREAD

**Issue by letswolf** [RoDNet/Bugtracker-Infinium-4.0.6a#668]
no puedo votar y generar puntos por q siempre que oprimo vota me aparece lo siguient; El sitio web ha detectado un error al recuperar la http://reignofdarkness.net/wow/votar?id=10&u=http%3A%2F%2Fwowservidoresprivados.com%3Fin%3D50 http://reignofdarkness.net/wow/votar?id=10&u=http%3A%2F%2Fwowservidoresprivados.com%3Fin%3D50. Es posible que esta esté inactiva debido a tareas de mantenimiento o que se haya configurado de forma incorrecta

**Comment by crowel** [comment]
Si miras bien en el foro veras que por lo menos escribieron 5 post con el mismo tema, los administradores estan mirando de solucionar esta incidencia para que podamos votar, supongo que cuando este reparado nos avisaran de ello.
Un saludo.

**Comment by searum** [comment]
este bugtracker es del wow solo
