### ISSUE TITLE
Misión: El calentamiento

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#670]
La misión http://es.wowhead.com/quest=12996 consiste en matar al mob Kirgaraak http://www.wowhead.com/npc=29352 mientras estas montado sobre Riendas de matriarca oso de guerra http://es.wowhead.com/item=42481 pero lo matas y no cuenta como si lo hubieras matado.

**Comment by redneo** [comment]
Arreglado

**Comment by ghost** [comment]
Wow xd, muchas gracias @redneo.
