### ISSUE TITLE
Misión: A lomos de la osa.

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#671]
No se puede montar a la osa http://es.wowhead.com/npc=29598/colmillo-de-hielo en la quest http://es.wowhead.com/quest=12851/a-lomos-de-la-osa y otra cosa más, tiene un error raro que si estas en la zona de la quest no puedes ver a los mounstros, pero si estas en la zona de al lado sí los puedes ver, como en la imágenes de abajo.

En estas puedo ver a los creeps:
http://i.imgur.com/IWwYsxP.jpg (zona Poblado Brunnhildar).
http://i.imgur.com/7reIAdS.jpg (zona Caverna Hibernal).

Y en estas ya desaparecieron:
http://i.imgur.com/SV4Q01P.jpg (zona Valle de los Viejos Inviernos)
http://i.imgur.com/IwWCinl.jpg (zona Valle de los Viejos Inviernos)

**Comment by searum** [comment]
fix
