### ISSUE TITLE
Denuncia por farmeo de arenas.

### ISSUE THREAD

**Issue by Paketon** [RoDNet/Bugtracker-Infinium-4.0.6a#682]
Apunte a arenas con mi compa y las 4 veces que salto arenas los otros teams no entraron y nos las dio por ganadas. Desde la primera vez ke no entraron ya nos olimos que habia mancos farmeando arenas asique estubimos atentos en el canal Who a ver quien se veia por arenas y contra que team nos saltaba.
Como ya no sale el anuncio de que teams apuntan a arenas solo pude ver el nombre de los team cuando entraba yo y ellos no. Porque hay un bug que cambia los nombres de los teams de los que hay en arenas. Por ejemplo me team es "Miau" y me salia "Damos asco" que es el nombre del team de los que no entraron 3 veces seguidas al ver que no les toco con sus amiguitos.

![WoWScrnShot_022413_113945](https://f.cloud.github.com/assets/3197965/189365/6ba35a82-7e70-11e2-9068-f4e25d897188.jpg)

![WoWScrnShot_022413_114020](https://f.cloud.github.com/assets/3197965/189366/7c258664-7e70-11e2-8cd9-9bfb137ad90f.jpg)

![WoWScrnShot_022413_114117](https://f.cloud.github.com/assets/3197965/189367/81b2add2-7e70-11e2-926f-10db82e9e558.jpg)

**Comment by crowel** [comment]
Esto tendria que ir en el foro no aquí.

**Comment by Paketon** [comment]
Me dijo el GM que habia ON ke lo pusiera aki. Igual se equivoco y quiso decir foro pero por eso lo puse aqui. Ademas las fotos se suben rapido y no dan los problemas ke dan en el foro.

**Comment by crowel** [comment]
Si es así y no deberia de estar en Denuncias/Reportes, perdona mi comentario.
Un saludo.

**Comment by HexR-zz** [comment]
foro pls
