### ISSUE TITLE
Druida-Talento: Don de la madre tierra

### ISSUE THREAD

**Issue by sheikaaa** [RoDNet/Bugtracker-Infinium-4.0.6a#684]
El Talento de Druida Restauracion Don de la madre tierra no funciona.
Adjunto fotos.
![WoWScrnShot_022413_122353](https://f.cloud.github.com/assets/3682242/189390/122768f4-7e75-11e2-9240-2dbabd04382a.jpg)
![WoWScrnShot_022413_123405](https://f.cloud.github.com/assets/3682242/189415/dd0dbc2a-7e7b-11e2-9d1e-959c7d0ade9a.jpg)
![WoWScrnShot_022413_122252](https://f.cloud.github.com/assets/3682242/189416/dd0fa1f2-7e7b-11e2-9347-3e3c9b513311.jpg)
![WoWScrnShot_022413_122251](https://f.cloud.github.com/assets/3682242/189418/1b7c7e2e-7e7c-11e2-832e-ed4dfeddc837.jpg)
![WoWScrnShot_022413_122317](https://f.cloud.github.com/assets/3682242/189420/4f7c7116-7e7c-11e2-97e8-e649cd801331.jpg)

**Comment by ghost** [comment]
Explícate mejor sobre qué es lo que no funciona. A parte ya lo reporté yo hace tiempo. PD: Qué addon o qué es lo que tienes para ver la SpellID?
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/598

**Comment by searum** [comment]
Zaska, es el idtip. Es muy util ^^

Cierro porque esta repetido.
