### ISSUE TITLE
Mision Bug: ( 2nd Issue ) ¡¿Un bazillón de macarrones?!

### ISSUE THREAD

**Issue by Areshan** [RoDNet/Bugtracker-Infinium-4.0.6a#686]
Hola, buenas tardes:
Aparte de lo que puse en la primera incidencia. Para el que le interese, que tenga en cuenta que allí adjunté varias imagenes como prueba.
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/635
( Para el que no quiera leerlo; resumo y añado novedades )

Tenía que entregar una misión a Sassy, en Kezan ( zona de inicio goblin ), pero el NPC no se ve, debe estar en una fase distinta a mi. He ido dnd indica el mapa, y dnd he visto que se hace la misión ( he visto un video de youtube ) pero ella no está.

Borax ( creo que se llamaba el GM que me ayudó) me dijo que borrara Caché y WTF, luego probó un par de cosas pero nada. Al final me cambió a la zona de las islas de los goblin y me cambió de fase.
Dijo q acabara todas las misiones q cuando lo hiciera me teleportarian a Orgrimmar y debería estar arreglado ( y era cierto ). Pero al relogear sigo igual.

La unica misión que no he completado es la que empezó a cambiarme de zona y por la cual abro la incidencia.

No veo al resto de jugadores, ni NPC ni siquiera veo el buzón de correos. Se me van a acabar las runas de teleport de probar a ver si se ha arreglado ( como no veo al NPC q las vende, no puedo reponer ) jajeje.

Por favor ayuda; no puedo hacer nada, ni farmear, ni hacer misiones, ni ir de campo de batalla, porque veo a la gente en el minimapa, pero aunque vaya a dnd están todos... no les veo, están en otra fase. Necesito que me cambien de fase ( o como se llame lo que me pasa; yo lo entiendo asi ) pero de forma definitiva, no que se me vaya al relogear.

**Comment by searum** [comment]
Ya esta arreglado. Pon un ticket ingame para que te pongan en la phase correcta.
