### ISSUE TITLE
Item perdido

### ISSUE THREAD

**Issue by nakran13** [RoDNet/Bugtracker-Infinium-4.0.6a#687]
Ayer día 24 de febrero me compre la varita Toque de derrota de gladiador sañoso, la cual he perdido, junto a los puntos de conquista que gane con 3 arenas, suman 1160p de conquista perdidos. Si al menos me pudiesen devolver el ítem, la varita. Gracias

**Comment by searum** [comment]
ayer se aviso del rollback, leete la noticia de ayer
