### ISSUE TITLE
Explosión Arcana bug

### ISSUE THREAD

**Issue by david-landin** [RoDNet/Bugtracker-Infinium-4.0.6a#688]
Antes de el último reinicio para solucionar los problemas con los jugadores de World Heroes mi mago hacia un daño con Explosión Arcana a un muñeco de 50.000 de daño y después de el reinicio causo 5.000 con esto el Mago Arcano junto al Mago Hielo está enterrado, si se buggea el mago Fuego sería mejor bloquear a los magos ya que no servirán para nada.

**Comment by searum** [comment]
fix
