### ISSUE TITLE
Bug de Desaparición de Equipamiento, Bolsas y Contenido.

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#689]
Buenas. Hoy al conectar en el server, me he encontrado con una situación algo incómoda (por decirlo de algún modo). Estaba sin equipo, sin bolsas (excepto la de serie) y además, la única bolsa que tenía estaba vacía. Sin, ni siquiera, la piedra de hogar. Creo que hasta el banco estaba vacío, aún y tener algunas cosas en él, ayer. Añado una imagen de como me he encontrado el personaje nada más logear. Por cierto, también me ha llegado un tipo de mensaje al buzón con el símbolo de Blizzard diciendo lo siguiente: "There were problems with equipping item(s)", el remitente es "Atención al Cliente". Gracias, espero que podáis ayudarme, a mi, y a otras personas que se han encontrado en la misma situación.
Imagen del personaje tal y como lo he encontrado: ![WoWScrnShot_022413_202534](https://f.cloud.github.com/assets/3687462/189918/499230c8-7eb9-11e2-86ba-cf7bc7604f84.jpg) 

Imagen del Correo recibido: 
![WoWScrnShot_022413_203540](https://f.cloud.github.com/assets/3687462/189922/75b26eb6-7eb9-11e2-9237-5090db53dac3.jpg)

**Comment by Dekadencee** [comment]
Al resto de gente que le ha pasado lo han solucionado con un borrado de la carpeta caché, prueba y nos cuentas.
