### ISSUE TITLE
Bug Subastas

### ISSUE THREAD

**Issue by jandrox** [RoDNet/Bugtracker-Infinium-4.0.6a#697]
He visto 2 bugs en subastas: 
1.- Los objetos de las subastas desaparecen si no los compran, explico, he puesto en subasta 16 gemas anteayer y al entrar hoy compruebo que he vendido 4 pero que el resto han desaparecido, ni están en la lista de subastas ni en mi correo de vuelta :(
2.- Las subastas tan solo aparecen en la facción, es decir los objetos de subastas puestos con personajes hordas no aparecen disponibles para los alis y viceversa.

Un saludo.

**Comment by ghost** [comment]
Ayer hubo rollback de items, tal vez por eso los perdiste, y lo de la  faccion es asi, no se puede comerciar entre facciones al menos que uses la subasta de bahia del botin, gadgetzan o vista eterna que son lugares neutrales.

**Comment by searum** [comment]
Exacto, fue el rollback y eso que dices de las subastas por facción es porque es asi, en el oficial y aqui.

cierro!
