### ISSUE TITLE
[Hunter > Spec: General > Spell > Aimed shot]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#7]
- Disparo de puntería 
  http://es.wowhead.com/spell=19434
  Bug; Daño bajo 

Fórmula 4.0.6: 200 % ranged weapon + (RAP*0.724)+776

**Comment by searum** [comment]
esta perfectamente. las cuentas salen

jetto, al cole! xd
