### ISSUE TITLE
[Quest > El gran atraco al banco(Kezan)]

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#701]
Hola me gustaria que pudieran arreglar esta misión para continuar las misiones goblin, se trata de cojer las riquezas personales de la camara del banco, pero no se puede interactuar con ella.
http://es.wowhead.com/quest=14122

**Comment by Dekadencee** [comment]
Esta mision estaba fixeada pero se tubo que deshabilitar y volver a revisar el script por un crash que probocaba, un momento que consulto a Searum como está el tema que fué el que la fixeo en su momento

**Comment by crowel** [comment]
Ok, gracias si quereis cerrar tema sino queda abierto mientras, un saludo^^

**Comment by dragonoit** [comment]
pra cuando va a estar arreglada ? soy nuevo y no puedo continuar con la cadena de quest

**Comment by Dekadencee** [comment]
Bug repetido, seguimos su estado desde el reporte anterior https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/543
