### ISSUE TITLE
[Instance > Boss Chimaeron (Descenso de Alanegra)]

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#709]
Hola queria informar que el boss chimaeron http://es.wowhead.com/npc=43296
Hoy lo intentamos hacer en 10n y a los 3 segundos de empezar, con el buffo del robot nos dio un golpe con Masacre http://es.wowhead.com/spell=82848
Con el cual nos mato a todos de un golpe seco, no deberiamos de morir por el buff del robot que nos tendria que dejar en 1 de vida como mínimo si el golpe supera a los 10000 de daño.
Nose si el problema esta en el buf del robot, que si aparece visual pero nose si hace el efecto realmente de mantenerte en 1 de vida ya que morimos todos, o si realmente el problema esta en el ataque masacre que nos hizo un daño excesivo.
Espero que con estos datos se pueda encontrar una respuesta.
Adjunto una imagen y doi las gracias de antemano.
Un saludo.
![masacre](https://f.cloud.github.com/assets/3537253/194865/9d57b156-7fc2-11e2-8209-ced366e6dffd.jpg)

**Comment by searum** [comment]
se supone que ya esta fix ^^
