### ISSUE TITLE
Bug Banco de Hermandad

### ISSUE THREAD

**Issue by chiflo1986** [RoDNet/Bugtracker-Infinium-4.0.6a#710]
Hola soy Huargwind el Guild Master de Guardians of Time Space!! Tengo un problema con el banco de la hermandad.. tenemos compradas todas las pestañas que se permite de principio, osea 6.. pero ami que soy el Guild Master solo me deja usar dos.. las otras 4 me salen como inactivas ( no me deja actuar en ellas.. es como q no estan ) a los demas les funciona todo bien en las 6 pestañas pueden meter y retirar cosas.. asiq el fallo solo lo tengo yo o "al q le paso el rango de Guild Master" xq e probado a borrar cache y WTF habiendo cedido el rango ( consejo de un GM y al los que se le cedi, na mas darles el rango se les bloqueaban tb las pestañas y pasaban de tener las 6 activas a solo tener 2..

En resumidas cuentas el que tiene el rango de Guild Master en mi hermandad se le bugean 4 de las 6 pestañas del banco sea quien sea.. actualmente tengo el rango yo.. por si os sirve de ayuda para arreglarlo..

Un saludo espero q nos podais ayudar =)

**Comment by crowel** [comment]
Hola si usas el buscador de issues veras que ya crearon este post https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/508 https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/552
Un saludo

**Comment by chiflo1986** [comment]
ey hola crowel la verdad no sabia q ya habia pasado a mas hermandades.. hay alguna sokucion o toca aguantar con el bug??

**Comment by crowel** [comment]
Creo que ya estan tratando el tema, nos toca esperar a una respuesta de un admin para saberlo con exactitud.
Saludos.

**Comment by chiflo1986** [comment]
ok pos tocara tener paciencia y esperar =) gracias por tus respuestas ^^

Un saludoo

**Comment by Dekadencee** [comment]
Fixed!
