### ISSUE TITLE
[Talento > Pellejo grueso(druida)]

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#711]
Hola queria poder informar sobre este talento, pellejo grueso(feral), este es el enlace del spell http://es.wowhead.com/spell=16931 aunque los efectos que marca en el wowhead no son los mismos.
Hoy después de comprobar los talentos para mi druida oso feral me he puesto a comprobar los talentos a medida que los iva poniendo para mejorar y comprobar las caracteristicas de esta rama de talentos hasta que llegue a este que menciono que es indispensable para los druida tanque.
Voi a adjuntar unas fotos y a explicar el motivo por el cual expongo que este talento me parece bug.

![talento explicacion](https://f.cloud.github.com/assets/3537253/199057/307b5700-8070-11e2-9e1c-b8692e687277.jpg)

Bien, como el talento explica con los puntos 3/3 : Aumenta un 10% los tu valor de armadura por objetos de tela y cuero, aumenta un 78% tu armadura cuando estas en forma de oso y reduce un 6% la probabilidad de que recibas un golpe crítico con ataques cuerpo a cuerpo.

Vale con esto dicho me gustaria explicarlo en dos partes.
La primera fijarme en el primer apartado del talento: Aumenta un 10% el valor de armadura por objetos de tela y cuero.
Como voi añadir en la siguiente imagen, sin estar el talento puesto tengo 22619 de armadura.
![Mi armadura sin el talento](https://f.cloud.github.com/assets/3537253/199060/47c63ace-8070-11e2-9246-eba679f58c2b.jpg)

Si se me tiene que añadir un 10% de 22619 tendrian que sumar 2261,9 que seria el aumento de esa armadura.
Una vez puesto el talento tengo 244334,  me esta sumando menos del 10%, ya pues 22619 que tenia mas el 10% serian 24880,9 para ser exacto el aumento del 10%, mas o menos esta bien solo que hai esa pequeña diferencia, adjunto una foto, el problema real viene en la segunda parte del talento.

![Mi armadura con el talento](https://f.cloud.github.com/assets/3537253/199072/c0788670-8070-11e2-8373-6f70753baf87.jpg)

Bien la segunda parte y gran problema del talento es aumenta un 78% tu armadura cuando estas en forma de oso, la cual como se ve en la imagen que acabo de poner al tener el talento puesto solo aumenta el 10% de la contribucion de objetos y el 78% de armadura en forma de oso no existe.

Segun el efecto del talento es que aumenta un 78% la armadura en forma de oso, asi que un 78% de 24880 tendria que aumentar 19406.4 a mayores que no se esta aumentando como especifica el segundo apartado del talento, dejando al oso para tanquear un poquito apartado, espero no equivocarme en mis calculos o comprension del talento
y espero haberme dado a explicar de una manera correcta y siento poner semejante testamento pero espero que se pueda mirar.
Gracias y un saludo.

**Comment by searum** [comment]
fix
