### ISSUE TITLE
Talento: Lider de la manada

### ISSUE THREAD

**Issue by xxizualxx** [RoDNet/Bugtracker-Infinium-4.0.6a#714]
Bueno seguro que los druidas se han dado cuenta de este bug, pero como es beneficioso nadie lo ha reportado, pues bien antes que nada lean la descripcion del talento http://es.wowhead.com/spell=17007 ya que lo leyeron si ven al final dice "Solo puede suceder una ves cada 6s" pues bien aqui esta el bug, que no cuenta esos 6s, caada golpe critico que dan los cura 4% de vida y 8% de mana, asi den 10 criticos seguidos esos 10 criticos los cura esa cantidad.

para saber cuando salta el talento es facil solo mirar el resplandor verde con unas como hojitas de arbol que aparecen cada que salta.

espero lo arreglen pronto que esos druidas se curan bastante con este talento bug.

**Comment by 50megas** [comment]
#564

**Comment by Dekadencee** [comment]
Bug repetido, seguimos su estado desde el reporte anterior #564
