### ISSUE TITLE
bug garrote

### ISSUE THREAD

**Issue by 50megas** [RoDNet/Bugtracker-Infinium-4.0.6a#716]
la habilida del roge http://es.wowhead.com/spell=703 hace menos daño del que deveria,
la descripcion pone que hace 8k de daño y hace 2,8k y eso  contado los tick criticos que  sino saltan criticos pos menos aun.

http://es.wowhead.com/spell=703

foto del dps del garrote full sañoso a un muñeco:

<a href="http://tinypic.com?ref=e64z6g" target="_blank"><img src="http://i56.tinypic.com/e64z6g.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

un saludo^^

**Comment by DatJetto** [comment]
Garrote > 8024p en tiempo. 
Da 404p cada 3 segundos durante 18 sec.
404 x 6 = 2424

Para que se adecuara al tooltip debería dar 1337p. por tick.

**Comment by 50megas** [comment]
como se puede ver en el recount un garrote salta 6 veces en 18 seg (salta cada 3 seg)

404x6= 2424 daño que hace

8024 -2424 = 5600 daño que no hace 

deveria meter 1337 en 6 tick para que diera los 8000 en mi caso

un saludo

**Comment by searum** [comment]
ya esta fix

**Comment by 50megas** [comment]
pues a quedado bastante bien, solo que tiene un pequeño fallo no le afecta el +30% del hemorragia http://old.wowhead.com/spell=16511

un saludo

**Comment by searum** [comment]
postea lo de hemorragia en otro issue a parte.
