### ISSUE TITLE
[ Hunter > Marksmanship > ¿Y mi Wild Quiver? ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#719]
Mastery > Wild Quiver: 
http://old.wowhead.com/spell=76659

Wild Quiver Auto Shot: Esta no se si servirá pero la añado por si acaso
http://old.wowhead.com/spell=53254

Las descripciones pertenecen al 3.3.5a así que pondré yo mismo:
- Tienes un 16% base ( modificado por la maestría ) de lanzar un proyectil adicional que causa 100% de daño con arma ( daño físico ). Cada punto de maestría aumenta la probabilidad un 1.8% extra.

---

Se ve afectado por la especialización en puntería:
- Carcaj artesanal: http://old.wowhead.com/spell=87326 
  Aumentando el daño de la maestría de 100% hacia 115% de Ranged Weapon Damage

---
- Todos los disparos del cazador tienen el mismo x% ( modified by mastery ) de lanzar este disparo extra:
  - Auto-shot: http://es.wowhead.com/spell=75
  - Disparo Firme: http://es.wowhead.com/spell=56641
  - Disparo de Cobra: http://es.wowhead.com/spell=77767
  - Disparo Arcano: http://es.wowhead.com/spell=3044
  - Disparo de Puntería: http://es.wowhead.com/spell=19434
  - ¡Disparo de Puntería!: http://www.wowhead.com/spell=82928
  - Disparo de Quimera: http://es.wowhead.com/spell=53209
  - Disparo silenciador: http://es.wowhead.com/spell=34490
  - Disparo de conmoción:http://es.wowhead.com/spell=5116
  - Disparo mortal: http://es.wowhead.com/spell=53351

---
- Puede ser crítico según el índice de golpe crítico del cazador.

---

Aquí la prueba del dummy típica, se ve como hago 4M de daño al dummy, un daño extenso para ver si alguno de mis disparos activa la mastery, para mi sorpresa, ¡NO!, no tengo maestría activa D:
Si tuviera maestría se referiría en el Recount como Carcaj Salvaje Auto shot o similar. Tampoco salían daños dobles, o flechas secundarias.

http://i56.tinypic.com/21eq3wj.jpg

**Comment by crowel** [comment]
Muy bien explicado ^^

**Comment by DatJetto** [comment]
<a href="http://tinypic.com?ref=21eq3wj" target="_blank"><img src="http://i56.tinypic.com/21eq3wj.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
