### ISSUE TITLE
garrote -  bug para picaro

### ISSUE THREAD

**Issue by paradicma** [RoDNet/Bugtracker-Infinium-4.0.6a#723]
hola con todo el staff de reign of darkness , felicitarlos por su trabajo, y aprovecho para ahcerles una consulta
a mi parecer la habilidad de garrote esta bug en los picaros, diganme si me equivoco, yo soy furukawa - rogue lvl 85, y practicando me he dado cuenta que al actibar garrote solo hace 133 de daño cada 3 segundos por 18 segundos. , por otro lado veo en la ventana de la habilidad ..supuestamente debe ahcer algo de 7k de daño....por favor vean eso..gracias http://es.wowhead.com/spell=703

**Comment by 50megas** [comment]
#716
