### ISSUE TITLE
Instance Rasganorte --> El Nexo 

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#724]
Buenas, como podéis comprobar en la foto, no se puede salir de la instance por el portal que hay en la entrada xD
![WoWScrnShot_022813_132554](https://f.cloud.github.com/assets/3328374/205289/7757f416-81a2-11e2-8e15-33b6e73f9d28.jpg)

**Comment by searum** [comment]
lo se, es un fallo que tratamos de resolver cuanto antes. cierro porque lo conocemos de sobra el bug xd
