### ISSUE TITLE
[Logros > Una muerte con honor]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#727]
Buenas, después de estar revisando mis logros, me di cuenta de que cuando empecé en el servidor el logro [Una muerte con honor] http://es.wowhead.com/achievement=238
No estaba disponible, y ahora que si lo está, no puedo conseguirlo, porque es como si ya lo tuviera al haber matado tropecientos millones de hordas.

**Comment by searum** [comment]
bueno tio, y me vas a llorar por esto? en fin
