### ISSUE TITLE
Personaje desaparecido.

### ISSUE THREAD

**Issue by Simonsville** [RoDNet/Bugtracker-Infinium-4.0.6a#729]
Buen dia, tarde o noche (depende de la hora en que lean este mensaje). el dia de hoy 28 de Febrero de 2013, a las 11:45 del dia (horario del centro de américa latina o 18:45 en horario de Madrid), el servidor experimentó una latencia alta, seguida de un reinicio del servidor.

He de comentar que varias personas perdieron al menos un personaje en el reinicio del servidor o cuando cambiaban de personaje y volvian a conectarse dando como resultado la perdida de un personaje.

En el canal global hacian comentarios a cerca de que si uno se conectaba y desconectaba, en la próxima conección perderían al personaje que estaban utilizando. Confirmé la hipotesis al desconectarme con mi picaro (un Worgen lvl 65 de nombre Redtalon) y solo quede con mi personaje principal.

Al revisar la pagina del foro, resulta que mi personaje picaro tenia nivel 255.

Esperemos que esto se solucione pronto.

Les envío un saludo.

**Comment by ghost** [comment]
http://www.reignofdarkness.net/wow/foros/t805/

Creo que el bugtracker es para reportar bugs concretos dentro del juego... pero bueno xd

**Comment by searum** [comment]
Hubo un rollback de 6 horas porque se rompio la base de datos
