### ISSUE TITLE
[Mapa > Infralar]

### ISSUE THREAD

**Issue by HexR-zz** [RoDNet/Bugtracker-Infinium-4.0.6a#73]
Según descubres determinadas zonas del mapa de Infralar no se quedan reveladas en tu mapa.

Edit.: Aunque a veces no se revele el mapa, cuando descubres otras zonas, se acaba revelando por completo. Cerrar Issue

**Comment by Dekadencee** [comment]
Oks pues cerramos el issue pues, muchas gracias por el reporte de todos modos hex ^^
