### ISSUE TITLE
Valiona en Bastión Crepuscular

### ISSUE THREAD

**Issue by Diezape** [RoDNet/Bugtracker-Infinium-4.0.6a#732]
No hemos encontrado con un bug en el encuentro con Valiona y Theralion en el bastión Crepuscular. Cuando utiliza la skill llamas devoradoras, que teóricamente la realiza en un cono frontal, en realidad nos la realiza a toda la raid independientemente del posicionamiento de ésta, con el consecuente wipe de la banda. No puedo adjuntar una imagen porque como mucho podría aparecer la raid muerta...lo siento.

**Comment by searum** [comment]
Oki ya lo tenemos fix! :D
