### ISSUE TITLE
Bug de ICC (categoría 10 jugadores normal)

### ISSUE THREAD

**Issue by Katty01** [RoDNet/Bugtracker-Infinium-4.0.6a#733]
El bug de esta instancia se presenta con el boss de Valithria Caminasueños, en el momento de comenzar a atacar los mobs que la custodian, comienzan a salir infinidades de mobs los cuales laguean el servidor y finalmente lo congelan. Posteriormente produciendo caída del mismo, y impidiendo loguear nuevamente.

http://es.wowhead.com/npc=36789#comments

**Comment by ghost** [comment]
#120

**Comment by chipi666** [comment]
efectivamente tenia unas fotos de lo exagerado de los mobs que salen pero s eme borro tomare otra foto para que lo revisen saludos...

**Comment by Dekadencee** [comment]
Se está reescribiendo ICC e incluyendo en ella también la batalla naval, que es el evento que falta para que la instance esté completa.

Gracias por el reporte! Lo seguimos desde el reporte anterior ^^

**Comment by Dekadencee** [comment]
El reporte anterior es https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/120 que se me olvido mencionarlo

**Comment by Katty01** [comment]
Wooo pues genial, la verdad yo jamas me había asustado tanto, solo me falto
la screen XD

2013/3/3 Dekadence notifications@github.com
