### ISSUE TITLE
[Instance > Boss Chimaeron Parte 2(Descenso de Alanegra)]

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#735]
Hola buenas, queria añadir un pequeño arreglo que se necesita para el boss chimaeron, el cual es que en la fase 2 del boss, usa la spell masacre, cosa que no deberia usar mas que en la fase uno, ya pues en la fase dos el boss pega más y no se puede curar a los miembros del grupo por el buff que pone de la sanacion reducida 99% y si aun encima este golpe nos deja en uno de vida nos mata inevitablemente.
Otra cosa que quiero añadir de este golpe masacre Fase1, es que despues de usarlo ataca de nuevo demasiado rapido con sus golpes creo que se deberia añadir al menos 1 segundo más al menos antes de golpear de nuevo, por lo que veo en el tiempo que tarda en atacar en el oficial, porque al usarlo deja a todos en uno de vida y aunque prepares las curas, el golpe que realiza él después es tan rapido que no da tiempo a curar a los miembros y siempre mata a un jugador por lo menos, creo que falta  1 segundo/ segundo y medio de pausa entre ataque(masacre) y lo que tarda de en golpear a la gente después de usarlo.

Otra cosa que quiero añadir es la vida del boss que está muy baja deben añadir los millones de vida que le falta.

Dejo un texto con los ataques a realizar en cada fase y la vida real que deberia tener el boss. http://www.guiaswow.com/descenso-de-alanegra/guia-chimaeron.html

CHIMAERON

```
Nivel: ??
Raza: Hidra
Salud: 25,939,384 [10] / 90,616,064 [25]
Enfurecimiento: 7 minutos
```

Con la ayuda del Bilistrón 800 podremos derrotar a Chimaeron, una criatura que ha ido cambiando a lo largo del tiempo con los experimentos de Alanegra.

Habilidades
Fase 1 - 100% hasta el 20%

```
*Babosa cáustica: Inflige 235,200 puntos de daño de Naturaleza y reduce brevemente la probabilidad de golpear de todos los enemigos en un área. El daño se divide entre todos los enemigos en un radio de 6 metros alrededor del cráter de impacto. En el modo de 10 jugadores, lo tira a 2 personas simultáneamente mientras que en modo 25 es a 4 personas. Para evitar que afecte a más gente, hay que separarse unos 6 metros entre sí.
*Masacre: Inflige daño máximo a todos los jugadores enemigos.
*Enemistad: Chimaeron no puede realizar ataques cuerpo a cuerpo mientras sus cabezas luchan entre ellas.
 *Ataque doble: Chimaeron golpeará dos veces en su siguiente ataque.
 *Romper: Chimaeron ataca con saña, lo que rompe las defensas de su objetivo. Aumenta el daño físico recibido un 25% y reduce la sanación realizada un 15% durante 1 minuto. Se acumula 4 veces.
```

Fase 2

```
*Mortalidad: Chimaeron monta en cólera y se vuelve inmune a los efectos de provocación, pero aumenta el daño que recibe un 10%. Además, reduce la sanación recibida por todos los miembros del grupo en un 99%.
*Ataque doble: Chimaeron golpeará dos veces en su siguiente ataque.
```

Como ven la salud que debe tener en 10jN debe ser 25,939,384 y los dos unicos spells que debe usar en la fase dos son mortalidad y ataque doble.

Con este ajuste en las spells y el arreglo de la vida creo que el boss quedaria 100% blizz, espero que mis indicaciones fueran bien explicadas^^.

Un saludo y gracias por su trabajo.

**Comment by searum** [comment]
fix
