### ISSUE TITLE
[Loots > Boss Suma Sacerdotisa Azil (El nucleo petreo HEROICO)]

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#736]
Hola hoy matamos a la suma sacerdotisa azil en modo H y nos tiró de loot 6 objetos azules, el problema está que el loot que suelta es de N y nosotros la matamos en Heroica. http://es.wowhead.com/npc=42333
Creo que se deberia mira el loot.
Un saludo.

**Comment by searum** [comment]
fix

**Comment by crowel** [comment]
Hola queria avisar que hoy hicimos de nuevo este boss y nos volvio a tirar objetos del modo NORMAL.
Un saludo.
