### ISSUE TITLE
Pala: exorcismo

### ISSUE THREAD

**Issue by ksunanda** [RoDNet/Bugtracker-Infinium-4.0.6a#739]
Exorcismo solo ha de causar daño en el tiempo si tienes el glifo, no lo tengo i causa ese daño aqui estan las imagenes. gracias.
![WoWScrnShot_030113_220538](https://f.cloud.github.com/assets/3740925/211402/f5f0ed34-82b3-11e2-81c7-23baebda65d5.jpg)
![WoWScrnShot_030113_220543](https://f.cloud.github.com/assets/3740925/211413/29c7123c-82b4-11e2-831a-0deb59b09e66.jpg)

**Comment by searum** [comment]
fix
