### ISSUE TITLE
Pala retry: ojo por ojo

### ISSUE THREAD

**Issue by ksunanda** [RoDNet/Bugtracker-Infinium-4.0.6a#742]
No se como probarlo pero simplemente no funciona, la descripcion es: todos los ataques mágicos contra ti tienen un 40% de posibilidades de inflingir un 30% del daño recibido al atacante. he llamado a un mago expresamente para comprobarlo, en un duelo no le atacaba para comprobar si sufria algun tipo de daño i nada, me iba curando a mi mismo asta k se me acabo el mana i el no recibio ningun tipo de daño asi k he llegado a la conclusion que el talento esta bug. gracias.

**Comment by searum** [comment]
fix
