### ISSUE TITLE
Logros: Asaltar ventormenta / ¡Por la horda!

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#743]
Cuando matamos al Rey Varyan Wrynn http://es.wowhead.com/npc=29611/rey-varian-wrynn nos dio los logros Asaltar ventormenta http://es.wowhead.com/achievement=615/asaltar-ventormenta y ¡Por la horda! (claro, previamente matamos a los demás lideres) http://es.wowhead.com/achievement=619/por-la-horda, pero al momento de morir el server cayó, y perdimos nuestros logros.

Imagen de que sí conseguimos los logros:

![Logros bug](https://f.cloud.github.com/assets/3508051/212404/c595b138-82f9-11e2-8a53-9206b6584fee.jpg)

**Comment by ghost** [comment]
Ah, y aclaro, si no nos pueden dar los logros que obtuvimos y perdimos, por lo menos arreglen el bug así podemos ir a conseguirlo otro día, muchas gracias de antemano.

**Comment by searum** [comment]
Qué bug quieres que arreglemos? Se a caido el server pues se a caido.. pero esta bien todo.

**Comment by ghost** [comment]
Pues el bug de que el server cae al matar a Varyan nada mas, si es que se cayó por ese motivo.
