### ISSUE TITLE
Misión: Corazón helado

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#744]
En esta misión http://es.wowhead.com/quest=12856/corazon-helado faltan los npcs Protodraco liberado http://es.wowhead.com/npc=29709/protodraco-liberado y Prisionera Brunnhildar http://es.wowhead.com/npc=29639/prisionera-brunnhildar para poder ser completada.

Un video de como debería ser la misión: http://www.youtube.com/watch?v=L_JXPyfUFYI

**Comment by redneo** [comment]
Puestos los Npcs en la fase correcta
