### ISSUE TITLE
Bug raid Lich King Boss Valithria Caminasueños

### ISSUE THREAD

**Issue by chipi666** [RoDNet/Bugtracker-Infinium-4.0.6a#745]
Hola aqui quiero poner una foto y un link del video donde podemos ver un bug con esta boss ya que los mob que salen son muy exagerados, saludos....

http://youtu.be/Yt8kw_qNrSo

![Lich King Bug](https://f.cloud.github.com/assets/3199832/212457/ebcf3984-8301-11e2-903a-ff10b029468c.jpg)

**Comment by searum** [comment]
BIEN! gracias! por fin me entero de que boss es y que npcs son. Ya encontre el bug.

**Comment by DatJetto** [comment]
JAJAJAJAJA looooool

**Comment by ghost** [comment]
Si lo arreglas puedes cerrar los bugs #733 y #120.

**Comment by Dekadencee** [comment]
Se agradece la captura, por fin sabemos lo que falla ^^
Seguimos el proceso mediante el reporte anterior https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/120
