### ISSUE TITLE
[Spell >Arma Muerdepiedras(chaman)]

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#757]
Al usar este hechizo se deberia de imbutir el arma y aparecer como encantamiento.
Lo que pasa es que al usarlo no hace nada.
http://es.wowhead.com/spell=6196
Un saludo.

**Comment by DatJetto** [comment]
esto ya está reportado https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/555

**Comment by crowel** [comment]
Perdonad.
