### ISSUE TITLE
Npcs que cambian honor por otros items

### ISSUE THREAD

**Issue by Wiinter** [RoDNet/Bugtracker-Infinium-4.0.6a#763]
En Orgrimmar tenemos a Rogoc [id=52033] que nos cambia honor por items útiles, como Cristales de la Vorágine, Esencias celestiales, etc. Y en Ventormenta tenemos a Edlan Halsing [id=52029] que hace la misma función que Rogoc pero en la Alianza.

**Comment by redneo** [comment]
Proximamente estarán puestos, gracias por el reporte
