### ISSUE TITLE
baneados

### ISSUE THREAD

**Issue by jankin** [RoDNet/Bugtracker-Infinium-4.0.6a#765]
hola al parecer estoy baneado por insultar a otro jugador y pone que la pena por eso son 3 dias bien ya han pasado mas de 72 horas y sigo baneado e intentado ir al gestor de cuentas donde dice que hay un tema para eso y no lo encuentro me podrian ayudar  y entre el manrenimiento y las caidas e estado mas tiempo esperando que jugando y yo agradecco todo pero me gustaria jugar tambien

**Comment by Dekadencee** [comment]
Esto es un tema que deberías haber puesto en nuestros foros, esto es única y exclusivamente para reportar errores en el juego
