### ISSUE TITLE
dragon maw clan

### ISSUE THREAD

**Issue by fofo901** [RoDNet/Bugtracker-Infinium-4.0.6a#767]
son dos queste en principal las que quiero reportar:

How to maim your dragon en tierras altas crepusculares que el dragon no hagarra el grifo y la otra es Total war que no salen unos barriles que hay que destruir, especialmente son para diarias de repu de esa faccion

**Comment by crowel** [comment]
Jajaja que bien explicas.
Respecto a la primera https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/652

**Comment by ghost** [comment]
Bueno ayudo un poco links:

Como domar a tu dragón: http://es.wowhead.com/quest=28043/como-domar-a-tu-dragon

Guerra total: http://es.wowhead.com/quest=28872/guerra-total

**Comment by fofo901** [comment]
lvmb gracias pero aun asi no deja D:

**Comment by ghost** [comment]
Los links eran por si algun gm/admin o alguien que arregle bug pida links a wowhead xd

**Comment by redneo** [comment]
Lvmb se agradece el esfuerzo, pero ambos links son los mismos!!!!!

De todas formas, ambas arregladas, esperando que pronto se apliquen.

**Comment by ghost** [comment]
Ah, que porqueria xd seguro fue por el sueño, gracias por arreglar
