### ISSUE TITLE
[Spell > Escudo de agua(chaman)]

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#768]
Hola quiero informar de este hechizo.
http://es.wowhead.com/spell=52127
El taumaturgo queda rodeado por tres esferas de agua que le otorgan 354 p. de maná cada 5 s. Cuando un hechizo o ataque cuerpo a cuerpo o a distancia golpea al taumaturgo restaurara 1515 p. de maná y consume una de las esferas.Solo se activara una esfera cada varios segundos.Dura 10 minutos.Un chaman solo puede tener un escudo elemental activo a la vez.

Lo que no funciona de este spell es la restauración de mana que da cada 5 sec, no existe.
La segunda parte del spell funciona perfecto ya que al golpearte si te restaura.

Un saludo.

**Comment by Overseer101** [comment]
Pues a mi me da el mana pasivo, 531p de mana cada 5s por tener el glifo, mira a ver si eres tu solo, o le pasa a mas gente U.u

**Comment by crowel** [comment]
En la descripcion del hechizo pone que tiene que darlo sin glifo^^

**Comment by Overseer101** [comment]
354 mp5 sin glifo y 531mp5 con glifo es lo que tiene que dar, y lo que me da a mi XD
