### ISSUE TITLE
[Talento > Despertar Ancestral(chaman Restauración)]

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#770]
Hola queria informar que este talento, http://old.wowhead.com/spell=51558
Despertar Ancestral, al realizar una sanación crítica con una sanación directa de objetivo individual, no se invoca al espiritu ancestral, nunca aparece.
Un saludo.

**Comment by NeKroZ** [comment]
El espiritu Ancestral, (Ancestral Awakening) es un extra healing que se hace al jugador con menos vida del grupo o raid, y eso si esta funcionando

**Comment by crowel** [comment]
Gracias nekroz cierro issue.
