### ISSUE TITLE
[ Shaman > Spell > Hex ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#773]
Maleficio:
http://old.wowhead.com/spell=51514

Transforma al enemigo en una rana. Mientras esté bajo el maleficio, el objetivo hechizado no puede ni atacar ni lanzar hechizos. Si se le inflige daño, se puede interrumpir el efecto. Dura 1 min. Solo se puede echar un maleficio a un objetivo a la vez. Solo funciona con humanoides y bestias.

El bug está en que al recibir daño, NUNCA se elimina el efecto de HEX

**Comment by ghost** [comment]
Pues será a ti xD Porque a mi sí que se me elimina jaja

**Comment by ninotauro** [comment]
ami tambien me pasa hecho maleficio  y le puedo seguir atacando en sapo ya q no se le quita.
