### ISSUE TITLE
Misión Bug>Horda>El camino de los caminasol

### ISSUE THREAD

**Issue by Andywowx3** [RoDNet/Bugtracker-Infinium-4.0.6a#780]
Es la misión de los tauren cuando el maestro paladin te dice aprende tal hechizo y practica lo en los muñecos y no me va

**Comment by redneo** [comment]
Enlace de wowhead o algo de la misión?

**Comment by ghost** [comment]
Link a wowhead http://es.wowhead.com/quest=27023/el-camino-de-los-caminasol

**Comment by redneo** [comment]
Gracias. Fixed
