### ISSUE TITLE
[Hunter > Spec: Marksmanship > Spell > Improved Steady Shot]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#8]
-Disparo firme mejorado
http://es.wowhead.com/spell=53224

¿Aumenta la celeridad pasivamente?
Se activa automáticamente al lanzar Disparo firme ( http://es.wowhead.com/spell=56641 );
sin necesidad de tener activo el talento.
Se activa cada vez que lanzas 1 disparo firme
Aumenta le celeridad un ¿0%? ( debería ser 15% )

**Comment by aerz** [comment]
Faltaba el fix completo del aura al activarse. Implementado en el core, visible en el próximo Update.
Cierro reporte :)
