### ISSUE TITLE
Picaro - Capa de las sombras bug

### ISSUE THREAD

**Issue by Oscarin** [RoDNet/Bugtracker-Infinium-4.0.6a#80]
Aqui dejo un video de lo que sucede cuando uso capa de las sombras i me meto en un anillo de escarcha:
http://www.youtube.com/watch?v=wFmZWee7lSk&feature=youtu.be

i tambien falla el talento: impetu mortal,de la rama asesinato.no se activa tras ganar honor.

**Comment by macols77** [comment]
Resiste algún hechizo, o solo no resiste ese?
