### ISSUE TITLE
Reiniciar Heroicas

### ISSUE THREAD

**Issue by Urano** [RoDNet/Bugtracker-Infinium-4.0.6a#802]
Cuando hago una mazz heroica,le doy a reiniciar,vuelvo a entrar y como si nada,sigue sin reiniciar.

**Comment by ghost** [comment]
Las masmorras heroicas no se pueden reiniciar..., deberían de informarse sobre como funciona el juego antes de reportar un bug o por lo menos preguntar dentro del juego a alguien.

**Comment by Urano** [comment]
Es que pregunte a un GM y me dijo que no se pueden reiniciar ahora porque estan arreglandolas ahora,entonces que quieres que piense.

**Comment by ghost** [comment]
Pues nada tampoco para que lo tomes a mal xd, puedes cerrar el bug.

**Comment by Dekadencee** [comment]
Como especifica @Lvmb no es un error del servidor, si no que el juego es así, por lo tanto cerramos.

Un saludo ^^
