### ISSUE TITLE
Problema migración

### ISSUE THREAD

**Issue by TORPEDO77** [RoDNet/Bugtracker-Infinium-4.0.6a#804]
Hola, el que caso es que migré un personaje, y seleccioné de profesión encantamiento, y el personaje ha aparecido sin ninguna profesión.
Gracias por las molestias.

**Comment by crowel** [comment]
Hola buenas, creo que este mensaje lo deberias de poner en la sección de migraciones del foro.
http://reignofdarkness.net/wow/foros/f10/
Un saludo.

**Comment by Dekadencee** [comment]
Esto es un tema que debes transmitir a través de nuestros foros, esto es solo para reportar errores en el juego
