### ISSUE TITLE
Abuso de BG

### ISSUE THREAD

**Issue by Lordenkidu** [RoDNet/Bugtracker-Infinium-4.0.6a#808]
![WoWScrnShot_030813_121734](https://f.cloud.github.com/assets/3300645/237347/2855ae6a-8811-11e2-967b-296260d1bdd4.jpg)
la alianza toma las banderas en el instante q se inicia la BG cuando aun la horda no puede salir del bastion

![WoWScrnShot_030813_121734](https://f.cloud.github.com/assets/3300645/237347/2855ae6a-8811-11e2-967b-296260d1bdd4.jpg)

**Comment by DatJetto** [comment]
https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/582, tanto la horda como la alianza pueden salir del portal, la cosa es que la gente sea honesta y no salga.

**Comment by Dekadencee** [comment]
Reporte repetido, seguimos su estado desde el reporte anterior #582
