### ISSUE TITLE
agradecimiento pero...

### ISSUE THREAD

**Issue by fofo901** [RoDNet/Bugtracker-Infinium-4.0.6a#810]
primero que nada gracias gms por escuchar nuestros gritos de ayuda XD y siempre salir adelante, la otra vez yo denucni esta quest

http://www.wowhead.com/quest=28872/total-war

que no estaban los items, ahora ya salen , el problema es q no deja ser dropeado, gracias por su ayuda

**Comment by fofo901** [comment]
y otra molestia XD http://www.wowhead.com/quest=28043/how-to-maim-your-dragon esta ya deja que el dragon "se pueda montar" pero al igual q la anterior no realiza la accion enserio muchas gracias por su ayuda me di cuenta que arreglaron otras 2 quest, osea las pusieron como en verdad se realizan

**Comment by ghost** [comment]
Supongo que lo que quieres decir es que no deja ser "looteado", no "dropeado" xd solo para que no se confundan los que arreglan.

**Comment by redneo** [comment]
http://www.wowhead.com/quest=28872/total-war ya tendría que ir cuando se reinicie el servidor y limpieis temporales.

La de domar al dragon, no se logra montar en el dragón o me lo parece a mi (teoricamente tendria que dejar montarte)

**Comment by redneo** [comment]
arreglado
