### ISSUE TITLE
Problema al reforjar

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#813]
Lo que pasa es lo siguiente, reforje todos los items que podía a celeridad, luego de reforjar se me sumaban todos los puntos bien, pero al desconectarme y volver a conectarme, los puntos en vez de sumar, se restaban, y la unica forma de arreglarlo es quitandome todas las partes reforjadas, relogear y volver a ponermelas, dejo imágenes para demostrar que sí sucede eso, perdón que sean tantas imagenes xd

Aqui se ve como después de quitarme todo el set que tengo reforjado en celeridad, tengo una celeridad de -0,21% y eso teniendo en cuenta que tengo el skill "oscuridad" del sacer sombras que aumenta 3% la celeridad.

![celeridad -0 21 sin equipo-anormal](https://f.cloud.github.com/assets/3508051/239111/5cd4a84e-885c-11e2-98c3-46708fe0e281.jpg)

Aqui tengo la celeridad normal, en 3% (relogee sin tener puesto el set y se puso normal)

![celeridad 3 00 sin equipo-normal](https://f.cloud.github.com/assets/3508051/239113/991953b8-885c-11e2-9af9-3ea0d0d7a825.jpg)

Luego del relogeo y conseguir mi 3% de celeridad, me equipe el set sin que este reforjado y obtuve 10% de celeridad

![celeridad 10 00 equipo-normal](https://f.cloud.github.com/assets/3508051/239115/c149a4aa-885c-11e2-97c9-a5827c98d256.jpg)

Luego reforje todo lo que podía a celeridad y obtuve 14,01%

![celeridad 14 01 reforjado-normal](https://f.cloud.github.com/assets/3508051/239116/df433f02-885c-11e2-99cb-9ea41a19c9d6.jpg)

Luego, más mi forma de las sombras, que me proporciona el buff "estímulo mental" que aumenta 5% mi celeridad obtuve 19.71% de celeridad.

![celeridad 19 71 reforjado-forma sombras-normal](https://f.cloud.github.com/assets/3508051/239122/0bd50abe-885d-11e2-93d4-5901e1b93912.jpg)

Hasta aquí todo bien, pero luego, al desconectarme y volverme a conectar (con todo mi equipo reforjado puesto) en vez de sumarme los puntos reforjados, me los resta, obteniendo 15.50% de celeridad en forma de las sombras.

![celeridad 15 50 reforjado-forma sombras-anormal](https://f.cloud.github.com/assets/3508051/239124/4376dda8-885d-11e2-8b22-7e2adc24bef3.jpg)

Bueno, solo puse tanta imagen para demostrar que el bug esta ahí y existe, y es al desconectarse y volver a entrar, luego de haber reforjado los items.
Espero que puedan arreglarlo, muchas gracias si es que vieron el reporte completo xd.

**Comment by Keough** [comment]
yo sólo vi las imágenes, pero bien posteado (Y) :D

**Comment by Dekadencee** [comment]
Reporte repetido, seguimos su estado desde el reporte anterior #67, nobstante se agradece el posteo con todo detalle, que lo cerremos no quiere decir que no sea válido, simplemente es para llevar un control y no tenerlos repetidos, obviamente nos es de gran ayuda tanto detalle, gracias ^^

**Comment by F4NT4SM4** [comment]
yo para evitar eso tengo que hacer esto:
http://reignofdarkness.net/wow/foros/t403/
