### ISSUE TITLE
Hechizo: Sangre de vida

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#814]
El hechizo Sangre de vida http://es.wowhead.com/spell=55503/sangre-de-vida de la profesión herboristeria, al usarla proporciona celeridad y vida(que creo funciona bien), la primera vez que lo usas te aumenta la celeridad los puntos correspondientes, pero la segunda vez que lo usas en vez de aumentar baja tus puntos de celeridad, y la tercera baja más y así hasta llegar a 0 de celeridad.

Aqui tengo 15% de celeridad sin usar el hechizo Sangre de vida
![celeridad 15 50 reforjado-forma sombras-anormal](https://f.cloud.github.com/assets/3508051/239168/169c7468-8863-11e2-8cc2-1142a54f7c18.jpg)

Luego de usar la primera vez el hechizo Sangre de vida mi celeridad aumento a 16%
![sangre vida aumentando](https://f.cloud.github.com/assets/3508051/239169/21e024aa-8863-11e2-9e61-7ca4ec36c09d.jpg)

La segunda vez al usar Sangre de vida mi celeridad disminuyó a 7%
![sangre vida bajando](https://f.cloud.github.com/assets/3508051/239170/3d24d33c-8863-11e2-989d-66029d16408c.jpg)

**Comment by ghost** [comment]
Lo cierro, ya no me sucede.

**Comment by redneo** [comment]
Lo que no hace es sacar las florecillas al caminar, que es una tontura, pero mola, jejejeje... me pongo a ello

**Comment by ghost** [comment]
Si, esparce flores por el piso.
