### ISSUE TITLE
Bug penetración de Hechizo

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#821]
Hola quiero informar de un pequeño bug que tengo con la penetración de hechizo.
Tengo 329 de penetracion de hechizo, me acabo de cojer el cinturon sanguinario el cual trae una gema azul, asi que decidi poner una gema de +50 de penetración de hechizo.¿cual es mi sorpresa? que al equiparla en vez de subirme otros 50 puntos me los resta a 279 que son los -50p de la gema.
En esta foto se ve como me desciende:
![WoWScrnShot_031013_035242](https://f.cloud.github.com/assets/3537253/240593/4f794876-892e-11e2-8f61-63dc5d61c4cc.jpg)

Y en esta otra como al equiparme otra gema en este caso +40 intelecto y al eliminar la de penetración que puse me devuelve mis puntos.
![WoWScrnShot_031013_035329](https://f.cloud.github.com/assets/3537253/240594/6d0f7c16-892e-11e2-9f0f-55418cc0da72.jpg)

Si me pudieran decir si hay un tope y yo lo sobrepase o si es que esta mal, lo agradeceria.
Un saludo.

**Comment by crowel** [comment]
Por lo que acabo de comprobar quitandome otra gema de penetración que tenia en los guantes me aumento otros +50 puntos osea que estas gemas en vez de subir el stat lo bajan xD

**Comment by DatJetto** [comment]
Esto ya estaba reportado :c

**Comment by ghost** [comment]
De todas formas, yo juraría que la penetración de hechizos está bug, jamás he resitido/me han resistido ningún hechizo y llevo 0 de penetración...es algo muy grave.

**Comment by ghost** [comment]
Por si algún día deciden arreglarlo...aquí dejo información de como debería ser:

http://todowow.com/clases/mago/indice-de-golpe-y-penetracion-de-hechizos/

http://www.wowwiki.com/Spell_penetration

**Comment by redneo** [comment]
Las gemas de penetracion con hechizos hacen eso... no se pq pero lo hace y lo pilla desde los ficheros del wow :S
