### ISSUE TITLE
Mision Bug - La bendicion del Oso

### ISSUE THREAD

**Issue by Alejo0701** [RoDNet/Bugtracker-Infinium-4.0.6a#822]
La mison dice que debo buscar al zancudo Pataveloz para obtener unas plumas pero no enceuntro al mob por ningun lado 

msion http://es.wowhead.com/quest=13544/la-bendicion-del-oso

pataveloz http://es.wowhead.com/npc=32997

**Comment by redneo** [comment]
Arreglada cuando se caiga el servidor. Un saludo
