### ISSUE TITLE
[NPC > Tiburón ballena > error]

### ISSUE THREAD

**Issue by Hellythium** [RoDNet/Bugtracker-Infinium-4.0.6a#824]
Buenas, este post es para reportar un problema grande que se me presento, yo soy un cazador de logros y me interece mucho por este logro: http://es.wowhead.com/achievement=4975/desde-el-corazon-del-infierno-te-hiero  pero el problema es que por mas de que lo busque en los sitios referidos no lo encontre y justo cuando me iba a dar por vencido lo encontre pero con un muy grande error que es que me aparecia su rastro por que soy Hunter y active rastrar bestias y me aparecio fue esto
https://f.cloud.github.com/assets/3613748/240673/b2f6c89c-893d-11e2-906d-5947419a246a.jpg  y por eso digo que es error por que en vez de aparecerme como un NPC enemigo me aparece como un aliado y busque por otras rutas y en diferentes puntos y nada entonces quiero saber que es lo que realmente sucede si es un problema tecnico o que.   Gracias por la colaboracion.

**Comment by ghost** [comment]
Claramente está bug, más que nada porque mira jeje
http://es.wowhead.com/npc=40728

Ese se tiene que matar entre un copón de gente o bien un hunter con muuuuucho tiempo libre para poder solearselo corriendo en círculos xD

**Comment by redneo** [comment]
Arreglado
