### ISSUE TITLE
[Mision > Horda > 100 años de soledad]

### ISSUE THREAD

**Issue by ajdap** [RoDNet/Bugtracker-Infinium-4.0.6a#84]
Al utilizar  la correa de múrloc en un múrloc Anca Vil, no sucede nada, no se puede capturar al murloc.

Link de la mision: http://es.wowhead.com/quest=24974#english-comments

Múrloc Anca Vil: http://es.wowhead.com/npc=1541

**Comment by searum** [comment]
fix
