### ISSUE TITLE
Bug el sistema de subir niveles por Puntos de voto/donacion

### ISSUE THREAD

**Issue by AlejandroAponteCa** [RoDNet/Bugtracker-Infinium-4.0.6a#848]
bueno como dice el titulo al parecer no funciona el sistema de subir niveles, me pide 100 puntos por cada nivel a subir y tengo en la cuenta 350 y al intentar subir 3 niveles a mi dk horda me dice que no tengo puntos suficientes... 

un saludo y puedan arreglarlo pronto :)

**Comment by DatJetto** [comment]
Si funciona, lo que pasa que el nivel que te marca no es tu nivel actual, es el nivel siguiente al que pasar, de manera que si tu Dk es lvl 10, en el apartado de subir empezará en 11 hacia delante. ;D

**Comment by AlejandroAponteCa** [comment]
entons yo lo tengo al lvl 80 que tengo que hacer??

**Comment by Alfonn** [comment]
Simplemente en subir niveles te pondrá : 81, 82, 83, 84, 85. Deberá elegir hasta el 83 que son tus tres niveles..

**Comment by Dekadencee** [comment]
Funciona correctamente, cerramos.
