### ISSUE TITLE
Quest Disciplina

### ISSUE THREAD

**Issue by dragonoit** [RoDNet/Bugtracker-Infinium-4.0.6a#849]
http://es.wowhead.com/quest=12906/disciplina

le pegas con el item y no los cuenta

**Comment by DatJetto** [comment]
Discrepo, la misión funciona perfectamente recientemente la hice, hará 1 o 2 semanas, solo debes pegar a los Agotados y tiene un % de que ellos se enfaden y ataquen y otro de que se ponga a trabajar, de cualquier modo, no es spammeable en el mismo NPC.

**Comment by dragonoit** [comment]
es verdad funca esta no me habia dado cuenta
