### ISSUE TITLE
Profesión encantamiento

### ISSUE THREAD

**Issue by sergito48** [RoDNet/Bugtracker-Infinium-4.0.6a#85]
He encontrado lo que creo que es un fallo en infinium en cuanto a la profesión encantador. El fallo se basa en que necesito hacer vara runica de adamantita la cual no sale para hacer en encantamientos de dicha profesion,aunque mi nivel de profesion es de 525 y el personaje es migrado de otro servidor.

**Comment by DatJetto** [comment]
la vara has de comprarle la receta a un npc en Terrallende dependiendo de tu facción Horda en Nagrand o Bosque de Terokkar, ahora no me acuerdo muy bien y si eres Ali en Península del fuego infernal. 

Esto no es un bug :camel:
