### ISSUE TITLE
Talento Bug Warrior Furia

### ISSUE THREAD

**Issue by pat123** [RoDNet/Bugtracker-Infinium-4.0.6a#853]
Talento BUG " Oleada de sangre "

http://img542.imageshack.us/img542/2255/wowscrnshot031613165530.jpg

En español : 
Sus éxitos Sed de sangre tienen una probabilidad del 30% de hacer su siguiente golpe instantáneo, gratis, y hacer daño un 20% más de 10 seg.

Y al parecer nunca se activa aunque siga tirando Sed de Sangre a cada rato no se activa.

**Comment by DatJetto** [comment]
Dejo el link de Slam: http://es.wowhead.com/spell=1464 
y del talento Bloodsurge: http://old.wowhead.com/spell=46915

**Comment by pat123** [comment]
Al parecer cuando mi wow estaba en ingles no se activava pero mi amigo me lo puso en español y se activa, al parecer no estaba bugeado aver si pueden cerrar el tema
