### ISSUE TITLE
Ultimo bos el nucleo petreo no da loot heroico ni chapas de valor

### ISSUE THREAD

**Issue by Naiira** [RoDNet/Bugtracker-Infinium-4.0.6a#854]
Buenas , anoche unimos aleatoria por el buscador de mazmorras y salio el nucleo petreo , el ultimo bos tenia lvl 84 y al matarlo no dio loot de heroico ni chapas. 
![WoWScrnShot_031713_040932](https://f.cloud.github.com/assets/3589001/267665/1180e38e-8eb1-11e2-8c3d-79e663e16f09.jpg)
![WoWScrnShot_031713_040922](https://f.cloud.github.com/assets/3589001/267666/1c6b4e88-8eb1-11e2-937c-8910c8c88cc6.jpg)
![WoWScrnShot_031713_034755](https://f.cloud.github.com/assets/3589001/267668/2a2cddb6-8eb1-11e2-81a5-d7ac820067bf.jpg)

**Comment by ghost** [comment]
#736 ya se habia reportado y fixeado pero sigue el problema.

**Comment by Fabercastell** [comment]
Ayer hicimos la mazmorra y nos paso lo mismo.
