### ISSUE TITLE
MISION BUG - A NUEVA THALANAAR

### ISSUE THREAD

**Issue by Alejo0701** [RoDNet/Bugtracker-Infinium-4.0.6a#857]
La mision dice que hay que hablar con dyslix kami-kaze para que nos preste un hipogrifo y poder ir a nueva thalanaar pero al hablar con el no nos presta nada y solo nos muestra el mapa normal de rutas de vuelo y por ende no se puede ir a nueva thalanaar                                                                mision: es.wowhead.com/quest=25479/a-nueva-thalanaar

**Comment by redneo** [comment]
Arreglada parcialmente.
Te cuenta, te lleva al lugar, pero no en grifo.
