### ISSUE TITLE
bug arquelogia

### ISSUE THREAD

**Issue by lexintor** [RoDNet/Bugtracker-Infinium-4.0.6a#859]
Mi problema es que tengo la abilidad de arquelogia ful 525 y no puedo digamos investigar uldum  no me salen las palas para "minear"

**Comment by lexintor** [comment]
parece que esta solucionado. pero sale muy poco...

**Comment by DatJetto** [comment]
La distribución de las zonas es aleatoria, es cuestión de suerte. Esto no es un bug.

**Comment by Dekadencee** [comment]
Comprobado, funcionar funciona, como dice jetto la distribución es aleatoria y depende de tu nivel del player y de arqueología.
