### ISSUE TITLE
Mision Bug - Desprestigiando a los desertores

### ISSUE THREAD

**Issue by Alejo0701** [RoDNet/Bugtracker-Infinium-4.0.6a#874]
Hay que entregar unos panfletos a los guardias de Theramore, pero al habalr con ellos no pasa nada ni los cuentan ni da la opcion de entregarle el panfleto ni nada. 

mision: http://es.wowhead.com/quest=27212#english-comments

Panfletos modificados: http://es.wowhead.com/item=33015

**Comment by redneo** [comment]
Arreglada
