### ISSUE TITLE
Mision Bug - Espiritus del Bastion Quebrantarrocas

### ISSUE THREAD

**Issue by Alejo0701** [RoDNet/Bugtracker-Infinium-4.0.6a#875]
Hay que usar el totem energizado sobre lso restos de los quebrantarrocas pero al usar el totem este carga pero no los cuenta por tanto no se puede terminar la mision. 

mision: http://es.wowhead.com/quest=27410

Totem: http://es.wowhead.com/item=33091

**Comment by redneo** [comment]
arreglada
