### ISSUE TITLE
Mision Bug - Arrasa el puesto Cuernatroz

### ISSUE THREAD

**Issue by Alejo0701** [RoDNet/Bugtracker-Infinium-4.0.6a#876]
Dice que hay que usar la antorcha de Tabetta para quemar unas tiendas (carpas) en el Puesto Cuernoatroz, pero cuando llego al puesto las tiendas ya estan quemandose y aun asi voy a una y al usar la antorcha me dice que debo esar en la tienda aun cuando ya estoy en ella.

mision: http://es.wowhead.com/quest=27296/arrasa-el-puesto-cuernoatroz

Antorcha: http://es.wowhead.com/item=33072

**Comment by redneo** [comment]
Arreglado
