### ISSUE TITLE
Mision Bug - Limpiar la colina de las Brujas

### ISSUE THREAD

**Issue by Alejo0701** [RoDNet/Bugtracker-Infinium-4.0.6a#877]
Dice que hay que colocar la antorcha ruinabruja al final del muelle y vencer a lo que aparezca, pero al usar la antorcha no aparece nada.

mision: http://es.wowhead.com/quest=27190#.

antorcha: http://es.wowhead.com/item=33113

**Comment by redneo** [comment]
Arreglado
