### ISSUE TITLE
Mision Bug - Inspecciona la isla de Alcaz

### ISSUE THREAD

**Issue by Alejo0701** [RoDNet/Bugtracker-Infinium-4.0.6a#878]
Dice que hay que pedrile un grifo a Cassa Ala Carmes para poder ir a la isla de Alcaz, pero al hablar con ella no da la opcion de ir a alcaz.

Mision: http://es.wowhead.com/quest=27239

NPC: http://es.wowhead.com/npc=23704#english-comments

**Comment by redneo** [comment]
Arreglada
