### ISSUE TITLE
Encantamiento, vara runica de titanio

### ISSUE THREAD

**Issue by sergito48** [RoDNet/Bugtracker-Infinium-4.0.6a#88]
Buenas , me han comentado varias personas que deberian haberme dado junto a la migracion la vara runica de titanio pero no ha sido asi, queria saber si me lo deberian de haber dado o solo es un error mio , ya que elegi como profesion encantamiento. Gracias

**Comment by Dekadencee** [comment]
Tema traspasado como consulta a los gms... esperando respuesta

**Comment by Dekadencee** [comment]
Me comentan que no, que las varas no se proporcionan, estas tienen que ser conseguidas a través de un herrero.

Un saludo ^^
