### ISSUE TITLE
bug misión joyería

### ISSUE THREAD

**Issue by problema** [RoDNet/Bugtracker-Infinium-4.0.6a#881]
Bueno, me hice un objeto de joyería el cual me daba la siguiente misión, Figurrilla de serpiente rota. 
Tengo todos los objetos necesarios y he estado frente al npc de Dalarán y Ventormenta que da las misiones diarias. Me dice que la tengo completada pero no me deja entregarla.

![WoWScrnShot_031613_030222](https://f.cloud.github.com/assets/3883161/280491/0294de66-9159-11e2-84e1-8745165159a0.jpg)

**Comment by redneo** [comment]
arreglada

**Comment by problema** [comment]
perfecto! gracias
