### ISSUE TITLE
Daño Ridículo del Rogue. (Emboscada)

### ISSUE THREAD

**Issue by Rueda888** [RoDNet/Bugtracker-Infinium-4.0.6a#889]
Solamente quisiera dar cuenta del daño tan bajo que hace la habilidad Emboscada. Que siendo full sañoso y a un tela sanguinario quitarle 9k-14.5k de crítico con emboscada preocupa. Todo esto teniendo activados  Derrumblo (+1000 AP), Distintivo sañoso (+1077 Ag.), y Trinket PVP (+1794 Ag.).  No es Normal.

Esta habilidad es la única oportunidad de relizar nuestro burst, ya que una vez acabado  este significa "a grosso modo" dedicarse a espamear hemorragia ( en torno a los 3k-5k por hit) y Slice and Dice y Recuperarse, y a esperar para la próxima Danza de las Sombras. 

Ya que el staff se ha propuesto arreglar las clases, consideren este post e intenten fixear esta habilidad por favor.

Una vez más, muchas felicidades por el server. Están haciendo un gran trabajo.

 Un Saludo.

**Comment by ghost** [comment]
Buenas, aquí dejo un par de fotitos para que veáis la descripción de Puñalada y Emboscada y comparéis vosotros mismos si debería hacer más daño Emboscada que Puñalada, cuando ahora mismo es al revés.

Ahí tenéis la descripción de ambas skills.
![WoWScrnShot_032213_133618](https://f.cloud.github.com/assets/3328374/295678/609957d8-94a8-11e2-8f52-ef719ae70f3e.jpg)

Y ahí después de usarlas el daño de cada una.
![WoWScrnShot_032213_133604](https://f.cloud.github.com/assets/3328374/295681/70579fc2-94a8-11e2-9534-9ae1f00f4950.jpg)

Está testeado con el dummie de Ventormenta.

Emboscada: http://es.wowhead.com/spell=8676
Puñalada: http://es.wowhead.com/spell=53

**Comment by searum** [comment]
fix
