### ISSUE TITLE
QUEST : No temerás peligro alguno.

### ISSUE THREAD

**Issue by Alfonn** [RoDNet/Bugtracker-Infinium-4.0.6a#891]
Esta quest es de nivel 1-10 y es de revivir/curar a unos soldados, lo intentas y no se curan , ni reviven, ni te cuentan.

![Dibujo](https://f.cloud.github.com/assets/3854953/285345/608080de-9217-11e2-8132-7d9f5b6cf17f.jpg)

**Comment by redneo** [comment]
Arreglada un poco chapuceramente, pero funciona
