### ISSUE TITLE
Emboscada Skill Picaro

### ISSUE THREAD

**Issue by alviu** [RoDNet/Bugtracker-Infinium-4.0.6a#893]
El skill este esta pegando 7k es demasiado poco al menos deberia pegar 15k o mas teniendo mi equipo

**Comment by ghost** [comment]
Por si no te has fijado, hay otro post de emboscada ;) https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/889
A parte se suele poner link de wowhead, imagenes, etc a la hora de reportar. Un saludo.
