### ISSUE TITLE
[Hunter > Spec: Marksmanship > Spell > Rapid Killing]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#9]
-Matanza rápida ( Al matar un enemigo que reporte experiencia u honor +20% daño en Disparo firme, disparo de cobra y disparo de puntería =

[12 / 11 / 2012 ] El aura no salta al matar un enemigo que de exp u honor.

http://es.wowhead.com/spell=35099
Bug: No aumenta el daño 20% de las spells; 

Disparo firme
http://es.wowhead.com/spell=56641

Disparo de cobra 
http://es.wowhead.com/spell=77767

Disparo de puntería
http://es.wowhead.com/spell=19434

**Comment by adrianrp1988** [comment]
Reparado en la próxima Rev
