### ISSUE TITLE
Piroexplosion bug.

### ISSUE THREAD

**Issue by lllalvarolll** [RoDNet/Bugtracker-Infinium-4.0.6a#903]
Buenas. La piroexplosion que sale automatica quita 3000-4000 daño nada mas.....
Se que el mago estaba over pero creo que es demasiado el "bajon" que ha dado. (lo digo porque para el equipo y la experiencia que tengo, no hago apenas daño, y, ademas mis compañeros que tienen un equipo similar con otras razas, me sacan demasiada diferencia.
Muchas gracias.

**Comment by ghost** [comment]
Ah que no era solo cosa mía por lo que veo jajajajaj han bajado el daño de la piro y con eso parece que piensan compensar el daño del mago...-_- lo que le pasa a los magos entre otras cosas es que tienen un bonus de spell de 3k, pero bajar el daño a la habilidad principal no es la solución, ya que ahora meto más con hechizos secundarios que con mis hechizos fuertes como piroexplosión...

**Comment by ghost** [comment]
Me he encontrado con lo mismo. Con la Piroexplosión casteada saco unos 18k de normal, y con la instantánea (que se supone que es lo mismo, pero sin tener que castear) saco 8k de crítico.. Me parece una descompensación bastante grande. Dejo el link a WowWiki de, tanto el talento que nos proporciona la Piro instantánea, como el link de la spell en sí.

Talento "Buena racha" / "Hot Streak" : http://www.wowwiki.com/Hot_Streak

Piroexplosión / Pyroblast : http://www.wowwiki.com/Pyroblast

Gracias.

**Comment by Dazand** [comment]
A mi me pega 4k el instant, eso no puede ser correcto xD
Espero que lo arreglen :)
Gracias 

Dazand

**Comment by ghost** [comment]
No lo es, sobre todo porque tiene 14k de daño base y es completamente imposible que pegue menos de lo que debería llevando +7k intel como llevaremos todos...

Completamente injugable, meter más con lanzas de hielo yendo en fuego o con dragón que con la propia piroexplosión que es el donde se basa el daño...

**Comment by searum** [comment]
fix
