### ISSUE TITLE
Guerrero BUG

### ISSUE THREAD

**Issue by pat123** [RoDNet/Bugtracker-Infinium-4.0.6a#905]
Ayer estaba en duelo junto a otro War llamado Predytor y cuando de pronto yo activo todos mis CD's y le tire un critico de 110k termino el duelo como ganador yo y me gustaria que agreglaran el daño del war ya que no me gusta jugar el war bug.

Saludos

**Comment by searum** [comment]
no me das ningun dato que me sirva
