### ISSUE TITLE
Bastión del crepúsculo.

### ISSUE THREAD

**Issue by Dazand** [RoDNet/Bugtracker-Infinium-4.0.6a#906]
Hola!
Soy uno de los muchosjugadores que viene de Wh (un mago fuego que tiene la cabeza de Sinestra hehe no se si me hsbran visto xD)  , allí teníamos varios bugs en spells pero las bandas andaban bien jeje.
Bueno, estaba acostumbrado a hacer BC todas las semanas jeje.
Bueno la cosa es que veo acá el PvE muy apagado, casi no hay, a duras penas veo que hacen baradin no más, bueno a mi me parece que el PvE es bastante importante, en mi caso fue como me armé de pequeños objetos mientras sacaba lo PvP, y me quedo gustando, el PvE es muy bacano jeje.
Bueno, me preocupa ésto hecho ya que el PvE es la mitad de WoW D:
bueno me gustaría que los Gm's le dediquen tiempo a esto, en verdad creo que es muy importante y en realidad podría atraer a mucha, mucha gente, bueno, pues es eso me gustaría que se pudiesen arreglar los boss de bastión del crepúsculo, y en un futuro no muy lejano Decenso jeje.
Me fije que andan mal los boss de BC, o no se puedne hacer por ataques catastróficamente elevados o no se les puede golpear...En fín espero que se puedan arreglar t gracias a lso del staff por el trabajo y esfyerzo que le dedican a todo esto.
Gracias.

Dazand

**Comment by adrianrp1988** [comment]
Ambas instancias han sido reescripteadas y han mejorado cantidad, pero todavia no estan 100 pero si a un 95 % diria yo
