### ISSUE TITLE
Misión Bug : Posponiendo lo inevitable

### ISSUE THREAD

**Issue by Alfonn** [RoDNet/Bugtracker-Infinium-4.0.6a#909]
Simplemente llegas, matas al boss y cuando intentas usar el objeto que te dan te dice ''No estas en la Falla...'' 

Link WoWHead:  http://es.wowhead.com/quest=11905/posponiendo-lo-inevitable

**Comment by redneo** [comment]
Si que funciona... tienes que ponerte justo donde está la falla. Segun la miras, un poco a la izquierda, en mi caso en las cohordenadas 64.91 21.39
