### ISSUE TITLE
[Skills] Mage Fire 

### ISSUE THREAD

**Issue by skyrex321** [RoDNet/Bugtracker-Infinium-4.0.6a#912]
Bueno después de la caída del servidor y la desconfiguracion que sufristeis el mago Fire a vuelto a las andadas y vuelve a estar como hace varios meses la Pyroexplosión Instantánea inflige 5k a los máximo de critico y eso estando casi full sañoso cuando esta habilidad deberia rondar entre los 19-23k de critico.

**Comment by skyrex321** [comment]
[Skills] Mage Fire 

El tick de daño del talento Ignición es superior al que debería ser haciendo incluso mas daño que el daño periódico de bomba viva

**Comment by searum** [comment]
fix, se hace 1 issue por bug
