### ISSUE TITLE
Misiones bug - Vash'jir.

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#913]
Misión "Sin miedo"
http://es.wowhead.com/quest=25948/sin-miedo misión bug, no se puede terminar/entregar la misión a Legionario Nazgrim http://es.wowhead.com/npc=41750

---

 Misión "Debilidad por los tiburones"
http://es.wowhead.com/quest=27699/debilidad-por-los-tiburones misión bug, no están los items "Diente de Bocados" http://es.wowhead.com/item=55212 para lootearlos.

---

 Misión "Descompresion"
http://es.wowhead.com/quest=26008/descompresion misión bug, al usar Piedra aliento http://es.wowhead.com/item=56169 en los npcs Guerreros encarcelados no suma como "Guerreros encarcelados liberados".

---

 Misión "Informe" 
http://es.wowhead.com/quest=26007/informe misión bug, no se puede hablar con el npc Gurrok http://www.wowhead.com/npc=41885/gurrok para terminar la misión.

**Comment by redneo** [comment]
La primera parte de la zona, para la horda, la he retocado para que sea algo funcional, por favor, reportame, lo que encuentres. Muchas gracias

**Comment by ghost** [comment]
Ok, volvere a ver, gracias.

**Comment by ghost** [comment]
@redneo ahí ya revise las misiones de nuevo, les puse "reparado" en mayúscula las que ya se pueden completar, las que no, pues no xd. Gracias por arreglarlas.

**Comment by redneo** [comment]
Poco a poco voy arreglando más, me entretengo mucho ya que cambio movimiento de algún npc, daños, magías. Toda la zona está realmente MAL... hasta los cementerios no están definidos!!!!!!!

**Comment by ghost** [comment]
Si, esta totalmente inutilizable xd, realmente es mucho trabajo el que estas haciendo.

**Comment by ghost** [comment]
@redneo pongo aquí las misiones reparadas y dejo las que faltan arriba.
http://es.wowhead.com/quest=27668 "Presta atención"
http://es.wowhead.com/quest=25944 "En cueros"
http://es.wowhead.com/quest=25651 "Oh, la locura"
http://es.wowhead.com/quest=25390  "El mejor amigo de una chica"
http://es.wowhead.com/quest=25587  "Necesito refugio"
http://es.wowhead.com/quest=27708 "La hora del celador"

**Comment by ghost** [comment]
Lo cierro para agrupar las misiones como pediste redneo, #1016
