### ISSUE TITLE
Problemas con la descripcion de las habilidades

### ISSUE THREAD

**Issue by odin2021** [RoDNet/Bugtracker-Infinium-4.0.6a#918]
![WoWScrnShot_032413_195956](https://f.cloud.github.com/assets/3957790/295800/268f4996-94b5-11e2-91ce-10acd60a19f1.jpg)
En todas las habilidades en la descripccion no me aparece el daño que causa cada habilidad,unicamente me aparece la descripcion de la abilidad.

Habia puesto ticket y me dijeron que era problema de la habilidad q no funciona bien y lo reportase por aki.Pero no me pasa con 1 habilidad me pasa con todasmhe creado otro personaje(sacer en vez de cazador) y me pasa exactamente lo mismo.

un saludo espeor una respuesta

**Comment by Dazand** [comment]
No te creo, de verdad hcisite ticket y te resdpondieron que hicieras post? XD
Mira no es más que una configuración en el interfaz, siemplemente buscala y desactivala,se llama consejos para principiantes o algo así.
Que gracioso que te hallan mandado al foro, no es un bug ni nada pro el estilo :)

Saludos.

Dazand

**Comment by odin2021** [comment]
Jajaja pues si me mando aki jeje fue allanysm muchas gracias ya esta solucionadomjusto me lo explico un amigo tb
