### ISSUE TITLE
QUEST mision TENGO UNA IDEA. PERO PRIMERO... 

### ISSUE THREAD

**Issue by Kiitt** [RoDNet/Bugtracker-Infinium-4.0.6a#919]
hay un problema con los mobs de la cámara acorazada nose pueden atacar por algun motivo podrian revisar el bug sino no se puede continuar la cadena de misiones
para pasar la mision es necesariopoder atacarlos

**Comment by redneo** [comment]
Cuando caiga el server tendría que funcionar, espero confirmacion para cerrar issue

**Comment by Kiitt** [comment]
gracias entiendo
