### ISSUE TITLE
BUG BRUJO piedra de salud

### ISSUE THREAD

**Issue by cypress1** [RoDNet/Bugtracker-Infinium-4.0.6a#922]
hechizo piedra de salud no c como sacar la spell pues wowhead creo k ya las modifico pero en el wow cuando creas la piedra dice k restaura 58% y mas el glifo k restaura 30% seria 88% y al usarla solo restaura un 18 % d mi vida ya k tngo 124k d vida creo io k sta mal o si esta bien adelane solo me gustaria k lo chekaran pues contra meles no syuda mucho es como si le kitaran hipotermia aun mago pero bueno chekenlo xfavor

**Comment by ghost** [comment]
La piedra en wow dice que restaura 45% de salud BASE, ¿qué significa salud base?, significa la salud que tienes sin equipo, armas, armaduras, pociones, etc, y si tienes el glifo que aumenta 30% la sanación con la piedra serian unos 75% de salud base. Teniendo en cuenta que todos los brujos al nivel 85 tendrian practicamente la misma salud base, suponiendo que sean unos 50k de vida, no va a superar la sanacion de los 38k aproximadamente si haces el calculo de la piedra que da 45% mas el glifo que aumenta 30%, que seria un 75% de salud base.

**Comment by DatJetto** [comment]
De hecho sería así:
http://old.wowhead.com/spell=6201

Restaura 45% de tu salud BASE como dice Lvmb, pero el glifo no aumenta la salud base de 45 a 75%, sino que ese 45% le haces un 30% y lo añades, de manera que si un brujo lvl 85 tiene 40k aprox. base la piedra curará 18k, sitiene el glifo el 30% de esos 18k son 5400, entonces la piedra tendría que curar 23,400 p. de salud.

**Comment by ghost** [comment]
En resumen... si esta bien como ahora, o tal vez cura de más inclusive xd.

**Comment by searum** [comment]
exacto, tal y como dice jetto, cierro.
