### ISSUE TITLE
El misterio infinito Vuelta atrás bug

### ISSUE THREAD

**Issue by verchdragon** [RoDNet/Bugtracker-Infinium-4.0.6a#929]
Hola amigos  pues para ver si esta bug esta misión la complete pero no la puedo entregar la misión esta en el titulo les dejo dos capturas de pantalla, espero  pronta respuesta :

Imagenes:
en la primer imagen se mata al enemigo  y mi yo del pasado me dice todo  el texto  y hasta cuando me dice gracias por la ayuda.
http://www.subeimagenes.com/img/wowscrnshot-032513-031625-583631.jpg
![WoWScrnShot_032513_031625](https://f.cloud.github.com/assets/3969051/300504/ccb5af96-959a-11e2-9e91-9543c328a2b9.jpg)

En la segunda imagen  estoy con el que la tengo que entregar  me aparece completada pero no me deja entregar 

![WoWScrnShot_032513_032019](https://f.cloud.github.com/assets/3969051/300493/962179ba-959a-11e2-824e-76e312f497cd.jpg)

**Comment by redneo** [comment]
Misiones arregladas. Esta que comentas y la anterior.

**Comment by verchdragon** [comment]
Gracias Saludos
