### ISSUE TITLE
Se nos comen los gusanos-Faucemagma-Descenso

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#937]
Hola queria comentar que hace un rato hicimos descenso, primero matamos a chimaeron y luego decidimos ir por faucemagma.
Lo que nos paso que cuando lo intentamos un try wipeamos, lo malo fué que al volver a entrar habia unos gusanitos una media docena que increiblemente rapido nos mataron los cuales de empezaron a multiplicar rapidisimamente hasta llegar a ser centenas de ellos, los cuales no nos dejaban entrar poniendonos a tope de debuf incluso lageando todo impidiendo casi moverse.
Dejo unas fotos para demostrar esto, como se puede ver en la foto hay una masa de adds, cosa que nunca habia visto que se multiplicaran de semejante manera.
Quiero añadir que el boss se hace bien solo que los gusanos me parecio excesivo jaja.
Un saludo.

![a](https://f.cloud.github.com/assets/3537253/311574/554625b6-9749-11e2-91ff-b8b79978e58a.jpg)
![b](https://f.cloud.github.com/assets/3537253/311576/60c4e616-9749-11e2-8b18-7e844971a7de.jpg)
![c](https://f.cloud.github.com/assets/3537253/311577/679abb32-9749-11e2-8a7d-f3c96fab0aa5.jpg)
![d](https://f.cloud.github.com/assets/3537253/311578/7419b8ea-9749-11e2-939d-caccc2229412.jpg)
![e](https://f.cloud.github.com/assets/3537253/311581/799fb594-9749-11e2-9464-0b2f7fa97b1c.jpg)
![f](https://f.cloud.github.com/assets/3537253/311582/8e2f425e-9749-11e2-88ab-74b7489446ab.jpg)

**Comment by pat123** [comment]
Los gusanos salen cada vez que te golpean osea si sale 1 y toca a alguien 1 gusano más si son 2 y los 2 te pegan son 2 más asi sucesivamente.

**Comment by Keough** [comment]
que raro, yo he hecho hoy día, logrando matar solo al gusanote mayor sin problemas xD

**Comment by Saskhaek** [comment]
Vamos a morir todos, es una epidemia, si son gusanos enormes tio, ni en Resident Evil son asi jajaja xD

Parecen regaliz rosa..

**Comment by Fabercastell** [comment]
Parece majin bu armandose en el suelo xDDDDD

**Comment by Yavoy** [comment]
Esto pasa por que cuando un gusano mata a un player, se multiplican, por eso se dice '' FULL GUSANOS '' o '' ALEJAROS DE ELLOS '', ya que si te tocan, o te matan y te meten una buena piña y si te matan, se multiplican.. yo de hecho la acabo de hacer hoy y no ha pasado nada de esto.
