### ISSUE TITLE
[BANDA > Castillo de la Tempestad]

### ISSUE THREAD

**Issue by HexR-zz** [RoDNet/Bugtracker-Infinium-4.0.6a#94]
En el último Boss, Kael'Thas, sus ayudantes tienen 25-50 de vida. Deberían tener mucha más.
A parte, Kael'Thas lanza una bola de fuego que inflige aprox. 480k de daño
http://es.wowhead.com/npc=19622 > http://es.wowhead.com/spell=36805
http://es.wowhead.com/npc=20062
http://es.wowhead.com/npc=20060
http://es.wowhead.com/npc=20063
http://es.wowhead.com/npc=20064

**Comment by searum** [comment]
Podrias facilitar la id de los ayudantes y la id de la spell? o el nombre por lo menos

**Comment by searum** [comment]
fixed
