### ISSUE TITLE
Misión bug "Corazón helado"

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#940]
Otro bug de esta misión http://es.wowhead.com/quest=12856 es que, cuando montas los Protodracos http://es.wowhead.com/npc=29708 no los puedes mover, y tampoco aparece la barra de hechizos con este hechizo Fragmento de hielo http://es.wowhead.com/spell=55046 que sirve para liberar a las Prisioneras Brunnhildar http://es.wowhead.com/npc=29639

Una imagen de cuando montas el Protodraco:
![WoWScrnShot_031713_074444](https://f.cloud.github.com/assets/3508051/314844/706cf676-97d5-11e2-9a3d-816ace6506bf.jpg)

Como se puede ver he montado al Protodraco, pero estoy en el piso.

**Comment by redneo** [comment]
Arreglada del todo

**Comment by ghost** [comment]
Muchas gracias.
