### ISSUE TITLE
Más misiones, y algunos bugs - Vash'jir

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#941]
---

Misión "Hinchado submarino"
http://es.wowhead.com/quest=25218 misión bug, al usar Globo aerostático de Sambino http://es.wowhead.com/item=54608, unas 10 veces para poder inflarlo, el objetivo "Llena el globo aerostático de Sambino" no se completa, imposibilitando completar la quest y entregarla.

---

Npc "Cangrejo de arena verde"
http://es.wowhead.com/npc=39418 no esta bug, pero deberían de haber más de estos npc en la zona de la quest para poder matarlos, creo que solo hay unos 4 en toda la zona de la misión "Clientes cangrejos" http://es.wowhead.com/quest=25360/clientes-cangrejos.

---

En algunas zonas te "baja el aire" hasta 0 y luego empiezas a perder vida, o inclusive te empieza a "fatigar" estando dentro de Vash'jir, lo de fatigar solo debería de pasar cuando sales de un mapa.

También hay muchos mobs que hacen sólo 1-2 de daño al golpearte, que no se pueden atacar a distancia porque te sale el mensaje de que estas lejos, o que los atacas desde lejos pero no te ponen "en foco" y por lo tanto no se mueven y se regeneran toda la vida de nuevo, tambíen muchos mobs que son amistosos y no los puedes atacar. Puedo ir poniendo las ids de los mobs que veo que tienen esos problemas si quieren.

Otra cosa bug es que, en todas las 3 zonas de Vash'jir que son: Bosque Kelp'thar, Extensión Bruñida y Profundidades Abisales, no se encuentra un solo Depósito de obsidium http://es.wowhead.com/object=202736 ni tampoco Velo de azshara http://es.wowhead.com/object=202749 (deberían de haber muchas de estas plantas).

Desde ya, muchas gracias por vuestra atención y por arreglar los bugs.

**Comment by redneo** [comment]
Tambíen quiero agregar que, al entrar a Vash'jir deberías de obtener el buff que te hace moverte más rapido y poder respirar bajo el agua (no se como se llama).

Te lo da una misión, la cual empieza con se busca heroes Vashj'ir o la de la horda... que creo que tampoco funcionan....

**Comment by ghost** [comment]
Mmmm si, creo que el portal a Vash'jir lo ves después de hacer la cadena de misiones que te llevan ahí.

Tema a parte, te dejo un enlace que tal vez te sirva, es para hacer quotes o citas https://github.com/blog/1399-quick-quotes

Lo cerre sin querer xd.

**Comment by crowel** [comment]
Hola me gustaria añadir unas cuantas misiones mas de vash todavia no reportadas, un saludo :)

*Arrinconados
http://es.wowhead.com/quest=25164
Defiende el campamento del Anillo de la Tierra hasta que los nagas se retiren. 
-Problema:Al cojer la misión no hay la opción de hablar con Clarividente Gadra para comenzar el evento de defender el campamento y matar los nagas que deberian aparecer.

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by ghost** [comment]
Pues algunas de las que pusiste, ya las reporte, mira aquí #913

**Comment by crowel** [comment]
Listo borradas esas dos de la lista.

**Comment by redneo** [comment]
- http://es.wowhead.com/quest=25219 arreglada
- Transportes arreglados
- http://es.wowhead.com/npc=40200 arreglado
- http://es.wowhead.com/quest=25598 arreglada
- http://es.wowhead.com/quest=25440  Arreglada
- http://es.wowhead.com/quest=25215  Arreglada
- http://es.wowhead.com/quest=25441  Arreglada
- http://es.wowhead.com/quest=25657  Arreglada

---

Misiones que no estan aquí pero que he arreglado:
http://es.wowhead.com/quest=14482 y la versión horda, cuidado que los barcos se solapan.
http://es.wowhead.com/quest=25281 y creo que la versión horda
De paso, la vida, el ataque y cosas por el estilo de algún npc que me he cruzado. A ver si algun día puedo terminar y se ordena el Bosque Kelp'thar

---

Limpio un poco el post.

**Comment by ghost** [comment]
Antes que nada, perdón si ya es mucho esto que pondre aquí xd, leelo cuando tengas tiempo y no tengas algo mejor que hacer redneo xd.

---

Esta misión sigue bug, http://es.wowhead.com/quest=25219  sigo sin poder lootear los caracoles.

---

Sobre los barcos que van a Vash'jir

Me he fijado que el barco de la alianza siempre aparece y va de vash'jir a ventormenta, donde se "encima" al mismo tiempo con el que va de ventor a rasganorte, supongo que no lo puedes mover o "ajustar" el tiempo para que no se encimen.
El barco de la horda también va de durotar a vash'jir y vuelve

Los barcos solo tienen que poder verlos los que hacen la misión, porque entan en una "fase", los puede usar/ver cualquiera.

Aquí en este enlace el primer comentario explica como es en la misión horda http://es.wowhead.com/quest=25924#english-comments.
Hacia el final de su comentario dice que cuando el barco esta llegando a vash'jir hay una "escena" de que un pulpo/calamar ataca el barco lo rompe y luego reapareces al lado de este npc http://www.wowhead.com/npc=41629 

Luego de la misión del barco, tienes que hacer esta http://www.wowhead.com/quest=25929, al terminarla te saca de la "fase", y te da el buff "Piernas de mar" http://es.wowhead.com/spell=86672 (que no lo obtienes, debería aparecer el icono de una burbuja azul creo).

Al terminar la misión, recien ahí deberia de aparecer el portal a vash'jir (o supongo que luego de terminar la misión de los barcos), si pudieras configurar el portal para que no pueda usarse sin antes completar esta mision.

---

Hay dos Erunak Hablapiedra http://es.wowhead.com/npc=41618/erunak-hablapiedra en el barco de la horda destrozado, uno esta arriba, y el otro adentro, solo debería de haber uno (el de adentro).

---

También decir que, la misión http://es.wowhead.com/quest=25924  para poder agarrarla hay 2 formas, una es haciendo una "mini cadena" de misiones, que son estas estas 3 (que no se pueden hacer porque no aparece para realizar/completar la primera):
http://www.wowhead.com/quest=28790
http://www.wowhead.com/quest=28805
http://www.wowhead.com/quest=28816
.
Y la otra es con esta:
http://www.wowhead.com/quest=27718, la cual sí funciona.

---

Esta misión Cadena de favores (horda) http://es.wowhead.com/quest=25936, no funciona, usas el item http://es.wowhead.com/item=52710  en los npcs http://es.wowhead.com/npc=43179 pero no cuenta/suma para completar la misión.

---

Las demás misiones están como dijiste.

---

Dejo aquí otras misiones más que encontre en extensión bruñida xd

Atropello a la carga 
http://es.wowhead.com/quest=25221 deberían de haber nagas fugandose/corriendo/en movimiento, los hay pero estan quietos, hay que usar el item Lanzas casadoras de Toshe http://es.wowhead.com/item=54466 pero cuando lo utilizas te daña a ti y no al naga.

Arrinconados
http://es.wowhead.com/quest=25164 al agarrar la misión, deberían de aparecer los nagas, y los que defienden el campamento, pero no aparecen, luego de que mueran los nagas, tiene que aparecer este npc para matarlo http://es.wowhead.com/npc=41049.

La amenaza en ciernes
http://es.wowhead.com/quest=25334 tienes que hablar con la clarividente Grada http://es.wowhead.com/npc=39226 para que te meta en un trance, pero le das clic derecho y nada.

Nespirah
http://www.wowhead.com/quest=25890 según el comentario nº 66 inglés en ese enlace, el maestro de vuelo (el caballo) debería de tener una opción para ir adentro de Nespirah, y cuando entras aparece el npc al que, que tienes que seguirlo y luego se completa la misión, y se la entregas. Dejo el comentario:

"Once you pick up the quest, go talk to the 'Flight Master' and select the 'I need to go to Nespirah' option (wording is not exact). The flight master will drop you at the end of the tunnel. <Do not mount up> Run inside and wait, as you enter the room the two Earthen Ring guys will appear, follow them into the brain room and wait. The quest will complete and another will become available."

**Comment by redneo** [comment]
Lo del barco... no siempre se solapan, si tienes ojo y buena suerte, puedes coger uno o el otro... Para ponerlo que solo salgan cuando tienes la misión no está en mi mano (o conocimientos) pero molaria, asi como meter a los tripulantes.

Segun vaya arreglando misiones de la zona, y se pueda llegar hasta cierta zona, caparé los portales para que solo se puedan usar si has terminado cierta misión (muy parecido a blizz que solo aparecen si has hecho cierta misión) a la par que las organizaré para que no salgan todas a saco, por lo demas....me pondré con ello.

http://es.wowhead.com/quest=25936 probe la de la faccion alianza, e iba, no me fije que en la horda pedia otros killcredit, arreglado

Edito por no llenar esto hasta arriba: el npc 39422 al hacer click en el te tiene que dar el item para la mision http://es.wowhead.com/quest=25219

**Comment by redneo** [comment]
Os parece hacer un nuevo tracker con las misiones, realemente por zonas, ya que hay tres zonas, y me las estais mezclando bastante
http://es.wowhead.com/quests=0.4815
http://es.wowhead.com/quests=0.5144
http://es.wowhead.com/quests=0.5145

**Comment by ghost** [comment]
Ya esta #1017
