### ISSUE TITLE
Misiones bug - Torneo Argenta

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#942]
Misión "Drottinn Hrotgar" 
http://es.wowhead.com/quest=14101 no se puede usar el item Cuerno de guerra http://es.wowhead.com/item=47006 en el lugar de la quest para invocar a Drottinn Hrothgar http://es.wowhead.com/npc=34980 dice "Requiere Monumentos Tualiq", pero estoy ahí con los monumentos y nada.

---

Misión "Esta vez la haz liado, Kul" 
http://es.wowhead.com/quest=14096 misión bug, el npc Kul el Temerario http://es.wowhead.com/npc=34956 no se encuentra en la jaula para ser rescatado, y no se puede completar la misión.

---

Misión "A las puertas del enemigo" 
http://es.wowhead.com/quest=13847 faltan los siguientes npc: Explorador Guardahuesos http://es.wowhead.com/npc=33550 Lacayo Guardahuesos http://es.wowhead.com/npc=33438 Teniente Guardahuesos http://es.wowhead.com/npc=33429 en realidad creo que "estan" pero en otra fase, porque desde lejos se ven algunos mobs y al llegar a la zona ninguno se ve.

---

Misión "Batalla ante la ciudadela" 
http://es.wowhead.com/quest=13864 falta el npc Comandante Guardahuesos http://es.wowhead.com/npc=34127 lo mismo que el anterior, parece que esta en otra "fase".

---

Misión "Amenaza desde el cielo"
#585 esta misión ya la había reportado, lo pongo aquí porque también es del torneo argenta.

---

Misión "Una espada de campeón" 
http://es.wowhead.com/quest=13783/una-espada-de-campeon la misión consiste en ir al Lago Fresno, usar el Cacao antipupas http://es.wowhead.com/item=44986 y usar el comando /kiss o /besar en las Ranas de Lago http://es.wowhead.com/npc=33211, al besar a una de esas ranas debería de aparece el npc Doncella de Lago Fresno http://es.wowhead.com/npc=33220 que tiene que entregarte la Espada de Lago Fresno http://es.wowhead.com/item=44981, el problema es que la doncella no aparece.

---

Misión "¿El Caballero Negro del Bosque de Argénteos?"
http://es.wowhead.com/quest=13634 al llegar al lugar de la misión en el Bosque de Argénteos, no se puede lootear el item Diario polvoriento http://es.wowhead.com/item=45062 y por tanto, no se puede completar la misión.

---

Para hacer las misiones:
Dominio de Romper escudo http://es.wowhead.com/quest=13835/ 
Dominio del combate cuerpo a cuerpo http://es.wowhead.com/quest=13828/
Dominio de Cargar http://es.wowhead.com/quest=13837
Necesitas montarte en una de las monturas que estan en el torneo argenta, pero no te puedes montar en ninguna.

Desde ya, muchas gracias por leer todo esto xd.

**Comment by redneo** [comment]
http://es.wowhead.com/quest=14101 Se puede hacer. Usas el cuerno encima de la hoguera y sale el http://es.wowhead.com/quest=14096 Puesto el npc
http://es.wowhead.com/quest=13847 Puestos los npcs, espero que en la fase correcta. Antes de poder ir a por ellos, tendria que haber unas monturas y un puesto, no me se las ids de los npcs, si tengo tiempo y me acuerdo, lo busco

http://es.wowhead.com/quest=13783/una-espada-de-campeon Le he pasado los datos a Searum para arreglarlo
http://es.wowhead.com/quest=13634 Puesto los dos gobs en su sitio (Alianza/Horda)
http://es.wowhead.com/quest=13835/  Arreglado para que te puedas montar tras haber realizado las misiones correctas.
http://es.wowhead.com/quest=13812/amenaza-desde-el-cielo creo que está arreglada, no lo he probado al 100% pero los npcs, creo que salen al matar al draco o estan montados... no lo he podido ver bien
http://es.wowhead.com/quest=13864 Spawneados los npc en la fase correcta (creo)

Si está todo bien procedo a cerrarel ticket (previo aviso vuestro)

**Comment by ghost** [comment]
Muchas gracias, los probare todas, supongo que hay que esperar a que actualicen el emulador, no?

**Comment by redneo** [comment]
No, cuando caiga el server todas menos la de la rana, tendrian que ir
(La mayoria de las misiones y o cosas que arreglo van por BD, con lo cual, solo hace falta un simple reinicio para que tomen efecto)

**Comment by ghost** [comment]
Todas estan como dijiste, solo faltaria la de los sapos, un pequeño detalle en una quest, estos npcs http://es.wowhead.com/npc=33550 muestra que estan por el piso, pero en realidad estan volando, te dice que no estas lo suficientemente cerca para atacarlos, pero es un detalle que no importa porque te acercas un poco mas y los puedes atacar.

Puedes cerrar el ticket/post si quieres.

**Comment by redneo** [comment]
Puesto volando, procedo a cerrar
