### ISSUE TITLE
Loteo de mobs de cumbres. [Religuia de Ulduar]

### ISSUE THREAD

**Issue by Alfonn** [RoDNet/Bugtracker-Infinium-4.0.6a#943]
Para empezar he buscado en wowhead que mobs lo lotean,dónde que porcentaje... y tras haber farmeado un rato no he sacado ni 1.. y me llega la conclusión que puede que este loteo este bug, y por tanto no se pueda conseguir la Petaca de Hierro . (No me refiero a la quest, la quest funciona correctamente).

http://es.wowhead.com/item=42780/reliquia-de-ulduar

**Comment by redneo** [comment]
Arreglado cuando caiga el server
