### ISSUE TITLE
Bug con mis profesiones

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#946]
Buenas, el problema que me aparecio después de relogear (a parte de esto que reporto ahora, ya me paso que perdi reputaciones, perdi skills, perdi items etc, para tenerlo en cuenta nada más.) es que desde mi segunda profesion principal, hasta todas mis profesiones secundarias me dicen "0/0", dejo imágenes, no sé si sólo es un bug mio o a otros les pase, también mi alquimia se bugeo, ayer me hice "Maestro en pociones" y en mi libro de hechizos dice que soy "Maestro transmutador". 

Aclaro que ya borre cache y relogee mil veces y nada.

Imágenes:

![maestro en pocion](https://f.cloud.github.com/assets/3508051/319733/e8bff83e-98da-11e2-911d-0a2598304511.jpg)
En esta imagen se puede ver como en el Libro de hechizos dice "Maestro transmutador" pero en mi barra de hechizos dice "Maestro en pociones" (que es lo que en realidad debería ser).

---

![herboristeria](https://f.cloud.github.com/assets/3508051/319738/840081a6-98db-11e2-91e4-f09a49180204.jpg)
Aqui se puede ver como tengo el hechizo "Sangre de vida" de herboristería rango 8 (que vendría a ser heroristería 525) pero en el Libro de hechizos no tengo herboristería. También aprovecho para poner de nuevo aquí el bug del hechizo Sangre de vida #814 

---

![arquelogia](https://f.cloud.github.com/assets/3508051/319741/ef5d995c-98db-11e2-9da8-ab94dad1358f.jpg)
Bueno aqui ya es muy notorio, en el Libro de hechizos no tengo arqueología pero, abriendo arqueología con el icono desde la barra de hechizos se ve como sí lo tengo.

**Comment by redneo** [comment]
Vale, eso viene dado (creo) porqué tienes mas de una especialización de alquimia. La quest de la especialización, creo (lo digo sin mirar por ningun lado) está mal, ya que no te tendria que dejar por ejemplo maestro transmutador si ya tienes hecha la misión de maestro en elixires.

Puedes buscar las misiones (en wowhead y en old.wowhead) de las especializaciones?

**Comment by ghost** [comment]
@redneo 
Aquí las tienes, son de wowhead pero ya estan marcadas como "obsoletas" y son exactamente iguales a las que hice, y aclaro que antes de hacerme maestro en pociones, me fui con el npc que me daba la misión de maestro en transmutación y pague 150g para olvidarla, o sino, no se me habilita para hacer las otras misiones de especializacón.

Maestro en transmutación
http://www.wowhead.com/quest=10907 Aquí agarras la misión para comenzarla
http://www.wowhead.com/quest=10899 Es la misión de transmutación

Maestro en pociones
http://es.wowhead.com/quest=10905 Aquí agarras la misión para comenzarla
http://es.wowhead.com/quest=10897 Es la misión de pociones (un bug de esta misión es este item http://es.wowhead.com/item=31744 debería ser drop 100% para los que tienen la misión, pero tuve que reiniciar la mazmo unas 3 veces hasta conseguirlo)

Maestro en elixires
http://es.wowhead.com/quest=10906 Aquí agarras la misión para comenzarla
http://es.wowhead.com/quest=10902 Es la misión de elixir

**Comment by ghost** [comment]
@redneo  Buenas, me atrevi a borrar mi especialización maestro en pociones, y efectivamente todo volvio a la normalidad, pero seguia teniendo maestro transmutador, y fui a borrarlo también, tenias razón, pero me parece extraño porque antes de hacerme maestro en pociones me fui a olvidar maestro en transmutación S:, habra sido algún rollback que hubo o algo por el estilo, ahora probare ponerme maestro en elixires.

Actualizo:

Relogee y, volvi a obtener Maestro en transmutación, y maestro en pociones S:, solo se borra temporalmente, si relogeo los  vuelvo a tener, no se si actualizar todo el post, o cerarrlo y volver a abrir otro con este bug?

**Comment by redneo** [comment]
Entré a ver si te encontraba (no suelo entrar a jugar, lo siento y mucho menos con el gm). La forma mas sencilla para solucionar tu problema, es que alguien te borre todas las misiones de especialización, ya que al tener alguna de la misión hecha, al reloguear automaticamente te da el spell reward de dicha misión.

A ver si algún gm caritativo te puede borrar todas las misiones que has enumerado (.quest remove xxxxx)

**Comment by ghost** [comment]
Muchas gracias, pedire ayuda a un gm, y no me encuentras porque supongo que hay una diferencia de 6 horas entre nosotros xd

**Comment by ghost** [comment]
Como ya esta arreglado, lo cierro, muchas gracias redneo :)
