### ISSUE TITLE
Loteo de Sartharion con problemas.

### ISSUE THREAD

**Issue by Alfonn** [RoDNet/Bugtracker-Infinium-4.0.6a#947]
Hice ayer mismo el Sagrario Obsidiana , y como dice en esta guía que os pondré más abajo, si matas a sartharion y has combatido a la vez a los mini boss (dracos) este tiene un 100% de probabilidades de soltar una montura voladora.Y este no lo hace. Les dejo links para probar lo que digo...

WOWHEAD :
http://es.wowhead.com/npc=28860/sartharion
http://es.wowhead.com/item=43986

GuiaasWOW: 
http://www.guiaswow.com/sagrario-obsidiana/sartharion-guide.html

Eso es todo , espero que lo arreglen y gracias. (Sé que hice bien lo de matarlo contra los tres dragones porque me saltó logro y título..)

**Comment by DatJetto** [comment]
Pues cuando yo lo he matado si ha soltado montura :c

**Comment by ghost** [comment]
Esto sucede en el modo 25n, en 10n si suelta la montura.
