### ISSUE TITLE
Los Hijos de Hodir [faccion] Quest Bug

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#949]
Hola saludos, de regreso aqui 8 meses despues xD y ahora asta estan estrenando nombre.

Bueno esta Faccion sigue estando Bug. So la reporte haze que? 9 meses :P (worldheroes)
# 

El Drakkensryd
http://es.wowhead.com/quest=12886

Se supone debes derrortar a otros dracos segun lo explica la quest utilizando este item.
http://es.wowhead.com/item=41058

Pero lo unico que pasa es que cuando lanzas el spell automaticamente te subes al draco y despues no pasa nada y si te bajas del draco caes a un vacio profundo y mueres. (por suerte soy sacerdote y uso plumas para caer despacio).

----- edito  para recordales que estoy hablando de la FACCION no de una simple quest asi que cuando arreglen esta posteare las que faltan. Son 2 cadenas de quest un poquito largas.

**Comment by redneo** [comment]
http://es.wowhead.com/quest=12886 arreglada
