### ISSUE TITLE
Bug - Huargen [El Observatorio del rey]

### ISSUE THREAD

**Issue by Detsu** [RoDNet/Bugtracker-Infinium-4.0.6a#95]
En esta misión teóricamente has de ir y hablar con el rey pero en este caso hablas con él y no te aparece ni el cuadro de dialogo !

http://es.wowhead.com/quest=14466

Os dejo la quest ahí para que lo veais

**Comment by Dekadencee** [comment]
Corregido en la siguiente actualizacion :)
