### ISSUE TITLE
Limpieza - Las Cumbres Tormentosas

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#951]
Limpieza
http://es.wowhead.com/quest=12818

Se supone que debes ir a recolectar partes de un cohete que exploto cerca del area k3 pero no hay nada

Restos carbonizados
http://es.wowhead.com/item=40603

**Comment by redneo** [comment]
Arreglado, tendras que limpiar temporales
