### ISSUE TITLE
El Núcleo Pétreo - Heróico

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#952]
Si el boss Corborus http://es.wowhead.com/npc=43438  mata a todo el grupo, al volver a entrar a la masmo e intentar nuevamente matarlo, dice "Objetivo no válido", no se lo puede atacar.

El boss Suma sacerdotisa Azil debería tirarar los items Heroicos http://es.wowhead.com/npc=42333#drops:mode=heroico pero tira items del modo Normal.

**Comment by crowel** [comment]
Sip a nosotros tambien nos pasa lo mismo con los objetos del ultimo boss. https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/736
