### ISSUE TITLE
[Paladin] Hechizo Colera Sagrada

### ISSUE THREAD

**Issue by crowel** [RoDNet/Bugtracker-Infinium-4.0.6a#953]
http://es.wowhead.com/spell=119072
Hola quiero añadir un bug que volvio aparecer en este spell.
Segun la descripción este hechizo solo deberia aturdir a : aturde a los demonios y no-muertos durante 3 s.
Sin embargo aturde a cualquier raza.
Un saludo.

**Comment by Yavoy** [comment]
Lo comprobe el otro dia ( Cuando te lo avise y de hecho lo comprobe contigo ) y buah.. no lo reporte por que Stormfury y yo estamos mirando cosas del paladin como por ejemplo venganza del tanque, la sentencia, luz alba y sus respectivas cargas.

Espero que varios usuarios que tengan paladines no abusen de este hechizo en PvP, ya que toca mucho la moral.

**Comment by crowel** [comment]
Ya no es abusar del hechizo ya pues yo lo uso, como muchos otros soy un paladin heal el cual este hechizo es uno de los 3 que tengo para atacar y no me gusta que se me llame buguero porque llevo toda la vida usando este hechizo, espero que se solucione.
Un saludo!.

**Comment by Yavoy** [comment]
Lo se, yo tambien lo uso, y me da igual que me digan bugero, forma parte de mi rotacion para poder defenderme, ya que muchas clases se aprovechan de otros bugs y no pasa nada.

si consiguen solucionarlo, pues me conformo, pero mientras, es mi rotacion y lo voy a usar, ya que esta permitido.

**Comment by ghost** [comment]
Bugeros!!, nah, ojala se arreglen este y todos los otros bugs de las demás clases.

**Comment by ghost** [comment]
@redneo puedes cerrar este bug, muchas gracias.

**Comment by redneo** [comment]
Hay que mirar si stunea a alguna raza, en un par de bgs se averigua :P
