### ISSUE TITLE
Mision bug: Punto de triangulación uno.

### ISSUE THREAD

**Issue by Simonsville** [RoDNet/Bugtracker-Infinium-4.0.6a#954]
La mision "Punto de triangulación uno" (http://es.wowhead.com/quest=10269) no se puede realizar debido a que el objeto de mision (http://es.wowhead.com/item=28962) al parecer no funciona o no genera su funcion. La mision cuenta como cadena de misiones para poder obtener la llave del arcatraz (http://es.wowhead.com/quest=10704).

**Comment by redneo** [comment]
FUnciona correctamente. Tienes que ir donde dice wowhead (66.66 - 38.60) te cuenta como hecha.
