### ISSUE TITLE
Mision .Huevos fritos con Jabinfermo

### ISSUE THREAD

**Issue by brujilla** [RoDNet/Bugtracker-Infinium-4.0.6a#958]
esta mision esta bugg pues uso la Mezcla purificadora para sanar la carne de jabinfermo transtornado pero no me la sana y asi no puedo pillar la receta de Pinchitos de aguila ratonera y  por consiguiente tampoco puedo sacar el logro de el gourmet de terrallende. ocurre algo parecido a la mision de seguimos destilando hice lo que pedia hable con el tio pero no me dio la mision terminada y ahora no me deja hablar al tio y eso que la borro pero no me deja hacerla y tampoco puedo conseguir esa receta la de kungaloosh gracias por vuestro tiempo

**Comment by redneo** [comment]
Arreglada http://es.wowhead.com/quest=9361/huevos-fritos-con-jabinferno
