### ISSUE TITLE
[DK- BLOOD- PACTO DE LA MUERTE]

### ISSUE THREAD

**Issue by keinting** [RoDNet/Bugtracker-Infinium-4.0.6a#961]
El Bug es el siguiente: Una vez que tenemos a nuestro esbirro http://es.wowhead.com/spell=46584 hasta alli todo bien, pero cuando usamos la facultad Pacto de la muerte http://es.wowhead.com/spell=48743 (La cual debe sacrificar el esbirro) esta nos otorga la salud, pero no sacrifica al esbirro, si no que sigue alli en combate sin morir, hasta que se le agota el tiempo... Eso en sangre, en las demás ramas no lo he probado... Un Saludo

**Comment by ghost** [comment]
Mírate los post antes de reportar, esto ya está reportado, ocurre en todas las ramas según dicen.
