### ISSUE TITLE
Misiones bug - Torneo argenta (parte 2)

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#964]
Misión "Ornolf el Cicatrices"  
http://es.wowhead.com/quest=14104 lo primero es, si se puede agrandar el radio para poder usar el estandarte http://es.wowhead.com/item=47029, solo se puede usar en un pequeño lugar al lado del mastil, lo segundo (que si es bug) es que al usar el estandarte aparece Ornolf el Cicatrices http://es.wowhead.com/npc=35012 pero es amistoso y no puede ser atacado.

Misión "El filo del invierno"
http://es.wowhead.com/quest=13770 la misión consiste en ir a matar a este npc Lord Llama Perpetua http://es.wowhead.com/npc=33289 que tira el item Ascua de llama perpetua http://es.wowhead.com/item=45005, que lo tienes que usar en la Doncella del Lago Aliento invernal http://es.wowhead.com/npc=33303 para liberarla y obtener el item Filoinvierno http://es.wowhead.com/item=45003, el probelma es que al usar el item Ascua de llama perpetua no puedes liberar a la Doncella del Lago Aliento invernal, aparece un mensaje que dice "Aún no puedes hacer eso".

Misión "Un arma digna"
http://es.wowhead.com/quest=13769 necesitas juntar 4 Jacinto de invierno http://es.wowhead.com/item=45000 para entregarselas a "Doncella de Drak'Mar http://es.wowhead.com/npc=33273, para que te de el item Hoja de Drak'Mar http://es.wowhead.com/item=44978, el problema es que no puedes lootear los Jacintos de invierno, estan ahí, pero no les puedes dar clic derecho para lootear.

Estas misiones deberían dar la moneda "Sello de Campeón" http://es.wowhead.com/currency=241 pero no las dan.

**Comment by redneo** [comment]
Arregladas, con los sellos y ordenando un poco las misiones.
