### ISSUE TITLE
Misiones... exacto, bug.

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#967]
Misiones de Torneo Argenta

Entre los campeones
http://es.wowhead.com/quest=13790 para hacer esta misión, tienes que hablar con uno de los tantos npc (o usar la el hechizo duelo http://es.wowhead.com/spell=62863 con ellos, no sé cual debe ser) llamados "Campeón de (nombre de la ciudad)" por ejemplo "Campeón de lunargenta" (perdón no encuentro id), el problema esta en que no puedes desafiarlos para ganarles y que te den Marca del Campeón http://es.wowhead.com/item=45500.

El gran combate cuerpo a cuerpo
http://es.wowhead.com/quest=13756 lo mismo que la anterior, hablar con uno de los npc (o usar el hechizo duelo, no sé la verdad como debe ser) con uno de los "Valeroso (nombre de la ciudad)" por ejemplo Valeroso de Entrañas http://es.wowhead.com/npc=33384 para poder ganarle y que te de el item Marca del Valeroso http://es.wowhead.com/item=45127, pero claro, no puedes desafiarlos.

---

Diaria Poblado Brunnhildar

Misión "De vuelta al foso"
http://es.wowhead.com/quest=13424 paso a reportar, dos bugs de esta misión, primero el npc/item/montura (lo que sea xd) Riendas de matriarca oso de guerra http://es.wowhead.com/item=42499 que invocas para luchar en el foso, su primer hechizo "Mordedura" (perdon no encontre id) te daña a ti mismo (en realidad a la montura) y tampoco hace los 3000 de daño que dice y te daña a ti si es que no llegas a pegar al objetivo, también la montura se mueve extremadamente lento, segun mi addon carbonite tiene una velocidad de -15% xd, el segundo bug es que al intentar atacar a Oso de guerra de El Encuentro Hyldnir http://es.wowhead.com/npc=30174 aparece "objetivo no válido" y si logro hacerle daño a alguno, no me pone "en foco" y se cura de nuevo.

---

Cadena de misiones Los Hijos de Hodir

Bueno, lo primero es que estas misiones:

1- La última de su raza http://es.wowhead.com/quest=12983
2- La oscuridad reptadora http://es.wowhead.com/quest=12989
3- El calentamiento http://es.wowhead.com/quest=12996

aparecen para hacerlas, sin haber hecho previamente las demás misiones que las anteceden, la última misión que antecede a la primera que puse aquí es Hacer un arnés http://es.wowhead.com/quest=12900 bueno, lo que reporto es que, las misiones no estan en "secuencia" como deberían ser, sino que se pueden hacer antes de hacer las misiones anteriores.
Un enlace a wowwiki que muestra el orden de la cadena de misiones http://www.wowwiki.com/Sons_of_Hodir

---

Actualizo/Edito esta parte de abajo.

Sucede que en la misión Corazón helado http://es.wowhead.com/quest=12856 (que ya funciona pero tiene ciertas "fallas"), algunas veces cuando te subes a un Protodraco http://es.wowhead.com/npc=29708 dejas de ver a las pricioneras Brunnhildar http://es.wowhead.com/npc=29639, y no las puedes rescatar, tienes que ir subiendote una y otra vez en los protodraco hasta que las puedas ver (esto me lo dijo una amiga, cuando la hice no me paso eso).
También, hay algunas prisioneras Brunnhilldar que estan debajo del mapa, puedes ver una pequeña parte de ellas, pero no les puedes lanzar el hechizo para subirlas al draco.

Oto bug más con las prisioneras, es que cuando las subes con el hechizo, algunas veces se "te caen" del protodraco y no las puedes volver a subir, o, si las subes, y vuelves a lanzarles el mismo hechizo las "echas" del protodraco.

Y una corrección/modificación si lo pudieras hacer con los protodracos, tienen una velocidad de -15%, y se hace insufrible cargar las 3 npcs y llevarlas hasta el lugar donde las tienes que dejar, creo que tarde unos 10 min en completarla la misión xd.

**Comment by redneo** [comment]
http://es.wowhead.com/quest=14144 reparada
http://es.wowhead.com/quest=13654 reparada
http://es.wowhead.com/quest=14102 reparada

http://es.wowhead.com/quest=13837 reparada
http://es.wowhead.com/quest=13835 reparada (estas dos ultimas habria que probarlas con ambas facciones)

http://es.wowhead.com/quest=13790 reparada, al menos eso creo, el servidor de pruebas me ha empezado a hacer cosas muy raras, de todas formas, lo aplico al normal y lo probais en la proxima caida. Decir que tambien cuenta como parte de logro.

Borro los datos de las mismas para no agobiarme tanto

http://es.wowhead.com/quest=13663 reparada
http://es.wowhead.com/quest=13664 esa reparada antes de que la reportes y probadas las siguientes que se pueden hacer.

**Comment by ghost** [comment]
@redneo aquí más misiones bug del torneo u.u (espero no darte un paro cardiaco con tanto bug xd)

Misión "Una espada de Campeón"
http://es.wowhead.com/quest=13783 fui a revisarla pero sigue sin aparecer el npc al usar el comando /kiss sobre los sapos, no sé si hay algún tipo de truco para poder completarla.

---

Misión "Un arma digna"
http://es.wowhead.com/quest=13769 

Primero: el item Jacinto de invierno http://es.wowhead.com/object=194213 mientras estas en la zona "Bosque Canto de Cristal", puedes verlos todos, pero cuando pasas a la zona "Corona de Hielo" desaparecen todos, sin poder lootearlos.

Segundo: al usar los jacintos en el circulo, sale el mensaje "Requiere circulo de ofrenda de dark mar".

---

Npc "Grifo del Caballero Negro"
http://es.wowhead.com/npc=33519 no esta bug, pero si pudieras aumentar su velocidad de vuelo un poquito, es de -2%.

---

Más bugs aquí

Primero: este npc http://es.wowhead.com/npc=35094 entrega dos misiones para realizar, que son: http://es.wowhead.com/quest=14108 y http://es.wowhead.com/quest=14107, debería de entregarlas al mismo tiempo, no una un día, y otra otro día (creo que es así, ya que no encontre información contraria), ahora mismo solo puedes agarrar una por dío. Para poder realizar estas dos misiones, antes debes de obtener este logro http://es.wowhead.com/achievement=2816, pero lo puedes hacer sin tenerlo.

Segundo, en esta misión http://es.wowhead.com/quest=14107 faltan más de estos items http://es.wowhead.com/item=47035, solo encontre 2 en el lugar, luego al tener ese item y usar este otro item http://es.wowhead.com/item=47033 sobre los npcs http://es.wowhead.com/npc=32149 no cuenta/suma para completar la misión.

Tercero: Este npc Kraken del mar de norte http://es.wowhead.com/npc=34925, al matarlo tiene que tirar este item http://es.wowhead.com/item=46955 que comienza la misión http://es.wowhead.com/quest=14095.

**Comment by ghost** [comment]
Esto también ya esta

> Unos pequeños detalles (bugs) en el torneo argenta (creo que no esta demás reportarlo xd, pero claro no son importantes)
> 
> Las montura "Corcel Quel'dorei de establo" y "Halcon zancudo atracasol de establo" (supongo que ha de pasar con todas), bueno, algunas veces cuando te subes a la montura y te vas a atacar a los objetivos te dice que "el objetivo esta lejos", y si te desmontas, te lleva al lugar de donde sacaste la montura, esto sucede porque te puedes montar encima de la montura, mientras ya estas montado, o sea sucede si te montas por segunda vez en la montura mientras ya estas montado.
> 
> También el hechizo "cargar" del caballo que'ldorei no funciona de la misma forma que el del halcon zancudo, cuando usas cargar sobre un objetivo, se queda en el lugar del objetivo atacado sin seguir el camino, tambíen hace menos daño que el del halcon zancudo.
> 
> El hechizo "estocada" del halcon zancudo hace menos daño que el del caballo quel'dorei.
> 
> Al caballo quel'dorei le falta el hechizo "duelo".

**Comment by lashadas** [comment]
Tengo en mi podre Naipe de la luna nagra :volcan le he dado a la mision y me he puesto hablar con el profesor thaddeus paleo en el bosque de terokkar, pero no me deja completar la mision solo me deja ver sus mercancias y solo me habla de las demas cartas .. pero mas que le doy saber mas de las cartas y si existe otras cartas no me deja completarlas .. tengo la mision , tengo la baraja de volcan pero no me deja hacer nada mas. lo pongo en este apartado por que me han dicho que esta baraja se liga solo una vez por cada pj y que no se puede poner mas veces podian ayudarme y hacer que la mision vaya bien para comseguir el objeto gracias por su tiempo, mi pj es blesilia

**Comment by redneo** [comment]
Misión "De vuelta al foso" http://es.wowhead.com/quest=12997 arreglada
Misión "El calentamiento" http://es.wowhead.com/quest=12996 arreglada

Misión "La maldición del Caballero Negro" http://es.wowhead.com/quest=14016 a mi me la completó bien.

Misión "Un arma digna" http://es.wowhead.com/quest=13769 Ya se pueden usar los jacintos en el circulo, puede que el radio de donde se puede usar sea pequeño... nada al rededor del circulo hasta encontrarlo.

**Comment by ghost** [comment]
Gracias redneo, que raro que a mi no me haya completado esa mision, porque la intente de hacer 2 veces y no pude xd, pero ahora si.

 Misión "El desafío del aspirante" http://es.wowhead.com/quest=13680 Reparada

Limpie el reporte inicial y los comentarios de las cosas ya arregladas.

**Comment by redneo** [comment]
Cierro este bugtrack y lo pones de uno en uno, que muchas estan reparadas ya

**Comment by ghost** [comment]
Entendido.
