### ISSUE TITLE
El Drakkensryd - SIGUE BUG o no entiendo

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#968]
Haciendo referencia al post anterior Y QUE FUE CERRADO.

https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/949

El Drakkensryd
http://es.wowhead.com/quest=12886

Se supone debes derrortar a otros dracos segun lo explica la quest utilizando este item.
http://es.wowhead.com/item=41058

Pero lo unico que pasa es que cuando lanzas el spell automaticamente te subes al draco y despues no pasa nada y si te bajas del draco caes a un vacio profundo y mueres. (por suerte soy sacerdote y uso plumas para caer despacio).
# 

----- Esta quest la reporte hace algunos dias dijieron que fue arreglada pero sigue pasando lo mismo montas el drako con el arpon y quedas colgando asta muy debajo de ellos y luego si te sales del drako CAES A UN PROFUNDO ABISMO y mueres. ----

Diganme si SOY YO el que no logra entender como hacer esta quest o si realmente esta bug.

EDITO: para agregar que ya borre la CACHE y la carpeta WTF y sigue pasando lo mismo.

**Comment by WarSxNes** [comment]
Bueno ahora mismo estoy en lo alto de la montaña y gracias a que soy un PJ de rango (sacerdote) alfin pude matar uno acercandome lo bastante a la orilla pero luego me tube que tirar al VACIO porque no podia usar montura voladora para salir de ahi.

Jinete de dracos de El Encuentro Hyldnir
http://es.wowhead.com/npc=29694

Me parece que estos son a los que tienes que matar. Pero como he dicho cuando usas el arpon quedas colgando del DRACo muy por debajo de ellos y no ves nada. Y si te sales del draco caes a un PROFUNDO VACIO y mueres.

**Comment by redneo** [comment]
Teoricamente los dragones tienen tipos montados, te montas en los dragones, tras el tipo, lo matas y cuenta. Usas el item de mision para montar en otro dragon.

Comentadme si no es así

**Comment by WarSxNes** [comment]
Si eso es lo que quiero hacer pero la cosa es QUE! quedo colgando del draco muy por debajo de ellos, y no puedo ver a ninguno de ellos.

El draco funciona como un vehiculo como esos de conquista de invierno. Pero sin habilidades solamente aparece el icono de DESMONTAR y cuando lo haces te caes al vacio.

Bien en el centro del TEMPLO hay unas lamparas o faroles donde usas el ARPON y te cuelgas bien eso funciona al 100% pero cuando lo usas en los dracos te quedas colgando debajo de ellos y no tienes opcion de volvel al TEMPLO y no te queda de otra mas  que TIRARTE AL VACIO Y MORIR.

Edito: para preguntarte REDNEO@: has probado la quest? Si eres GM usala sin poderes de GM o mejor aun usala con otra cuenta que no sea la de un GM. En ocasiones los GM puden ver cosas y hacerlas que los demas no.

Hace ya algun tiempo recuerdo sobre una CUEVA o CAVERNA donde entrabas y te comenzaban a golpear a si como si nada asta que te mataban ya estando MUERTO ves que puedes librerar no? lo chistoso es que cuando buscabas tu cadaver dentro de la cueva lograbas ver a un centenar de NPC enemigos invisibles, no fue sino que asta que un GM llego y dijo "como entras asi nomas directamente a morir acaso no vez el monton de NPCs" y nosotros (eramos 8 ahi presents) le respondimos "NO, no se ve a nadie ahi dentro" Y no fue sino asta que el se quito un aura o algo ahi (eso fue lo que explico) que el tambien dejo de verlos. RARO no?

**Comment by redneo** [comment]
Lo probé en el server de pruebas, ya que en el normal por A o por B no me apetece entrar, puede ser que alguna query se me quedara en el tintero... voy a mirar a ver.

Edito. Lo acabo de probar en los dos servers... el problema viene dado por las monturas y / o los paquetes enviados. Si te montas en los npcs volando, te montas bien, si lo haces desde tierra, caes al vacío. Dificil solución tiene...

**Comment by WarSxNes** [comment]
auch... disculpa pero no entiendo muy bien lo ultimo; (a lo mejor sera por mi acento) me estas dando la solucion? O me explicas lo que podria ser el problema.

Es que la parte en la que dices "Si te montas en los NPCs volando (te refieres a los Dracos no?) te montas bien." o te refieres a que debo montarlos desde mi montura estando volando?

Lo que pasa es que al final dices "dificil solucion tiene..." (es que de donde soy me das a entender que soy yo el del problema :P)

Pero bueno de cualquier forma voy hacer el intento y si no funciona regreso a comentar. (voy a borrar la Cache y WTF).

---

hahaha.... Lo intente y me parti toda la cara. (quiero decir me mori al caer al vacio). Nop, no funciono usando montura voladora y subiendo directamente a ellos simplemente me tiro al vacio. Si me monte al draco pero automaticamente me arrojo al vacio.

Oe puedo darte una sugerencia? no seria mas facil poner los jinetes dentro del templo en suelo firme y ponerles algo de vida y damage y asi matarlos y completar la quest?

Es que sin esta quest no puedo subir con la faccion Los Hijos de Hodir.

Bueno es una sugerencia no mas.

**Comment by redneo** [comment]
Eso es lo que haré, pero tengo que andar con ojo con no joder las GUIDs... mañana o pasado los pongo correctamente para que los puedas matar sin tener que montar en dracos (mierda de solución, pero la unica que se puede hacer por ahora)

**Comment by WarSxNes** [comment]
Hola creo que se le olvido arreglar esta quest, No mas es un recordatorio.

Saludos

**Comment by ghost** [comment]
Lo puedes cerrar @redneo, @WarSxNes hazte responsable responsable del bug y cierralo xd.

**Comment by WarSxNes** [comment]
WoW Ghost@: de que hablas? que de por si ya estaba bug xD.

> Y al final la solucion de redneo fue en lo que habiamos quedado. Dejo los Jinetes dentro del templo. Por que cuando te subias al draco y lanzabas el arpon (en mi caso) quedabas colgado del draco y no podias ver nada y quedabas fuera de rango (osea muy lejos) para poder lanzarles un spell a los jinetes.

Bien confirmado ya funciona  100% la quest. **_jinetes dentro del templo_**
