### ISSUE TITLE
Hunter no genera foco disparo firme

### ISSUE THREAD

**Issue by chiflo1986** [RoDNet/Bugtracker-Infinium-4.0.6a#97]
mi hunter no genera foco cuando lanza disparo firme.. no se si les pasara a todos los hunters.. soy warwolf =)

**Comment by DatJetto** [comment]
Edito: Lo he comprobado es cierto que no produce +9 Foco. 

http://es.wowhead.com/spell=56641
Le falta esta spell: http://es.wowhead.com/spell=77443

**Comment by Dans-hunter** [comment]
Edito mi post  como mi compañero Jetto para afirmar lo que el dice :)

**Comment by Dekadencee** [comment]
Corregido en la siguiente actualización :)
