### ISSUE TITLE
[ Hunter > Arcane Shot  ]

### ISSUE THREAD

**Issue by DatJetto** [RoDNet/Bugtracker-Infinium-4.0.6a#974]
Buenas a todos, creía que ya había puesto esto antes pero antes repasando vi que no, la cosa es que Disparo Arcano ha sufrido un cambio en su daño, el cual por lo visto se ha desproporcionado:

http://es.wowhead.com/spell=3044
- Un disparo instantáneo que inflige un 100% de daño con arma más x% Rap como daño arcano.

Según las notas del parche 4.0.6 el daño de disparo arcano se ha aumentado un 15%.

Pero esque en pve mete --30k y en pvp 19-20k crit.-- el %Rap supongo que estará equivocado. 

[UPDATE] 6 April 2013
Descargué el addon Dr Damage y procedí a testear el daño: 

El addon muestra que debería pegar de 5 a 7.5k mientras que el disparo da 8.6
- http://i45.tinypic.com/2hoi8p5.jpg
- http://i46.tinypic.com/vjiv7.jpg
  En critical vemos como de 11-15.5k pasa a 22k

**Comment by exi96** [comment]
no esta perfecto en todos los severs esta igual

**Comment by Yavoy** [comment]
¿Perfecto? xDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.

Adios.
