### ISSUE TITLE
mision. Seguimos destilando

### ISSUE THREAD

**Issue by brujilla** [RoDNet/Bugtracker-Infinium-4.0.6a#975]
estoy  haciendo la mision Seguimos destilando , y cuando sale la barrica para coger el licor aparece vacia y no consigo acabar la mision ya me a pasado 3 veces sale la barrica que da McManus Chispa pero dentro no hay nada esta vacia asi que no `puedo acabar esa mision del pnche de los cebatruenos en cuenca . Muchas gracias

**Comment by ghost** [comment]
Link de wowhead http://es.wowhead.com/quest=12644/ con lo de la "barrica" se refiera esto http://es.wowhead.com/object=190643 aparece al terminar de hacer la mision, pero cuando la looteas esta vacia, debería dar este item http://es.wowhead.com/item=38688.

**Comment by redneo** [comment]
Arreglado, el gob ya tiene loot
