### ISSUE TITLE
Curación del DK exagerada

### ISSUE THREAD

**Issue by jandrox** [RoDNet/Bugtracker-Infinium-4.0.6a#976]
Hola, ayer en las arenas estuvimos más de media hora intentando matar a un DK el cual era básicamente "inmortal" por más que le dábamos siempre se curaba y regeneraba como muestro en las capturas sus curas eran una barbaridad, se curaba más de lo que curaba mi compañera una chamán heal y hacía más daño que mi guerrero furi Hattori y la chamán juntos hay que decir que estábamos muy bien equipados los dos.
Pongo las capturas para que juzguen si es medio normal:
![WoWScrnShot_040213_223826](https://f.cloud.github.com/assets/3144712/334809/40e9c508-9c7d-11e2-9434-fd19f063fd5a.jpg)
![WoWScrnShot_040213_230252](https://f.cloud.github.com/assets/3144712/334817/7d889bf6-9c7d-11e2-95b8-72a1160317c8.jpg)
![WoWScrnShot_040213_230356](https://f.cloud.github.com/assets/3144712/334819/7da7358e-9c7d-11e2-8e58-cffe60373884.jpg)
![WoWScrnShot_040213_230328](https://f.cloud.github.com/assets/3144712/334820/7da9bcaa-9c7d-11e2-97a5-8813e2a304eb.jpg)
Y aquí el resultado tras retirarse por aburrimiento creo yo:
![WoWScrnShot_040213_225056](https://f.cloud.github.com/assets/3144712/334827/ae9d5240-9c7d-11e2-82af-0352ce73aed9.jpg)

Un saludo.
"Por un buen juego equilibrado"

**Comment by chipi666** [comment]
Yo también tenia esa duda de los DK en general pero sacando bien las cuentas el golpe letal sana al menos 7 % de su salud máxima y un 15 % mas de la sanación realizada con el talento de golpe letal mejorado.

132.6 K \* .07 % = 9.282 K
9.282 K \* .45% = 4.204 K
9.282 + 4.204 = 13.486 K

**Comment by ghost** [comment]
Aca hay un reporte muy completo de los dk #938

**Comment by jandrox** [comment]
Precisamente he discutido varias veces con los administradores por la forma de ver lo de los porcentajes y los cálculos y ellos usan los bonificadores con respecto a los porcentajes con lo que el cálculo sería: 
7% + (15% del 7%)  = 9282 + 1392.3 == 10674.3
Y seguro que me van a decir que es menos como me pasó con el guerrero, así que lo mires por donde lo mires están over.

**Comment by Overseer101** [comment]
132.6k de vida, a ver vamos por partes, el golpe letal sin talento  sana un 7% de tu vida maxima lo cual es

132600_0.07= 9282, tened en cuenta que el talento de golpe letal mejorado no aumenta un 15% su sanacion si no un 45% (y un 90% el daño) con lo cual pasa  a ser un 132600_(0.07+0.0315)=13458, ese 0.0315 es el 45% extra por talento para que no haya dudas, asi que lo siento, pero las sanaciones del dk son asi, y en el ofi era aun peor, que os recuerdo que aqui no van los gusanos aun (y pueden tener hasta 4 a la vez), y la sanacion dinamica del golpe letal tampoco

**Comment by adrianrp1988** [comment]
Haber para ir cerrando con el tema de la sanación del DK aqui les pondre como va:

Curacion base: 7% de la vida maxima:
132600 \* 0.07= 9282

Añadimos el talento Improved Death Strike que incrementa un 45% (con 3 puntos dados) de la sanacion:
9282 \* 1.45 = 13458 

Ahora volvemos a realizar los calculos pero esta vez teniendo en cuenta el Glyph of Dark Succor(96279)

Curacion base: 15% de la vida maxima:
132600 \* 0.15 = 19890

Añadimos el talento Improved Death Strike que incrementa un 45% (con 3 puntos dados) de la sanacion:
19890 \* 1.45 = 28840

Y asi queda el tema con esta spell, @Stormfury tiene razon en lo que les plantea

**Comment by jandrox** [comment]
No me parece bien que cierres el tema, si te fijas no era solo la cuestión de la cura sino de que en esta ocasión era totalmente inmortal como demuestro en las capturas y como puede apoyar mi compañera de arenas, me da igual si están bien o mal los porcentajes o lo que sea, lo único que importaba en este tema era que los programadores vieran que aquí hay un cambio totalmente desproporcionado en cuanto al daño y curación de esta clase en particular o en este jugador específicamente, lo que hace que el juego no sea igualado con lo que empeora el server.

**Comment by Overseer101** [comment]
Pero si el problema viene de Blizzard que en cata hizo a los DK dioses literalmente, aqui el unico achaque que puedes hacer es que las runas funcionan como quieren, y en sangre yo por lo menos me tiro mas  tiempo sin runas que pegando por esa misma razon, en el ofi para bajarte un dk sangre sañoso minimo en bg se tenia que ir 5,(y si eran verdes ya olvidate, a un amigo mio sanguinario le pegaban 8 y se los cargaba metiendo ostias de cerca de 70k) por que si no era imposible, y esto lo he visto yo de testigo con mis propios ojos, ten en cuenta que esta clase es la unica clase tanque que encima se soleaba las mazmorras de 5 heroico con la gaita, con las demas era imposible hacerselas solo, pero si es que hasta se hacian arenas 2vs2 ellos solos, y si tenias algo de manos las ganabas sin demasiado esfuerzo..., la culpa te repito, de Blizzard y de lo que se fumaron para dejar los dks asi, por que el tema de "igualdad" contra un dk, no lo saben hacer muy bien que digamos

**Comment by jandrox** [comment]
Pues es una pena que los de blizzard hayan metido así el patón intentaremos aguantar entonces lo que se pueda.

**Comment by keinting** [comment]
Y por eso amo ser DK? jajajaja... Venga dejen de llorar tanto, solo es un juego... Stormfury menudo crack que sos tio! O_O
