### ISSUE TITLE
Server Caido? como saberlo?

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#977]
Hoy 4/3/2013 a las 10:10am hora del PACIFICO (UTC -08:00) el server muestra señales que se callo.

Pero como saberlo si lo esta o no? En la web ustedes tienen una seccion que se llama ESTADO y en ella una llamada Lista de jugadores.

Pero realmente estas personas estan connectadas? O es alguna clase de delay de la web que sigue mostrando que ellos estan conectados cuando en realidad no hay nadie.

Son las 10:13am y sigo sin poder entrar. y la web muestra que el server esta ON.

+++ Sugerencia +++
Seria posible que pudieran poner alguna especie de ChatBox de esas simples para foros y poder preguntarle al que este ahi, seria una forma sencilla de saber no.

Edito: son las 10:19am hora del PACIFICO y al fin la web ahora esta mostrando que el server esta OFF en la seccion de ESTADO. wow 5 minutos de delay.

Yeap 10:24am sigue mostrando que esta OFF.

**Comment by ghost** [comment]
La sugerencia deberías de hacerla en el foro, este lugar es para errores del emulador, pero si, estaría bien lo que sugieres para los que no se pueden aguantar xd.

**Comment by Dekadencee** [comment]
El estado de la web es REAL si la web dice que está on es que está on, si pone que está off está off, es imposible que tenga delay ya que tiene conexión directa con el emulador.

Sobre el chatbox ya está implementado en la nueva web.

Un saludo ^^
