### ISSUE TITLE
Pala: maestria

### ISSUE THREAD

**Issue by ksunanda** [RoDNet/Bugtracker-Infinium-4.0.6a#980]
la mestria del paladin no funciona

**Comment by crowel** [comment]
Muy bien especificado, ahora ya sabemos que rama de la maestria y el porque no funciona, gran post.

**Comment by ghost** [comment]
@ksunanda un enlace para que veas como se debe elaborar un reporte: http://www.reignofdarkness.net/wow/noticia/34/

**Comment by ghost** [comment]
/clap por las personas que reportan algo suuuper bien xD 

A ver, si quieres que arreglen algo, facilítales el trabajo al Staff con fotos, links de lo que no funciona, etc :)

**Comment by Yavoy** [comment]
Sabes? no tardaran encerrar tu post Ksunanda, gente como tu, asi va el mundo.

**Comment by ksunanda** [comment]
gente como yo, asi va el mundo?
que coño tiene que ver esto con el mundo, menudo payaso estas echo, si ni me conoces no ables flipao
