### ISSUE TITLE
Divisor de llamas

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#986]
Esta quest no esta bug.
http://es.wowhead.com/quest=25323

Cual es el problema? Hay muy pocos NPC de estos.
Elemental vinculado a las llamas
http://es.wowhead.com/npc=38896

Necesitas matar a 40 de estos.
Espíritu flameante desatado
http://es.wowhead.com/npc=40065

Utilizando este item para invocarlos. (FUNCIONA AL 100%)
Bastón de vidente de llamas
http://es.wowhead.com/item=53107

El problema es que se supone que cuando los invocas tendrian que salir por montones y solamente sale 1. Si, asi es! de un grandote solamente sale 1 ._. y necesitas matar 40 de ellos.

Lo otro es que como se supone que es un campo de batalla todos los NPC aliados te AYUDAN a matar al UNICO npc invocado. Y QUE CREEN? te lo roban y no te cuenta.

PARA COLMO DE MALES: los NPC [Elemental vinculado a las llamas] tienen 10 minutos de respawn. Que como lo se? por que les tome tiempo para ver cuanto tardaban en reaparecer. 10 MINUTOS y necesitas matar de los chiquitos 40 OMG !!! ._.

**Comment by redneo** [comment]
Ya saca más y se lo puedes lanzar varias veces si estas vivo.

Por otra parte, ese item, ese spell, es uno de los cientos que no tiene restricciones (remito a https://github.com/RoDNet/Bugtracker-Infinium-4.0.6a/issues/981 si alguien lo quiere mirar)
