### ISSUE TITLE
Misión bug "Libera tu mente"

### ISSUE THREAD

**Issue by ghost** [RoDNet/Bugtracker-Infinium-4.0.6a#989]
http://es.wowhead.com/quest=12893 tienes que usar el item Vara soberana http://es.wowhead.com/item=41366 para resucitar a 3 npcs "Vil transformado", "Lady Bosqueténebro transformada" y "El Saltador transformado" (perdón no encuentro links de los cadáveres de la misión), el problema es que esos npcs no están, la vara sólo debe dejarte usarla cerca de los npcs pero te deja usarla en toda la zona.

Esta misión es una misión de la cadena de misiones (4 misiones creo, algo corto) para ver a los npcs de la facción los caballeros de la espada del ebano.

**Comment by redneo** [comment]
http://es.wowhead.com/quest=12893 arreglada y como extra, la siguiente http://es.wowhead.com/quest=12896

Cierra el reporte si esta todo bien (phases y todo eso)

**Comment by ghost** [comment]
Ya esta arreglado y se pueden ver los npcs, gracias redneo.
