### ISSUE TITLE
Chaman > Mejora > Talento

### ISSUE THREAD

**Issue by Azraelt** [RoDNet/Bugtracker-Infinium-4.0.6a#99]
El talento del chaman mejora Latigazo de lava mejorado etsa bug ya que no aumenta el daño ni consume las aplicaciones del Tótem Abrasador.  No les puedo poner el link de wow head de esas 2 spells porque ya no estan debido a la nueva expansion... Espero que al menos el decir esto les ayude un poco.

**Comment by Faked** [comment]
Añado los talentos:
http://old.wowhead.com/spell=77700 Latigazo de lava mejorado Rango 1
http://old.wowhead.com/spell=77701#see-also-ability Latigazo de lava mejorado Rango 2

**Comment by searum** [comment]
fix
