### ISSUE TITLE
Bralla Alanube - no tiene faccion

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#993]
Bien simple NO TIENE FACCION
Bralla Alanube
http://es.wowhead.com/npc=43769

-=Error=-
Se supone que deberia de ser de la faccion VENTORMENTA y asi conforme subas reputacion con esta faccion; Los costos de equitacion y vuelo deberian ir desminuyendo 250 de oro por nivel de reputacion. Comenzando desde Neutral asta Exaltado.

Pls la Maestria de vuelo me saca un ojo de la cara 5000 [>.0] Me dicuenta del error por que ya soy exaltado con ventormenta (faccion) y sigue estando al mismo precio.

**Comment by redneo** [comment]
Cambiada a faccion 12 (Ventormenta) otra cosa es que como estan las cosas baje los precios :P
