### ISSUE TITLE
Instructora Mylva - no esta - Entrenamiento Crepuscular [quest]

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#994]
Instructora Mylva
http://es.wowhead.com/npc=39413
![GitHub Logo](http://wow.zamimg.com/uploads/screenshots/thumb/286280.jpg)

-=BUG=-
No esta y la necesito para completer una quest. Y comenzar una cadena de quest.

---

Entrenamiento Crepuscular
http://es.wowhead.com/quest=25291

Simple quest tienes que hablar con Mylva pero no esta en su lugar. En el minimapa muestra claramente el '?' donde debiera encontrase.

![GitHub Logo](http://wow.zamimg.com/uploads/screenshots/thumb/232040.jpg)

**Comment by redneo** [comment]
Puesto
