### ISSUE TITLE
Pelea! - LUCHA DE BESTIAS

### ISSUE THREAD

**Issue by WarSxNes** [RoDNet/Bugtracker-Infinium-4.0.6a#996]
¡Pelea!
http://es.wowhead.com/quest=25496

Esta quest seria facinante si la pudieran arreglar; Se supone que vas y retas a un Ogro y su raptor. Y comienzan a pelar el raptor y tu can, pero no pasa nada.

(tienes que hablar con el Ogro pero nada pasa). 

![GitHub Logo](http://wow.zamimg.com/uploads/screenshots/resized/205430.jpg)

---

NPC
Gromm'ko
http://es.wowhead.com/npc=40409
![GitHub Logo](http://wow.zamimg.com/uploads/screenshots/normal/179924.jpg)

Este es el Ogro al que tienes que hablarle y retarle pero no pasa nada.

**Comment by redneo** [comment]
Arreglado!
