### ISSUE TITLE
Entrada al Trono de las Mareas BUG!

### ISSUE THREAD

**Issue by Alfonn** [RoDNet/Bugtracker-Infinium-4.0.6a#998]
La supuesta entrada al trono de las mareas está bug, ya que hay como una especie de tornado que te traga y este no lo hace , haciendo así imposible la entrada para farmear aguas en esta maz.

http://www.youtube.com/watch?v=OuAKRuEb20Y

![asdasd](https://f.cloud.github.com/assets/3854953/347967/c1f8259c-9f0f-11e2-93f8-b8b44b26effb.jpg)

Un saludo.

**Comment by redneo** [comment]
Ostras, muchas gracias por el aporte, era una cosa que me llevaba preguntando desde hace unos años, jejeje

Espero poderlo arreglar pronto, ya que lleva su ratillo.

**Comment by Alfonn** [comment]
Nada, un placer y buen trabajo !

**Comment by redneo** [comment]
Ya puedes ir a farmear.
